### ISSUE TITLE
Wayland apps failing to resize themselves.

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#271] opened 2022-06-27 11:42 UTC
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.
Log: https://mclo.gs/gNZVUjY
![image](https://user-images.githubusercontent.com/68589851/175933326-03b83d91-f334-4b65-9c10-a3d06169ef24.png)

**Comment by KyleUltimate** [comment] 2022-06-27 11:45
This might be a quirk with floating windows? Cause any floating windows seems to unable to resize the window by itself(i.e. fctix5 rime selection window)

**Comment by vaxerski** [comment] 2022-06-27 11:46
My guess is that it is based on chromium / electron. These apps are currently broken under ozone wayland. Try forcing it to run under XWayland.

Floating windows *can* resize themselves, but some don't want to properly, sometimes.

**Comment by KyleUltimate** [comment] 2022-06-27 11:54
Yeah, forcing it to run under `GDK_BACKEND=x11` will fix it. I'll change this title to doesn't work under wayland instead

**Comment by vaxerski** [comment] 2022-06-27 12:09
I use ibus and it sometimes has a wrong size too, didn't figure out yet why.

**Comment by ozls** [comment] 2022-07-02 14:14
Ulauncher is GTK, and I have the same issue with the launcher Albert which uses Qt. I'm not sure the issue is their fault, because at least Albert works perfectly fine on Sway. But it is true that Electron apps are also weird on Hyprland. I've noticed they work just fine until they are animated (for instance when resizing them), then there is some lag and possibly a crash.

**Comment by vaxerski** [comment] 2022-07-02 19:33
found the root of the issue, protocol violations in the xdg standard. Will fix.

**Comment by vaxerski** [comment] 2022-07-02 19:45
actually, no, never mind, I think it's down to how ulauncher thinks it can resize itself (spoiler: it cannot)

**Comment by vaxerski** [comment] 2022-07-02 20:16
tried some other things, so far fruitless, will see tomorrow (or day after, tmr im really busy)

For now, force it to XWayland.

**Comment by KyleUltimate** [comment] 2022-07-29 15:26
Update on this issue.
Currently forcing it to XWayland does make it resize, but it when I type, and don't select anything, do `ulauncher-toggle`, it will just... move away from the center.
Typing stuff
![image](https://user-images.githubusercontent.com/68589851/181792651-4a1e5b03-8a67-4cd0-b9be-276704ab1549.png)
After typing stuff
![image](https://user-images.githubusercontent.com/68589851/181792669-0d7340e8-667a-4e53-b526-54005ca10ae8.png)

**Comment by fufexan** [comment] 2022-07-29 15:37
Sounds similar to https://github.com/lbonn/rofi/issues/49

**Comment by Dickby** [comment] 2022-10-06 10:39
@KyleUltimate  some things changed lately, could you test if the problem is still the same?

**Comment by Dickby** [comment] 2022-10-06 10:40
@KyleUltimate  some things changed lately, could you test if the problem is still the same?

**Comment by KyleUltimate** [comment] 2022-10-06 10:48
Yes, it's still present

**Comment by shackra** [comment] 2022-11-16 04:24
with `GDK_BACKEND=x11 ulauncher --hide-window -v` I'm unable to see Ulauncher with `ulauncher-toggle`

**Comment by cycomanic** [comment] 2023-01-24 02:23
I'm experiencing the same issue, moreover forcing to X11 does cause the ulauncher window to close when typing a letter (it's somewhat random, sometime you can type 2 letters). As the previous poster said, it is working fine under sway.

**Comment by DimitrisMilonopoulos** [comment] 2023-01-28 08:12
I think this might be in general with all apps that request to resize themselves. Namely this happens to emacs mini frames, when they pop up. I have a regex to set it to floating. But if it attempts to resize it fails.

It's a wayland app, and works fine on gnome wayland for reference.

**Comment by JustSimplyKyle** [comment] 2023-02-04 12:31
similar behaviour found in https://github.com/otsaloma/catapult 
a rust port of ulauncher also shares it https://github.com/diced/dlauncher
all three are gtk-based app launchers
https://github.com/diced/dlauncher/tree/trunk/data/ui check the gtk code if you want

**Comment by jnsgruk** [comment] 2023-05-16 15:28
Just noting that I also experience this issue with 1Password's quick access window as of today with the latest version of Hyprland from the flake.

**Comment by GianniBYoung** [comment] 2023-05-20 00:30
Still seeing this issue with ulauncher

**Comment by JustSimplyKyle** [comment] 2023-05-20 11:35
Actually, try the git version
They are using layershell so it should be fixed

**Comment by vaxerski** [comment] 2023-05-26 12:49
fixed in 5f4659afef5856c509d53957e62b7f6c38d39f41

**Closed by vaxerski** 2023-05-26 12:49 UTC
Labels: bug
