### ISSUE TITLE
odd transition between two fullscreen windows within a workspace 

### ISSUE THREAD

**Issue by 257** [hyprwm/Hyprland#966] opened 2022-11-06 16:09 UTC
Steps to reproduce:
- fire up a terminal (kitty/alacritty)
- fire up a browser (qutebrowser/chrome)
- given `bind=ALT,f,fullscreen` `ALT-f` to make everything fullscreen
- now `movefocus,{l,r,u,d}` and watch the transition between windows

driver notes: this is less obvious (happens quicker?) on Intel graphics compared to Nvidia

**Comment by vaxerski** [comment] 2022-11-06 19:01
how is it odd

**Comment by 257** [comment] 2022-11-07 19:33
> how is it odd


https://user-images.githubusercontent.com/1268392/200398383-426480dd-0211-4c6d-8278-000d566a16cf.mp4

**Comment by vaxerski** [comment] 2022-11-07 19:43
completely normal and how it's expected to be. dupe of #683

**Closed by vaxerski** 2022-11-07 19:43 UTC
Labels: bug
