### ISSUE TITLE
'movewindow, u' doesn't work if border_size is set to 0

### ISSUE THREAD

**Issue by Axenide** [hyprwm/Hyprland#6488] opened 2024-06-14 03:19 UTC
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.9.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000


GPU information: 
06:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] [10de:1f08] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/adriano/.config/hypr/hyprland.conf: Read Succeeded
#     ___                    _     __    _       
#    /   |  _  _____  ____  (_)___/ /__ ( )_____ 
#   / /| | | |/_/ _ \/ __ \/ / __  / _ \|// ___/ 
#  / ___ |_>  </  __/ / / / / /_/ /  __/ (__  )  
# /_/ _|_/_/|_|\___/_/ /_/_/\__,_/\___/ /____/ __
#    / / / /_  ______  _____/ /___ _____  ____/ /
#   / /_/ / / / / __ \/ ___/ / __ `/ __ \/ __  / 
#  / __  / /_/ / /_/ / /  / / /_/ / / / / /_/ /  
# /_/ /_/\__, / .___/_/  /_/\__,_/_/ /_/\__,_/   
#       /____/_/                                 

# https://github.com/Axenide/Dotfiles

# Monitor configuration
monitor=,preferred,auto,1

# Load NVIDIA environment variables only when needed
# exec-once = ~/.config/hypr/scripts/nvidia.sh

# Source a file (multi-file configs)
source = ~/.config/hypr/source/environment.conf
source = ~/.config/hypr/source/binds.conf
source = ~/.config/hypr/source/autostart.conf
source = ~/.config/hypr/source/windowrules.conf
source = ~/.config/hypr/source/input.conf
# source = ~/.config/hypr/source/plugins.conf

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 0
    col.active_border = rgba(111111FF)
    col.inactive_border = rgba(000000FF)
    layout = dwindle
}

decoration {
    blur {
        enabled = yes
        size = 5
        passes = 3
        new_optimizations = yes
        contrast = 1
        brightness = 1
    }
    rounding = 10
    drop_shadow = yes
    shadow_range = 10
    shadow_render_power = 2
    col.shadow = rgba(0, 0, 0, 0.25)
    dim_inactive = true
}

animations {
    enabled = yes
    bezier = myBezier, 0.0, 1.00, 0.0, 1.00
    animation = windows, 1, 5, myBezier, slide
    animation = border, 1, 5, myBezier
    animation = fade, 1, 5, myBezier
    animation = workspaces, 1, 5, myBezier, slidevert
}

misc {
    disable_hyprland_logo = 1
    disable_splash_rendering = 1
    focus_on_activate = 1
    # animate_manual_resizes = true
    # animate_mouse_windowdragging = true
    no_direct_scanout = yes
    allow_session_lock_restore = true
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = on
}

# device:epic mouse V1 {
    # sensitivity = -0.5
# }

opengl {
  nvidia_anti_flicker = true
}


Config File: /home/adriano/.config/hypr/source/environment.conf: Read Succeeded
env = LIBSEAT_BACKEND=logind
env = _JAVA_AWT_WM_NONREPARENTING=1
env = XDG_SESSION_TYPE,wayland
env = QT_SELECTION=/usr/bin/qmake
env = ELECTRON_ARGS="--enable-features=UseOzonePlatform --ozone-platform=wayland"
env = MOZ_DBUS_REMOTE=1
env = XCURSOR_SIZE=24
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC=1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION=1


Config File: /home/adriano/.config/hypr/source/binds.conf: Read Succeeded
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, C, killactive, 
bind = $mainMod SHIFT, escape, exit, 
bind = $mainMod, E, exec, nemo
bind = $mainMod SHIFT, E, exec, [float]nemo

# Floorp
bind = $mainMod, W, exec, floorp
# Private Floorp
bind = $mainMod SHIFT, W, exec, floorp --private-window

# # Brave
# bind = $mainMod, W, exec, brave-nightly
# # Brave Incognito
# bind = $mainMod SHIFT, W, exec, brave-nightly --incognito

# # Firefox
# bind = $mainMod, W, exec, firefox
# # Private Firefox
# bind = $mainMod SHIFT, W, exec, firefox --private-window

bind = $mainMod, space, togglefloating, 
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod SHIFT, D, togglesplit, # dwindle
# bind = $mainMod, L, exec, swaylock

# Rofi
$rofiPath = ~/.config/rofi
# Launcher
# bind = $mainMod, R, exec, $rofiPath/launcher/launcher.sh
# bind = $mainMod, R, exec, ~/.config/ags/shared/scripts/sidebar.sh toggle-applauncher
# Powermenu
bind = $mainMod, escape, exec, $rofiPath/powermenu/powermenu.sh
# Emoji
bind = $mainMod, PERIOD, exec, $rofiPath/emoji/emoji.sh
# Wallpaper
# bind = $mainMod, COMMA, exec, $rofiPath/wallpaper/wallpaper.sh
# Tmux
bind = $mainMod, T, exec, $rofiPath/tmux/tmux.sh
# Notes
bind = $mainMod, N, exec, $rofiPath/notes/notes.sh
# Volume
bind = $mainMod, V, exec, $rofiPath/applets/bin/volume.sh --row 3
# To-Do's
bind = $mainMod, Q, exec, $rofiPath/todo/todo.sh
# Calculator
# bind = $mainMod, M, exec, ~/.config/rofi/calc/calc.sh
bind = $mainMod, M, exec, gnome-calculator
# Bluetooth
bind = $mainMod, B, exec, $rofiPath/bluetooth/bluetooth.sh
# Network
# bind = $mainMod, D, exec, python ~/.config/rofi/network/network.py
# Keepass
bind = $mainMod, U, exec, $rofiPath/keepmenu/keepmenu.sh
# Calendar
bind = $mainMod, I, exec, $rofiPath/calendar/calendar.sh
# Screenshot
bind = $mainMod, S, exec, $rofiPath/screenshot/screenshot.sh

# Fullscreen screenshot
# CopySave
bind = , Print, exec, grimblast --notify copysave screen $XDG_PICTURES_DIR/Screenshots/$(date +%Y-%m-%d-%H-%M-%S).png
# Copy
bind = SHIFT, Print, exec, grimblast --notify copy screen

# Area screenshot
bind = $mainMod SHIFT, S, exec, grimblast --notify copy area

# Waybar
# Hide/Show waybar
# bind = $mainMod SHIFT, B, exec, killall -SIGUSR1 waybar

# Restart waybar
# bind = $mainMod ALT, B, exec, killall waybar;waybar

# Fullscreen toggle
bind = $mainMod, F, fullscreen,
bind = $mainMod CTRL, F, fullscreen, 1
bind = $mainMod SHIFT, F, fakefullscreen,

# Start Kitty terminal
bind = $mainMod, RETURN, exec, kitty
# Start Kitty terminal in floating mode
bind = $mainMod SHIFT, RETURN, exec, kitty --class kitty-floating
# Execute kitty-slurp.sh
bind = $mainMod ALT, RETURN, exec, ~/.config/kitty/kitty-slurp.sh

# Open notification center
# bind = $mainMod, A, exec, swaync-client -t -sw

# Fabric
bind = $mainMod ALT, B, exec, killall ax-bar; cd ~/.config/fabric/bar && python main.py

$fabricSend = python ~/.config/fabric/bar/scripts/send.py

bind = $mainMod, A, exec, $fabricSend chat
bind = $mainMod, D, exec, $fabricSend dashboard
bind = $mainMod, COMMA, exec, $fabricSend wallpapers
bind = $mainMod, R, exec, $fabricSend apps
bind = $mainMod SHIFT, B, exec, $fabricSend update-style

# Pin a window
bind = $mainMod, Y, pin,

# Center window
bind = $mainMod, G, centerwindow

# ARROWS

# Move focus with mainMod + arrow keys
bind = $mainMod, Left, movefocus, l
bind = $mainMod, Right, movefocus, r
bind = $mainMod, Up, movefocus, u
bind = $mainMod, Down, movefocus, d

# Move active window with mainMod + SHIFT + arrow keys
bind = $mainMod SHIFT, Left, movewindow, l
bind = $mainMod SHIFT, Right, movewindow, r
bind = $mainMod SHIFT, Up, movewindow, u
bind = $mainMod SHIFT, Down, movewindow, d

# Resize active window with mainMod + CTRL + arrow keys
bind = $mainMod CONTROL, Left, resizeactive, -50 0
bind = $mainMod CONTROL, Right, resizeactive, 50 0
bind = $mainMod CONTROL, Up, resizeactive, 0 -50
bind = $mainMod CONTROL, Down, resizeactive, 0 50

# Move floating window with mainMod + ALT + arrow keys
bind = $mainMod ALT, Left, moveactive, -50 0
bind = $mainMod ALT, Right, moveactive, 50 0
bind = $mainMod ALT, Up, moveactive, 0 -50
bind = $mainMod ALT, Down, moveactive, 0 50

# Move floating window with mainMod + SHIFT + ALT + arrow keys
bind = $mainMod SHIFT ALT, Left, moveactive, -10 0
bind = $mainMod SHIFT ALT, Right, moveactive, 10 0
bind = $mainMod SHIFT ALT, Up, moveactive, 0 -10
bind = $mainMod SHIFT ALT, Down, moveactive, 0 10

# VIM-LIKE

# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move active window with mainMod + SHIFT + arrow keys
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Resize active window with mainMod + CTRL + arrow keys
bind = $mainMod CONTROL, H, resizeactive, -50 0
bind = $mainMod CONTROL, L, resizeactive, 50 0
bind = $mainMod CONTROL, K, resizeactive, 0 -50
bind = $mainMod CONTROL, J, resizeactive, 0 50

# Move floating window with mainMod + ALT + arrow keys
bind = $mainMod ALT, H, moveactive, -50 0
bind = $mainMod ALT, L, moveactive, 50 0
bind = $mainMod ALT, K, moveactive, 0 -50
bind = $mainMod ALT, J, moveactive, 0 50

# Move floating window with mainMod + SHIFT + ALT + arrow keys
bind = $mainMod SHIFT ALT, H, moveactive, -10 0
bind = $mainMod SHIFT ALT, L, moveactive, 10 0
bind = $mainMod SHIFT ALT, K, moveactive, 0 -10
bind = $mainMod SHIFT ALT, J, moveactive, 0 10

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e-1
bind = $mainMod SHIFT, Z, workspace, e-1
bind = $mainMod, mouse_up, workspace, e+1
bind = $mainMod SHIFT, X, workspace, e+1

# Next/previous workspace with Z and X
bind = $mainMod, Z, workspace, -1
bind = $mainMod, X, workspace, +1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Audio
bind=,XF86AudioPlay,exec,playerctl play-pause
bind=,XF86AudioPrev,exec,playerctl previous
bind=,XF86AudioNext,exec,playerctl next

bindl=,XF86AudioMedia,exec,playerctl play-pause
bindl=,XF86AudioStop,exec,playerctl stop

# volume
bindle=,XF86AudioRaiseVolume,exec,swayosd-client --output-volume 5
bindle=,XF86AudioLowerVolume,exec,swayosd-client --output-volume -5
bindle=,XF86AudioMute,exec,swayosd-client --output-volume mute-toggle
# brightness
bindle=,XF86MonBrightnessUp,exec,swayosd-client --brightness=raise 5
bindle=,XF86MonBrightnessDown,exec,swayosd-client --brightness=lower 5
# bind=,XF86Calculator,exec, ~/.config/rofi/calc/calc.sh 
bind=,XF86Calculator,exec, gnome-calculator

# Plugins
# bind = $mainMod, D, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable

# bind = $mainMod SHIFT, SEMICOLON, exec, notify-send colon
# bind = $mainMod, SEMICOLON, exec, notify-send semicolon


Config File: /home/adriano/.config/hypr/source/autostart.conf: Read Succeeded
exec-once = rm $XDG_RUNTIME_DIR/swww.socket
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = hyprpm reload -n
exec = swww init
exec = swaync
exec = swayosd-server
# exec = wl-clip-persist -c both
# exec-once = waybar
exec = alpha start
exec-once = cd ~/.config/fabric/bar && python main.py
exec-once = maestral_qt


Config File: /home/adriano/.config/hypr/source/windowrules.conf: Read Succeeded
# Blur
# blurls=waybar
# layerrule = ignorezero, waybar
# layerrule = ignorezero, swaync-control-center
layerrule = noanim, swaync-control-center
layerrule = noanim, swaync-notification-window
# layerrule = ignorezero, rofi
layerrule = noanim, rofi

# blurls=rofi
# blurls=swaync-control-center

# Fabric
layerrule = noanim, fabric
# layerrule = ignorealpha 0.75, fabric
# blurls=fabric

windowrulev2 = float, class:^(org.gnome.Calculator)$

# Firefox Picture-in-picture
windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-picture)$
windowrulev2 = move 1492 839, class:^(firefox)$, title:^(Picture-in-picture)$
windowrulev2 = size 427 240, class:^(firefox)$, title:^(Picture-in-picture)$
windowrulev2 = pin, class:^(firefox)$, title:^(Picture-in-picture)$

# Floorp Picture-in-picture
windowrulev2 = float, class:^(floorp)$, title:^(Picture-in-picture)$
windowrulev2 = move 1492 839, class:^(floorp)$, title:^(Picture-in-picture)$
windowrulev2 = size 427 240, class:^(floorp)$, title:^(Picture-in-picture)$
windowrulev2 = pin, class:^(floorp)$, title:^(Picture-in-picture)$

# Kitty floating
windowrulev2 = float, class:^(kitty-floating)$
# windowrulev2 = dimaround, class:^(kitty-floating)$

layerrule=noanim,selection


Config File: /home/adriano/.config/hypr/source/input.conf: Read Succeeded
input {
    kb_layout = us
    kb_variant = altgr-intl
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.25
    }

    sensitivity = 0
}

======Config-End========
```

</details>

### Description

When I tried to do `movewindow, u` it wasn't working, but worked with all other directions. Then I added borders to windows again and... It worked.

### How to reproduce

```
general {
    border_size = 0
}

bind = $mainMod SHIFT, Up, movewindow, u
```

The binding can be any combination.

**Comment by 299792458ms** [comment] 2024-06-14 07:26
Tried to reproduce with the same version and did not happen. 
I had your bind `bind = $mainMod SHIFT, Up, movewindow, u` like this: `bind = $mod SHIFT, up, movewindow, u` and it worked both ways, also with or without border.

**Comment by Axenide** [comment] 2024-06-14 07:40
@299792458ms That's really weird. This is happening both in my PC and my laptop.

**Comment by macydnah** [comment] 2024-06-18 19:04
This is really weird indeed. I have wouldn't imagine that this is related to `border_size`. I can reproduce this bug, but in my case behaves differently:

For more context I'm on dwindle layout and I daily driver `border_size = 0`

Windows on tile mode acts totally fine and behaves as expected (i.e. `bind = $mainMod SHIFT, Up, movewindow, u`  moves the window up in the grid and so on the `l`,`r`,`d`  parameters moves the windows correctly to their respective directions).

As I change the window to floating mode, I can't move it neither left nor up, but moving it to the right and down works. As @Axenide states setting `border_size = 1` makes everything work just right.

Here's my info

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)


System Information:
System name: Linux
Node name: HuaaaliP0NKH-ER0S
Release: 6.9.1-zen1-2-zen
Version: #3 ZEN SMP PREEMPT_DYNAMIC Sat May 25 22:07:16 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0126] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/macydnah/.config/hypr/hyprland.conf: Read Succeeded
# ~/.config/hypr/hyprland.conf

#monitor=name,resolution,porition,scale
monitor=,preferred,auto,auto

$mod = SUPER
#$terminal = st
$terminal = footclient
$fileManager = pcmanfm
$menu = /home/macydnah/.config/rofi/launcher.sh

exec-once = pcmanfm -d
exec-once = foot --server
exec-once = swaybg --output LVDS-1 --image /usr/share/backgrounds/fgm.png --mode fill


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = GDK_BACKEND,wayland
env = LIBVA_DRIVER_NAME,i965
env = LIBVA_DRIVERS_PATH,/usr/lib/dri
env = MOZ_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland-egl
env = SDL_VIDEODRIVER,wayland
env = XDG_SESSION_TYPE,wayland
env = _JAVA_AWT_WM_NONREPARENTING,1

#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 2
    gaps_out = 4

    border_size = 0

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

cursor {
    inactive_timeout = 2
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 3

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.9

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
#    screen_shader = /home/macydnah/.config/hypr/blue-light-filter.frag

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        
        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default	
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = true
    force_split = 2
    preserve_split = true
    no_gaps_when_only = 0
    use_active_for_splits = true

    bind = $mod, P, pseudo
    bind = $mod, C, togglesplit
}

master {
    new_is_master = true
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

binds {
    allow_workspace_cycles = true
}

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = altgr-intl
    kb_model = pc104
    kb_options =
    kb_rules =

    follow_mouse = 2

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


####################
### KEYBINDINGS ###
####################

# Volume/Brightness Control
bind = ,XF86AudioMute, exec, volfade.sh -m
bind = ,XF86AudioRaiseVolume, exec, volfade.sh -i
bind = ,XF86AudioLowerVolume, exec, volfade.sh -d
binde = ,XF86MonBrightnessUp, exec, xbacklight -inc 3 -fps 60 -time 111 -perceived
binde = ,XF86MonBrightnessDown, exec, xbacklight -dec 3 -fps 60 -time 111 -perceived
bind = SHIFT,XF86MonBrightnessUp, exec, hyprctl keyword decoration:screen_shader /home/macydnah/.config/hypr/blue-light-filter.frag
bind = SHIFT,XF86MonBrightnessDown, exec, hyprctl keyword decoration:screen_shader '' 
bind = $mod, Menu, exec, kblight

# Keybinds/shortcuts for applications
bind = $mod, Return, exec, $terminal
bind = $mod, grave, exec, togglescrat.sh
bind = $mod, A, exec, $menu
#bind = $mod, B, exec, $bar
bind = $mod, E, exec, $fileManager
bind = $mod, N, exec, networkmanager_dmenu

# Window manager functions
bind = $mod, Q, killactive
bind = $mod, F, fullscreen, 0
bind = $mod, Tab, workspace, previous
bind = $mod, space, togglefloating,
bind = $mod SHIFT, Escape, exec, hyprctl dispatcher exit

# Keyboard navigation
bind = $mod, J, movefocus, l
bind = $mod, semicolon, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, d
bind = $mod SHIFT, J, movewindow, l
bind = $mod SHIFT, semicolon, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mod, S, togglespecialworkspace, magic
bind = $mod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mod + scroll
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

# Move/resize windows with mod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow


##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

floating-st {
windowrulev2 = pseudo,class:^(floating-st)$
windowrulev2 = workspace special:magic,class:^(floating-st)$
}

floating-foot {
windowrulev2 = workspace special:magic,class:^(floating-foot)$

windowrulev2 = size 677 382,class:^(floating-foot)$
windowrulev2 = float,class:^(floating-foot)$
windowrulev2 = pseudo,class:^(floating-foot)$
windowrulev2 = tile,class:^(floating-foot)$
}

scrcpy {
windowrulev2 = float,class:^(scrcpy)$,title:^(SM-G935F)$
windowrulev2 = size 32% 99%,class:^(scrcpy)$,title:^(SM-G935F)$
windowrulev2 = tile,class:^(scrcpy)$,title:^(SM-G935F)$
windowrulev2 = pseudo,class:^(scrcpy)$,title:^(SM-G935F)$
}

======Config-End========
```

</details>

**Comment by Axenide** [comment] 2024-06-18 19:15
@macydnah Yeah, I forgot to say that this happened when I tried to move while I had a floating window. But only up doesn't work.

**Comment by cebem1nt** [comment] 2024-06-20 02:50
Hi, im facing the same issue with floating windows. but in my case window doesn't move to the left. i've fixed that by setting border_size and deleting inactive / active border's colors variables

**Comment by MightyPlaza** [comment] 2024-07-24 15:12
didn't I fix this already?
the window had to be floating
@vaxerski

**Comment by MightyPlaza** [comment] 2024-07-24 16:09
dupe of https://github.com/hyprwm/Hyprland/issues/6372

**Closed** 2024-07-24 17:08 UTC
Labels: bug

**Comment by cebem1nt** [comment] 2024-07-24 17:10
Issue still persists , v0.41.2

https://github.com/user-attachments/assets/54d12da5-dc32-4f0b-84c6-871270772fc1
