### ISSUE TITLE
IME in foot terminal is weird

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#504] opened 2022-08-09 11:35 UTC
Hyprland version: hyprland-bin 0.10 from AUR
input method: fcitx5 with Chinese pinyin input method.
IME works well in kitty, but in foot, IME can't find the position of cursor. After selected word in IME, it doesn't dissappear.
![20220809_19h34m27s_grim](https://user-images.githubusercontent.com/24190403/183637654-ce2d6d27-9f2e-437e-b954-92dc54840ef3.png)

**Comment by vaxerski** [comment] 2022-08-10 15:25
![image](https://user-images.githubusercontent.com/43317083/183943644-84a1c197-422d-4d2d-9097-1b0c46f50a2f.png)

cannot reproduce. This is foot.

**Comment by dragove** [comment] 2022-08-11 14:56
It seems like a random bug, I don't know what conditions to make it happen.
Here is my hyprland config file: [my config](https://github.com/dragove/dotfiles/blob/master/hyprland/.config/hypr/hyprland.conf)
And the attachment shows my bug. (There is also a weird bug in obs-studio, some frames disappears, it can be reproduced with kdenlive)

https://user-images.githubusercontent.com/24190403/184163087-01d4164a-80a8-447d-8a70-8804d546ceeb.mp4

**Comment by KyleUltimate** [comment] 2022-08-11 15:02
>  After selected word in IME, it doesn't dissappear.

I can only produce this, cannot reproduce the displacement

**Comment by smartding** [comment] 2022-08-13 04:58
For me, the fcitx5 candidate popup window shows at the right position.
But the popup window remains after a word is  selected.

**Comment by vaxerski** [comment] 2022-08-23 09:16
fixed in 23c5760538c8db68c0b0d3b170c6e812f50a1bb4

**Closed by vaxerski** 2022-08-23 09:16 UTC
Labels: bug
