### ISSUE TITLE
[Plugins] Cannot hook to listener_monitorDestroy

### ISSUE THREAD

**Issue by levnikmyskin** [hyprwm/Hyprland#3971] opened 2023-11-26 17:14 UTC
### Hyprland Version

Hyprland, built from branch main at commit 68e57b7ee36f015d99988f38cb3a8b83c23ae7c3  (renderer: proper full occlusion checks for back layer).

### Bug or Regression?

Bug

### Description

Hi!
So, this must be me getting something wrong, but I've been trying for several hours and I really don't know what's going on.

I'm trying to hook to `Events::listener_monitorDestroy` (`events/Monitors.cpp`, line 184). The hook itself seems to be successfull, but when I call the original function, Hyprland crashes with no useful logs :/.
Debugging into it, the original events function never gets called, Hyprland crashes the moment I call the original function from my code. I've also verified that pointers are valid at that point.  
Notice that I'm also hooking to `listener_newOutput`, and calling its original function works successfully

Now, to the weird part (which leads me to believe it's my fault probably):  
If I compile Hyprland with `make debug`, the call to the original function works perfectly, no crashes whatsoever.

Could you please help me verify whether this is my fault or Hyprland's?

### How to reproduce

Snippet of the code I used:
```cpp
inline CFunctionHook*               g_pMonitorDestroy = nullptr;
typedef void (*origMonitorDestroy)(void*, void*);

inline CFunctionHook* g_pMonitorAdded = nullptr;
typedef void (*origMonitorAdded)(void*, void*);

// ...

// This only works if I compile Hyprland with make debug
void hookMonitorDestroy(void* owner, void* data) {
    (*(origMonitorDestroy)g_pMonitorDestroy->m_pOriginal)(owner, data);
}

// This always works well
void hookMonitorAdded(void* owner, void* data) {
    (*(origMonitorAdded)g_pMonitorAdded->m_pOriginal)(owner, data);
}

// ... 


APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
    PHANDLE = handle;

    static const auto METHODS_DESTROY = HyprlandAPI::findFunctionsByName(PHANDLE, "listener_monitorDestroy");
    static const auto METHODS_ADDED   = HyprlandAPI::findFunctionsByName(PHANDLE, "listener_newOutput");

    g_pMonitorDestroy = HyprlandAPI::createFunctionHook(PHANDLE, METHODS_DESTROY[0].address, (void*)&hookMonitorDestroy);
    g_pMonitorAdded   = HyprlandAPI::createFunctionHook(PHANDLE, METHODS_ADDED[0].address, (void*)&hookMonitorAdded);
}

```

**Comment by vaxerski** [comment] 2023-11-26 17:36
dupe of #2479 I am pretty sure

**Closed by vaxerski** 2023-11-26 17:36 UTC
Labels: bug
