### ISSUE TITLE
Hyprland crashes when disabling last monitor

### ISSUE THREAD

**Issue by nguyenston** [hyprwm/Hyprland#4628] opened 2024-02-06 02:32 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 181f651de2e67917c7fcc72f7a69e6f4707954e5  ().
Date: 2024-02-05
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.7.2
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu Jan 25 23:45:31 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107BM [GeForce RTX 3050 Mobile] [10de:25e2] (rev a1) (prog-if 00 [VGA controller])
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 01) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240131.b8b232a"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes when I close my laptop lid and reopen it again when there is no external monitor connected. For context, I have this in my `hyprland.conf`:

```
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "desc:California Institute of Technology 0x1410, 3072x1920, 0x0, 2"
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "desc:California Institute of Technology 0x1410, disable"
```

And this in my `configuration.nix`:

```
  services.logind = {
    lidSwitch = "suspend";
    lidSwitchExternalPower = "suspend";
    lidSwitchDocked = "ignore";
  };
```

### How to reproduce

1. Launch `Hyprland`
2. Make sure there are no external monitors connected
3. Close the lid and make sure laptop is suspended
4. Reopen the lid
5. Maybe fiddle with the touchpad? I'm not sure since it showed me a black screen at first and only booted me to tty when I do this.

### Crash reports, logs, images, videos

Attached is two different instances of recreating the crash.
[hyprlandd_log_1.txt](https://github.com/hyprwm/Hyprland/files/14173970/hyprlandd_log_1.txt)
[coredump_1.txt](https://github.com/hyprwm/Hyprland/files/14173972/coredump_1.txt)
[hyprlandd_log_2.txt](https://github.com/hyprwm/Hyprland/files/14173973/hyprlandd_log_2.txt)
[coredump_2.txt](https://github.com/hyprwm/Hyprland/files/14173974/coredump_2.txt)

**Comment by vaxerski** [comment] 2024-02-07 00:57
[patch.txt](https://github.com/hyprwm/Hyprland/files/14187709/patch.txt)

try

**Comment by nguyenston** [comment] 2024-02-07 03:16
Sorry I'm not the most familiar with this, how do you apply the patch?

**Comment by nguyenston** [comment] 2024-02-07 06:07
I found a new way to crash hyprland, same setup as above, along with the patch.
1. Launch `Hyprland`
2. Make sure there are no external monitors connected
3. Close the lid and make sure laptop is suspended
4. Connect an external monitor
5. Reopen the lid

Here are the logs and coredump
[hyprlandd_log_3.txt](https://github.com/hyprwm/Hyprland/files/14189732/hyprlandd_log_3.txt)
[coredump_3.txt](https://github.com/hyprwm/Hyprland/files/14189736/coredump_3.txt)

**Comment by Cybolic** [comment] 2024-02-07 23:31
At the risk of adding noise, I'm not sure this is related to touch handling. On my desktop PC, with no touchpads or such attached, Hyprland will crash if my (singular) monitor goes fully to sleep. Disabling DDC-CI on the monitor seems to prevent this, so it looks similar to this issue: monitor disappears, Hyprland crashes.

**Comment by 1over137** [comment] 2024-02-08 21:26
I wonder if this is related to https://github.com/hyprwm/Hyprland/issues/4638.
I could reproduce that one easily, and I ran a git bisect.
7b3d03938888f399c3c14adfce73ea22bbe461ea is the first bad commit

**Comment by nguyenston** [comment] 2024-02-08 22:22
Yes, it seems the touch pad only induces a workspace change/creation and that in turn crashes `Hyprland` when there are no screen enabled.

**Comment by vaxerski** [comment] 2024-02-13 18:20
can someone get a `bt -full` from a debug build

**Comment by nguyenston** [comment] 2024-02-13 19:17
I have a debug build built from source. I'd do it but I'm not sure how to. Can you elaborate?

**Comment by vaxerski** [comment] 2024-02-13 21:11
after crash `coredumpctl debug Hyprland` and `bt -full`

**Comment by nguyenston** [comment] 2024-02-13 21:37
Here you go, this contains both the `coredump` output and `bt` output.

[coredump_debug_bt.txt](https://github.com/hyprwm/Hyprland/files/14272509/coredump_debug_bt.txt)

**Comment by dedsm** [comment] 2024-02-15 11:50
I have a similar error but judging from the coredump it seems to take a different path:
[coredump.txt](https://github.com/hyprwm/Hyprland/files/14296344/coredump2.txt)

The behavior is the same, after unplugging my dock, hyprland will fail since my laptop's screen was disabled, I've tried enabling the screen in the docked kanshi profile and hyprland does a very smooth transition when disconnecting the dock.

**Comment by erahhal** [comment] 2024-02-17 20:59
Since #4638 was closed, I'll attach crash logs here. I'm still seeing crashes with commit e4bb5fa4af1a6c36aab1c28651b5403dc4952f93

[hyprlandCrashReport82366.txt](https://github.com/hyprwm/Hyprland/files/14320214/hyprlandCrashReport82366.txt)

apologies if this is the same thing as before.

**Comment by erahhal** [comment] 2024-02-18 00:04
BTW the crash happens when I change the hyprland config and it reloads automatically. No change of monitor layout/enabling/disabling monitors.

**Comment by alexandru0-dev** [comment] 2024-02-19 19:05
thx to https://github.com/hyprwm/Hyprland/pull/4738 i have no issues anymore
@1over137 @dedsm @nguyenston try it out and pls report if any issues

**Comment by vaxerski** [comment] 2024-02-19 20:30
closing then

**Closed by vaxerski** 2024-02-19 20:30 UTC
Labels: bug

**Comment by nguyenston** [comment] 2024-02-21 19:25
Unfortunately the problem still persists for me, I'm still able to crash `Hyprland` following the steps here https://github.com/hyprwm/Hyprland/issues/4628#issuecomment-1931353496. I've attached the new logs and coredump-bt, this is from the latest commit.

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fc5ca391adeef3673e579ebf21759032c2455efc  ().
Date: 2024-02-21
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.7.5
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:14:32 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107BM [GeForce RTX 3050 Mobile] [10de:25e2] (rev a1) (prog-if 00 [VGA controller])
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 01) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240221.0e74ca9"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

[hyprlandd_log_4.txt](https://github.com/hyprwm/Hyprland/files/14364098/hyprlandd_log_4.txt)
[coredump_4.txt](https://github.com/hyprwm/Hyprland/files/14364099/coredump_4.txt)

**Comment by nguyenston** [comment] 2024-02-23 04:44
With this patch here https://github.com/hyprwm/Hyprland/issues/4770#issuecomment-1956442344, the crash no longer occurs. However, monitor settings are still skipped when waking up from suspend.

**Comment by erahhal** [comment] 2024-04-14 16:47
I've found that the issue no longer occurs as well, except in one case: Undocking while DPMS is off. Still get the red screen every time.
