### ISSUE TITLE
Can't interact with certain steam windows

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/Hyprland#2661] opened 2023-07-06 13:32 UTC
Since the new steam UI rolled out I can't interact with some windows, mainly the context menu opened by right-clicking someone my friendlist.

# Steps to reproduce
- Open steam
- Open friendlist
- Right click someone on friendlist

# Expected outcome
I can interact with the opened menu

# Actual outcome
Menu can't be interacted with

----
I ran a git bisect and the offending commit seems to be 
https://github.com/hyprwm/Hyprland/commit/fcf1bafb098c8f756550195269dcd95202124277

Had some trouble running the bisect as after the `git bisect skip` the menus wouldn't always show up or crash steam.

<details><summary>Bisect log</summary><p>

```
# bad: [51a930f802c71a0e67f05e7b176ded74e8e95f87] version: bump to 0.26.0
# good: [c02ac5e08a425d5ec44b48e24ca2695d9cafd38d] fix un-normalized missed color
git bisect start 'v0.26.0' 'v0.20.0beta'
# bad: [06244555915339967864292dd0b83cd9732516d8] Meson: add rdynamic ld flag
git bisect bad 06244555915339967864292dd0b83cd9732516d8
# bad: [38c25bb50d76409193db2438db60369f3868edf9] Added a crash reporter
git bisect bad 38c25bb50d76409193db2438db60369f3868edf9
# good: [12e293e3092b03dbb9d82e7a749f482ef2b7ea6e] update animated deco values after setprop
git bisect good 12e293e3092b03dbb9d82e7a749f482ef2b7ea6e
# bad: [be6325dd4b0a99561281ba557f1d37e945fa183f] ext_workspace_unstable: send done after output_enter when wl_output is bound late (#1481)
git bisect bad be6325dd4b0a99561281ba557f1d37e945fa183f
# skip: [5d35c0432b70e2d5e82296caf7f496dc4612f3e5] add a minimize ipc event
git bisect skip 5d35c0432b70e2d5e82296caf7f496dc4612f3e5
# good: [32381fe6c4e33232401d7a74f587ee7296a61fcf] send a 1 on unknown minimize event
git bisect good 32381fe6c4e33232401d7a74f587ee7296a61fcf
# good: [a46abd8b1adaf850e243380ea2a7d6b02677fc86] update wlroots dep
git bisect good a46abd8b1adaf850e243380ea2a7d6b02677fc86
# good: [d81f45e54a423cf3af522ca901a2f356d63100c0] clear focus on failed unlock attempt
git bisect good d81f45e54a423cf3af522ca901a2f356d63100c0
# good: [3e6601fa2989d750135d218c1fea3a13ddeae5c3] ext_workspace_unstable: send output_enter when wl_output is bound late (#1480)
git bisect good 3e6601fa2989d750135d218c1fea3a13ddeae5c3
# good: [668842124067f9b6513edf1c28478bec12d709a0] minor adjustments to xwayland positioning
git bisect good 668842124067f9b6513edf1c28478bec12d709a0
# bad: [fcf1bafb098c8f756550195269dcd95202124277] conform to unmanaged X11 activate requests
git bisect bad fcf1bafb098c8f756550195269dcd95202124277
# first bad commit: [fcf1bafb098c8f756550195269dcd95202124277] conform to unmanaged X11 activate requests
```

</p></details>

**Comment by Roger-Roger-debug** [comment] 2023-07-08 18:02
Commenting out the line  [     g_pCompositor->focusWindow(PWINDOW);](https://github.com/hyprwm/Hyprland/blob/f49af187bc0755f9b5be9376bfd52c0cf12c1e11/src/events/Windows.cpp#L940) makes the menus interactable again but reintroduces the issues of the windows not always showing up.

This table sums up the behavior when right-clicking someone in my friend list with and without the line commented out (oddly enough the menu opened by right clicking the game works).
|  | `focusWindow` | Commented out |
|---|----|----|
| Friendlist | doesn't get focus | gets focus|
| right click menu | not interactable | interactable |
| workspace | no window focused | friendlist has focus |
| Steam issues |  everything ok| context menu randomly doesn't show up, main steam window content shifts a few pixels |
| mouse leaving menu | stays as long as friendlist is focused | closes |

**Comment by vaxerski** [comment] 2023-07-10 11:51
I think this was a steam bug and IIRC got fixed?

**Comment by Roger-Roger-debug** [comment] 2023-07-10 14:06
Could be as steam is the only app exhibiting this behavior. I switched to steam beta and even reinstalled it a few days ago so if it was fixed then it's something else on my end that's still breaking it.

**Comment by vaxerski** [comment] 2023-07-10 15:43
for me only some right-click menus dont get focus, friendlist ok

**Comment by Roger-Roger-debug** [comment] 2023-07-10 18:15
Didn't know of the setting. Looks like something is misconfigured on my end, will try out some more stuff.

**Comment by Moltenkore** [comment] 2023-07-16 18:17
I'm running into this issue too, specifically the friend context menu when you open a chat and right click their name at the top.

Did you find a fix or workaround for it?

**Comment by Roger-Roger-debug** [comment] 2023-07-17 11:46
I haven't actually but fullscreening makes it work again.

**Comment by abigrock** [comment] 2023-07-20 20:05
I am seeing the same thing with the friends list and other places in the steam UI. For example when clicking the "Add a Game" option at the bottom left the context menu is unresponsive. Doesn't matter if the "context menu focus compatibility mode" option is enabled or not. As mentioned in the above comments, it does work if steam is full-screened.

**Comment by zjeffer** [comment] 2023-07-22 20:49
I have the same behaviour as @abigrock.

@Roger-Roger-debug  Can you reopen this issue? Not sure if this is a steam bug or Hyprland bug. Does it work on other Wayland compositors like sway?

**Comment by Roger-Roger-debug** [comment] 2023-07-23 18:01
I assumed it was a mostly me issue since it seemed to work for Vaxerski. I have tried it out with Sway stable and didn't have the issue there. Could still be a steam issue though...

**Comment by romanstingler** [comment] 2023-08-03 19:06
@zjeffer @Roger-Roger-debug can you test with the latest commit or -git package?

**Comment by Roger-Roger-debug** [comment] 2023-08-03 21:44
Still happens on 2e6693fbb650dd2c9b7ad4b6d830899589504bda for me.

**Comment by zjeffer** [comment] 2023-08-03 22:02
Same for me.

**Comment by MaKaNu** [comment] 2023-08-26 20:10
hyprland user same here can reproduce the fullscreen working

**Comment by ogios** [comment] 2023-09-03 01:08
same issue with `add a game`

**Comment by ouzdll** [comment] 2023-09-03 03:28
I can reproduce this bug, both with Steam stable and beta and both with and without enabling the "Enable context menu compatibility mode" option. Making the friend list window fullscreen (using `fullscreen 0` dispatcher, not with the `1` as arg) seems like fixes the issue. I've been searching for this issue on steam-for-linux repo and haven't found anyone experienced the exact thing and this makes me think it's somehow related to Hyprland (haven't tried with another DE or WM, sorry).

**Comment by Roger-Roger-debug** [comment] 2023-09-04 18:05
iirc I tried this on sway originally and there it worked and concluded that it must be specific to Hyprland (and it used to work before the commit I mentioned when I opened the issue)

**Comment by gwstorm** [comment] 2023-09-26 16:44
Upgrading to Hyprland 0.30.0-1 breaks the full screen workaround to use the context menu on the friends list for me. Returning to 0.29.1-1 restored the workaround.

**Comment by Roger-Roger-debug** [comment] 2023-09-27 09:36
You can still use big picture mode and use the functions that way if you have to

**Comment by pwnfooj716** [comment] 2023-10-05 01:34
> You can still use big picture mode and use the functions that way if you have to

Thanks for the workaround! I panicked when the fullscreen trick no longer worked since i really didn't want to have to downgrade. Really hope a real fix to this issue can be found. It doesn't happen on riverwm, but I prefer to use hyprland.

**Comment by vaxerski** [comment] 2023-10-06 01:09
if 0.30 breaks the fullscreen fix I'd love for that to be bisected

**Comment by Roger-Roger-debug** [comment] 2023-10-06 12:36
Did a quick bisect and got this
```
# bad: [1b48642fd15c433c53876f1b933dcd46265caf8f] props: bump version to 0.30.0
# good: [0a78f6031c8fcc6773f136fccde3d560aaac239d] props: bump ver to 0.29.0
git bisect start 'v0.30.0' 'v0.29.0'
# good: [a781c152ff9805c1a5c69c6d8575deee6fdce34b] fix(layout): remove `focusWindow` calls from `onWindowCreatedTiling` (#3233)
git bisect good a781c152ff9805c1a5c69c6d8575deee6fdce34b
# bad: [e6651334f264591cffef96738a2355b1b207eaa6] refactor: flatten nesting `if`s in layout window creation method (#3294)
git bisect bad e6651334f264591cffef96738a2355b1b207eaa6
# good: [bc41d7ec8515723d79cc921454a739d65db69467] fix: inconsistent behaviour where last workspace was not saved (#3261)
git bisect good bc41d7ec8515723d79cc921454a739d65db69467
# good: [b884544ee63b4c3b3b150ff69cf24c90058c2777] input: don't refocus on switched workspace on the same monitor
git bisect good b884544ee63b4c3b3b150ff69cf24c90058c2777
# good: [84f8f4d77ddf4b6c772459584234e1f8f9d5f2ce] keybinds: warp cursor to correct window in moveWindowOutOfGroup (#3290)
git bisect good 84f8f4d77ddf4b6c772459584234e1f8f9d5f2ce
# good: [0dc8289b0292d3c3c35a06fdecbe41cd57a1a918] dwindle: fix: don't merge groups when moving window (#3302)
git bisect good 0dc8289b0292d3c3c35a06fdecbe41cd57a1a918
# good: [0e64dd2ea58aa1b41418d78d5aa27f787de6a267] master: respect the resizing animation option in master layout (#3300)
git bisect good 0e64dd2ea58aa1b41418d78d5aa27f787de6a267
# first bad commit: [e6651334f264591cffef96738a2355b1b207eaa6] refactor: flatten nesting `if`s in layout window creation method (#3294)
```

However it might not be the commit that really breaks it. At that commit I just couldn't open the menus, maybe I'll find some time later to test the other commits.

**Comment by abigrock** [comment] 2023-10-25 22:53
Chiming in with a quick partial workaround on latest stable (0.30.0). Setting steam to small mode and using the Games menu at the top allows interacting with that menu. The Friend List right-click menu is still broken, but it tends to work fine inside the steam in-game overlay. Worth noting I have the "Enable context menu focus compatibility mode" interface option enabled.

**Comment by K0SS4** [comment] 2023-10-28 23:33
Same issue for me. Cannot even interact with the top bar menus(Steam, View, Friends etc.). My workaround was to launch steam with gamescope as described here: https://wiki.archlinux.org/title/Gamescope

It's only possible to set a static resolution for steam app so it's not perfect(steam subwindows get buggy sometimes)

**Comment by Sincide** [comment] 2023-11-08 19:24
This happens to me on 0.31 and 0.32. 
It's working as it should on 0.30 fyi

**Comment by phonetic112** [comment] 2023-11-21 20:36
If anyone is still having this issue, try adding this line to your config:
```
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
```
This lets me hover through most of the drop-down menus in the main UI, but the friends list windows are still borken for me.

**Comment by Doable149** [comment] 2023-12-03 16:09
> If anyone is still having this issue, try adding this line to your config:
> 
> ```
> windowrulev2 = stayfocused, title:^()$,class:^(steam)$
> ```
> 
> This lets me hover through most of the drop-down menus in the main UI, but the friends list windows are still borken for me.
> 
> UPDATE: Add this line as well to fix friends list:
> 
> ```
> windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
> ```

Thank you so much!

**Comment by jh-devv** [comment] 2023-12-10 11:40
> If anyone is still having this issue, try adding these lines to your config:
> 
> ```
> windowrulev2 = stayfocused, title:^()$,class:^(steam)$
> windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
> ```
> 
> This lets me hover through the drop-down menus in the main UI, as well as the friends list.

Thank you so much! This worked :3

**Comment by Roger-Roger-debug** [comment] 2023-12-30 12:59
Huh, focus used to stick to steam, making me unable to interact with any other windows on the workspace but now it works as expected.

**Comment by gwstorm** [comment] 2023-12-30 17:25
> Huh, focus used to stick to steam, making me unable to interact with any other windows on the workspace but now it works as expected.

I just updated to the latest git and I'm still unable to interact with menus normally. In fact, I can't interact with my friends at all anymore. My friends list now shows a transparent window that I can interact with, but can't see what it is that I'm interacting with. If anything, it's slightly worst now because of that. 

Are you still using any window rules? Which version of Hyprland are you on?
![2023-12-30_09-19](https://github.com/hyprwm/Hyprland/assets/57640252/a745ff9d-905f-4a14-9d0c-1fc8c7edd0a3)

**Comment by zjeffer** [comment] 2023-12-30 18:48
> I just updated to the latest git and I'm still unable to interact with menus normally. In fact, I can't interact with my friends at all anymore. My friends list now shows a transparent window that I can interact with, but can't see what it is that I'm interacting with

I have the same issue as you, on this version:

```
Hyprland, built from branch main at commit 78f9ba9fdd7e258747b862ca2ae7d4cf5335f4ed dirty (makefile: add symbolic link for lowercase binary name).
Date: Fri Dec 29 10:37:58 2023
Tag: v0.33.1-113-g78f9ba9f
```

**Comment by gwstorm** [comment] 2023-12-30 18:59
I think this might have been closed prematurely. The original menu interaction issue of 

- Open steam
- Open friendlist
- Right click someone on friendlist

all still exist.

**Comment by Roger-Roger-debug** [comment] 2023-12-30 19:44
Nvm, I was a dummy and actually just overlooked the window rules I had.

With the windowrules applied it works perfectly for me on the latest release and git the last time I checked.
I'm not entirely sure how much of this actually a bug or an unintended side-effect from the way Hyprland works (though you could argue that that's still a bug).

It might be better to document the workaround somewhere in the wiki if the bug just occurs because Steam does menus in a weird way that doesn't play well with Hyprland?

**Comment by zjeffer** [comment] 2023-12-30 19:49
> With the windowrules applied it works perfectly for me on the latest release and git the last time I checked.

With these rules I get a transparent right-click menu:

```
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
```

Without the rules, the right-click menu immediately dissapears, but is also transparent.

**Comment by Roger-Roger-debug** [comment] 2023-12-30 19:51
> > With the windowrules applied it works perfectly for me on the latest release and git the last time I checked.
> 
> With these rules I get a transparent right-click menu:
> 
> ```
> windowrulev2 = stayfocused, title:^()$,class:^(steam)$
> windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
> ```
> 
> Without the rules, the right-click menu immediately dissapears, but is also transparent.

Tried latest git and I get the same behavior. Menus with windowrules worked last time I checked (~2 weeks ago), I can bisect this tomorrow.

**Comment by phonetic112** [comment] 2023-12-30 20:30
I bisected blurry right click menu, c0d9dcc586ab17bf67c48c02a08bca28727f9237 is what broke it

**Comment by Roger-Roger-debug** [comment] 2024-01-31 16:15
Is this supposed to fix all menus?

Drop down menus still don't work for me. Is this actually a Hyprland issue, or is steam doing something it's not supposed to do? If it's the latter it's probably just better to document the workaround somewhere on the wiki, no?

**Comment by jh-devv** [comment] 2024-02-07 14:08
> I bisected blurry right click menu, [c0d9dcc](https://github.com/hyprwm/Hyprland/commit/c0d9dcc586ab17bf67c48c02a08bca28727f9237) is what broke it

Do I need the rules still? I use the git version (Flake, NixOS) of Hyprland?

**Comment by Roger-Roger-debug** [comment] 2024-02-21 13:48
Okay, finally got around to testing this a bit more. As far as I can tell both windowrules are still needed. 

- Add a game and the menu bar need both window rules
- Right clicking a friend works, but subsequent menus are broken without both windowrules

**Comment by y0nei** [comment] 2024-03-01 20:41
The windowrules now freeze hyprland

**Comment by 42Willow** [comment] 2024-03-02 01:30
I can confirm, this also happens to me. This issue should be reopened

**Comment by Seercat3160** [comment] 2024-03-02 02:03
The issue with the window rules was mentioned in my issue #4722, and should be fixed in 0.36.0 (though I haven't tested).

**Comment by willswats** [comment] 2024-03-02 11:07
The drop down menus work for me on git without the windowrules most of the time, however, the "Add a game" button occasionally doesn't disappear after clicking off of it (I had to click on it and click off of it about 5 times to make it occur), and it causes Steam to freeze for a few seconds, or sometimes it causes the Steam window to close. Other Steam windows (such as settings) also don't close instantly, instead they go blurry and transparent for a second, or sometimes for longer. Both of these issues occur with and without the windowrules.

**Comment by Roger-Roger-debug** [comment] 2024-03-02 13:10
Tested again with latest git version, steam beta and compatibility UI enabled and can confirm willswats observations. 

As far as I can tell every all menus mentioned in this issue (add a game, drop down, friendlist, ...) work now but have a high probability (maybe 30%?) of freezing or crashing the steam client. Only when that happens do menus not correctly disappear again and steam cpu usage rises pretty high. 

While the experience isn't great, steam is now functional without windowrules.
Should the freezing/crashing be tracked in another issue and this one closed?

**Comment by jh-devv** [comment] 2024-03-04 18:49
Now there is an issue that the windows close too fast!

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`

Hyprland, built from branch  at commit v0.35.0  ().
Date: 2024-02-05
```

**Comment by vaxerski** [comment] 2024-03-04 19:27
![image](https://github.com/hyprwm/Hyprland/assets/43317083/568544a7-a62e-4e90-9f44-0f6d7dab76fd)

what beta ui are yall talkin bout

**Comment by willswats** [comment] 2024-03-04 21:04
> ![image](https://private-user-images.githubusercontent.com/43317083/309876921-568544a7-a62e-4e90-9f44-0f6d7dab76fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODU5MDEsIm5iZiI6MTcwOTU4NTYwMSwicGF0aCI6Ii80MzMxNzA4My8zMDk4NzY5MjEtNTY4NTQ0YTctYTYyZS00ZTkwLTlmNDQtMGY2ZDdkYWI3NmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDIwNTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzI0ODhmZTNkMGM2NjNhOTE2YzZkZWUyMTFjNDA5OGMxMjYxZmU5YWJhNGU0ZDdmNjZjY2U2NjU3OTJmMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9LpV7DRErFTlgWteKLxBVHtUfawy_Av_nZrSbvFbDVI)
> 
> what beta ui are yall talkin bout

Steam Settings -> Interface -> Client Beta Participation. The issues that I mentioned occur with and without the beta.

**Comment by vaxerski** [comment] 2024-03-05 02:38
your issues just sound like typical steam. The client is very slow and poorly designed.

**Comment by MaKaNu** [comment] 2024-03-05 09:09
I noticed that the crashes creates coredumps, but I am not able to understand them. What I can say: The coredumps are created because of a "bad System call"

**Comment by proJM-Coding** [comment] 2024-03-05 09:37
If I remember correctly though in the early days of hyprland steam worked normally without crashes or menus disappearing too fast.

**Comment by vaxerski** [comment] 2024-03-05 13:56
feel free to `git bisect`

**Comment by MaKaNu** [comment] 2024-03-08 07:50
This might be difficult to approach. At thursday the 29.02.2024 I started my steam application like the day before an the typical steam updater launched. After that the crashes starts happens. I now tested yesterday on KDE Plasma. My interaction which creates repeatable the crashes opens as friends profile page. If I do that under KDE Plasma the Application doesn't got killed, instead it freezes until I try to kill the process itself. Since KDE doesn't kill the complete steam application only the opened windows, the profile opens instantly after the other windows are killed.

It seems the issue is initiated by steam and has to do with wayland.

**Comment by proJM-Coding** [comment] 2024-03-12 05:49
I had a crash the other day too, I wasn't using any window rules for steam too. It's going to take some time for me to find the old version of hyprland that did work because I'm because I'm busy and I need to patch for my nvidia gpu. (The older versions didn't have the patches)

**Comment by proJM-Coding** [comment] 2024-03-24 10:42
All menus in steam are working again and I haven't had crash while using steam. Can anyone else confirm that it's working for them?  Happy 2 years of Hyprland!!

**Comment by 42Willow** [comment] 2024-03-25 10:35
https://github.com/hyprwm/Hyprland/assets/70784752/cc137744-4a49-40d9-803f-10d17fa3c264

Everything works fine for me too, except for this small issue that only happens when the window is floating and I click on one of the top menu buttons - you need to hover over to another one and back to the one you want to get the context menu.

**Closed** 2024-03-25 18:05 UTC
Labels: bug

**Comment by madfanat** [comment] 2024-05-10 00:15
Hi! I face the same problem: window flickering because of a jumping focus.
I really tried everything from this topic to fix it. Is there an actual solution for this bug?

**Comment by gwstorm** [comment] 2024-05-10 00:24
> Is there an actual solution for this bug?

The solution was to update. No more window rules magic needed.

**Comment by proJM-Coding** [comment] 2024-05-10 03:02
> Hi! I face the same problem: window flickering because of a jumping focus. I really tried everything from this topic to fix it. Is there an actual solution for this bug?

What version are you using?
