### ISSUE TITLE
Dispatcher to manipulate dwindle layout splits

### ISSUE THREAD

**Issue by Fincali197** [hyprwm/Hyprland#3137] opened 2023-09-01 20:24 UTC
### Description

This feature is supposed to be a new dispatcher(for example, splitwindow, with a direction argument)

This explanation expects that the dwindle layout windows are in a tree-like hierarchy

1. Suppose we have:
    Our focused window `F`(node `nF`)
    It's parent node `nP`
    A function to get the window in a direction(maybe the same implementation as swapwindow dispatcher has) `get_dir(direction)`

2. Explanation
    When the dispatcher is called, for example `hyprctl dispatch splitwindow direction_var`
    you move the `nF` node from being a child of `nP` to being a child of `get_dir(direction_var)`,
    creating a new split from the `get_dir(direction_var)` node and removing a split from the `nP` node.

    If the `get_dir(direction_var)` function doesn't return a window, simply do nothing lol

This feature request exists because this functionality already exists with a mouse:
`bindm = $mainMod, mouse:272, movewindow`

Maybe here's a more detailed explanation of what should occur when you call `hyprctl dispatch splitwindow r`
https://www.reddit.com/r/hyprland/comments/1668v99/keybind_to_manipulate_window_layout/

I made a vid demonstrating how this feature would work:
https://github.com/hyprwm/Hyprland/assets/130681919/e0323dc4-11c1-4c53-902b-87c7af3e4de0

hopefully it's clear what I'm requesting, if not, please ask

**Comment by MightyPlaza** [comment] 2023-09-01 20:27
maybe dupe of https://github.com/hyprwm/Hyprland/issues/2804
also checkout hy3

**Comment by vaxerski** [comment] 2023-09-01 20:28
^

**Closed by vaxerski** 2023-09-01 20:28 UTC
Labels: enhancement

**Comment by Fincali197** [comment] 2023-09-01 21:02
> maybe dupe of #2804

pretty much, the only thing is that the movewindow dispatcher is properly documented and works as expected, so the functionality should probably just be implemented in a new dispatcher

> also checkout hy3

I think I've heard of it, but Hyprland is my first tiler. Thanks for the tip tho, ill look into it.


also, just a quick question. Do I mark this issue as closed or is there a way to mark it as a duplicate?
