### ISSUE TITLE
Visual bug with group titles

### ISSUE THREAD

**Issue by ouzdll** [hyprwm/Hyprland#2555] opened 2023-06-20 11:51 UTC
**Steps to reproduce:**

1. Make a group from a tiled window using `togglegroup` dispatcher.
2. Move the grouped window with mouse, or most of the time bug occurs by itself because groupbar takes space and moves the window down a bit.

**Expected outcome:**

No visual bugs.

**Noted outcome:**

https://github.com/hyprwm/Hyprland/assets/12971014/4cf83d5c-77dc-4f77-8934-58b6e435755e

**Comment by unuing** [comment] 2023-06-20 13:57
Looks quite like the same issue I'm experiencing #2544 .

**Comment by ouzdll** [comment] 2023-06-20 14:43
Oh yes, they're visually equal. My search was based on "group" and "title" keywords so I must've missed that. This can be closed or get merged (if possible?) if the causes and solutions are the same for the bug.

**Comment by MightyPlaza** [comment] 2023-06-20 19:26
Simply closing the tabbed window causes the same issue.

**Comment by vaxerski** [comment] 2023-06-20 19:37
dupe closing

**Comment by vaxerski** [comment] 2023-06-20 19:37
nvm not dupe

**Comment by vaxerski** [comment] 2023-06-21 11:16
fixed 83ad6b9af8e0216f04692187986283121299cb94

**Comment by MightyPlaza** [comment] 2023-06-21 11:44
Can still reproduce on latest git

**Comment by vaxerski** [comment] 2023-06-21 11:50
[patch.txt](https://github.com/hyprwm/Hyprland/files/11817169/patch.txt)
what if this

**Comment by MightyPlaza** [comment] 2023-06-21 12:59
doesn't seem to do anything
can't you repro?

**Comment by vaxerski** [comment] 2023-06-21 13:12
oh wait nvm I can my bad XD

**Comment by ouzdll** [comment] 2023-06-21 13:20
Gosh, thought I failed to apply the patch and rebuilt like 4 or 5 times lol. Yeah it seems like didn't work and still reproducable.

**Comment by MightyPlaza** [comment] 2023-06-26 15:51
Lol, enabling damage_blink damages the group bar and removes the issue.

**Comment by vaxerski** [comment] 2023-06-26 17:58
> Lol, enabling damage_blink damages the group bar and removes the issue.

that is expected

**Comment by MightyPlaza** [comment] 2023-06-26 18:35
The function ```g_pHyprRenderer->damageBox(&dm);``` in this context doesn't seem to be doing anything since removing it does not seem to make any difference.

**Comment by ouzdll** [comment] 2023-06-27 15:53
Here are the drivers installed on my system:

```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
	DeviceName:  Onboard IGD
	Subsystem: Dell HD Graphics 630
	Kernel driver in use: i915
	Kernel modules: i915

01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)
	Subsystem: Dell GP107M [GeForce GTX 1050 Ti Mobile]
	Kernel driver in use: nouveau
	Kernel modules: nouveau
```

It's an Optimus laptop, but I don't use NVIDIA proprietary driver, I use the integrated Intel GPU most the time (idk if I should install it, please let me know).

Here's my config, cut out the window rules and keybinds:

<details>
<summary>hyprland.conf</summary>

```
# Default env vars.
env = XDG_CURRENT_DESKTOP,Hyprland 
env = XDG_SESSION_TYPE,wayland 
env = XDG_SESSION_DESKTOP,Hyprland 

env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct #env = QT_STYLE_OVERRIDE,kvantum
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

env = SDL_VIDEODRIVER,wayland 
env = _JAVA_AWT_WM_NONREPARENTING,1
# env = WLR_NO_HARDWARE_CURSORS,1 

env = MOZ_DISABLE_RDD_SANDBOX,1
env = MOZ_ENABLE_WAYLAND,1 

env = OZONE_PLATFORM,wayland

# Execs
exec-once = wl-clipboard-history -t
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = ~/.config/hypr/scripts/.autostart
exec-once = systemctl --user restart pipewire
exec-once = hyprctl setcursor Dracula-cursors 24
exec-once = hyprpaper
exec-once = waybar

# Delayed Execs
exec-once = hyprctl dispatch exec "sleep 15s && ckb-next --background"
exec-once = hyprctl dispatch exec "sleep 15s && blueman-applet"
exec-once = hyprctl dispatch exec "sleep 15s && keepassxc"

# Monitors
monitor = eDP-1,1920x1080@60,auto,1
monitor = DP-3,1440x900@75,auto,1

# Workspace Bindings
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 11, monitor:DP-3, default:true 
workspace = 12, monitor:DP-3 
workspace = 13, monitor:DP-3 
workspace = 14, monitor:DP-3

# Input 
input {
  
  # Keyboard
  kb_layout = tr # us for euro variant
  # kb_variant = euro
  numlock_by_default = true

  # Mouse
  follow_mouse = 1
  sensitivity = 0
  accel_profile = flat
  force_no_accel = true
  mouse_refocus = false

  # Touchpad
  touchpad {
  natural_scroll = true
  }
}

# General
general {
  gaps_in = 5
  gaps_out = 5
  border_size = 2
  col.active_border = rgba(e5b9c6ff) rgba(c293a3ff) 45deg
  col.inactive_border = 0xff382D2E
  no_border_on_floating = false
  layout = dwindle
  no_cursor_warps = true
  # cursor_inactive_timeout = 0 
  # no_focus_fallback = false 
  # resize_on_border = false 
}

# Misc
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = true
  vrr = 0
  animate_manual_resizes = true
  mouse_move_focuses_monitor = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
}

# Decoration
decoration {
  # Rounded Corners
  rounding = 1
  
  # Opacity
  active_opacity = 1.0
  inactive_opacity = 1.0
  
  # Blur
  blur = true
  blur_size = 6
  blur_passes = 3
  blur_new_optimizations = true
  blur_xray = true
  blur_ignore_opacity = true
  
  # Shadows
  drop_shadow = false
  shadow_ignore_window = true
  shadow_offset = 1 2
  shadow_range = 10
  shadow_render_power = 5
  col.shadow = 0x66404040

  # blurls = gtk-layer-shell
  blurls = waybar
  blurls = lockscreen
}

# Animations
animations {
  enabled = true

  # Bezier Curves 
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1

  # Rules
  animation = windows, 1, 6, wind, slide
  animation = windowsIn, 1, 6, winIn, slide
  animation = windowsOut, 1, 5, winOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, loop
  animation = fade, 1, 10, default
  animation = workspaces, 1, 5, wind
}

# Layout
dwindle {
  no_gaps_when_only = false
  pseudotile = true
  preserve_split = true
}
```

</details>

**Comment by MightyPlaza** [comment] 2023-06-27 19:00
I have a feeling your issue might be related to nvidia, maybe try messing around a bit with the drivers using nvidia and intel, and closed soure and open source.

**Comment by ouzdll** [comment] 2023-06-27 19:05
Thanks. I'll and inform you.

**Comment by vaxerski** [comment] 2023-06-27 19:22
this is not an nvidia issue

**Comment by MightyPlaza** [comment] 2023-06-27 19:41
Tested the config on latest git, and couldn't repro

**Comment by ouzdll** [comment] 2023-06-27 20:51
> Tested the config on latest git, and couldn't repro

Did you try `blur = false`? I can still reproduce it. This is what happens when you close a grouped window, they're normally all over the screen but only one at the top and one at the bottom appears in the screenshot:

![1687898632](https://github.com/hyprwm/Hyprland/assets/12971014/08b02b31-5f94-4473-b453-a2d9bab2d6c1)

**Comment by MightyPlaza** [comment] 2023-06-27 20:58
Even with blur can't str

**Comment by MightyPlaza** [comment] 2023-06-27 21:01
Even with blur false still can't repro your issue.
The closing issue for me on your config is even worse since the animation swipes through all the screen from up to down getting much more issues. It's strange you get just 2.

**Comment by ouzdll** [comment] 2023-06-27 21:13
It **looks like** there's only 2 in the screenshot, normally all over the screen. Maybe it'll be easier with a screen recording:

https://github.com/hyprwm/Hyprland/assets/12971014/69bfbabb-488f-4d6e-85ef-84d90b98f265

**Comment by MightyPlaza** [comment] 2023-06-27 21:45
The closing part is the the same for me, but can't repro the other one

**Comment by burein-ita** [comment] 2023-06-29 03:34
> It **looks like** there's only 2 in the screenshot, normally all over the screen. Maybe it'll be easier with a screen recording:
> blur-false.mp4

Same as #2351

**Comment by MightyPlaza** [comment] 2023-06-29 10:49
This issue has 2 separate issue, but yes mine is a duplicate. I've removed all visual artifacts by enabling blur and changing the value to higher for now.
Simply turning blur off makes it easy to reproduce since doesn't depend on config values anymore.
The other issue I can't repro.

**Comment by MightyPlaza** [comment] 2023-08-09 00:43
any changes on latest build?

**Comment by ouzdll** [comment] 2023-08-09 21:54
@MightyPlaza seems like not present anymore. I can close if you agree.

**Comment by MightyPlaza** [comment] 2023-08-09 21:56
my issues was only on closed, so probably unrelated
vaxry fixed it today, so you can close

**Comment by ouzdll** [comment] 2023-08-09 22:01
> my issue was only on close, so probably unrelated vaxry fixed it today, so you can close

You replied exactly at the moment I was editing my comment :D

https://github.com/hyprwm/Hyprland/issues/2555#issuecomment-1610229156 last bug in the video in this comment still exists. The one that happens while closing a grouped window.

**Closed** 2023-08-09 22:04 UTC
Labels: bug
