### ISSUE TITLE
White flash before Hyprland loads

### ISSUE THREAD

**Issue by clevoman** [hyprwm/Hyprland#3117] opened 2023-08-31 04:03 UTC
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Bug

### Description

When running the Hyprland command from tty to start Hyprland, the screen flashes white briefly before loading. Hyprland works fine otherwise. Installed Hyprland from official Arch repository.

System details:
OS: Arch Linux
Model: Gigabyte A5 K1
CPU: AMD Ryzen 5 5600H
GPU: NVIDIA GeForce RTX 3060 

Yes I read and followed the steps detailed in the wiki for NVIDIA

### How to reproduce

1. Install and start Hyprland
2. Become blind

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/143679398/44c33b2b-5995-4de0-af28-df1a18babff2

**Comment by clevoman** [comment] 2023-08-31 04:19
Further testing:
- Occurs when launching from both tty and through a display manager (e.g. sddm)
- Occurs even when only Hyprland and its dependencies are installed, on first run and subsequently

**Comment by MightyPlaza** [comment] 2023-08-31 11:53
wlroots issue
dupe of https://github.com/hyprwm/Hyprland/issues/2762

**Comment by hvitoi** [comment] 2023-08-31 22:26
blinds me everytime I log in

**Comment by MightyPlaza** [comment] 2023-08-31 22:30
there is a patch ready and a better solution is getting worked on that also fixes the issue on wlroots gitlab

**Closed** 2023-09-01 20:59 UTC
Labels: bug
