### ISSUE TITLE
multi monitor performance issue

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#4387] opened 2024-01-08 16:15 UTC
### Hyprland Version

Hyprland, built from branch main at commit d7d333d162da2d3fc852b2c7a3faa2709440cefa dirty (opengl: apply box rot to projections).
Date: Sun Jan 7 14:51:08 2024
Tag: v0.34.0-31-gd7d333d1

flags: (if any)

System Information:
System name: Linux
Node name: matrix
Release: 6.6.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:41 +0000

GPU information: 
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:
  hyprload by Duckonaut ver 1.4.0
  hyprshell by killown ver 0.1

### Bug or Regression?

Bug

### Description

this video https://youtu.be/7pNI3KkY6rc shows mouse cursor moving between two windows and two monitors, cpu usage increases a lot when moving between monitors

### How to reproduce

https://youtu.be/7pNI3KkY6rc 

### Crash reports, logs, images, videos

https://youtu.be/7pNI3KkY6rc

**Comment by vaxerski** [comment] 2024-01-08 18:16
expected. When compositor has to do something, it consumes more CPU. magic. Dupe of something, I dont remember which number.

**Closed by vaxerski** 2024-01-08 18:16 UTC
Labels: bug
