### ISSUE TITLE
A way to manually order workspaces

### ISSUE THREAD

**Issue by lucascoelho07** [hyprwm/Hyprland#4336] opened 2024-01-03 12:37 UTC
### Description

Mainly named ones, maybe by setting an id for each one in the config?

**Comment by ParetoOptimalDev** [comment] 2024-01-03 19:04
So I was trying to do this and since it's alphabetical tried to come up with a workaround using "1-SOMENAME". However I've messed something up... somewhere. Here's my attempt anyway:

```
bind=SUPER,1,workspace,name:1-personal
bind=SUPER,2,workspace,name:2-work
bind=SUPER,3,workspace,name:3-game
bind=SUPERSHIFT,1,movetoworkspacesilent,name:1-personal
bind=SUPERSHIFT,2,movetoworkspacesilent,name:2-work
bind=SUPERSHIFT,3,movetoworkspacesilent,name:3-game

workspace=name:1-personal, persistent:true
workspace=name:2-work, persistent:true
workspace=name:3-game, persistent:true
```

And in waybar:

```
    "hyprland/workspaces": {
      "active-only": false,
      "all-outputs": true,
      "sort-by": "number"
    },
```

**Comment by kreejzak** [comment] 2024-01-09 14:07
It would be awesome to have the ability to sort workspaces. For instance, I use stacked dual monitors with Q, W, E, R workspaces on the top and A, S, D, F on the bottom. Coming from sway, having workspaces sorted as E, Q, R, W feels a bit unusual. It's not a groundbreaking issue, but having the option to arrange workspaces would be a nice feature to have.

**Comment by lucascoelho07** [comment] 2024-01-11 02:54
> It would be awesome to have the ability to sort workspaces. For instance, I use stacked dual monitors with Q, W, E, R workspaces on the top and A, S, D, F on the bottom. Coming from sway, having workspaces sorted as E, Q, R, W feels a bit unusual. It's not a groundbreaking issue, but having the option to arrange workspaces would be a nice feature to have.

yes!! this is exactally my case, but I use A, S, D, F for the main ones and U, I, O for other stuff

**Comment by pdf** [comment] 2024-01-23 06:45
Duplicate of #665 ?

**Closed** 2024-02-27 22:41 UTC
Labels: enhancement
