### ISSUE TITLE
Fullscreen mode doesn't reset window border radius

### ISSUE THREAD

**Issue by liamrahum** [hyprwm/Hyprland#4120] opened 2023-12-11 07:52 UTC
### Hyprland Version

efdf07e295d00cf5391a8c0089967a69a76d9b08

### Bug or Regression?

Bug

### Description

When going into fullscreen the border radius of it is still visible.

### How to reproduce

Open window in Hyprland's full-screen mode.

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/45101400/8ef7200f-d0de-4aa4-a821-90f05f918c13)
(Top and bottom left is most visible)

**Comment by cprin21** [comment] 2023-12-11 11:56
Dupe of #4117 , it is also a regression. See https://github.com/hyprwm/Hyprland/issues/4117#issuecomment-1849229651 for a temporary workaround until this is fixed.

**Closed** 2023-12-11 16:32 UTC
Labels: bug
