### ISSUE TITLE
Damage tracking stops working after wlroots update

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#786] opened 2022-10-05 17:27 UTC
Looking at the damage_blink disco, it seems like the damage tracking is disabled if i build from aur or a fresh clone.
In my local repo however (build from current main) the damage tracking seems to work.
How is that possible?

**Comment by vaxerski** [comment] 2022-10-05 18:27
if you can type this it means it's working tho

**Comment by vaxerski** [comment] 2022-10-05 18:28
don't use damage_blink to judge damage tracking. If shit is updated on the screen, it means it's working. damage_blink is ONLY a debug tool.

**Comment by Dickby** [comment] 2022-10-05 19:14
@vaxerski 

> damage_blink is ONLY a debug tool.

I'm kind of trying to use it as that.
Either i don't understand that at all, or i didn't say it in an understandable way.
If i just clone and build the repo, it looks like damage_tracking is set to `none`
(all the screen is blinking all the time).
That doesn't happen if i build from my old local repo.

**Comment by vaxerski** [comment] 2022-10-05 19:19
disable on launch, enable during runtime, should work

**Comment by Dickby** [comment] 2022-10-05 19:25
I'm on a shitty laptop, but it didn't use to do that.

**Comment by Dickby** [comment] 2022-10-05 19:38
This is not about damage_blink.
The frame rate shown in the overlay tells the same story.
Build from aur = framerate drop with one

**Comment by Dickby** [comment] 2022-10-05 19:47
Did you try to reproduce it?

**Comment by vaxerski** [comment] 2022-10-05 19:47
been using the AUR for a while never noticed anything as such

**Comment by primalmotion** [comment] 2022-10-05 19:47
let me jump in to say that I was also about to open an issue about framerate drop. It seems that initially everything is butter smooth, but after a little while (or after a suspend? or after a reload.. not sure) the framerate seems to drops (mouse feels laggy and videos have a 80's dreamy effect).

**Comment by vaxerski** [comment] 2022-10-05 19:48
reproducible example plox

**Comment by vaxerski** [comment] 2022-10-05 19:48
and since apparently @Dickby has that, maybe you can profile it and narrow down the hotspot?

**Comment by Dickby** [comment] 2022-10-05 19:50
I will try to perf it though!

**Comment by vaxerski** [comment] 2022-10-05 19:51
`hyprctl getopt general:damage_tracking_internal`?

**Comment by Dickby** [comment] 2022-10-05 19:54
2

**Comment by vaxerski** [comment] 2022-10-05 19:54
full

**Comment by Dickby** [comment] 2022-10-05 19:55
so why do i get low framerate and whole thing blinking only if i don't use my own repo.

**Comment by vaxerski** [comment] 2022-10-05 19:55
damage_blink forces re-render of the entire monitor every frame

**Comment by Dickby** [comment] 2022-10-05 19:56
but the framerate thing is happening without damage_blink too!
I'm sorry to be annoying here, but there is something wrong.
Since it's basicly the same code compiled, i would guess it's the sub repo

**Comment by vaxerski** [comment] 2022-10-05 19:57
na, cant be wlroots. Have you tried disabling damage blink and restarting?

**Comment by Dickby** [comment] 2022-10-05 19:58
Let me try a fresh clone debug build.
Then i can perf the thing.

**Comment by Dickby** [comment] 2022-10-05 19:59
yes i tried.
Why should there be a difference between two basicly identical builds?
Try to turn on your damage blink and see!?

**Comment by vaxerski** [comment] 2022-10-05 20:00
works for me man lol

**Comment by Dickby** [comment] 2022-10-05 20:02
@primalmotion can you turn on damage_blink for a second with more than 1 window opened on the active workspace?
Tell if all the windows are blinking, or only the focused/active window.

**Comment by Dickby** [comment] 2022-10-05 20:03
> works for me man lol

works for me too if i build from my local.
I'm concerned about how it works for other people.

**Comment by vaxerski** [comment] 2022-10-05 20:04
yo wait no wtf it broken yea

**Comment by Dickby** [comment] 2022-10-05 20:05
Thanks god for fuck sake!

**Comment by vaxerski** [comment] 2022-10-05 20:06
which one of yall mfs broke damage blink

oh wait prolly me

**Comment by primalmotion** [comment] 2022-10-05 20:07
> can you turn on damage_blink for a second with more than 1 window opened on the active workspace?
>Tell if all the windows are blinking, or only the focused/active window.

all windows are blinking

**Comment by Dickby** [comment] 2022-10-05 20:10
I'm so happy this is over, can i help somehow?

**Comment by vaxerski** [comment] 2022-10-05 20:11
you can teach me how to get bitches

**Comment by vaxerski** [comment] 2022-10-05 20:12
it's wlroots :trollface:ing us

**Comment by Dickby** [comment] 2022-10-05 20:12
Kind of what is said, no?

**Comment by vaxerski** [comment] 2022-10-05 20:13
yeah u right, I take back what I said

weird tho

**Comment by Dickby** [comment] 2022-10-05 20:14
It's fine!
I have some more early out pixman things to push and i tried to 
test the changes against the main build. That's how i found it.

**Comment by Dickby** [comment] 2022-10-05 20:17
Did they anounce a change?
Where to read those?

**Comment by vaxerski** [comment] 2022-10-05 20:19
announce a change? lol

their gitlab if anything. There is a meta 0.16 post but not much 'bout this, this just a bug or sumn

https://gitlab.freedesktop.org/wlroots/wlroots

**Comment by primalmotion** [comment] 2022-10-05 20:49
@Dickby what is the current commit sha you use for wlroots that does not have the issue?

**Comment by Dickby** [comment] 2022-10-05 21:18
Sorry, how do i check that?

**Comment by vaxerski** [comment] 2022-10-05 21:22
`git rev-parse HEAD`

**Comment by Dickby** [comment] 2022-10-05 21:25
2ad25b14..

**Comment by Dickby** [comment] 2022-10-05 21:26
I guess, i updated some times, but i think i only build it once

**Comment by primalmotion** [comment] 2022-10-05 21:43
Ok. I had to run but when I get back, I'll try to bisect wlroots to find the bad patch

**Comment by primalmotion** [comment] 2022-10-05 23:14
So bisect tells me this is the culprit

```
0556aa0c5918b90118da8abdf572b27a44e1b51d is the first bad commit
commit 0556aa0c5918b90118da8abdf572b27a44e1b51d
Author: Simon Ser <contact@emersion.fr>
Date:   Sun Sep 18 16:29:36 2022 +0200

    output: rejigger attach/clear for back buffer

    In wlr_output_attach_render(), stop setting
    wlr_output.pending.buffer. This removes one footgun: using the
    wlr_buffer at that stage is invalid, because rendering operations
    haven't been flushed to the GPU yet. We need to wait until
    output_clear_back_buffer() for the wlr_buffer to be used safely.

    Instead, set wlr_output.pending.buffer in wlr_output_test() and
    wlr_output_commit().

    Additionally, move the output_clear_back_buffer() from
    wlr_output_commit_state() to wlr_output_commit(). This reduces the
    number of calls in the failure path.

 types/output/output.c | 37 +++++++++++++++++++++----------------
 types/output/render.c |  7 +------
 2 files changed, 22 insertions(+), 22 deletions(-)
```

**Comment by vaxerski** [comment] 2022-10-06 11:56
it's not for me - at least with damage_blink off

**Comment by vaxerski** [comment] 2022-10-06 11:56
graphics pipe sits at around 0-3% on my laptop

**Comment by primalmotion** [comment] 2022-10-06 16:28
so with latest everthing (from the AUR) I get a max of 35/40fps when I play a 60fps video. With latest Hyprland (and wlroots 2ad25b) I'm at a solid 60fps (with the same number of windows opened, and the same video playing).

So there is indeed a regression here.

**Comment by vaxerski** [comment] 2022-10-06 16:37
can you report it to wlroots then? I can't repro this.

**Comment by primalmotion** [comment] 2022-10-06 16:46
done https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3503

**Comment by vaxerski** [comment] 2022-10-06 17:11
> so with latest everthing (from the AUR) I get a max of 35/40fps when I play a 60fps video. With latest Hyprland (from sourtce and with wlroots 2ad25b) I'm at a solid 60fps (with the same number of windows opened, and the same video playing).
So there is indeed a regression here.

Still. Is this with damage_blink enabled?

**Comment by primalmotion** [comment] 2022-10-06 17:17
> Still. Is this with damage_blink enabled?

Does not matter if damage_blink is on or off

**Comment by vaxerski** [comment] 2022-10-06 21:23
I've reverted to pre-faulty commit in the HEAD and pushed 15.1.

**Comment by vaxerski** [comment] 2022-10-06 21:37
damn @Dickby I should trust you more. It really was damage tracking that was completely fucked.

**Comment by primalmotion** [comment] 2022-10-06 21:42
no shit :p

**Comment by vaxerski** [comment] 2022-10-06 21:43
for now the issue is "resolved" temporairly - please verify guys that 0.15.1 is A-OK. Will monitor both this thread and the wlroots one closely to chase the issue down.

**Comment by primalmotion** [comment] 2022-10-06 21:57
yep that works. "fixed" in latest master

**Comment by vaxerski** [comment] 2022-10-06 21:59
thanks for reporting. Will try to debug wlr tomorrow as well (if there wont be a reply yet) and see what went wrong

**Comment by vaxerski** [comment] 2022-10-07 21:41
the devs over at wlroots (thanks Kirill) have apparently fixed the issue, can you verify that?

**Comment by primalmotion** [comment] 2022-10-07 23:15
trying with wlroots master

**Comment by primalmotion** [comment] 2022-10-07 23:16
but it does not build :(

**Comment by primalmotion** [comment] 2022-10-07 23:21
trying again with the actual fix commit 46a686ce6b02724f42b8d9ab8b7aeed958d4c7f6

**Comment by primalmotion** [comment] 2022-10-07 23:25
no it's not fixed. I mean it's a bit better, but it is stuck a 60fps now. and the blink thing is blinking on the entire screen like crazy. Then it stops a for a while. Then everything starts to randomly blink again

**Comment by primalmotion** [comment] 2022-10-07 23:29
I reverted to hyperland-git from AUR and check the blink. It makes sense here. With the wlroots, it does not.

**Comment by primalmotion** [comment] 2022-10-07 23:40
mmh wait scratch that. I fucked up something. it seems to work actually.

**Comment by primalmotion** [comment] 2022-10-07 23:46
ok no yeah it worlks.

However I just noticed something weird. If I play a 60fps video on my HDMI monitor, then only this monitor is at 60fps. the laptop screen is at like 4fps. But if the video plays on the laptop screen, both monitors run at 60fps (even if there absolutely nothing on the second monitor). This may be a different though..

**Comment by vaxerski** [comment] 2022-10-08 09:17
that's not an issue, it's called VFR.

```
misc:no_vfr=yes
```

and they will run at 60FPS, but your battery will suffer.

**Comment by primalmotion** [comment] 2022-10-08 16:45
I understand VFR. that's not what I mean. If I run something on a screenA and nothing on screenB i expect screenA to run at 60fps and screenB at mostly 0.

what I see is it works like that is screenA is DP-1 (DP-1: 60fps, eDP-1: 4fps) but not when screenA is eDP-1 (eDP-1: 60fps, DP-1: 60fps)

**Comment by vaxerski** [comment] 2022-10-08 16:51
odd

**Comment by vaxerski** [comment] 2022-10-08 17:02
closing this, wlroots updated and issue fixado

**Closed by vaxerski** 2022-10-08 17:02 UTC
Labels: bug

**Comment by primalmotion** [comment] 2022-10-08 17:06
Yep will open a new issue. Thx!
