### ISSUE TITLE
Crash on Hyprland Launch:  m_sWLRBackend was NULL!

### ISSUE THREAD

**Issue by s-daveb** [hyprwm/Hyprland#3082] opened 2023-08-26 14:31 UTC
### Hyprland Version

hyprland-git-0.28.0.r100.299d201e-

### System Information
```
Kernel: Linux 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux
GPU: AMD Radeon 6600
GPU Driver: amdgpu
MESA: mesa-git 23.3.0_devel.177071.5ce6e09ffc7.d41d8cd-1
```
### Bug or Regression?

~~Bug~~
Regression

**EDIT**: Switching back to Arch's "Stable" hyprland 0.28.0-1 pkg seems to resolve the problem for me. It's probably a regression

### Description

I'm not sure what is causing it, but whenever I launch Hyprland after getting the latest Arch updates with pacman and AUR, Hyprland has started crashing on login. 

The log files show:
```
[CRITICAL] m_sWLRBackend was NULL!
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!
```

### How to reproduce

I wish I could tell you how to reproduce it on any system. 
All I've done is update my system, and try to run Hyprland through the sddm display manager, as well as on the framebuffer.

### Crash reports, logs, images, videos

[hyprlandd.log](https://github.com/hyprwm/Hyprland/files/12445552/hyprlandd.log)
[hyprlandCrashReport2046.txt](https://github.com/hyprwm/Hyprland/files/12445553/hyprlandCrashReport2046.txt)
[hypr2046-coredump-bt.txt](https://github.com/hyprwm/Hyprland/files/12445554/hypr2046-coredump.txt)

**Comment by s-daveb** [comment] 2023-08-26 14:42
When I run Hyprland straight from the TTY, I get the following:

[hyprlandd-tty.log](https://github.com/hyprwm/Hyprland/files/12445571/hyprlandd-tty.log)
[hyprlandCrashReport5188.txt](https://github.com/hyprwm/Hyprland/files/12445572/hyprlandCrashReport5188.txt)

The program prints the following on the terminal:
```
00:00:00.000 Llibseat] [Llibseat/backend/seatd.c:641] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.001 [Llibseat] [libseat/libseat.c:761] Backend seatd' failed to open seat, skipping 
terminate called after throwing an instance of 'std: :runtime_error ckendd0 as DRM device such file or directory
what: wIr_backend_autocreate() failed!
```

**Comment by s-daveb** [comment] 2023-08-26 14:47
Switching back to Arch's "Stable" hyprland 0.28.0-1 pkg seems to resolve the problem for me. It's probably a regression

**Comment by vaxerski** [comment] 2023-08-26 15:11
git bisect please

**Comment by salimp2009** [comment] 2023-08-26 18:40
I dont know if this related . I have nvidia and on hyrplad-nvidia git on Arch. After todays kernel and driver update everything was working. Then I update hyprland and it crashed. I tought this either kernel or nvidia driver . 
it also crashed with kernel 6.4.11 and 6.4.10  and nvidia drivers 535.104 and 535.98 , it only worked when I down graded to hyprland-nvidia-git version 0.28.0.r68.g942ee943-1 (last weeks update; 19/08/2023) and it works with latest kernel and latest nvidia drivers
This is the first crash report with kernel 6.4.12 and nividia driver 535.104.05 , hyprland version v0.28.0-99-gd63a42e9

[hyprlandCrashReport549.txt](https://github.com/hyprwm/Hyprland/files/12446521/hyprlandCrashReport549.txt)

**Comment by VincentBerthier** [comment] 2023-09-01 10:21
Note that this might not be caused by Hyprland itself, I’m unable to launch Plasma on Wayland either…
I tried to revert my flake.lock to one from the 25th, but didn’t change anything though, weird…

**Comment by salimp2009** [comment] 2023-09-01 10:38
> Note that this might not be caused by Hyprland itself, I’m unable to launch Plasma on Wayland either… I tried to revert my flake.lock to one from the 25th, but didn’t change anything though, weird…

I am not sure if AMD issue here is the same with the one for Nvidia. Nvidia issue is actually caused by wlroot as discovered By @fazzi from discord channel and he opened an issue at wlroots repo and wlroots devs dont want to deal with because they think it is only nvidia related. 
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3724
But again if those 2 issues are related then we would have same problem from AMD users too. So far other than here I have not seen a post on discord or here

**Comment by VincentBerthier** [comment] 2023-09-01 11:01
Ha, makes sense, thanks. 
@"$!# Nvidia, as usual. I really should get myself an AMD card…

**Comment by vaxerski** [comment] 2023-09-01 20:48
well, I will close this as 
```
[CRITICAL] m_sWLRBackend was NULL!
``` 
is always wlroots failing to open a backend, which means your gpu drivers are most likely broken

**Closed by vaxerski** 2023-09-01 20:48 UTC
Labels: bug

**Comment by salimp2009** [comment] 2023-09-02 09:21
although keep in mind that the original issue creator was using AMD so are all our GPU drivers are bad  ? Or is there something wrong with the wlroots ?
 it was working until the commit @fazzi has bisected and found out. 
 So maybe if they could have a look at it ? Maybe there is actually something wrong in that commit ?
 And this is not the first time wlroots breaks thing. last time it was fixed since it effected everyone.

**Comment by s-daveb** [comment] 2023-09-02 13:55
I’ve been at work all week and haven’t had a chance to git bisect.  I’ll try it and will open another issue if I can pinpoint it to a wlroots hyprland change.

That being said, I tend to run bleeding edge kernels and amdgpu drivers, so it’s not entirely impossible for that to be a factor.

**Comment by gvolpe** [comment] 2023-09-14 18:09
Not the best timing for me to try Hyprland it seems 🥲 

Here's an easy way to reproduce using Nix: https://github.com/gvolpe/nixos-hyprland

**Comment by AlekHed** [comment] 2023-09-26 06:48
Problem disappears if I enable Multi-Monitor option in BIOS. I have 13700 with IGP and nVidia.
