### ISSUE TITLE
Random crashing (Mostly after Swayidle)

### ISSUE THREAD

**Issue by bpwillis** [hyprwm/Hyprland#1982] opened 2023-04-07 15:55 UTC
Hyprland crashes at random times, but mostly after swayidle has turned off my display.  Sometimes my system can be idle for hours or even a couple days and come back up okay.  Other times it crashes after only a few minutes or hours after being idle.[](url)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/11179987/hyprland.log)
[hyprland config.txt](https://github.com/hyprwm/Hyprland/files/11179996/hyprland.config.txt)
[hyprlandCrashReport815.txt](https://github.com/hyprwm/Hyprland/files/11180004/hyprlandCrashReport815.txt)

**Comment by vaxerski** [comment] 2023-04-07 17:07
dupe of #804

**Closed by vaxerski** 2023-04-07 17:07 UTC
Labels: bug
