### ISSUE TITLE
Context menus are flashing (perhaps, `libadwaita` specific)

### ISSUE THREAD

**Issue by paveloom** [hyprwm/Hyprland#1366] opened 2023-01-11 20:03 UTC
Here's a recording:

https://user-images.githubusercontent.com/49961859/211906337-2ab58d81-349e-4dac-9e1c-32690ec4ab71.mp4

**Comment by mustardfrog** [comment] 2023-01-17 00:41
I also have this problem with nautilus. But also I can't open images from nautilus with most image viewer like feh and sxiv. Risttero works fine though.
I am On EndeavourOS.

**Comment by yavko** [comment] 2023-02-10 00:48
I used to have this issue om arch, but went away when i switched to NixOS

**Comment by romanstingler** [comment] 2023-06-29 22:20
@paveloom can you test latest git version, I can't reproduce on arch, thx

**Comment by paveloom** [comment] 2023-06-30 07:10
@romanstingler I'm not running Hyprland anymore. Up to you, guys.

**Comment by romanstingler** [comment] 2023-06-30 07:29
@vaxerski I think we can close that one

**Comment by Readf0x** [comment] 2023-08-14 22:45
still an ongoing issue, bumping this

**Comment by vaxerski** [comment] 2023-11-05 16:46
is this still happening?

**Comment by Hydroxycarbamide** [comment] 2023-11-05 17:07
I had the same issue on Arch and the recent [pr](https://github.com/hyprwm/Hyprland/pull/3716) solved it for me. I've also tried other GTK4 applications with libadwaita other than nautilus and that worked too.

**Comment by vaxerski** [comment] 2023-11-05 18:06
closing then

**Closed by vaxerski** 2023-11-05 18:06 UTC
Labels: bug
