### ISSUE TITLE
exit bind black screen

### ISSUE THREAD

**Issue by kojq** [hyprwm/Hyprland#3741] opened 2023-11-03 18:39 UTC
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0

### Bug or Regression?

Bug

### Description

When using the exit bind, there there is a chance to hang on a black screen. I'm unsure if it's a hardware-specific issue.

### How to reproduce

Use the exit bind.

**Comment by andresilva** [comment] 2023-11-05 14:52
Duplicate of https://github.com/hyprwm/Hyprland/issues/3558.

**Closed** 2023-11-05 16:28 UTC
Labels: bug
