### ISSUE TITLE
OBS viewport is very glitchy

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2129] opened 2023-04-22 15:22 UTC
When resizing OBS at smaller sizes, the viewport becomes squished vertically. If the OBS window is then grown, the bottom of the viewport will be stretched downward.

Video of the issue:

https://user-images.githubusercontent.com/44881120/233792847-82d5b502-300d-4040-b0c9-dd54ed8b348c.mp4

Additionally, though I believe this is known and not a major issue, the viewport gets its corners incorrectly rounded, and it is not animated alongside the OBS window.

https://user-images.githubusercontent.com/44881120/233792959-2dfc4657-d708-49cf-854b-c51f4cb19de1.mp4

**Comment by vaxerski** [comment] 2023-04-22 15:37
dupe of #1462 and #1558

**Closed by vaxerski** 2023-04-22 15:37 UTC
Labels: bug
