### ISSUE TITLE
`movetoworkspacesilent` not refocusing window

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#1845] opened 2023-03-21 14:38 UTC
Currently on master and stack layout, the `movetoworkspacesilent` dispatcher no longer refocuses the active window to one in the current workspace. Instead I have to refocus using the cursor after the dispatcher is called.

After using the dispatcher, no window is currently active.

**Comment by Pyxels** [comment] 2023-04-14 09:54
Probably a duplicate of #1507, which is now resolved.

**Closed** 2023-04-14 12:34 UTC
