### ISSUE TITLE
Setting disable_hyprland_logo breaks hyprland

### ISSUE THREAD

**Issue by A-Shahbazi** [hyprwm/Hyprland#8816] opened 2024-12-23 01:18 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.0 built from branch main at commit 71dc9f6128b8d2e382b2a574d2d5f15e2d907f3a  (pluginAPI: add register dispatcher v2).
Date: Thu Dec 19 21:23:32 2024
Tag: v0.46.0-18-g71dc9f61, commits: 5573
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: ali-n43jq
Release: 6.12.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:30:31 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF108M [GeForce GT 435M] [10de:0df2] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/ali/.config/hypr/hyprland.conf: Read Succeeded
# This is an example Hyprland config file.
#
# Refer to the wiki for more information.

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#
# info at https://wiki.hyprland.org/
# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto

# mirror two screens HDMI-A-1 to left of HDMI-A-2
# monitor=HDMI-A-1,1920x1080@60,0x0,1,mirror,HDMI-A-2
# monitor=,preferred,auto,1,mirror,HDMI-A-1

# Output
# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

#monitor=HDMI-A-1,1920x1080@60,0x0,1
#workspace=HDMI-A-1,1
#monitor=HDMI-A-2,1920x1080@60,1920x0,1
#workspace=HDMI-A-2,2

# Example :
#monitor=eDP-1,1920x1080@60,0x0,1
#monitor=eDP-1,transform,0
#monitor=eDP-1,addreserved,10,10,10,10
#workspace=eDP-1,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Setting variables
$mainMod = SUPER
$localBin = $HOME/.local/bin
$scriptsDir = $HOME/.config/hypr/scripts
$hyprDir = $HOME/.config/hypr
$term = foot
$menu = $scriptsDir/menu
$fullmenu = $scriptsDir/fullmenu
$volume = $scriptsDir/volume
$backlight = $scriptsDir/brightness
$screenshot = $scriptsDir/screenshot
$lock = $scriptsDir/lockscreen
$colorpicker = $scriptsDir/colorpicker
$wofi_beats = $scriptsDir/wofi-beats
$files = pcmanfm-qt
$browser = min
$editor = micro

# Some default env vars
env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland

# Startup
exec-once = $scriptsDir/startup
#exec-once = swaybg -m fill -c #000000
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $scriptsDir/portal
#exec-once = variety -n

# with lock - hyprctl
# exec-once = swayidle -w timeout 1200 '$lock' timeout 1200 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep '$lock'

# with lock - swaylock
# exec-once = swayidle -w timeout 1200 'swaylock -f -c 111111' timeout 1200 '' resume '' before-sleep 'swaylock -f -c 111111'

# without lock
# exec-once = swayidle -w  timeout 1200 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'


# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
  # qwerty
  kb_layout = us, ir

  # azerty
  #kb_layout = be

  kb_variant =
  kb_model =
  kb_options = grp:alt_shift_toggle, lv3:ralt_alt
  kb_rules =

  follow_mouse = 1
  numlock_by_default = 0

  touchpad {
    natural_scroll = true
    tap-to-click = true
    drag_lock = true
    disable_while_typing = true
  }

  #sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification
}

misc {
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  force_default_wallpaper = 0
  #disable_hyprland_logo = true
  background_color = 0x000000
}

binds {
  workspace_back_and_forth = true
}

general {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more

  gaps_in = 3
  gaps_out = 7
  border_size = 2

  #one color
  #col.active_border = rgba(7aa2f7aa)

  #two colors - gradient

  col.active_border = rgba(7aa2f7aa) rgba(c4a7e7aa) 45deg
  col.inactive_border = rgba(414868aa)

  layout = master
  #layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 1
    }

    #drop_shadow = true
    #shadow_range = 4
    #shadow_render_power = 3
    #col.shadow = rgba(1a1a1aee)
}

blurls = waybar

animations {
  enabled = true

  # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05

  animation = windows, 1, 7, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}

dwindle {
  # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  pseudotile = true
  preserve_split = true
}

master {
  # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  new_status = master
  mfact = 0.5
}

gestures {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more
  workspace_swipe = false
  workspace_swipe_fingers = 3
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
#device:epic mouse V1 {
#  sensitivity = -0.5
#}

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Example windowrule v1
# windowrule = float, yad|nm-connection-editor|pavucontrol
# windowrule = float, feh|Gimp|qt5ct

windowrule = float, nlogout

# Example windowrule v2
windowrulev2 = tile, class:^(Spotify)$

# windowrulev2 = workspace 4, class:^(Apache Directory Studio)$
# windowrulev2 = bordercolor rgb(EE4B55) rgb(880808), fullscreen:1
# windowrulev2 = bordercolor rgb(282737) rgb(1E1D2D), floating:1
# windowrulev2 = opacity 0.8 0.8, pinned:1
# windowrulev2 = workspace 10, class:^(Microsoft-edge)$
# windowrulev2 = workspace 8 silent, class^(Steam)$, title:^(Steam)$
# windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$

# for waybar yay update click
windowrulev2 = animation popin, class:^(update)$, title:^(update)$
windowrulev2 = float, class:^(update)$, title:^(update)$
windowrulev2 = size 60% 50%, class:^(update)$, title:^(update)$
windowrulev2 = center, class:^(update)$, title:^(update)$

# for ttyclock
windowrulev2 = float, class:^(clock)$, title:^(clock)$
windowrulev2 = size 33% 27%, class:^(clock)$, title:^(clock)$
windowrulev2 = center, class:^(clock)$, title:^(clock)$

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod SHIFT, F1, exec, $fullmenu
bind = $mainMod, D, exec, $menu
bind = $mainMod SHIFT, Q, killactive
bind = $mainMod SHIFT, Return, exec, $files
bind = $mainMod SHIFT, Space, togglefloating
bind = $mainMod, C, exec, conky-toggle
bind = $mainMod, E, exec, code
bind = $mainMod, F, fullscreen
bind = $mainMod, Q, killactive,
bind = CTRL, Q, killactive,
bind = $mainMod, R, exec, rofi-theme-selector
bind = $mainMod, Return, exec, $term
bind = $mainMod, T, exec, $term
bind = $mainMod, V, exec, pavucontrol

bind = CTRL ALT, A, exec, xfce4-appfinder
bind = CTRL ALT, C, exec, catfish
bind = CTRL ALT, B, exec, $files
bind = CTRL ALT, E, exec, archlinux-tweak-tool
bind = CTRL ALT, F, exec, firefox
bind = CTRL ALT, G, exec, chromium -no-default-browser-check
bind = CTRL ALT, I, exec, nitrogen
bind = CTRL ALT, K, exec, $scriptsDir/lockscreen
bind = CTRL ALT, L, exec, $scriptsDir/lockscreen
bind = CTRL ALT, NEXT, exec, conky-rotate -n
bind = CTRL ALT, P, exec, pamac-manager
bind = CTRL ALT, PREVIOUS, exec, conky-rotate -p
bind = CTRL ALT, R, exec, rofi-theme-selector
bind = CTRL ALT, Return, exec, foot
bind = CTRL ALT, S, exec, spotify
bind = CTRL ALT, T, exec, $term
bind = CTRL ALT, U, exec, pavucontrol
bind = CTRL ALT, V, exec, vivaldi-stable
bind = CTRL ALT, W, exec, arcolinux-welcome-app

bind = CTRL SHIFT, Escape, exec, $term --class btop -T btop -e btop
bind = CTRL ALT, END, exec, $term --class btop -T btop -e btop

# change wallpaper
# bind = ALT, n, exec, $scriptsDir/changeWallpaper
# bind = ALT, p, exec, $scriptsDir/changeWallpaper
# bind = ALT, left, exec, $scriptsDir/changeWallpaper
# bind = ALT, right, exec, $scriptsDir/changeWallpaper
# bind = ALT, up, exec, $scriptsDir/changeWallpaperDesktop
# bind = ALT, down, exec, $scriptsDir/changeWallpaperDesktop

# Variety
# trash wallpaper
bind = ALT, t, exec, variety -t
# next wallpaper
bind = ALT, n, exec, variety -n
bind = ALT SHIFT, n, exec, variety -n && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) && ~/.config/hypr/scripts/statusbar &
bind = ALT, right, exec, variety -n
# previous wallpaper
bind = ALT, p, exec, variety -p
bind = ALT SHIFT, p, exec, variety -p && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) && ~/.config/hypr/scripts/statusbar &
bind = ALT, left, exec, variety -p
# favorite wallpaper
bind = ALT, f, exec, variety -f
# pause wallpaper
bind = ALT, up, exec, variety --toggle-pause
# pause wallpaper + wal
bind = ALT SHIFT, up, exec, variety --toggle-pause && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) && ~/.config/hypr/scripts/statusbar &
# resume wallpaper
bind = ALT, down, exec, variety --resume

# effect
bind = ALT, g, exec, $scriptsDir/glassmorphismToggle

bind = ALT, F3, exec, xfce4-appfinder

bind = , F12, exec, xfce4-terminal --drop-down

bind = $mainMod SHIFT, M, exec, hyprctl dispatch splitratio -0.1
bind = $mainMod, M, exec, hyprctl dispatch splitratio 0.1

bind = $mainMod SHIFT, Y, exec, $term --class clock -T clock -e tty-clock -c -C 7 -r -s -f "%A, %B, %d"
#bind = $mainMod, D, layoutmsg, removemaster
bind = $mainMod, Escape, exec, hyprctl kill
bind = $mainMod, I, layoutmsg, addmaster
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev

bind = $mainMod, P, pseudo
bind = $mainMod CTRL, Return, layoutmsg, swapwithmaster
bind = $mainMod, Space, exec, $scriptsDir/changeLayout
bind = $mainMod, X, exec, nwg-bar -i 96
bind = ALT, X, exec, nlogout
bind = ALT SHIFT, X, exec, nlogout
bind = $mainMod SHIFT, X, exec, arcolinux-powermenu
bind = $mainMod, Y, exec, $term --class update -T update -e cava # f to cycle through foreground colors

# Mainmod + Function keys
bind = $mainMod, F1, exec, $browser
bind = $mainMod, F2, exec, $files
bind = $mainMod, F3, exec, qbittorent
bind = $mainMod, F4, exec, virtualbox
bind = $mainMod, F5, exec, waydroid
bind = $mainMod, F6, exec, celluloid
bind = $mainMod, F7, exec, thunderbird
bind = $mainMod, F8, exec, qimgv
bind = $mainMod, F9, exec, playonlinux
bind = $mainMod, F10, exec, $wofi_beats
#bind = $mainMod, F11, exec, rofi -show drun
#bind = $mainMod, F12, exec, rofi -show drun

# Special Keys
bind = , xf86sleep, exec, systemctl suspend
bind = , xf86audioraisevolume, exec, $volume --inc
bind = , xf86audiolowervolume, exec, $volume --dec
bind = , xf86audiomute, exec, $volume --toggle
bind = , xf86audioplay, exec, playerctl play-pause
bind = , xf86audionext, exec, playerctl next
bind = , xf86audioprev, exec, playerctl previous
bind = , xf86audiostop, exec, playerctl stop
bind = , xf86monbrightnessup, exec, $brightness --inc
bind = , xf86monbrightnessdown, exec, $brightness --dec

# # Backlight control
# bind = $mainMod SHIFT, equal, submap, backlight
# submap = backlight
# bind = , equal, exec, $backlight --inc
# bind = , minus, exec, $backlight --dec
# bind = , escape, submap, reset
# submap = reset


# Volume control
bind = $mainMod, equal, submap, volume
submap = volume
bind = , equal, exec, $volume --inc
bind = , minus, exec, $volume --dec
bind = , 0, exec, $volume --toggle
bind = , 9, exec, $volume --toggle-mic
bind = , escape, submap, reset
submap = reset

# Resize
binde = $mainMod SHIFT, H, resizeactive,-50 0
binde = $mainMod SHIFT, L, resizeactive,50 0
binde = $mainMod SHIFT, K, resizeactive,0 -50
binde = $mainMod SHIFT, J, resizeactive,0 50

# Move
bind = $mainMod CTRL, H, movewindow, l
bind = $mainMod CTRL, L, movewindow, r
bind = $mainMod CTRL, K, movewindow, u
bind = $mainMod CTRL, J, movewindow, d

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Special workspace
bind = $mainMod SHIFT, U, movetoworkspace, special
bind = $mainMod, U, togglespecialworkspace,

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod, period, workspace, e+1
bind = $mainMod, comma, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, G, togglegroup
bind = $mainMod, tab, workspace, m+1
bind = $mainMod SHIFT, tab, workspace, m-1
bind = ALT, tab, workspace, m+1
bind = ALT SHIFT, tab, workspace, m-1

bind = $mainMod, O, exec, $colorpicker
bind = $mainMod SHIFT, O, exec, $term --class hyprpicker --hold -e hyprpicker
bind = $mainMod CTRL, S, exec, $wofi_beats

# Screenshot keybindings
bind = , Print, exec, $screenshot --now
bind = $mainMod, Print, exec, $screenshot --in5
bind = SHIFT, Print, exec, $screenshot --in10
bind = CTRL, Print, exec, $screenshot --win
bind = $mainMod CTRL, Print, exec, flameshot gui

# Qwerty
# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Azerty
# Switch workspaces with mainMod + [0-9]
#bind = $mainMod, Ampersand, workspace, 1
#bind = $mainMod, Eacute, workspace, 2
#bind = $mainMod, Quotedbl, workspace, 3
#bind = $mainMod, Apostrophe, workspace, 4
#bind = $mainMod, Parenleft, workspace, 5
#bind = $mainMod, Section, workspace, 6
#bind = $mainMod, Egrave, workspace, 7
#bind = $mainMod, Exclam, workspace, 8
#bind = $mainMod, ccedilla, workspace, 9
#bind = $mainMod, agrave, workspace, 10

# Qwerty
# Move active window and follow to workspace
bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10
bind = $mainMod CTRL, bracketleft, movetoworkspace, -1
bind = $mainMod CTRL, bracketright, movetoworkspace, +1

# Azerty
# Move active window and follow to workspace
#bind = $mainMod CTRL, Ampersand, movetoworkspace, 1
#bind = $mainMod CTRL, Eacute, movetoworkspace, 2
#bind = $mainMod CTRL, Quotedbl, movetoworkspace, 3
#bind = $mainMod CTRL, Apostrophe, movetoworkspace, 4
#bind = $mainMod CTRL, Parenleft, movetoworkspace, 5
#bind = $mainMod CTRL, Section, movetoworkspace, 6
#bind = $mainMod CTRL, Egrave, movetoworkspace, 7
#bind = $mainMod CTRL, Exclam, movetoworkspace, 8
#bind = $mainMod CTRL, ccedilla, movetoworkspace, 9
#bind = $mainMod CTRL, agrave, movetoworkspace, 10
#bind = $mainMod CTRL, bracketleft, movetoworkspace, -1
#bind = $mainMod CTRL, bracketright, movetoworkspace, +1

# Qwerty
# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10
bind = $mainMod SHIFT, bracketleft, movetoworkspacesilent, -1
bind = $mainMod SHIFT, bracketright, movetoworkspacesilent, +1

# Azerty
# Move active window to a workspace with mainMod + SHIFT + [0-9]
#bind = $mainMod SHIFT, Ampersand, movetoworkspacesilent, 1
#bind = $mainMod SHIFT, Eacute, movetoworkspacesilent, 2
#bind = $mainMod SHIFT, Quotedbl, movetoworkspacesilent, 3
#bind = $mainMod SHIFT, Apostrophe, movetoworkspacesilent, 4
#bind = $mainMod SHIFT, Parenleft, movetoworkspacesilent, 5
#bind = $mainMod SHIFT, Section, movetoworkspacesilent, 6
#bind = $mainMod SHIFT, Egrave, movetoworkspacesilent, 7
#bind = $mainMod SHIFT, Exclam, movetoworkspacesilent, 8
#bind = $mainMod SHIFT, ccedilla, movetoworkspacesilent, 9
#bind = $mainMod SHIFT, agrave, movetoworkspacesilent, 10
#bind = $mainMod SHIFT, bracketleft, movetoworkspacesilent, -1
#bind = $mainMod SHIFT, bracketright, movetoworkspacesilent, +1

======Config-End========

```

</details>

### Description

If I set `disable_hyprland_logo: true` under `misc` configuration, only a black screen with mouse cursor is shown. If I launch an app using keyboard shortcuts the window also shows a black surface.

### How to reproduce

Set `disable_hyprland_logo: true` under `misc` configuration and launch Hyprland.

**Comment by vaxerski** [comment] 2024-12-23 21:02
well the first part is expected: you disable the logo, so we draw black instead...

Wdym apps are black tho??

**Comment by mikiadev** [comment] 2024-12-24 12:17
I think this is pretty much a duplicate of #8613 and has something to do with Nvidia graphics/drivers...

**Comment by vaxerski** [comment] 2024-12-25 14:59
prolly, right

**Closed by vaxerski** 2024-12-25 14:59 UTC
Labels: bug
