### ISSUE TITLE
wlogout "logout" function hangs if activated by mouse click.  Hotkey ("e") works fine.

### ISSUE THREAD

**Issue by joekm** [hyprwm/Hyprland#4599] opened 2024-02-03 02:29 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Just got the latest hyprland-git today and did not have this behavior prior to it.  

If I run wlogout and try to logout with a mouse click, it will hang until i hit a key.  If I use the hotkey for logout ("e"), it works just fine.  If I just type the command called by wlogout in a terminal ("hyprctl dispatch exit 0"), it also works just fine.    So, it seems to be an issue with the mouse click.   

Lock, reboot, and shutdown all work just fine (I don't use suspend or hibernate on this machine).

### How to reproduce

Call wlogout and attempt to logout using a mouse click.

**Comment by vaxerski** [comment] 2024-02-03 03:27
wouldn't that make it an issue with wlogout?

**Comment by joekm** [comment] 2024-02-03 03:35
wlogout code hasn't changed in years and this issue started with the latest hyperland-git update.  My suspicion is that it's something to do with grabbing the mouse input on the hyprland side.

**Comment by MightyPlaza** [comment] 2024-02-03 03:38
> wlogout code hasn't changed in years and this issue started with the latest hyperland-git update. My suspicion is that it's something to do with grabbing the mouse input on the hyprland side.

if it is a regression mark it as one

do a git bisect (aka find the commit where it broke)

**Comment by zakk4223** [comment] 2024-02-03 07:18
It's this commit: 5eeec8860e2dc8ff80dda26243778b5ecc923ca2

It's because the exit flag processing only happens inside of onKeyboardKey()

Even in the case where it 'works' it's actually firing on the e key-up event. If I navigate to the logout entry with the arrow keys and then hit enter, it usually misses the enter-up event, causing me to have to hit another key to trigger the exit.

**Comment by Fxzzi** [comment] 2024-02-08 18:22
I use wleave instead of wlogout. wleave can use existing wlogout configs, it's literally a drop in replacement. Try with that instead?

**Comment by joekm** [comment] 2024-02-08 22:25
> I use wleave instead of wlogout. wleave can use existing wlogout configs, it's literally a drop in replacement. Try with that instead?

I did actually, and the issue persist.  For now, I'm just using hotkey "e" to logout.

**Comment by Fxzzi** [comment] 2024-02-09 07:15
> I'm not a developer so I don't really know "bug" vs "regression".

Bug is "it's always been an issue"
Regression is "it used to work, now vaxry broke it"

**Comment by zakk4223** [comment] 2024-02-24 15:36
Fixing this involves not processing the exit flag inside of the keyboard event handler. But where to put it? I don't know the motivation behind the patch that moved it there, so I'm afraid that anywhere I do move it might just be reintroducing some issue this was meant to fix. Halp

**Comment by dmayle** [comment] 2024-03-16 18:16
I don't see why exits can't be processed in both onKeyboardKey and onMouseMoved, which should allow it to work.  I'm going to try a patch locally

**Comment by zakk4223** [comment] 2024-03-16 19:09
That just means instead of having to hit a key, I can also wiggle the mouse. It doesn't address the fundamental race condition.

**Comment by Rabcor** [comment] 2024-03-19 18:26
> I don't see why exits can't be processed in both onKeyboardKey and onMouseMoved, which should allow it to work. I'm going to try a patch locally

It should quite frankly not be processed in either of those, what if you want to execute it from inside a script?

**Comment by dmayle** [comment] 2024-03-19 21:02
Yes, unless you are performing `dispatch exit` from a timer, it has to come from some input mechanism.  Mouse and keyboard covers most of the bases.

**Comment by Rabcor** [comment] 2024-03-19 21:04
> Yes, unless you are performing `dispatch exit` from a timer, it has to come from some input mechanism. Mouse and keyboard covers most of the bases.

I have a script that gracefully closes all applications first before closing hyprland. I have to use the kill command to close hyprland because dispatch exit is worthless if executing it from a script.

**Comment by dmayle** [comment] 2024-03-20 01:03
It looks like the purpose of that commit is to prevent the cleanup from happening in the dispatch handler.  It is instead attached to the keyboard listener, but it should be able to work in any listener.  I've looked at the list of listeners in Compositor.cpp and there doesn't seem to be any per-frame listeners.  It shouldn't be too tough to use a different listener.  The surface onCommit should be called frequently enought to be able to handle the processing:

https://github.com/hyprwm/Hyprland/blob/main/src/desktop/WLSurface.cpp#L129

I'm debugging another issue right, if no movement has happened in this issue in a couple of days, I'll try a patch.

**Comment by dmayle** [comment] 2024-03-24 01:28
So I just tested moving this to WLSurface onCommit.  It works, but it's not as fast as using the input manager callbacks.  (Takes 3-5 seconds before exiting).

Since there are multiple surfaces, and not a single global like the input manager, I moved the exit signalling into the compositor, and the first event to hit the exit signal resets it, then requests the compositor exit.

My patch is against 0.36, not 0.37.1.

I'm going to look for another event to see if there is one which happens per-frame, even if I have to add the listener.

**Comment by dmayle** [comment] 2024-03-24 01:30
I forgot to attach the patch:

[0001-Move-exit-trigger-to-surface.patch.txt](https://github.com/hyprwm/Hyprland/files/14734054/0001-Move-exit-trigger-to-surface.patch.txt)

**Comment by dmayle** [comment] 2024-03-24 01:50
...and I've solved it.  monitorFrame is what I wanted.  Here's the patch to 0.36:

[0001-Move-exit-trigger-to-monitor-frame.patch.txt](https://github.com/hyprwm/Hyprland/files/14734089/0001-Move-exit-trigger-to-monitor-frame.patch.txt)

**Closed** 2024-03-25 01:47 UTC
Labels: bug

**Comment by bubba-champion** [comment] 2024-06-07 19:37
@vaxerski, can it be reopened? https://github.com/hyprwm/Hyprland/issues/4849#issuecomment-2113644323
