### ISSUE TITLE
[Feature request] Set workspaces as persistent, and set a static order for named workspaces

### ISSUE THREAD

**Issue by zoro11031** [hyprwm/Hyprland#1007] opened 2022-11-13 10:17 UTC
Right now you can choose to name your workspaces using the name:[name] variable, but they will be ordered in the order they are created/have windows added to them. It would be great to add a functionality to give named workspaces a set order

**Comment by vaxerski** [comment] 2022-11-13 14:23
dupe of #665

**Closed by vaxerski** 2022-11-13 14:23 UTC
Labels: enhancement
