### ISSUE TITLE
animations:enabled = no flicker

### ISSUE THREAD

**Issue by KaiJan57** [hyprwm/Hyprland#4105] opened 2023-12-09 22:28 UTC
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).

### Bug or Regression?

Bug

### Description

With `animations:enabled = no` in `hyprland.conf`, we should expect perfect frames without flicker. However, whenever the layout changes, one can briefly see frames from the animations, as if animation speed was set to a very high value, but not high enough to skip animation frames altogether.

### How to reproduce

set `animations:enabled = no` in `hyprland.conf` and start changing the layout, e.g. open/close windows, resize, change split factor etc.

**Comment by vaxerski** [comment] 2023-12-09 23:47
firstly, you are wrong.

secondly, dupe of #2767

**Closed by vaxerski** 2023-12-09 23:47 UTC
Labels: bug
