### ISSUE TITLE
Crashes when changing resolution or frame rate

### ISSUE THREAD

**Issue by hawkpro-1** [hyprwm/Hyprland#1925] opened 2023-03-31 18:37 UTC
I use a 120fps monitor and hyprland defaults to 60fps by default when I try to modify the framerate or lower/change the resolution it crashes on initial application launch (I don't think its because of themes), I'm on Nix and I use Nvidia Please sue me already.

The log file
[hypr.log](https://github.com/hyprwm/Hyprland/files/11124876/hypr.log)

CrashReport 
[hyprlandCrashReport14621.txt](https://github.com/hyprwm/Hyprland/files/11124937/hyprlandCrashReport14621.txt)

The Config file (pretty much default but the change in res)
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11124879/hyprland.conf.txt)

**Comment by vaxerski** [comment] 2023-03-31 19:40
symbols are stripped from the coredump. @fufexan does nix set -rdynamic for the linker?

**Comment by fufexan** [comment] 2023-04-02 21:05
It does not afaik. I haven't seen it in the build logs at least.

**Comment by hawkpro-1** [comment] 2023-04-03 12:11
Is there anything that I can do to get the symbols ? is this gonna be stuck until we get the symbols ?

**Comment by hawkpro-1** [comment] 2023-04-04 18:46
For the life of me cannot install debug package ( Im a nix noob ) .  I tried setting it in nixpkgs.overlays I tried setting  ```package = hyprland.packages."x86_64-linux".debug; ```
none of them work can you help me out here pls 

```
{
  description = "Nix Config";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    hyprland = { url = "github:hyprwm/Hyprland"; };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    neovim-nightly-overlay = {
      url = "github:nix-community/neovim-nightly-overlay";
    };

  };

  outputs = { self, nixpkgs, hyprland, home-manager, neovim-nightly-overlay }: {
    nixosConfigurations = {
      hawk = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.hawk = { imports = [ ./packages ]; };

          }
          { nixpkgs.overlays = [ neovim-nightly-overlay.overlay ]; }
          hyprland.nixosModules.default
          {
            programs.hyprland = {
	      package = hyprland.packages."x86_64-linux".default;
              enable = true;
              xwayland = {
                enable = true;
          { nixpkgs.overlays = [ neovim-nightly-overlay.overlay ]; }
          hyprland.nixosModules.default
          {
            programs.hyprland = {
	      package = hyprland.packages."x86_64-linux".default;
              enable = true;
              xwayland = {
                enable = true;
                hidpi = true;
              };
              nvidiaPatches = true;
            };
                hidpi = true;
              };
              nvidiaPatches = true;
            };
          }

        ];
      };
    };
  };
}
```

**Comment by fufexan** [comment] 2023-04-04 20:44
```nix

{
  description = "Nix Config";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    hyprland.url = "github:hyprwm/Hyprland"; 

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    
    neovim-nightly-overlay.url = "github:nix-community/neovim-nightly-overlay";
  };

  outputs = { self, nixpkgs, hyprland, home-manager, neovim-nightly-overlay }: {
    nixosConfigurations = {
      hawk = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
          home-manager.nixosModules.home-manager
          hyprland.nixosModules.default
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              users.hawk.imports = [ ./packages ];
            };

            nixpkgs.overlays = [ neovim-nightly-overlay.overlay ];

            programs.hyprland = {
              enable = true;
      	      package = hyprland.packages."x86_64-linux".default.override {
                debug = true;
                hidpiXWayland = true;
                nvidiaPatches = true;
              };
            };
          }
        ];
      };
    };
  };
}
```

This should work.

**Comment by vaxerski** [comment] 2023-04-04 21:06
set an explicit scale in the config and see if that helps

**Comment by hawkpro-1** [comment] 2023-04-04 21:39
That seems to fix it

**Comment by vaxerski** [comment] 2023-04-04 21:43
dupe of #1579 then

**Closed by vaxerski** 2023-04-04 21:43 UTC
Labels: bug
