### ISSUE TITLE
Renderer defects: blinking and black lines

### ISSUE THREAD

**Issue by urose415** [hyprwm/Hyprland#879] opened 2022-10-19 17:45 UTC
Hello!
First, thanks for making this amazing compositor!

I just recently noticed that whilst playing games for example, the screen randomly starts flickering with small vertical lines stretching down. Here's a [video](https://workupload.com/start/6LUkexEsqpd) showcasing it.

It also happens when watching videos at times. I did find an issue that somewhat resembles this, but not quite: #649.
I've checked if the refresh-rate is properly setup, pushing it all the way down to 60Hz and checking wlr-randr if it's the correct value, but this issue still occur.

**Comment by vaxerski** [comment] 2022-10-19 17:51
either I am blind or there is nothing amiss in the video.

**Comment by urose415** [comment] 2022-10-19 17:57
![image](https://user-images.githubusercontent.com/116200083/196768303-db628bd3-370b-40fb-8089-d65cd026ee4a.png)
That's the lines at 1 second into the video

**Comment by vaxerski** [comment] 2022-10-19 17:58
??? Can you circle them, I literally see only a normal game and a fuckton of pixel artifacts because you're using a camera. Can't you record with OBS? Or does it not show on OBS?

**Comment by urose415** [comment] 2022-10-19 18:01
They don't show up on OBS, only on the screen itself. Tested with 2 different screens from 2 different brands, all have this issue.

Here's a better video where I was playing back a video and checked the top corner, whereas you can see it flickering: https://workupload.com/file/vQSZ8GnUymh

**Comment by vaxerski** [comment] 2022-10-19 18:04
Looks like either a damaged component (possibly the cable?) or a driver bug.

**Comment by vaxerski** [comment] 2022-10-19 18:12
Although I can reproduce this.... In some limited capacity. Have noticed this a while ago, but on my DP-2 monitor it subtly changes brightness whenever I type in firefox. Odd.

**Comment by urose415** [comment] 2022-10-19 18:15
Yeah, I just swapped the cable out for a HDMI one and it seems to be gone from the game, but still noticing slightly abrupt brightness changes in for say, wofi and other applications. Should I close the issue or leave it open?

**Comment by vars1ty** [comment] 2022-10-19 18:18
> Yeah, I just swapped the cable out for a HDMI one and it seems to be gone from the game, but still noticing slightly abrupt brightness changes in for say, wofi and other applications. Should I close the issue or leave it open?

Tested opening Wofi myself and also noticed the brightness changes, both on HDMI and DisplayPort, weird.

**Comment by vaxerski** [comment] 2022-10-19 18:18
regression, I am bisecting this atm.

**Comment by vaxerski** [comment] 2022-10-19 18:49
Found the culprit for me: VFR. Disabling it fixes the issue. Perhaps related to the ancient #351?

**Comment by vaxerski** [comment] 2022-10-19 18:50
can yall verify?

**Comment by vaxerski** [comment] 2022-10-19 18:54
and for both of you, your GPUs please if disabling VFR fixes the issue.

**Comment by urose415** [comment] 2022-10-19 19:10
It seems to have gone away by disabling it, the lines are still there but found out that it is indeed an issue with my cable, as changing profiles on my monitor between cinema vs normal drastically changes the output.

@vars1ty Your results?

**Comment by vaxerski** [comment] 2022-10-19 19:10
what GPU

**Comment by urose415** [comment] 2022-10-19 19:11
3070ti, so NVIDIA and when I think about it, it's probably their hacky drivers that cause it

**Comment by vaxerski** [comment] 2022-10-19 19:11
No, I am on AMD.

**Comment by urose415** [comment] 2022-10-19 19:12
No I was referring to the lines being an NVIDIA issue, as it only happens on Wayland for some strange reason (?), both Sway and Hyprland

**Comment by vars1ty** [comment] 2022-10-19 19:13
> Found the culprit for me: VFR. Disabling it fixes the issue. Perhaps related to the ancient #351?

Disabled and it seems to no longer be haunted.

**Comment by vars1ty** [comment] 2022-10-19 19:14
NSI GeForce RTX 3070TI

**Comment by vaxerski** [comment] 2022-10-19 19:26
follow the issue here: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3514

**Comment by vaxerski** [comment] 2022-10-19 19:28
I'll close this in favor of #351

**Closed by vaxerski** 2022-10-19 19:28 UTC
Labels: bug, Major, renderer
