### ISSUE TITLE
Extreme stuttering in Apex Legends

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#2085] opened 2023-04-17 09:59 UTC
Apex Legends stutters immensely when compared to GNOME despite being launched the exact same way (Lutris with gamescope enabled)

**Comment by vaxerski** [comment] 2023-04-17 12:13
sway?

**Comment by lou-perret** [comment] 2023-04-17 18:29
It works fine for me on Steam, did you try it ?

**Comment by ThatOneCalculator** [comment] 2023-04-17 18:29
Sway is weird and refuses to launch apps for me, but Wayfire (built as wayfire-git from the aur) gives the sane performance as GNOME, so it does appear to be Hyprland specific.

**Comment by ThatOneCalculator** [comment] 2023-04-17 18:32
> It works fine for me on Steam, did you try it ?

Lutris just acts as a launcher for Steam games, although I did try Steam directly and got the same results.

**Comment by Edgars-Cirulis** [comment] 2023-04-17 23:15
Same here but with other games, Games stuttering compared to KDE in my case.

**Comment by vaxerski** [comment] 2023-04-17 23:18
> but Wayfire (built as wayfire-git from the aur) gives the sane performance as GNOME, so it does appear to be Hyprland specific.

wf doesn't use wlroots-git. It might be a wlr issue after all.

Can anyone check sway-git?

**Comment by knipferrc** [comment] 2023-04-17 23:44
Apex works well for me through steam. I will say a fresh apex install stutters for me at first until it compiles/caches shaders. Not sure if that’s what your experiencing or not

**Comment by ThatOneCalculator** [comment] 2023-04-18 00:13
Nah, I went into firing range for almost half an hour and it was still constantly stuttering.

**Comment by Edgars-Cirulis** [comment] 2023-04-18 00:35
Tested sway-git it seems it gave me fluid experience on gaming compared to hyprland, but I had mouse issues on sway.

**Comment by Edgars-Cirulis** [comment] 2023-04-18 11:17
Any news?

**Comment by vaxerski** [comment] 2023-04-18 11:39
No, idk what's up

**Comment by Edgars-Cirulis** [comment] 2023-04-19 02:36
Maybe updating to the latest version of wlroots will fix it? I've seen that they've made a lot of changes.

**Comment by Edgars-Cirulis** [comment] 2023-04-19 08:28
> we are not that far behind -git.

Still it's a try.

**Comment by Zeioth** [comment] 2023-04-24 06:37
Try to isolate the issue. It runs perfectly fine on my end. Both on Sway and Hyprland.

**Comment by Edgars-Cirulis** [comment] 2023-04-28 19:51
Does it present on latest -git version wlroots had update

**Comment by ThatOneCalculator** [comment] 2023-04-28 21:31
I can test tomorrow

**Comment by Zeioth** [comment] 2023-04-30 07:44
I can confirm. The problem is present on hyprland-git+wlroots-git but not on wlroots+hyprland. The bug is several stuttering.

**Comment by GrabbenD** [comment] 2023-04-30 12:41
I've noticed this as well, Sway is visibly smoother than Hyprland (GIT).
Although according to Mangohud, frametimes and fps are very similar?
I've tried playing around with VRR/VFR without luck.
I'm not sure how to debug this to be honest

**Comment by vaxerski** [comment] 2023-04-30 12:52
> I can confirm. The problem is present on hyprland-git+wlroots-git but not on wlroots+hyprland. The bug is several stuttering and -10 -20 fps

Hyprland bundles wlroots, your system wlroots don't matter.

If this is a regression, I'd like a `git bisect` to be done.

**Comment by Edgars-Cirulis** [comment] 2023-04-30 13:42
> I can confirm. The problem is present on hyprland-git+wlroots-git but not on wlroots+hyprland. The bug is several stuttering and -10 -20 fps

Could you test with kernel command line parameter gpu_sched.sched_policy=0

**Comment by GrabbenD** [comment] 2023-04-30 16:37
@vaxerski I noticed that if I move with just the keyboard, the game is completely smooth (Halo Infinite in my instance but it's most likely the same issue as with Apex Legends). The stuttering only occurs when I actually move the mouse.

Could this be related?
> One thing that hasn't been mentioned here yet might warrant a protocol for VRR: the hardware cursor. When the application controls the refresh rate a hardware cursor will refresh slowly and stutter, when the cursor controls the refresh rate the application content will appear to stutter. There is also the option of refreshing the panel with a multiple of the application refresh rate while the cursor is changing but that has its limits in hardware and might still cause stutter with strongly fluctuating frame times, though the latter could be somewhat alleviated with present-timing.
>
> What I implemented for KWin is to always give the cursor precedence (I think in Sway it's the same?) and we'll give the user the option to disable that (for fullscreen) but that's far from ideal. While apps that explicitly want to control their timing could always draw a software cursor (or with present-timing only when VRR presentation occurs) that's not really a good solution either.
>
> (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/44#note_897546)

**Comment by Edgars-Cirulis** [comment] 2023-04-30 16:53
> @vaxerski I noticed that if I move with just the keyboard, the game is completely smooth (Halo Infinite in my instance but it's most likely the same issue as with Apex Legends). The stuttering only occurs when I actually move the mouse.
> 
> Could this be related?
> 
> > One thing that hasn't been mentioned here yet might warrant a protocol for VRR: the hardware cursor. When the application controls the refresh rate a hardware cursor will refresh slowly and stutter, when the cursor controls the refresh rate the application content will appear to stutter. There is also the option of refreshing the panel with a multiple of the application refresh rate while the cursor is changing but that has its limits in hardware and might still cause stutter with strongly fluctuating frame times, though the latter could be somewhat alleviated with present-timing.
> > What I implemented for KWin is to always give the cursor precedence (I think in Sway it's the same?) and we'll give the user the option to disable that (for fullscreen) but that's far from ideal. While apps that explicitly want to control their timing could always draw a software cursor (or with present-timing only when VRR presentation occurs) that's not really a good solution either.
> > (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/44#note_897546)

Could you test with kernel command line parameter gpu_sched.sched_policy=0

**Comment by GrabbenD** [comment] 2023-04-30 17:06
There's no difference with `gpu_sched.sched_policy=0` on a RX 6800 XT :/

**Comment by Edgars-Cirulis** [comment] 2023-04-30 17:47
> There's no difference with `gpu_sched.sched_policy=0` on a RX 6800 XT :/

Does enabling vsync fixes stuttering?

**Comment by GrabbenD** [comment] 2023-04-30 17:57
> Does enabling vsync fixes stuttering?

I've tried enabling/disabling these to no avail:
- Direct scanout
- VRR
- VFR
- 10 bit colors
- Low/high refresh rate
- Vulkan/GLES2 renderer
- WLR_DRM_NO_ATOMIC env
- WLR_NO_HARDWARE_CURSORS env

I may be wrong but it seems like this issue is correlated to the mouse cursor, moving around in game with just the keyboard is buttersmooth.

For wlroots, there is a experimental patch here for wlroots if it's indeed the mouse cursor causing it in Hyprland: https://gitlab.freedesktop.org/drm/amd/-/issues/2186#note_1765619 (but Hyprland would need to be tweaked to use this patch and it's outside of my expertise)

**Comment by GrabbenD** [comment] 2023-04-30 18:42
@ThatOneCalculator This is how the stuttering looks on my end. Is it the same as yours?

https://youtu.be/LuTYTEaJJyI
[![https://youtu.be/LuTYTEaJJyI](https://img.youtube.com/vi/LuTYTEaJJyI/maxresdefault.jpg)](https://youtu.be/LuTYTEaJJyI)

**Comment by Edgars-Cirulis** [comment] 2023-04-30 20:13
> @ThatOneCalculator This is how the stuttering looks on my end. Is it the same as yours?
> 
> https://youtu.be/LuTYTEaJJyI [![https://youtu.be/LuTYTEaJJyI](https://camo.githubusercontent.com/155484502e950ecac34360eab02af81b9a5ddcbe44ad57b57ac24a2deb3f4e60/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f4c7554595445614a4a79492f6d617872657364656661756c742e6a7067)](https://youtu.be/LuTYTEaJJyI)

Try switching to linux-lts kernel. It should fix.

**Comment by ThatOneCalculator** [comment] 2023-04-30 20:36
@GrabbenD mine is a bit more ittermittent

**Comment by GrabbenD** [comment] 2023-04-30 20:48
> Try switching to linux-lts kernel. It should fix.

Thanks for the idea
Certain kernels make the issue less apparent but it's still there 🙁 . Here's all I've tried:
- 5.15.109-LTS
- 6.1.26-LTS
- 6.1.26-RT
- 6.1.13-rt7-xanmod (smoothest in my opinion)
- 6.2.11-xanmod
- 6.2.13-LQX
- 6.2.13-ZEN
- 6.2.13-TKG

**Comment by Edgars-Cirulis** [comment] 2023-05-01 09:05
> 

6.2 has some more demand stuttering then 6.1 in case

**Comment by Edgars-Cirulis** [comment] 2023-05-01 09:06
> > Try switching to linux-lts kernel. It should fix.
> 
> Thanks for the idea Certain kernels make the issue less apparent but it's still there 🙁 . Here's all I've tried:
> 
> * 5.15.109-LTS
> * 6.1.26-LTS
> * 6.1.26-RT
> * 6.1.13-rt7-xanmod (smoothest in my opinion)
> * 6.2.11-xanmod
> * 6.2.13-LQX
> * 6.2.13-ZEN
> * 6.2.13-TKG

Reason i suggested because 6.2.x has some stuttering issues that was introduced meanwhile 6.1 has less

**Comment by Zeioth** [comment] 2023-05-02 17:01
I've been testing on both hyprland and hyprland-git today and I cannot reproduce now. My kernel is beign josh's 6.0.0-1-hdr-git-02753-gff57328e5784 for all my tests so far. I'll keep an eye on this issue in case I can find something conclusive.

**Comment by GrabbenD** [comment] 2023-05-02 17:05
Thanks for the update @Zeioth
- Did you try Halo Infinite? (It's free on Steam)
- What's your distro?
- Which GPU?
- Did you try it with GameScope? (On my end it almost fixes stuttering completely)

I'm in progress of trying OpenSuSE instead of NixOS.

**Comment by GrabbenD** [comment] 2023-05-03 18:07
Update: the stuttering in NixOS (hyprland-git https://github.com/hyprwm/Hyprland/commit/2e28e88dfdca3d836c5dbedb916e0f629fc6a540) is worse than with OpenSuSE Tumbleweed (Hyprland v0.24.1). OpenSuSE gives me roughly 20-30 better fps & decreases frametime with 3-4ms since they're using x64_86-v3 optimization level with LTO+PGO.

**Turns out the stuttering only happens when the game runs below my monitor's refresh rate even with `vrr=1`** 
```
~> hyprctl monitors
Monitor DP-3 (ID 0):
	3840x1600@119.982002 at 0x0
	description: Dell Inc. Dell AW3821DW #HLAYMxgwABTR (DP-3)
	make: Dell Inc.
	model: Dell AW3821DW
	serial: #HLAYMxgwABTR
	active workspace: 2 (2)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 1
```

My monitor's Freesync range is 1-144 hz and it even has a dedicated GSync Ultimate chip :/

For clarification, I pretty much only installed Hyprland, xdg, MESA, codecs, kernel-firmware, pipewire, steam, mangohud & gamemoded while testing this.

**Comment by GrabbenD** [comment] 2023-05-04 09:30
Another update:

1. Changing power profile for the GPU greatly improved 1% lows and avg fps but the stuttering is still visible when fps falls below monitor's refresh rate:
    ```
    # /etc/udev/rules.d/30-amdgpu.rules
    KERNEL=="card1", SUBSYSTEM=="drm", DRIVERS=="amdgpu", ATTR{device/power_dpm_force_performance_level}="manual", ATTR{device/pp_power_profile_mode}="1"
    ```
    (see: https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_1854170)

2. Furthermore I tried using async frames (`MESA_VK_WSI_PRESENT_MODE`) but it looks like it's not supported by wl-roots yet.
    (see: https://docs.mesa3d.org/envvars.html#envvar-MESA_VK_WSI_PRESENT_MODE)
    (reference: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/65)

3. > Does enabling vsync fixes stuttering?
    
    **Just a update: `vsync off` (ingame) with `vrr=0` (Hyprland) performs exactly the same as: `vsync off` (ingame) with `vrr=1` (Hyprland)**
    (it vastly reduces stuttering but it's still there when fps < refresh rate)

It seems like Variable Refresh Rate (VRR) in Hyprland doesn't actually adjust monitor's refresh rate in that case? I have no way of verifying this in my panel unfortunately

**Comment by GrabbenD** [comment] 2023-05-04 15:25
@ThatOneCalculator If your intermittent stuttering is actually caused by frame drops and not a different bug like fTPM stutter bug in AMD CPUs, I don't think there is much we can do about it until the VRR implementation gets improved:
https://github.com/hyprwm/Hyprland/issues/927

Related issues:
- [With vrr and atomic modesetting, some cursor plane updates are dropped](https://gitlab.freedesktop.org/drm/amd/-/issues/2186)
- https://github.com/swaywm/sway/issues/6832
- https://github.com/swaywm/sway/issues/5601
- https://github.com/swaywm/sway/issues/5076
- [RFC: Add zwp_vrr_v1](https://gitlab.freedesktop.org/wayland/wayland/-/issues/84#note_609628)

**Comment by grappas** [comment] 2023-05-06 16:34
@ThatOneCalculator Isn't that connected?
https://github.com/hyprwm/Hyprland/issues/1919
Check it with `hyprctl keyword debug:overlay true`

**Comment by GrabbenD** [comment] 2023-05-07 21:05
Great find @grappas!
On my end VRR/vsync seems to be the culprit as the compositor's FPS is correct (`debug:overlay=1` + `misc:vfr=0`):
![1683493231-wayshot](https://user-images.githubusercontent.com/45666572/236702452-c055b8c6-96e0-4665-b330-ac2df229578e.png)

**Comment by grappas** [comment] 2023-05-08 17:10
> Great find @grappas! On my end VRR/vsync seems to be the culprit as the compositor's FPS is correct (`debug:overlay=1` + `misc:vfr=0`): ![1683493231-wayshot](https://user-images.githubusercontent.com/45666572/236702452-c055b8c6-96e0-4665-b330-ac2df229578e.png)

But just to be sure check it CPU bottlenecked (lowest settings possible).

**Comment by GrabbenD** [comment] 2023-05-21 19:38
> But just to be sure check it CPU bottlenecked (lowest settings possible).

Sure @grappas, I can reproduce your issue by forcing my game to be CPU bound. Let's continue the discussion here: https://github.com/hyprwm/Hyprland/issues/1919#issuecomment-1556268402 (since it's unclear if this PR is about stuttering from VRR or resource starvation as the author isn't replying).

**Comment by roman3pm** [comment] 2023-10-03 21:04
Same here on sway. For me is the only way to smooth run Apex is turn screen mode to Windowed and run sway with `-Dnoscanout`. Switch to Fullscreen or Borderless causes immediate stuttering. Removing noscanout option completely disables vrr. Really annoying but it works for now. Can someone else check that Windowed mode helps with stuttering?

**Comment by vaxerski** [comment] 2023-10-03 23:48
why not try on -git with tearing?

**Comment by roman3pm** [comment] 2023-10-04 01:53
> why not try on -git with tearing?

Can confirm it works but personally not a fan of tearing. Fells pretty stuttery even witn 200+ fps on 144Hz monitor. I'm looking for smooth vrr gameplay, but this game even with regular vsync is kinda of a mess.

**Comment by GrabbenD** [comment] 2023-10-04 07:05
I have not found any way to resolve this in Hyprland 🙁
It has the worst stuttering in comparison to Sway, KDE (Wayland) and RiverWM.
However, I have a really good solution for Sway:

**There's 2 parts to this problem**
1. [Atomic Modesetting](https://gitlab.freedesktop.org/drm/amd/-/issues/2186) causes your mouse's polling rate to change your monitor's refresh rate. Here's is a [workaround for Sway](https://github.com/swaywm/sway/issues/6832#issuecomment-1698442549) (check this [comment](https://github.com/swaywm/sway/issues/6832#issuecomment-1703684151) for Sway 1.9-dev compatible patches).
As a reference, [here's the outdated](https://github.com/swaywm/sway/issues/6832#issuecomment-1612314863) solution to this issue.
2. Direct scanout causes the monitor to run at max refresh rate, [here's a workaround for Sway](https://github.com/swaywm/sway/issues/7370#issuecomment-1688612523) 
3. _Extra: make sure VSync is disabled in-game to avoid having multiple buffers_
4. _Extra: try to force enable VRR with kernel [boot argument on AMD](https://github.com/swaywm/sway/issues/7370#issuecomment-1694485033)_

I've tried this with a RX 6800 XT + Ryzen 9 5950X (fTPM off) + 1000Hz mouse and confirmed this issue exists in multiple monitors in Arch Linux, Fedora & OpenSuSE Tumbleweed:
- AOC Q32G1WG4
- MSI MAG27CQ
- Alienware AW3821DW

> why not try on -git with tearing?

Thanks for the idea but this makes it worse, the stuttering is still there and in-game textures are completely smeared out due to tearing.

**Comment by GrabbenD** [comment] 2023-10-05 20:04
@vaxerski
My monitor's built-in FPS counter reports 6 HZ in desktop when VRR is enabled with Sway. However, with Hyprland it's stuck at 120Hz all the time, even when playing games at 80 FPS. What's strange is that the monitor claims adaptive sync is enabled when using Hyprland. I'm guessing something in Hyprland is constantly pushing max FPS to the screen - maybe to make the animations buttersmooth?

I've tried isolating this issue with various combinations of settings to no avail:
- `misc:vrr` 2/1/0
- `misc:vfr` 1/0
- `misc:no_direct_scanout` 1/0
- `debug:damage_tracking` 2/1/0

I'm not sure what else to try, I've back revising this issue once in a while since March of this year (when I started using Hyprland)

**Comment by vaxerski** [comment] 2023-10-05 23:56
what if you enable tearing? without that it will push 2x fps of your game

**Comment by grappas** [comment] 2023-10-06 05:48
> However, with Hyprland it's stuck at 120Hz all the time,

It's actually a gamescope thing. If you want i.e. 240Hz you want to set -r 480.

**Comment by GrabbenD** [comment] 2023-10-06 07:00
Thanks for taking a look guys!

> what if you enable tearing? without that it will push 2x fps of your game most likely

My games are GPU bounds
I'm getting stable 80-90 FPS
Enabling tearing gives me the same result as @roman3pm, it's still stuttering since the monitor is stuck at 120 HZ 

> It's actually a gamescope thing. If you want i.e. 240Hz you want to set -r 480.

I don't use Gamescope since I haven't found any performance difference when it's running in nested mode. Nonetheless I tried `gamescope -f -r 120 -- %command%` and `gamescope -f -r 240 -- %command%` but there's no difference, the monitor is still stuck at 120 HZ

---

@vaxerski
When I say the monitor is stuck at 120 HZ, I mean it. It never dips below 120 HZ in Hyprland.
I find it strange that I can reproduce this issue on 3 different monitors
I'm currently running Arch Linux with pretty much defaults settings everywhere, I only installed MESA drivers, Pipewire, Wireplumber, Pavucontrol, Steam, Halo Infinite, Brave browser & Foot terminal.

**Comment by grappas** [comment] 2023-10-06 09:31
Have you tried forcing fps with mangohud?

**Comment by GrabbenD** [comment] 2023-10-06 10:07
> Have you tried forcing fps with mangohud?

Are you thinking about forcing vsync through MangoHud? Gave this a shot but it made no diference:

```
# ~/.config/MangoHud/MangoHud.conf

### Vulkan VSync [0-3] 0 = adaptive; 1 = off; 2 = mailbox; 3 = on
vsync=0

### OpenGL VSync [0-N] 0 = off; >=1 = wait for N v-blanks, N > 1 acts as a FPS limiter (FPS = display refresh rate / N)
gl_vsync=1
```

Considering I have to disable direct scanout in Sway to get the right refresh rate (which I verify with my monitor's OSD), there's probably a similar bug somewhere in Hyprland but I'm not sure how to go about finding it 🙁

**Comment by roman3pm** [comment] 2023-10-07 10:50
To uncap fps without vsync in Apex you should switch mangohud's `vsync=1` (means off) and in game switch to triple buffering and maybe include launch command `+fps_max 300`. It helps a bit if you play with tearing on.
Try to play in windowed mode. I saw some pro player streamers plays in windowed mode in OS Windows too. Something strange with this game.
By the way I think Apex devs should pay attention to this. CS2 runs perfectly smooth without any tinkering at all with vsync off.

**Comment by ParetoOptimalDev** [comment] 2024-01-06 00:58
> To uncap fps without vsync in Apex you should switch mangohud's vsync=1 (means off) and in game switch to triple buffering and maybe include launch command +fps_max 300. It helps a bit if you play with tearing on.
Try to play in windowed mode. I saw some pro player streamers plays in windowed mode in OS Windows too. Something strange with this game.

Apex plays fine without stuttering in KDE fullscreen though.

In hyprland though I still get stuttering.

**Comment by ParetoOptimalDev** [comment] 2024-01-08 00:00
Updated workaround I found in another issue is to launch gamescope in embedded mode in another tty:

So press `Ctrl+alt+F2`, then after replacing your monitor dimensions and frame rate:

```
https://github.com/ValveSoftware/gamescope/issues/995gamescope -W 1920 -H 1080 -r 144 --adaptive-sync -e -f -- steam
```

Though things seemed less good with a limited frame rate for me so I do:

```
https://github.com/ValveSoftware/gamescope/issues/995gamescope -W 1920 -H 1080 --adaptive-sync -e -f -- steam
```

**Comment by GrabbenD** [comment] 2024-01-08 01:07
@ParetoOptimalDev Just leave a link to the solution next time instead of making your own half-assed copy & paste with missing details

https://github.com/hyprwm/Hyprland/issues/927#issuecomment-1556270866

**Comment by ParetoOptimalDev** [comment] 2024-01-08 01:47
> @ParetoOptimalDev Next time just leave the link to the workaround instead of making your own half-assed copy & paste with missing details
> 
> [#927 (comment)](https://github.com/hyprwm/Hyprland/issues/927#issuecomment-1556270866)

Don't be an asshole for no reason.

**Comment by rurigk** [comment] 2024-03-01 00:07
I only noticed stuttering in games in 2 situations
If i use gamescope some games like Apex stutters for me
If i have vrr enabled in my monitor the GPU is stuck at 96mhz (linux 6.7.6)

I have a 6700XT and R7 2700X the monitor is a Samsung Odyssey G5 32" 165hz

**Comment by wyqydsyq** [comment] 2024-07-04 03:07
Not related to Apex Legends specifically but I've been intermittently having this issue on UE5 based games as well. 
Occurring in Mortal Online 2 and Gray Zone Warfare. It's most severe when game FPS is lower than my monitor refresh rate (165hz), if I FPS limit a game to 60fps it's practically motion-sickness inducing. Making sure the game's FPS matches or exceeds my refresh rate minimizes the effect but it is still noticeable

**Comment by wyqydsyq** [comment] 2024-08-13 00:19
Not running -git build but the OpenSUSE TW repo recently updated to 0.42. I can't speak for OP since I don't play Apex Legends but the (mostly UE5 via VKD3D but also happened in BG3 using Vulkan renderer) games that were exhibiting this stuttering for me under wlroots all seem to be fixed now under aquamarine, so it definitely seems to have been a wlroots-specific issue at least in my case.

**Comment by izmyname** [comment] 2024-08-13 05:49
Closing, then?

**Closed** 2024-08-13 17:22 UTC
Labels: bug, reason-unknown
