### ISSUE TITLE
Mouse click on Remmina VNC over Hyprland and Wayvnc doesn't work

### ISSUE THREAD

**Issue by fooryo** [hyprwm/Hyprland#5482] opened 2024-04-07 16:26 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)

System Information:
System name: Linux
Node name: orione
Release: 6.6.25-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:16:56 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [UHD Graphics] [8086:4628] (rev 0c) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

</details>

### Bug or Regression?

Bug

### Description

Pardon my noobness. These are my first attempts to do this kind of deployment.

Host:
A small host connected to the home network without any keyboard nor mouse attached, only a (fake) display (basically an HDMI dongle.
Arch Linux 
Hyprland 0.38.1-1
wayvnc 0.8.0-1

Guest:
Manjaro Linux KDE Plasma 5.27.11
Remmina 1:1.4.35-1

I can change the focus between containers/windows moving the mouse on Remmina but nothing happens clicking on buttons/UI/stuff (neither on applications nor waybar tray) . Tigervnc doesnt even show a mouse pointer on the screen but same behaviour: can shange hyprland focus but no click.

### How to reproduce

1) start hyrpland session
2) start wayvnc server
3) connect to vnc server via remmina

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14897982/hyprland.log)

**Comment by Micovec** [comment] 2024-04-08 12:25
Isn't this dupe of #1497 ?

**Comment by fooryo** [comment] 2024-04-08 13:53
> Isn't this dupe of #1497 ?

I don't know if it can be considered a dupe. He launches Hyprland, then wayvnc and _then detaches the mouse_.

I don't even have a mouse (nor a kb) at the beginning. Nothing to detach. 

(I would even detach the fake monitor HDMI dongle if I knew how to create a virtual one, but that's another story.)

**Comment by vaxerski** [comment] 2024-04-08 17:21
it's a dupe.

**Closed by vaxerski** 2024-04-08 17:21 UTC
Labels: bug
