### ISSUE TITLE
A bunch of issues

### ISSUE THREAD

**Issue by constantitus** [hyprwm/Hyprland#3542] opened 2023-10-10 11:32 UTC
### Hyprland Version

Hyprland, built from branch HEAD at commit 8abb6e1cee3e967ff414af0d6a1a31ebced95f5b  (screencopy: enhance error logging).

### Bug or Regression?

Bug

### Description

Sorry for my bad naming sense regarding the title.
So I am trying to transition from xorg to Hyprland and I have a bunch of issues. I'll start with the most annoying one.
- When my cpu usage is high, the whole WM lags, especially the cursor. This usually happens when I'm compiling stuff and my cpu sits at 100%, but it may also happen when running other cpu intensive tasks. This has never happened on xorg.
- Sometimes my cursor disappears and it doesn't appear after moving. I have to switch focus to another workspace and back to make it reappear. If this is a setting, I'd like this behaviour to stop entirely. I never want my cursor to disappear.
- Sometimes firefox and other GUI windows become unclickable. Not sure if it's a Hyprland issue, but clicking on another window and then back on it makes it clickable again. This usually triggers in firefox when rightclicking to open menus or when browsing for files to upload onto a site (the window that pops and allows me to select files is also unclickable until I click on some other window). Does not happen on xorg.
- Also on the topic of firefox, if I try to start another instance of firefox, it tells me that "Firefox is already running, but not responding...". Perhaps not a hyprland issue, but I'm leaving this here because it doesn't do that on xorg.
- htop is full of xdg-desktop-portal-hyprland. I thought this was resolved with 1.2.1, but apparently not for me.

I am running gentoo, hyprland is from master branch and 2 monitors on AMD RX590.
Ironically, I run Hyprland with roughly the same settings on a laptop with nvidia gpu and I don't face most of these issues.

### How to reproduce

My config files:
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/12856449/hyprland.conf.txt)
[execs.conf.txt](https://github.com/hyprwm/Hyprland/files/12856455/execs.conf.txt)

**Comment by vaxerski** [comment] 2023-10-10 11:35
ad 1)
this is a scheduling issue. Set the nice value of hyprland lower or set a different scheduling policy for it, manually.

ad 2)
reported issue, dupe of something I am on mobile search the issue tracker

ad 3)
iirc dupe as well, but it's most likely a ff issue

ad 4)
firefox issue

ad 5)
full of...? But at 100% cpu or something, or just multiple entries? if multiple entries, those are just threads. If 100% cpu usage, thats a dupe of an issue reported at xdph.

regards

**Closed by vaxerski** 2023-10-10 11:35 UTC
Labels: bug

**Comment by constantitus** [comment] 2023-10-10 12:16
>threads

![image](https://github.com/hyprwm/Hyprland/assets/118078873/97fa31ac-3858-44e0-88ca-149a5e028e00)
if this plethora of threads is a normal thing, then I'll let you know that they impede with the functionality of other programs such as wezterm.
'''
~ % wezterm
15:13:05.371  ERROR  env_bootstrap > panic at config/src/lib.rs:507:59 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_main
  16: <unknown>

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), paths: [] }', config/src/lib.rs:507:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
'''
And yes, their cpu usage is high
![image](https://github.com/hyprwm/Hyprland/assets/118078873/c16997ed-a460-478c-a8c4-50724d3ad26e)

**Comment by constantitus** [comment] 2023-10-10 12:26
Also, regarding the other, more important issues
1)
If I spawn Hyprland with a lowe nice value, then every window launched in Hyprland will inherit the nice value, so that won't help.
2)
I'll have to look through them, sorry for not looking before
3)
not a ff issue, it happens in other windows. their border indicate that they are focused, but aren't clickable.
4)
again, my bad

**Comment by vaxerski** [comment] 2023-10-10 13:40
the issue you see in xdph was fixed in 1.2.0/1.2.1
