### ISSUE TITLE
re-focusing main window after popup has been shown makes intellij not respond to keyboard inputs

### ISSUE THREAD

**Issue by pulsar256** [hyprwm/Hyprland#1229] opened 2022-12-15 11:44 UTC
## Steps to reproduce

- affects at least b89a07596e9f1caa353caec13cb328a98b39944c
- open a text file in an Jetbrains Product such as IntelliJ Idea or GoLand
- Ctrl+Shift+F to open a search and replace dialog
- escape to close the dialog

## Expected outcome

- after closing the dialog main window is focused accepting user inputs

## Noted outcome

- main window is indicated as focused by the decoration border but no cursor is active
- mouse selection still works
- keyboard input does not work 
- after focusing another window and going back to the main editor window functionality is restored

[jetbrains_refocus.txt](https://github.com/hyprwm/Hyprland/files/10236543/jetbrains_refocus.txt)

https://user-images.githubusercontent.com/1245126/207849829-6b52d37a-1178-4a95-9def-193e5d4785b9.mp4

**Comment by vaxerski** [comment] 2022-12-15 12:24
funny that the shift shift search menu isnt affected, lol

**Comment by vaxerski** [comment] 2022-12-15 12:39
fixed in efc686423ac9764b64177db9c80e4835d57863d7

**Closed by vaxerski** 2022-12-15 12:39 UTC
Labels: bug

**Comment by pulsar256** [comment] 2022-12-15 14:06
there are a couple of other dialogs suffering from the same issue. Search and replace dialog is fixed though. F5 (copy), F6 (rename) for example. how would i go about to list the `HYPRATOMS` keys required to add the special handling?

**Comment by vaxerski** [comment] 2022-12-15 14:35
can't repro those. They work for me.

**Comment by pulsar256** [comment] 2022-12-15 14:44
does this help?

idle state ide:

```
~ ᐅ xdotool search --any idea | xargs -i xprop -id {} | grep -i atom
Defaulting to search window name, class, classname, and role
_SUNW_JAVA_AWT_TIME(ATOM) =
XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_STATE(ATOM) =
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
```

ide with "offending" dialog open:

```
~ ᐅ xdotool search --any idea | xargs -i xprop -id {} | grep -i atom
Defaulting to search window name, class, classname, and role
_SUNW_JAVA_AWT_TIME(ATOM) =
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
XdndAware(ATOM) = BITMAP
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_STATE(ATOM) =
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
```

https://user-images.githubusercontent.com/1245126/207890127-2f92118e-2e2e-45f4-bc4b-9c7af13ba2a8.mp4

**Comment by vaxerski** [comment] 2022-12-15 14:46
what is that? I am only testing intellij idea.

**Comment by pulsar256** [comment] 2022-12-15 14:47
it is idea. distraction free mode, new ui enabled.

**Comment by vaxerski** [comment] 2022-12-15 14:47
new ui?

also make sure you're running the new commit by verifying the hash in `hyprctl version`

**Comment by pulsar256** [comment] 2022-12-15 14:48
```
ᐅ hyprctl version
Hyprland, built from branch main at commit e405490593cd8f38e95bdbbc90fcb617039f23b1dirty (fix workspace special rules).
flags: (if any)
```

![image](https://user-images.githubusercontent.com/1245126/207891200-0073d0d9-bff0-4b54-91f1-651d14be308f.png)

**Comment by vaxerski** [comment] 2022-12-15 14:52
Ah, found it and I see. It's a problem with IntelliJ (and/or the shitness of java/x11)

The issue is:
  - IJ opens a new dialog
  - Hyprland focuses the dialog.
  - Dialog receives keystrokes
  - You close the dialog
  - Hyprland closes the dialog and refocuses IJ again
 
 Everything is fine. However if:
  - IJ opens a new dialog
  - Hyprland focuses the dialog
  - The user focuses the IJ window back (e.g. mouse move or deliberate refocus)
  - IJ will _still pass the events to the dialog (???)_
  - You close the dialog
  - Hyprland will _not_ refocus IJ (it's already focused)
  - IJ refuses to accept input.

**Comment by vaxerski** [comment] 2022-12-15 14:55
reproduced this on sway as well. This is to be reported to IJ devs.

**Comment by pulsar256** [comment] 2022-12-15 16:13
thanks for looking into it. I'll try my luck with Jetbrains then. 

Maybe it is worth mentioning though, that this does not happen when running Gnome/Wayland. Given the number of moving parts (java, awt, swing(?), x11, xwayland and custom ui stuff Jetbrains do) it will be a rather difficult one to pin down.

**Comment by pulsar256** [comment] 2022-12-15 16:16
`follow_mouse = 0` will bring some remedy to the issue i think. This can't be disabled on a root-window level, right?

**Comment by vaxerski** [comment] 2022-12-15 16:49
it's intellij / java's fault.

the problem is that many X11 apps due to the nature of X11 being "let's hack this garbage into the modern day" rely on very wonky sideways behavior of the server, and it's really hard to replicate on wayland.

**Comment by pulsar256** [comment] 2022-12-15 16:50
seems related https://youtrack.jetbrains.com/issue/JBR-1822

**Comment by pulsar256** [comment] 2022-12-15 16:52
Also, this fix breaks other dialogs now. So perhaps reverting it might be the safest bet for the moment. I will dig through the JB thread and check with other compositors and update this thread if i gain any new insights for this particular issue.
