### ISSUE TITLE
regression: Firefox "File Upload" window missplaced

### ISSUE THREAD

**Issue by MightyPlaza** [hyprwm/Hyprland#3150] opened 2023-09-02 21:53 UTC
### Hyprland Version

https://github.com/hyprwm/Hyprland/commit/9dae8ece712ab710a6ff36284b4be408c11526b4

### Bug or Regression?

Regression

### Description

After commit https://github.com/hyprwm/Hyprland/commit/9dae8ece712ab710a6ff36284b4be408c11526b4 Firefox "File Upload" (not gtk portal) window doesn't get centered anymore.
Not sure if Firefox issue or not

### How to reproduce

Upload anything in Firefox (without using gtk portal)
(doesn't seem to work on nested sessions)

**Comment by tchofy** [comment] 2023-09-02 22:46
Huh, I noticed xfce-polkit window was off center, then tested with virt-manager and lutris and their dialogue windows are offcenter as well, but I can't reproduce it with Qt dialogues, even though I don't have any ``center`` rules on them.

**Comment by hekatonkheirex** [comment] 2023-09-02 23:13
Mostly all floating windows are off center now. Happens with version 0.29, but downgrading to 0.28 solves the issue.
Tried with Firefox, Brave and Vivaldi.
https://i.imgur.com/cGG0oJQ.png

**Comment by vaxerski** [comment] 2023-09-03 11:07
fixed in c6c820d16d87c175719569e7ac8c5088ea63f0b2

sing hallelujah

**Closed by vaxerski** 2023-09-03 11:07 UTC
Labels: bug
