### ISSUE TITLE
monitor "highres" can't work after update to v0.29

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#3103] opened 2023-08-29 04:19 UTC
### Hyprland Version

Hyprland, built from branch  at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (). Tag: v0.29.0  flags: (if any) debug

### Bug or Regression?

Bug

### Description

when set monitor config to:
```
monitor=,highres,auto,1
```
it can't enter hyprland

when set monitor config to:
```
monitor=,1920x1080,auto,1
```
it work.

Are there something wrong about "highres"?

### How to reproduce

1.set monitor config to
```
monitor=,highres,auto,1
```

2. reboot your pc

**Comment by moilong** [comment] 2023-08-29 08:33
Thanks for the hint. Im also having the same issue.
`Hyprland, built from branch main at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (props: bump ver to 0.29.0).
Tag: v0.29.0
flags: (if any)`
My config before:
`monitor=,preferred,auto,1`
Needs to be changed as `monitor=,1366x768,auto,1`

**Comment by vaxerski** [comment] 2023-08-29 10:18
can you post a crash report

**Comment by DreamMaoMao** [comment] 2023-08-29 10:45
> can you post a crash report你能发布一份事故报告吗

I haven't seen any crash report under ~ /. hyprland. This problem is more likely a code logic error, rather than a program crash

**Comment by MightyPlaza** [comment] 2023-08-29 10:46
send the tty error or hyprland log then

**Comment by DreamMaoMao** [comment] 2023-08-29 11:01
hyprland log:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12463763/hyprland.log)

**Comment by vaxerski** [comment] 2023-08-29 11:03
everything looks in order, tbh

**Comment by vaxerski** [comment] 2023-08-29 11:10
I'd request a `git bisect` on this as it's a regression, I can't repro this.

**Comment by michal-mnich** [comment] 2023-08-29 23:35
I also have the same problem, my crash log shows:
> [LOG] Set a custom mode 2560x1600@60.000000 (mode not found in monitor modes)
> [LOG] Monitor eDP-1 -> destroyed all render data
The "preferred" refresh rate of my monitor is 120Hz, but this setting previously worked just fine and didn't crash hyprland. The bug was introduced 1-2 days (commits?) before v0.29 I think. As the "highres" setting tends to lower the refresh rate, I guess it has something to do with that.

**Comment by vaxerski** [comment] 2023-08-29 23:43
thats a dupe of #3083 it seems

**Comment by memchr** [comment] 2023-08-31 06:10
> thats a dupe of #3083 it seems

Unlikely, the patch upstream or reverting wlroots/e85c7905 does not affect this behaviour.

**Comment by memchr** [comment] 2023-08-31 06:13
In #3083 Hyprland will abort outright, and this abort is only triggered if you are using a resolution that is not defined by your monitor. But this is not the case here. The event loop is still works normally.
```c
epoll_wait (@epoll_wait:25)
wl_event_loop_dispatch (/usr/src/debug/wayland/wayland-1.22.0/src/event-loop.c:1004)
wl_display_run (/usr/src/debug/wayland/wayland-1.22.0/src/wayland-server.c:1493)
CCompositor::startCompositor() (/home/arthur/src/tmp/hyprland/src/Compositor.cpp:505)
main (/home/arthur/src/tmp/hyprland/src/main.cpp:105)
___lldb_unnamed_symbol3190 (@___lldb_unnamed_symbol3190:29)
__libc_start_main (@__libc_start_main:44)
_start (@_start:15)
```

**Comment by memchr** [comment] 2023-08-31 06:43
This is the summarised behaviour table with different resolution and scaling parameters

| resolution              | scaling | behaviour |
| ----------------------- | -------- | --------- |
| highres                 | 1        | freeze    |
| highres                 | auto     | normal    |
| preferred               | 1        | freeze    |
| preferred               | auto     | normal    |
| defined(e.g. 1920x1080) | 1        | normal    |
| defined(e.g. 1920x1080) | auto     | normal    |

likely related: [#3079](https://github.com/hyprwm/Hyprland/issues/3079)

wlroots first bad commit: [717ded9b](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/717ded9bb0191ea31bf4368be32e7a15fe1b8294) (currently subproject HEAD)

```diff
diff --git a/backend/drm/drm.c b/backend/drm/drm.c
index a012e678..9f9a105b 100644
--- a/backend/drm/drm.c
+++ b/backend/drm/drm.c
@@ -692,11 +692,6 @@ bool drm_connector_commit_state(struct wlr_drm_connector *conn,
 		return false;
 	}
 
-	if ((base->committed & COMMIT_OUTPUT_STATE) == 0) {
-		// This commit doesn't change the KMS state
-		return true;
-	}
-
 	bool ok = false;
 	struct wlr_drm_connector_state pending = {0};
 	drm_connector_state_init(&pending, conn, base);
```

**Comment by vaxerski** [comment] 2023-09-03 10:53
can yall check with 423b129b24a0ff14c5e2898a748b916f892cc0b9

**Closed** 2023-09-03 11:10 UTC
Labels: bug
