### ISSUE TITLE
Groupbar remains visible after switching to a new workspace 

### ISSUE THREAD

**Issue by goggi** [hyprwm/Hyprland#5362] opened 2024-03-31 22:02 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 8cb38d41d203f95ea9c2be79996a5f0deda3eabf  ().
Date: 2024-03-31
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: gza
Release: 6.6.23
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Mar 26 22:22:53 UTC 2024


GPU information: 
2f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240329.d8fe5e6"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Groupbar remains visible after switching to a new workspace 

### How to reproduce

1. Open two windows, 
2. Group them
3. Change workspace  

### Crash reports, logs, images, videos

  
[Kooha-2024-04-01-00-01-42.webm](https://github.com/hyprwm/Hyprland/assets/1946339/b041ff58-6698-4c5b-9eec-ce4edb7ccb6b)

![image](https://github.com/hyprwm/Hyprland/assets/1946339/b860a321-070f-44f5-a4ea-264d87debf98)

  
  
  group {
    col.border_inactive=0xff313244
    groupbar:render_titles = false
    groupbar:font_size = 11
    # groupbar:text_color = 0x000000
    groupbar:height = 1
    col.border_active	=0xffcba6f7 0xfff38ba8 45deg
    groupbar:gradients = false
    groupbar:col.inactive=0xff313244
    groupbar:col.active	=0xffcba6f7 0xfff38ba8 45deg
  }

**Comment by thejch** [comment] 2024-03-31 22:06
yea i can reproduce this. probably related to https://github.com/hyprwm/Hyprland/issues/5361

**Comment by MightyPlaza** [comment] 2024-03-31 22:26
can't repro, but if it's not a regression it's a dupe of https://github.com/hyprwm/Hyprland/issues/3363

**Comment by goggi** [comment] 2024-03-31 22:34
Issue is fixed by https://github.com/hyprwm/Hyprland/pull/5364

**Closed** 2024-04-01 01:58 UTC
Labels: bug
