### ISSUE TITLE
Copy & Paste from Keepass2 not working since Hyprland 0.41.0

### ISSUE THREAD

**Issue by degobbis** [hyprwm/Hyprland#6519] opened 2024-06-15 18:10 UTC
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
$ hyprctl systeminfo -c
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: FRAMEWORK16
Release: 6.9.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:16:55 +0000


GPU information:
c2:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  split-monitor-workspaces by Duckonaut ver 1.1.0

======Config-Start======


Config File: /home/guido/.config/hypr/hyprland.conf: Read Succeeded
#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#
# -----------------------------------------------------
# IMPORTANT: Don't overwrite ML4W configuration.
# Create your own custom configuration variation instead.
# https://gitlab.com/stephan-raabe/dotfiles#hyprland-configuration-variations

# Hyprland Plugins laden
exec-once = hyprpm reload

plugin {
    split-monitor-workspaces {
        count = 10
        keep_focused = 0
        enable_notifications = 0
    }
}

# Jetbrains IDE Fix for rendering
exec-once = wmname LG3D

# -----------------------------------------------------
# Monitor
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/monitor.conf

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/autostart.conf

# -----------------------------------------------------
# Cursor
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/cursor.conf

# -----------------------------------------------------
# Environment
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/environment.conf

# -----------------------------------------------------
# Keyboard
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/keyboard.conf

# -----------------------------------------------------
# Load pywal color file
# -----------------------------------------------------
source = ~/.cache/wal/colors-hyprland.conf

# -----------------------------------------------------
# Load configuration files
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/window.conf
source = ~/dotfiles/hypr/conf/decoration.conf
source = ~/dotfiles/hypr/conf/layout.conf
source = ~/dotfiles/hypr/conf/misc.conf
source = ~/dotfiles/hypr/conf/keybinding.conf
source = ~/dotfiles/hypr/conf/windowrule.conf

# -----------------------------------------------------
# Animation
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/animation.conf

# -----------------------------------------------------
# Custom
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/custom.conf

# -----------------------------------------------------
# ML4W Configuration
# -----------------------------------------------------
source = ~/dotfiles/hypr/conf/ml4w.conf

# -----------------------------------------------------
# Environment for xdg-desktop-portal-hyprland
# -----------------------------------------------------
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = dbus-update-activation-environment --systemd --all
#exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start NetworkManager applet
exec-once = ~/dotfiles/scripts/nm-applet.sh

# Start my apps
exec-once = ~/dotfiles/scripts/guido-autostart.sh


Config File: /home/guido/dotfiles/hypr/conf/monitor.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/monitors/guido.conf

Config File: /home/guido/dotfiles/hypr/conf/monitors/guido.conf: Read Succeeded
# -----------------------------------------------------
# Monitor Setup
# name: "2560x1440"
# -----------------------------------------------------

monitor=eDP-1,2560x1600@165,auto,1
#monitor=DP-9,2560x1440@60,auto-right,1
#monitor=DP-10,2560x1440@60,auto-right,1
monitor=,2560x1440,auto-right,1


Config File: /home/guido/dotfiles/hypr/conf/autostart.conf: Read Succeeded
# -----------------------------------------------------
# Autostart
# -----------------------------------------------------

# Setup XDG for screen sharing
exec-once = ~/dotfiles/hypr/scripts/xdg.sh

# Start Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Dunst Notification Manager
exec-once = dunst

# Load GTK settings
exec-once = ~/dotfiles/hypr/scripts/gtk.sh

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize Wallpaper Engine
exec-once = ~/dotfiles/hypr/scripts/init-wallpaper-engine.sh

# Autostart ML4W App
exec-once = ~/dotfiles/hypr/scripts/ml4w-welcome-autostart.sh

# Start ewww daemon
exec-once = ~/dotfiles/hypr/scripts/eww.sh

# Start autostart cleanup
exec-once = ~/dotfiles/hypr/scripts/cleanup.sh

# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh


Config File: /home/guido/dotfiles/hypr/conf/cursor.conf: Read Succeeded
exec-once = hyprctl setcursor Bibata-Modern-Ice 48


Config File: /home/guido/dotfiles/hypr/conf/environment.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/environments/kvm.conf


Config File: /home/guido/dotfiles/hypr/conf/environments/kvm.conf: Read Succeeded
# -----------------------------------------------------
# Environment Variables
# name: "KVM"
# -----------------------------------------------------

env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Evtl. Auskommentieren. Genauer Prüfen
env = QT_QPA_PLATFORM,wayland

env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1
env = WLR_RENDERER_ALLOW_SOFTWARE, 1
env = WLR_NO_HARDWARE_CURSORS, 1


Config File: /home/guido/dotfiles/hypr/conf/keyboard.conf: Read Succeeded
# -----------------------------------------------------
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = de
    kb_variant = nodeadkeys
    kb_model = pc105
    kb_options = shift:breaks_caps
    numlock_by_default = true
    mouse_refocus = false

    # For United States
    # kb_layout = us
    # kb_variant = intl
    # kb_model = pc105
    # kb_options =

    follow_mouse = 1
    touchpad {
        # for desktop
        # natural_scroll = false

        # for laptop
        natural_scroll = true
        middle_button_emulation = true
        clickfinger_behavior = true
        disable_while_typing = true
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
    workspace_swipe = true
}


Config File: /home/guido/.cache/wal/colors-hyprland.conf: Read Succeeded
$background = rgb(091418)
$foreground = rgb(c6f0f1)
$color0 = rgb(091418)
$color1 = rgb(325A65)
$color2 = rgb(24636E)
$color3 = rgb(466D76)
$color4 = rgb(35817E)
$color5 = rgb(347985)
$color6 = rgb(4CAFB5)
$color7 = rgb(c6f0f1)
$color8 = rgb(8aa8a8)
$color9 = rgb(325A65)
$color10 = rgb(24636E)
$color11 = rgb(466D76)
$color12 = rgb(35817E)
$color13 = rgb(347985)
$color14 = rgb(4CAFB5)
$color15 = rgb(c6f0f1)

Config File: /home/guido/dotfiles/hypr/conf/window.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/windows/border-2-reverse.conf


Config File: /home/guido/dotfiles/hypr/conf/windows/border-2-reverse.conf: Read Succeeded
# -----------------------------------------------------
# General window layout and colors
# name: "Default"
# -----------------------------------------------------

general {
    gaps_in = 10
    gaps_out = 14
    border_size = 2
    col.active_border = rgba(ffffffff)
    col.inactive_border = $color11
    layout = dwindle
}


Config File: /home/guido/dotfiles/hypr/conf/decoration.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/decorations/default.conf

Config File: /home/guido/dotfiles/hypr/conf/decorations/default.conf: Read Succeeded
# -----------------------------------------------------
# General window decoration
# name: "Default"
# -----------------------------------------------------

decoration {
    rounding = 5
    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = on
        ignore_opacity = true
        xray = true
        # blurls = waybar
    }
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    drop_shadow = true
    shadow_range = 30
    shadow_render_power = 3
    col.shadow = 0x66000000
}


Config File: /home/guido/dotfiles/hypr/conf/layout.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/layouts/laptop.conf


Config File: /home/guido/dotfiles/hypr/conf/layouts/laptop.conf: Read Succeeded
# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = true
}

Config File: /home/guido/dotfiles/hypr/conf/misc.conf: Read Succeeded
# -----------------------------------------------------
# Misc settings
# -----------------------------------------------------

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

debug {
    disable_logs = false
}


Config File: /home/guido/dotfiles/hypr/conf/keybinding.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/keybindings/guido.conf


Config File: /home/guido/dotfiles/hypr/conf/keybindings/guido.conf: Read Succeeded
# -----------------------------------------------------
# Key bindings
# name: "Default"
# -----------------------------------------------------

# SUPER KEY
$mainMod = SUPER

# Applications
bind = $mainMod, RETURN, exec, ~/dotfiles/.settings/terminal.sh
bind = $mainMod, W, exec, ~/dotfiles/.settings/browser.sh
bind = $mainMod, V, exec, ~/dotfiles/hypr/scripts/phpstorm.sh
bind = $mainMod, A, exec, brave --app=https://chat.openai.com

# Windows
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, G, exec, geany
bind = $mainMod, E, exec, ~/dotfiles/.settings/filemanager.sh
bind = $mainMod, T, togglefloating
bind = $mainMod SHIFT, T, exec, ~/dotfiles/hypr/scripts/toggleallfloat.sh
bind = $mainMod, J, togglesplit
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod SHIFT, right, resizeactive, 100 0
bind = $mainMod SHIFT, left, resizeactive, -100 0
bind = $mainMod SHIFT, up, resizeactive, 0 -100
bind = $mainMod SHIFT, down, resizeactive, 0 100
#bind = $mainMod, G, togglegroup

# Actions
bind = $mainMod, L, exec, hyprlock
bind = $mainMod ALT, Q, exec, wlogout
bind = $mainMod ALT, R, exec, ~/dotfiles/hypr/scripts/loadconfig.sh
bind = $mainMod SHIFT, A, exec, ~/dotfiles/hypr/scripts/toggle-animations.sh
bind = $mainMod, PRINT, exec, ~/dotfiles/hypr/scripts/screenshot.sh
bind = $mainMod SHIFT, W, exec, ~/dotfiles/hypr/scripts/wallpaper.sh
bind = $mainMod CTRL, W, exec, ~/dotfiles/hypr/scripts/wallpaper.sh select
bind = $mainMod, D, exec, rofi -show drun -replace -i
bind = $mainMod CTRL, H, exec, ~/dotfiles/hypr/scripts/keybindings.sh
bind = $mainMod SHIFT, B, exec, ~/dotfiles/waybar/launch.sh
bind = $mainMod CTRL, B, exec, ~/dotfiles/waybar/toggle.sh
bind = $mainMod CTRL, F, exec, ~/dotfiles/scripts/filemanager.sh
#bind = $mainMod CTRL, C, exec, ~/dotfiles/scripts/cliphist.sh
bind = $mainMod, C, exec, chromium
bind = $mainMod CTRL, C, exec, pkill chromium
bind = $mainMod SHIFT, V, exec, ~/dotfiles/scripts/cliphist.sh
bind = $mainMod CTRL, T, exec, ~/dotfiles/waybar/themeswitcher.sh
bind = $mainMod CTRL, S, exec, ~/dotfiles/apps/ML4W_Dotfiles_Settings-x86_64.AppImage
bind = $mainMod CTRL, P, exec, hyprpicker -a
bind = $mainMod SHIFT, S, exec, ~/dotfiles/hypr/scripts/hyprshade.sh

# Workspaces
bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4
bind = $mainMod, 5, split-workspace, 5
bind = $mainMod, 6, split-workspace, 6
bind = $mainMod, 7, split-workspace, 7
bind = $mainMod, 8, split-workspace, 8
bind = $mainMod, 9, split-workspace, 9
bind = $mainMod, 0, split-workspace, 10
bind = $mainMod SHIFT, 1, split-movetoworkspace, 1
bind = $mainMod SHIFT, 2, split-movetoworkspace, 2
bind = $mainMod SHIFT, 3, split-movetoworkspace, 3
bind = $mainMod SHIFT, 4, split-movetoworkspace, 4
bind = $mainMod SHIFT, 5, split-movetoworkspace, 5
bind = $mainMod SHIFT, 6, split-movetoworkspace, 6
bind = $mainMod SHIFT, 7, split-movetoworkspace, 7
bind = $mainMod SHIFT, 8, split-movetoworkspace, 8
bind = $mainMod SHIFT, 9, split-movetoworkspace, 9
bind = $mainMod SHIFT, 0, split-movetoworkspace, 10
bind = $mainMod, mouse_down, split-workspace, e+1
bind = $mainMod, mouse_up, split-workspace, e-1
#bind = $mainMod CTRL, down, split-workspace, empty
bind = $mainMod CTRL, left, split-changemonitor, prev
bind = $mainMod CTRL, right, split-changemonitor, next

# Fn keys
bind = , XF86MonBrightnessUp, exec, brightnessctl -q s +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl -q s 10%-
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind = , XF86Calculator, exec, qalculate-gtk
bind = , XF86Lock, exec, hyprlock
bind = , XF86Tools, exec, alacritty --class dotfiles-floating -e ~/dotfiles/hypr/settings/settings.sh

# Passthrough SUPER KEY to Virtual Machine
bind = $mainMod, P, submap, passthru
submap = passthru
bind = SUPER, Escape, submap, reset
submap = reset


Config File: /home/guido/dotfiles/hypr/conf/windowrule.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/windowrules/default.conf

Config File: /home/guido/dotfiles/hypr/conf/windowrules/default.conf: Read Succeeded
# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrulev2 = monitor 0,class:^(rambox)$
windowrule = tile,^(Microsoft-edge)$
windowrule = tile,^(Brave-browser)$
windowrule = tile,^(Chromium)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(qalculate-gtk)$


Config File: /home/guido/dotfiles/hypr/conf/animation.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/animations/animations-high.conf


Config File: /home/guido/dotfiles/hypr/conf/animations/animations-high.conf: Read Succeeded
# -----------------------------------------------------
# Animations
# name: "High"
# -----------------------------------------------------
animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}


Config File: /home/guido/dotfiles/hypr/conf/custom.conf: Read Succeeded
# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
env = QT_QPA_PLATFORMTHEME,qt5ct

# Wegen Problemen mit QT/GTK Anwendungen
# verursacht fehler bei nextcloud
#env = QT_QPA_PLATFORM,wayland,xcb
env = QT_QPA_PLATFORM,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11


Config File: /home/guido/dotfiles/hypr/conf/ml4w.conf: Read Succeeded
# -----------------------------------------------------
# ML4W configurations
# -----------------------------------------------------

windowrulev2 = float,class:(.*chat.openai.com.*)
windowrulev2 = size 500 50%,class:(.*chat.openai.com.*)
windowrulev2 = move 20 70,class:(.*chat.openai.com.*)

windowrulev2 = float,class:(com.ml4w.welcome)
windowrulev2 = size 700 600,class:(com.ml4w.welcome)
windowrulev2 = center,class:(com.ml4w.welcome)

windowrulev2 = float,class:(ml4w-welcome.py)
windowrulev2 = size 400 500,class:(ml4w-welcome.py)
windowrulev2 = center,class:(ml4w-welcome.py)

windowrulev2 = float,class:(com.ml4w.dotfilessettings)
windowrulev2 = size 700 600,class:(com.ml4w.dotfilessettings)
windowrulev2 = move 10% 20%,class:(com.ml4w.dotfilessettings)

windowrulev2 = float,class:(ml4w-dotfiles-settings.py)
windowrulev2 = size 400 500,class:(ml4w-dotfiles-settings.py)
windowrulev2 = move 10% 20%,class:(ml4w-dotfiles-settings.py)

windowrulev2 = float,class:(com.ml4w.hyprland.settings)
windowrulev2 = size 700 600,class:(com.ml4w.hyprland.settings)
windowrulev2 = center,class:(com.ml4w.hyprland.settings)

windowrulev2 = float,class:(ml4w-hyprland-settings.py)
windowrulev2 = size 700 600,class:(ml4w-hyprland-settings.py)
windowrulev2 = center,class:(ml4w-hyprland-settings.py)

windowrulev2 = float,class:(dotfiles-floating)
windowrulev2 = size 1000 800,class:(dotfiles-floating)
windowrulev2 = center,class:(dotfiles-floating)

env = APPIMAGELAUNCHER_DISABLE,1
env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland


======Config-End========
```

</details>

### Description

With version 0.40.0 all works fine, after the update to version 0.41.[0|1] the copy & paste from KeePass2 is not more possible.

### How to reproduce

To reproduce the issue, KeePass2 is needed.
1. Open KeePass2 and select the credentials You will copy something
2. Click on the button to "copy password" or "copy username" and switch to a browser or text editor and try to paste.

**Comment by vaxerski** [comment] 2024-06-15 19:49
surely does on my end... though idk what "keepass 2" is? I am just using keepass
![image](https://github.com/hyprwm/Hyprland/assets/43317083/49f6096a-7836-4eb6-8c6b-31e5933072a9)

**Comment by MightyPlaza** [comment] 2024-06-15 19:51
likely running in xwayland from missing env vars

**Comment by degobbis** [comment] 2024-06-15 19:53
@vaxerski is this
![grafik](https://github.com/hyprwm/Hyprland/assets/10517822/351419fb-cf63-42b9-acc0-4e4561fa4e9c)

**Comment by vaxerski** [comment] 2024-06-15 19:53
is it running in xwayland?

**Comment by degobbis** [comment] 2024-06-15 19:55
How do I find out?

**Comment by vaxerski** [comment] 2024-06-15 20:04
hyprctl clients will tell you

**Comment by degobbis** [comment] 2024-06-15 20:07
Thx, yes is using xwayland
```sh
Window 56d80d70e970 -> mykeepassdb.kdbx - KeePass:
	mapped: 1
	hidden: 0
	at: 3852,67
	size: 1252,1357
	workspace: 11 (11)
	floating: 0
	monitor: 1
	class: KeePass2
	title: mykeepassdb.kdbx - KeePass
	initialClass: KeePass2
	initialTitle: mykeepassdb.kdbx - KeePass
	pid: 97784
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 1
```

**Comment by vaxerski** [comment] 2024-06-15 20:08
dupe of #6247 then

**Closed by vaxerski** 2024-06-15 20:08 UTC
Labels: bug

**Comment by degobbis** [comment] 2024-06-15 20:30
THX to bring my attention to #6247, it seems to be the same problem.
It's been 3 days since the last comment, is a fix planned?

**Comment by vaxerski** [comment] 2024-06-15 20:31
god knows, maybe. I hate X code.

**Comment by MightyPlaza** [comment] 2024-06-15 20:35
> THX to bring my attention to #6247, it seems to be the same problem. It's been 3 days since the last comment, is a fix planned?

`env=QT_QPA_PLATFORM,wayland;xcb` try using this env var, maybe it makes it run under wayland

**Comment by degobbis** [comment] 2024-06-15 21:15
> >  `env=QT_QPA_PLATFORM,wayland;xcb` try using this env var, maybe it makes it run under wayland

Tested, but not solving my problem.
THX
