### ISSUE TITLE
Hyprland is unsable in wayvnc if the physical host doesn't have a connected mouse

### ISSUE THREAD

**Issue by s-daveb** [hyprwm/Hyprland#1497] opened 2023-02-05 18:43 UTC
Hello all, this is something that surprised me this morning, but I think I figured out what was going on.

I tried to connect to my gaming PC running Hyprland over VNC, and for some unknown reason, I was unable to produce any mouse input no matter what device I used for the VNC connection.

I spent some time troubleshooting and it looks like Hyprland disables all mouse functionality if there is no physical mouse connection.  

While this seems okay for those who use a wired mouse, for those who use bluetooth adapters to navigate desktop UIs, this will render the computer unusable over remote connections if the wireless mouse goes to sleep.

Steps to reproduce:
1. Start Hyprland
2. Launch wayvnc
3. Disconnect your wired or wireless mouse from your host.
4. From your phone or another host, connect to your computer via VNC.
5. You should be able to launch applications with your keyboard input, but good luck using an X11 application 😅

**Comment by root2185** [comment] 2023-02-06 15:54
`hyprland-bin-0.20.1beta-1` from the AUR on a tablet.
The touchscreen moves the pointer a little, while on wayland it shouldn't right?

If I don't have a mouse connected I cannot click with the touchscreen.

**Comment by romanstingler** [comment] 2024-03-09 21:48
@s-daveb can you try that again with the latest version of hyprland, there have been a lot of input updates

**Comment by fooryo** [comment] 2024-04-08 17:51
@romanstingler said:
> @s-daveb can you try that again with the latest version of hyprland, there have been a lot of input updates

As I mentioned in #5482 (closed considered as dupe of this one, sorry for that):

 no, it seems that it does not work

**Comment by lukeomatik** [comment] 2024-04-12 07:55
@s-daveb , @fooryo , start your wayvnc server using `-r` option (`--render-cursor`)

**Comment by lukeomatik** [comment] 2024-04-12 20:16
turns out it was only working because I had sunshine enabled on the host and it attach a fake mouse in the session

**Comment by izmyname** [comment] 2024-10-13 07:45
Still a thing?

**Comment by lukeomatik** [comment] 2024-10-13 09:12
@izmyname not for me, anymore, actually. but I dont know why and I didnt try on a clean setup so give it a try and report us!

**Comment by izmyname** [comment] 2024-10-13 09:25
> @izmyname not for me, anymore, actually. but I dont know why and I didnt try on a clean setup so give it a try and report us!

Nah, I'm just tagging old issues for the sake of cleaning up the bug tracker.

Anyway, it's good to hear the stuff works for you. Now, waiting for the op to report or Vaxry to close this.

**Closed** 2024-10-13 20:28 UTC
Labels: bug

**Comment by Yarn** [comment] 2024-10-18 15:57
for future reference this was probably fixed by https://github.com/hyprwm/Hyprland/pull/6366
