### ISSUE TITLE
apple: explicit_sync enabled, breaks every gpu accelerated applications using vulkan

### ISSUE THREAD

**Issue by nerdyinu** [hyprwm/Hyprland#8803] opened 2024-12-22 03:05 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: inu-macbookpro
Release: 6.12.1-404.asahi.fc40.aarch64+16k
Version: #1 SMP PREEMPT_DYNAMIC Mon Dec  2 23:04:11 UTC 2024


GPU information:
apple,agx-t6020

os-release: NAME="Fedora Linux Asahi Remix"
VERSION="40 (KDE Plasma)"
ID=fedora-asahi-remix
ID_LIKE=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux Asahi Remix 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora-asahi-remix:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedora-asahi-remix.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://discussion.fedoraproject.org/c/neighbors/asahi/asahi-help/94"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:
        unknown: not runtime
```

</details>

### Description

setting the config to use explicit_sync=2 breaks every app that uses vulkan gpu acceleration.
zed, wezterm , etc

### How to reproduce

set explicit_sync=2
use webgpu as frontend in wezterm at set to use gpu with vulkan driver
or launch zed
they crash
setting explicit_sync=0 solves it.

### Crash reports, logs, images, videos

here is wezterm crash log
```
➜  wezterm                                                                                              [11:52:24]
wp_linux_drm_syncobj_timeline_v1#57: error 1: Timeline failed importing
11:52:28.178  ERROR  wgpu_hal::vulkan::adapter > get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR
11:52:28.178  ERROR  wgpu_hal::vulkan::adapter > get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR
11:52:28.179  ERROR  env_bootstrap             > panic at /builddir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: __libc_start_call_main
  27: __libc_start_main@@GLIBC_2.34
  28: <unknown>

thread 'main' panicked at /builddir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18:
Error in Surface::configure: Validation Error

Caused by:
  Requested format Bgra8UnormSrgb is not in list of supported formats: []

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
panicked at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/thread/local.rs:260:26:

thread panicked while processing panic. aborting.
Error: nu::shell::core_dumped

  × External command core dumped
   ╭─[entry #1:1:1]
 1 │ wezterm
   · ───┬───
   ·    ╰── core dumped with SIGABRT (6)
   ╰────

```

**Comment by vaxerski** [comment] 2024-12-22 12:53
you are using apple for a gpu driver, which is notoriously... not perfect.

I'd blame it on some funky stuff happening there, as nvidia intel and amd work.

**Comment by vaxerski** [comment] 2024-12-22 14:55
I think this is a dupe of #8158

**Closed by vaxerski** 2024-12-22 14:55 UTC
Labels: bug
