### ISSUE TITLE
Hyprland crashes after run fcitx5

### ISSUE THREAD

**Issue by ZreXoc** [hyprwm/Hyprland#4503] opened 2024-01-22 13:11 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
% hyprctl version
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes in a few seconds after running `fcitx5` in terminal.

OS: ArchLinux

### How to reproduce

1. install following packages with pacman:
```
fcitx5 5.1.7-2
fcitx5-chinese-addons 5.1.3-1
fcitx5-configtool 5.1.3-1
fcitx5-gtk 5.1.1-1
fcitx5-material-color 0.2.1-1
fcitx5-pinyin-moegirl 20231114-1
fcitx5-pinyin-zhwiki 1:0.2.4.20231205-1
fcitx5-qt 5.1.4-3
```
2. then run `fcitx5`

### Crash reports, logs, images, videos

`~/.config/fcitx5/crash.log` not found.

Crash reports:
```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Well this is awkward.

Hyprland received signal 11 (Segmentation fault)

Version: 03ebbe18ed8517ee22591eac82cd54322f42cb7d
Tag: v0.34.0

System info:
	System name: Linux
	Node name: xichensarch
	Release: 6.7.0-arch3-1
	Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28e0] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x5e441f405412]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x5c5) [0x5e441f3d28a5]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x4c) [0x5e441f34c5ec]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x716c0fd6f710]
		??
		??:0
	#4 | /usr/lib/libwayland-server.so.0(wl_resource_post_event+0xd0) [0x716c10662dd0]
		??
		??:0
	#5 | /usr/lib/libwlroots.so.13032(wlr_text_input_v3_send_leave+0x2c) [0x716c10735fbc]
		??
		??:0
	#6 | Hyprland(_ZN17CInputMethodRelay15onKeyboardFocusEP11wlr_surface+0x1a8) [0x5e441f459c68]
		??
		??:0
	#7 | Hyprland(+0x1bce01) [0x5e441f459e01]
		??
		??:0
	#8 | Hyprland(_ZN18CHookSystemManager4emitEPKSt6vectorI14SCallbackFNPtrSaIS1_EER13SCallbackInfoSt3any+0x323) [0x5e441f42ab73]
		??
		??:0
	#9 | Hyprland(_ZN11CCompositor12focusSurfaceEP11wlr_surfaceP7CWindow+0x178) [0x5e441f357cd8]
		??
		??:0
	#10 | Hyprland(_ZN11CCompositor11focusWindowEP7CWindowP11wlr_surface+0x388) [0x5e441f34f5d8]
		??
		??:0
	#11 | Hyprland(_ZN13CInputManager16mouseMoveUnifiedEjb+0x1064) [0x5e441f447234]
		??
		??:0
	#12 | Hyprland(_ZN13CInputManager12onMouseMovedEP24wlr_pointer_motion_event+0x139) [0x5e441f447d79]
		??
		??:0
	#13 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x716c1066201e]
		??
		??:0
	#14 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x716c1066201e]
		??
		??:0
	#15 | /usr/lib/libwlroots.so.13032(+0x50078) [0x716c106fb078]
		??
		??:0
	#16 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x716c10663ae2]
		??
		??:0
	#17 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x716c106642d7]
		??
		??:0
	#18 | Hyprland(_ZN11CCompositor15startCompositorEv+0xc65) [0x5e441f34def5]
		??
		??:0
	#19 | Hyprland(main+0x727) [0x5e441f3341f7]
		??
		??:0
	#20 | /usr/lib/libc.so.6(+0x27cd0) [0x716c0fd58cd0]
		??
		??:0
	#21 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x716c0fd58d8a]
		??
		??:0
	#22 | Hyprland(_start+0x25) [0x5e441f349815]
		??
		??:0


Log tail:
-> 5e4420226bd0 (owner: CWLSurface)
[LOG] CWLSurface 5e4420226bb8 called init()
[LOG] Activate request for surface at 5e4421989410
[LOG] Callback 5e4420226bf8 -> 5e4420226bf0, CWLSurface removed.
[LOG] CWLSurface 5e4420226bb8 called destroy()
[LOG] Activate request for surface at 5e4421989410
[LOG] Activate request for surface at 5e4421989410
[LOG] Searching for matching rules for kitty (title: fcitx5)
[LOG] Window rule nomaximizerequest ->  class:.* matched [Window 5e442198a150: title: "fcitx5"]
[LOG] Window 5e442198a150 set title to fcitx5
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5e4421a778c0: 5e44219e0360 -> 5e4421a78010 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a778c0: 5e44219e0370 -> 5e4421a78078 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a778c0: 5e44219e02e0 -> 5e4421a779f8 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a778c0: 5e44219e0410 -> 5e4421a77fa8 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a778c0: 5e44219e02f0 -> 5e4421a77e08 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5e4421a78e60: 5e4421a0cc20 -> 5e4421a795b0 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a78e60: 5e4421a0cc30 -> 5e4421a79618 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a78e60: 5e4421a0cba0 -> 5e4421a78f98 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a78e60: 5e4421a0ccd0 -> 5e4421a79548 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a78e60: 5e4421a0cbb0 -> 5e4421a793a8 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5e4421a7a400: 5e4421a0cf10 -> 5e4421a7ab50 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a7a400: 5e4421a0cf20 -> 5e4421a7abb8 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a7a400: 5e4421a0ce90 -> 5e4421a7a538 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a7a400: 5e4421a0cfc0 -> 5e4421a7aae8 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a7a400: 5e4421a0cea0 -> 5e4421a7a948 (owner: XWayland Window)
[LOG] Registered signal for owner 5e4421a06a70: 5e4421a5f888 -> 5e4421a06a78 (owner: Keyboard)
[LOG] Registered signal for owner 5e4421a06a70: 5e4421a5f878 -> 5e4421a06ae0 (owner: Keyboard)
[LOG] Registered signal for owner 5e4421a06a70: 5e4421a5f758 -> 5e4421a06bb0 (owner: Keyboard)
[LOG] Registered signal for owner 5e4421a06a70: 5e4421a5f898 -> 5e4421a06b48 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "wlr_virtual_keyboard_v1", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "wlr_virtual_keyboard_v1"
[LOG] New virtual keyboard created, pointers Hypr: 5e4421a06a70 and WLR: 5e4421a5f740
[LOG] New IME added!
[LOG] Registered signal for owner 5e44202268f0: 5e4421a962d0 -> 5e4420226998 (owner: IMERelay)
[LOG] Registered signal for owner 5e44202268f0: 5e4421a96300 -> 5e4420226a00 (owner: IMERelay)
[LOG] Registered signal for owner 5e44202268f0: 5e4421a962f0 -> 5e4420226a68 (owner: IMERelay)
[LOG] Registered signal for owner 5e44202268f0: 5e4421a962e0 -> 5e4420226ad0 (owner: IMERelay)
[LOG] FractionalScaleManager bound successfully!
[LOG] Registered signal for owner 5e4420226bb8: 5e44219892e0 -> 5e4420226bd0 (owner: CWLSurface)
[LOG] CWLSurface 5e4420226bb8 called init()
[LOG] Callback 5e4420226bf8 -> 5e4420226bf0, CWLSurface removed.
[LOG] CWLSurface 5e4420226bb8 called destroy()
[LOG] Registered signal for owner 5e4420226bb8: 5e44219892e0 -> 5e4420226bd0 (owner: CWLSurface)
[LOG] CWLSurface 5e4420226bb8 called init()
[LOG] Searching for matching rules for kitty (title: fcitx5)
[LOG] Window rule nomaximizerequest ->  class:.* matched [Window 5e442198a150: title: "fcitx5"]
[LOG] Set keyboard focus to surface 5e44219cb2a0, with [Window 5e44219d4bf0: title: "Fcitx5 - ArchWiki --- Fcitx5 - ArchWiki — Mozilla Firefox"]
```

**Comment by vaxerski** [comment] 2024-01-22 13:16
dupe of #2146

start fcitx5 in an exec-once instead of a terminal for a temporary fix until this crash is fixed.

**Closed by vaxerski** 2024-01-22 13:16 UTC
Labels: bug
