### ISSUE TITLE
disable_splash_rendering not working

### ISSUE THREAD

**Issue by tombryden** [hyprwm/Hyprland#4340] opened 2024-01-03 17:35 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Tue Jan 2 21:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.6.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000


GPU information:
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev ca) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

`disable_splash_rendering = true` does not work

### How to reproduce

Set `disable_splash_rendering = true` in misc, observe splash remaining visible.

### Crash reports, logs, images, videos
![image](https://github.com/hyprwm/Hyprland/assets/31113935/fe7c5815-18b2-4f17-a91a-d3432fbf5d33)

**Comment by fufexan** [comment] 2024-01-03 17:38
Duplicate of https://github.com/hyprwm/Hyprland/issues/4338.

**Closed by fufexan** 2024-01-03 17:38 UTC
Labels: bug
