### ISSUE TITLE
Floating windows in normal workspaces rendered on top of window in special workspace

### ISSUE THREAD

**Issue by jacekpoz** [hyprwm/Hyprland#3936] opened 2023-11-24 20:16 UTC
### Hyprland Version

Hyprland, built from branch  at commit e40e486f61f2643578b9977b86f408799dbc75fd  (). Tag:   flags: (if any) debug

### Bug or Regression?

Bug

### Description

title + gets temporarily hidden behind tiled windows upon switching workspaces

### How to reproduce

make a keybind that toggles some special workspace, put a window in that

then open one tiled window each in 2 separate workspaces, in one of them open a floating window or a few, press the keybind that toggles the special workspace to turn it on

switch between the 2 workspaces mentioned above and the thing in the description will happen

unfortunately can't record because of the portal having a skill issue and obs crashing

**Comment by jacekpoz** [comment] 2023-11-24 20:57
just checked, no changes on latest commit (d79cf0afe26fd6503a47c17a524d45742bf2461a)

**Comment by thejch** [comment] 2023-11-24 20:58
I think this is being worked on in https://github.com/hyprwm/Hyprland/pull/3928

**Comment by vaxerski** [comment] 2023-11-24 21:01
dupe of one of the mentioned in #3928

**Comment by jacekpoz** [comment] 2023-11-24 21:02
sorry

**Closed by vaxerski** 2023-11-24 21:01 UTC
Labels: bug

**Comment by jacekpoz** [comment] 2023-11-24 22:00
yeah that PR fixed it, thanks
