### ISSUE TITLE
Inability to navigate in Steam menu

### ISSUE THREAD

**Issue by TAforever** [hyprwm/Hyprland#4027] opened 2023-12-02 18:07 UTC
### Hyprland Version

0.32.3

### Bug or Regression?

Bug

### Description

When I click on menu items in steam, drop-down menus appear that cannot be captured with the mouse cursor focus.

### How to reproduce

https://github.com/hyprwm/Hyprland/assets/52626363/babed0f6-2726-4644-854e-17a1f74c0123

**Comment by TZProgrammer** [comment] 2023-12-03 05:37
Could this be related to #4029? The flickering/darkening issues there happen when the mouse hovers/moves on top of the menu items.

**Comment by TAforever** [comment] 2023-12-03 09:50
@vaxerski  Is this a duplicate of https://github.com/hyprwm/Hyprland/issues/2661 should I close this issue?

**Comment by vaxerski** [comment] 2023-12-03 12:57
it is a dupe of #2661

FYI if you click on the button at the veeeery bottom of it, you will be able to hover on the menu.

**Closed by vaxerski** 2023-12-03 12:57 UTC
Labels: bug
