### ISSUE TITLE
Warframe launcher window is drawn yet it doesn't receive any input

### ISSUE THREAD

**Issue by tpkee** [hyprwm/Hyprland#433] opened 2022-07-26 11:10 UTC
The warframe launcher window is drawn yet it doesn't receive any input. For example: if there is Firefox under the floating launcher window, the input is registered by Firefox but not the launcher.

Not sure it's the compositor, but last month it worked correctly and even trying a clean install I've got the same error (and didn't find anyone else reporting it either)

**Comment by vaxerski** [comment] 2022-07-26 11:12
any other app that experiences the same behavior? Not keen on installing a 20GB bad game just to test.

**Comment by tpkee** [comment] 2022-07-26 11:22
Not that I've noticed. Dragon Age Origins (Steam) works fine, idem Fallout New Vegas. Age of Mythology has an ictus whenever I start it but I doubt it's related. 
Another thing is that when I move warframe window to another workspace / display, it freezes the whole pc

**Comment by vaxerski** [comment] 2022-07-26 12:32
`git bisect` then and provide the faulty commit

**Comment by tpkee** [comment] 2022-07-26 13:29
`f9985a36b345acf3fd4f6a1ad8170a475658fb60dirty`

**Comment by vaxerski** [comment] 2022-07-26 13:35
do a bisect mAN https://www.google.com/search?q=how+to+git+bisect

**Comment by tpkee** [comment] 2022-07-26 15:20
I'm using the aur release tho, how do i do that? 
Anyway I tested on Awesome and it works as expected

**Comment by vaxerski** [comment] 2022-07-26 15:25
compile manually.

> Anyway I tested on Awesome and it works as expected

thats literally xorg not even wayland

**Comment by GloriousWizard** [comment] 2022-08-09 21:42
faulty commit: 75a580fedab7f12934d6c2885b48efb3fb00f3f1. You don't need to install the entire game, only the launcher since that's where the problem is

**Comment by vaxerski** [comment] 2022-08-10 10:50
in that case this should fix it 7e8666754f70109dcccb5e3eea389900d446767a

**Comment by tpkee** [comment] 2022-08-13 17:09
Doesn't work for me tbh

**Comment by vaxerski** [comment] 2022-08-13 17:18
do you confirm the faulty commit tho?

**Comment by tpkee** [comment] 2022-08-18 17:04
I'm not really sure as I couldn't it to work, but Mass Effect Legendary Edition has the same problem too

**Comment by vaxerski** [comment] 2022-08-18 17:05
can you show the output of `hyprctl clients` with the launcher open?

**Comment by tpkee** [comment] 2022-08-18 17:08
```
Window 90b26e10 -> Steam:
	at: 18,68
	size: 1252,1354
	workspace: 1 ()
	floating: 0
	monitor: 0
	class: Steam
	title: Steam
	pid: 42761

Window 90b4d340 -> hyprctl clients:
	at: 1290,68
	size: 1252,1354
	workspace: 1 ()
	floating: 0
	monitor: 0
	class: kitty
	title: hyprctl clients
	pid: 43259

Window 90c3af30 -> Wine System Tray:
	at: 3757,697
	size: 166,45
	workspace: 2 ()
	floating: 1
	monitor: 1
	class: steam_app_1328670
	title: Wine System Tray
	pid: 44493

Window 90c96e50 -> Origin:
	at: 956,457
	size: 140,100
	workspace: 1 ()
	floating: 1
	monitor: 1
	class: steam_app_1182480
	title: Origin
	pid: 44606

Window 90c9e290 -> Origin:
	at: 956,457
	size: 181,86
	workspace: 1 ()
	floating: 1
	monitor: 1
	class: steam_app_1182480
	title: Origin
	pid: 44606

Window 90ca0e20 -> Origin:
	at: 956,457
	size: 152,51
	workspace: 1 ()
	floating: 1
	monitor: 1
	class: steam_app_1182480
	title: Origin
	pid: 44606

Window 90c9b9f0 -> Origin:
	at: 956,457
	size: 112,58
	workspace: 1 ()
	floating: 1
	monitor: 1
	class: steam_app_1182480
	title: Origin
	pid: 44606

Window 90ca3580 -> Origin:
	at: 956,457
	size: 112,59
	workspace: 1 ()
	floating: 1
	monitor: 1
	class: steam_app_1182480
	title: Origin
	pid: 44606

Window 90b0d0d0 -> Warframe launcher window is drawn yet it doesn't receive any input · Issue #433 · hyprwm/Hyprland — Mozilla Firefox:
	at: 2578,68
	size: 2524,1354
	workspace: 2 ()
	floating: 0
	monitor: 1
	class: firefox
	title: Warframe launcher window is drawn yet it doesn't receive any input · Issue #433 · hyprwm/Hyprland — Mozilla Firefox
	pid: 42164

Window 90cac350 -> Origin:
	at: 1057,397
	size: 237,389
	workspace: 1 ()
	floating: 1
	monitor: 0
	class: steam_app_1182480
	title: Origin
	pid: 44606

Window 90ce6920 -> Mass Effect Launcher:
	at: -735,314
	size: 1920,1080
	workspace: 1 ()
	floating: 1
	monitor: 0
	class: steam_app_1328670
	title: Mass Effect Launcher
	pid: 45078
```

Sure

**Comment by vaxerski** [comment] 2022-08-18 17:10
Is Mass Effect wine/proton? in that case, can you launch it in a Wine Virtual Desktop?

`WINEPREFIX=/path/to/the/pfx winecfg`

Graphics tab -> emulate a virtual desktop

**Comment by tpkee** [comment] 2022-08-18 17:15
Yup, it works like that (Warframe)

**Comment by vaxerski** [comment] 2022-08-18 17:16
I suspect then that it was on a second monitor. Unfortunately, for some reason, wine XWayland games sometimes receive no mouse input when not on the leftmost monitor. Closing then

**Closed by vaxerski** 2022-08-18 17:16 UTC
Labels: bug

**Comment by tpkee** [comment] 2022-08-18 17:51
> I suspect then that it was on a second monitor. Unfortunately, for some reason, wine XWayland games sometimes receive no mouse input when not on the leftmost monitor. Closing then

While the fix works, though, it doesn't depend on XWayland since I tried both games in Sway with the desktop emulation disabled and they work correctly

**Comment by vaxerski** [comment] 2022-08-18 17:52
meh. Virtual desktop usually fixes most wine issues that are either hl or xw

**Comment by tpkee** [comment] 2022-08-18 20:08
That prevents the use of frequencies higher than 60hz though, doesn't it?

**Comment by vaxerski** [comment] 2022-08-18 20:10
what?

**Comment by tpkee** [comment] 2022-08-18 20:11
if I have a >60hz monitor doesn't the virtual desktop still runs at 60hz?

**Comment by vaxerski** [comment] 2022-08-18 20:11
why would it?

**Comment by vaxerski** [comment] 2022-08-18 20:12
and if it does, use `gamescope`, it's like a better wine virtual desktop.

**Comment by vaxerski** [comment] 2022-08-27 11:03
can you please check with 5d63152219514ecbe861cb70e9359adc0c5b2878 if adding a window rule for the launcher called `forceinput` won't fix this?
