### ISSUE TITLE
Windows spawn somewhere in the corner

### ISSUE THREAD

**Issue by DADA30000** [hyprwm/Hyprland#6154] opened 2024-05-19 16:16 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit f8857e6072bd85b95393499688872aaf7f088b5b  ().
Date: 2024-05-18
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.9.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:18:09 UTC 2024


GPU information: 
	Flags: bus master, VGA palette snoop, 66MHz, medium devsel, latency 64, NUMA node 0, IOMMU group 11
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117 [GeForce GTX 1650] [10de:1f82] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240517.4a6b83b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hyprexpo by Vaxry ver 1.0

```

</details>

### Bug or Regression?

Bug

### Description

https://github.com/hyprwm/Hyprland/assets/73874445/eda0c1b4-1b97-451d-b9da-d6bf8ba0b465

### How to reproduce

Use latest hyprland from git

**Comment by The-Briel-Deal** [comment] 2024-05-19 21:37
Please attach config. Cannot repro.

**Comment by DADA30000** [comment] 2024-05-20 08:31
[hyprland.conf.zip](https://github.com/hyprwm/Hyprland/files/15374722/hyprland.conf.zip)

**Comment by The-Briel-Deal** [comment] 2024-05-20 08:40
Can you also give steps to reproduce this issue? And can you explain what the issue is? It looks like the auth pop up is popping up in the top right. Is that the the problem?

**Comment by DADA30000** [comment] 2024-05-20 09:37
And steps to reproduce
1. Install hyprland using flake on NixOS
2. Open floating window

**Comment by Agent00Ming** [comment] 2024-05-20 09:44
> And steps to reproduce
> 
>     1. Install hyprland using flake on NixOS
> 
>     2. Open floating window

same energy as "install linux, why no work" :rofl:



I suspect it's [this](https://github.com/hyprwm/Hyprland/pull/5999#issuecomment-2111175246)

**Comment by Plyply99** [comment] 2024-05-20 13:49
https://github.com/hyprwm/Hyprland/assets/103620143/33feeb64-ce07-4465-9316-685a6a12f83d

**Comment by The-Briel-Deal** [comment] 2024-05-21 11:42
> Video_2024-05-20_09-44-40.mp4

This doesn't look like no config lol. Can you post the config. I am trying this right now and I am not getting this issue. I'll try it with OP's config a later today and update this.

**Comment by Plyply99** [comment] 2024-05-21 11:53
[hyprland.zip](https://github.com/hyprwm/Hyprland/files/15389434/hyprland.zip)

Here you are friend.

**Comment by random2907** [comment] 2024-05-22 11:16
it also happen when using  windowrulev2  size.

**Comment by Plyply99** [comment] 2024-05-24 06:10
I wonder if this could be because of a mesa bug as mentioned here:

https://github.com/russelltg/wl-screenrec/issues/47

And here:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/10658

**Comment by SnipeXandrej** [comment] 2024-05-24 11:32
nevermind, doesn't happen anymore in a normal non-nested session (although it did some days ago, weird...)

but the windows spawning in the top-left or bottom-right corners still happens

**Comment by reidlabwastaken** [comment] 2024-05-24 14:14
it seems the center window rule still works, heres a video showing a popup w/ the center window rule and without

Center:
https://github.com/hyprwm/Hyprland/assets/45904911/6dcd68a5-54fb-4233-a7a2-97fad56e9bd4
Without center:
https://github.com/hyprwm/Hyprland/assets/45904911/0a7ba551-eb65-474b-bf2e-c0e6f812b86e

`hyprctl systeminfo` (this issue also happened on my nvidia machine fyi)
```
Hyprland, built from branch  at commit 7ad9116de8d0b7dac27eaf080bd92998a8fb40e5  ().
Date: 2024-05-22
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: goopnet-interface
Release: 6.9.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Plus Graphics G4 (Ice Lake) [8086:8a5c] (rev 07) (prog-if 00 [VGA controller])
74:00.1 Non-VGA unclassified device [0000]: Apple Inc. T2 Bridge Controller [106b:1801] (rev 01)
74:00.2 Non-VGA unclassified device [0000]: Apple Inc. T2 Secure Enclave Processor [106b:1802] (rev 01)


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240521.5710852"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

**Comment by reidlabwastaken** [comment] 2024-05-24 14:22
> The mesa bug I posted affects AMD. Looks like you're on Intel?
yeah, iris plus g4 (integrated graphics for the i3-1000ng4)
i do not have any AMD gpus on this system

**Comment by shvedes** [comment] 2024-05-26 16:16
Same issue after switching to git version (Because the waybar module idle_inhibitor did not work). Seems like it happens only with gnome-polkit window in my case. For example, in the video I opened the zenity window, which appeared in the center as needed. Also, the telegram context menu slides to the center (or above) of the screen when it was invoked at the bottom of the screen (in which case it is expected to be drawn just above the selected message, but not in another part of the screen). I admit that this may be a telegram problem


https://github.com/hyprwm/Hyprland/assets/84767665/4e1b92db-fad1-49d0-8c4e-3364a504b06c

**Comment by lionur** [comment] 2024-05-26 21:51
I noticed that this behavior happened after this commit 4cdddcfe466cb21db81af0ac39e51cc15f574da9, so it was the last good commit
It happened somewhere here: 121d3a72137d4780602cf245704615f63357ea22, 0cfdde3d1acbfbf698af17f6986fbc4d644214da, fc72df8e58bc127442a245f2f29a3246acf77cce
And on this commit 7eeee2c94e882a5df1914234df0571b221f9aa35 windows were not spawning in the center anymore
Maybe this helps

**Comment by MightyPlaza** [comment] 2024-06-02 20:34
they always seem to spawn at X = width / 2 and Y = height / 2, so there is likely a typo somewhere.

**Comment by MightyPlaza** [comment] 2024-06-02 20:45
close
they now spawn at the `center + window_size / 2` instead of `center - window_size / 2`

**Comment by MightyPlaza** [comment] 2024-06-02 20:48
```diff
diff --git a/src/layout/IHyprLayout.cpp b/src/layout/IHyprLayout.cpp
index 108f9039..123f27ac 100644
--- a/src/layout/IHyprLayout.cpp
+++ b/src/layout/IHyprLayout.cpp
@@ -147,7 +147,7 @@ void IHyprLayout::onWindowCreatedFloating(PHLWINDOW pWindow) {
                 pWindow->m_vRealPosition = pWindow->m_pXDGSurface->toplevel->parent->window->m_vRealPosition.goal() +
                     pWindow->m_pXDGSurface->toplevel->parent->window->m_vRealSize.goal() / 2.F - desiredGeometry.size() / 2.F;
             else
-                pWindow->m_vRealPosition = PMONITOR->vecPosition + desiredGeometry.size() / 2.F;
+                pWindow->m_vRealPosition = PMONITOR->vecPosition + PMONITOR->vecSize / 2.F - desiredGeometry.size() / 2.F;
         } else {
             // if it is, we respect where it wants to put itself, but apply monitor offset if outside
             // most of these are popups
```
fixes it

**Comment by vaxerski** [comment] 2024-06-02 21:04
isnt that what I've done? maybe its too late and I am idiot

**Comment by vaxerski** [comment] 2024-06-02 21:13
is this fixed now then?

**Comment by Agent00Ming** [comment] 2024-06-02 21:58
you might have dropped two commits during force push but that did fix this issue :P
6868a39f1145dcb11c1d721e765077f21128e80c and 1cc35cfd817ed5dc87cb3e50e2bd46b87cf17c33

**Comment by vaxerski** [comment] 2024-06-03 14:01
sometimes I feel like I should revoke the perms to force push to main from myself, muscle memory sometimes does -f...

**Comment by vaxerski** [comment] 2024-06-03 16:46
done, enjoy

**Closed by vaxerski** 2024-06-03 16:46 UTC
Labels: bug
