### ISSUE TITLE
 screen not fully stretched

### ISSUE THREAD

**Issue by eranif2** [hyprwm/Hyprland#4939] opened 2024-03-03 09:10 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0

flags: (if any)


System Information:
System name: Linux
Node name: eran-x1.eran.home
Release: 6.7.6-100.fc38.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Fri Feb 23 18:29:24 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="38 (Sway)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Sway)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://gitlab.com/fedora/sigs/sway/SIG/-/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Sway"
VARIANT_ID=sway


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

seem that my laptop monitor is not fully stretched,  my main screen is working
```console
# config
# eDP-1 -> laptop monitor
monitor=desc:ASUSTek COMPUTER INC VG27A KALMQS172296,2560x1440@60, 1920x0,1
monitor=eDP-1,1920x1080@58.94, 0x0,1
```

```sh
❯ hyprctl monitors list
Monitor eDP-1 (ID 0):
	1920x1080@58.94000 at 0x0
	description: California Institute of Technology 0x1404
	make: California Institute of Technology
	model: 0x1404
	serial: 
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 48 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-2 (ID 1):
	2560x1440@59.95100 at 1920x0
	description: ASUSTek COMPUTER INC VG27A KALMQS172296
	make: ASUSTek COMPUTER INC
	model: VG27A
	serial: KALMQS172296
	active workspace: 9 (9)
	special workspace: 0 ()
	reserved: 0 48 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

I tried different setting and scaling seems when I lower my resolution it fixes the issue
for example
```
monitor=eDP-1,1720x1080@58.94, 0x0,1
# or also working
monitor=eDP-1,1920x1204@58.94, 0x0,1
```

### How to reproduce

not sure if it happens on all monitor's / hardwars

### Crash reports, logs, images, videos

![non-wokring](https://github.com/hyprwm/Hyprland/assets/29957623/a8a3bbb5-92bc-470d-b5b1-f4338c90d9f7)
![working](https://github.com/hyprwm/Hyprland/assets/29957623/8aadf940-cea5-47b1-aaee-3da4d8f0b498)

**Comment by vaxerski** [comment] 2024-03-03 16:54
I think dupe of #4474

**Closed by vaxerski** 2024-03-03 16:54 UTC
Labels: bug

**Comment by eranif2** [comment] 2024-03-03 16:56
I tried changing scale that didn't work on my case

**Comment by vaxerski** [comment] 2024-03-03 17:05
does the cursor render over the black area?

**Comment by eranif2** [comment] 2024-03-03 17:07
No

**Comment by vaxerski** [comment] 2024-03-03 17:22
then it's a bug with your driver, physically damaged display, or wlroots
