### ISSUE TITLE
Wrong window placement on special workspace with dual monitors

### ISSUE THREAD

**Issue by imxyy1soope1** [hyprwm/Hyprland#3130] opened 2023-09-01 08:52 UTC
### Hyprland Version

Hyprland, built from branch main at commit 1a13d44d5dbe8e13480366dc97ea7eeee4ff42bb dirty (refactor: raise SIGABRT instead of write to null address (3124)). Tag: v0.29.0-10-g1a13d44d  flags: (if any)

### Bug or Regression?

Bug

### Description

the window seems to be placed on the other monitor (see the video)

### How to reproduce

1. toggle a special workspace
2. open a window in the special workspace
3. move mouse focus to the other monitor
4. toggle the special workspace

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/103114856/7f7c5030-fb2b-482e-b1ad-23480d05e539

**Comment by vaxerski** [comment] 2023-09-01 20:50
dupe of #1151

**Closed by vaxerski** 2023-09-01 20:50 UTC
Labels: bug
