### ISSUE TITLE
crash on exec "wlrctl pointer move 33 77"

### ISSUE THREAD

**Issue by jheroy** [hyprwm/Hyprland#6072] opened 2024-05-15 03:37 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.6.30-2-lts
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:45:29 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070 Ti] [10de:1b82] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

XIO: fatal IO error 13 (Permission denied) on X server ":0"

### How to reproduce

execute `wlrctl pointer move 33 77` tiwice

**Comment by jheroy** [comment] 2024-05-15 03:43
By the way, using `https://github.com/moverest/wl-kbptr` to click the mouse also triggers the same crash effect. Suspecting it's the same bug.

**Comment by vaxerski** [comment] 2024-05-15 15:28
can't repro. Try on git, plus, always post a crash report.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/9f3248cf-6b90-48d7-ab82-e2acf9504270)

**Comment by jheroy** [comment] 2024-05-16 01:07
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15328371/hyprland.log)

I have conducted further tests and found that the Hyprland does not crash when only one terminal is open. However, if I launch X11 programs that use Xwayland, the Hyprland crashes. Additionally, my monitor arrangement is as follows:

```
monitor=DP-1,highres,auto,1
monitor=DP-2,highres,-2160x-1190,1,transform,1

```

**Comment by amarakon** [comment] 2024-07-13 19:15
@vaxerski Have you tried reproducing the bug with more than one window open? I'm experiencing the same thing as @jheroy, where it works when only one terminal is open.

**Comment by vaxerski** [comment] 2024-07-14 21:09
marking this for 0.42 if I will be able to reproduce

**Comment by amarakon** [comment] 2024-07-14 21:50
I tried it on the latest git commit, and I still get this issue. Unfortunately, I can't get a debug stacktrace since I'm on OpenRC. Here's a log if it helps though.
[hyprland.log](https://github.com/user-attachments/files/16228881/hyprland.log)

**Comment by vaxerski** [comment] 2024-07-22 11:06
can't repro, is this still a thing after #6608 was merged?

**Comment by vaxerski** [comment] 2024-08-03 17:51
closing, no activity

**Closed by vaxerski** 2024-08-03 17:51 UTC
Labels: bug
