### ISSUE TITLE
Default tabbed/grouped layout option

### ISSUE THREAD

**Issue by jfaz1** [hyprwm/Hyprland#2281] opened 2023-05-10 23:36 UTC
Would love to switch from i3, but I actually use tabbed mode more than tiled (more frequently using GUI applications than consoles, and even then, a lot of the time I prefer full-screen terminals without taking up a lot of workspaces). 

It would be great if there was an option like in i3 that let us set whether to use tabbed/grouped or tiled layout by default.

Thanks!

**Comment by vaxerski** [comment] 2023-05-10 23:38
groups exist, wdym groups by default?

**Comment by Aqa-Ib** [comment] 2023-05-11 21:09
duplicate of #1505

**Closed** 2023-05-12 00:17 UTC
Labels: enhancement
