### ISSUE TITLE
openSUSE aquamarine package out of date, hyprland crashing on startup.

### ISSUE THREAD

**Issue by aliqut** [hyprwm/Hyprland#7812] opened 2024-09-15 23:52 UTC
Can't get into my desktop, happened after updating my packages. Other desktop environments/window managers are working fine. 

Not sure what's causing this just by looking at the logs.

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11(SEGV)
Version: 0000000000000000000000000000000000000000
Tag: 0.43.0
Date: Thu Jan 01 00:00:00 1970
Flags:

System info:
        System name: Linux
        Release: 6.10.9-1-default
        Version: #1 SMP PREEMPT_DYNAMIC Sun Sep  8 13:43:05 UTC 2024 (5af7788)

GPU:
        01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])

os-release:
        NAME="openSUSE Tumbleweed"
        # VERSION="20240913"
        ID="opensuse-tumbleweed"
        ID_LIKE="opensuse suse"
        VERSION_ID="20240913"
        PRETTY_NAME="openSUSE Tumbleweed"
        ANSI_COLOR="0;32"
        # CPE 2.3 format, boo#1217921
        CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240913:*:*:*:*:*:*:*"
        #CPE 2.2 format
        #CPE_NAME="cpe:/o:opensuse:tumbleweed:20240913"
        BUG_REPORT_URL="https://bugzilla.opensuse.org"
        SUPPORT_URL="https://bugs.opensuse.org"
        HOME_URL="https://www.opensuse.org"
        DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
        LOGO="distributor-logo-Tumbleweed"
Backtrace:
        # | Hyprland(_Z12getBacktracev+0x5b) [0x562b0339fe1b]
                getBacktrace()
                ??:?
        #1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xaa1) [0x562b033358c1]
                CrashReporter::createAndSaveCrash(int)
                ??:?
        #2 | Hyprland(_Z25handleUnrecoverableSignali+0x5c) [0x562b032d556c]
                handleUnrecoverableSignal(int)
                ??:?
        #3 | /lib64/libc.so.6(+0x41290) [0x7f1e8a041290]
                ??
                ??:0
        #4 | /lib64/libaquamarine.so.2(+0x104430) [0x7f1e8aeff430]
                ??
                ??:0

Log tail:
[LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-eDP-1
[ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-eDP-1, no devnode
[LOG] [AQ] drm: Found 1 GPUs
[LOG] [AQ] drm: Starting backend for /dev/dri/card0, with driver nvidia-drm
[LOG] [AQ] drm: Registered gpu /dev/dri/card0
[LOG] [AQ] drm: Atomic supported, using atomic for modesetting
[LOG] [AQ] drm: drmProps.supportsAsyncCommit: true
[LOG] [AQ] drm: drmProps.supportsAddFb2Modifiers: true
[LOG] [AQ] drm: drmProps.supportsTimelines: true
[LOG] [AQ] drm: found 4 CRTCs
[LOG] [AQ] drm: found 12 planes
[LOG] [AQ] drm: Plane 36 has type 1
[LOG] [AQ] drm: Plane 36 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 39 has type 2
[LOG] [AQ] drm: Plane 39 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 44 has type 0
[LOG] [AQ] drm: Plane 44 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 49 has type 1
[LOG] [AQ] drm: Plane 49 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 52 has type 2
[LOG] [AQ] drm: Plane 52 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 57 has type 0
[LOG] [AQ] drm: Plane 57 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 62 has type 1
[LOG] [AQ] drm: Plane 62 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 65 has type 2
[LOG] [AQ] drm: Plane 65 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 70 has type 0
[LOG] [AQ] drm: Plane 70 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 75 has type 1
[LOG] [AQ] drm: Plane 75 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 78 has type 2
[LOG] [AQ] drm: Plane 78 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 83 has type 0
[LOG] [AQ] drm: Plane 83 has 22 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Basic init pass for gpu /dev/dri/card0
[LOG] [AQ] drm: Scanning connectors for /dev/dri/card0
[LOG] [AQ] drm: Scanning connector id 89
[LOG] [AQ] drm: Initializing connector id 89
[LOG] [AQ] drm: Connector gets name DP-1
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 89 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 93
[LOG] [AQ] drm: Initializing connector id 93
[LOG] [AQ] drm: Connector gets name HDMI-A-1
[LOG] [AQ] drm: Connector 93 connection state: 1
[LOG] [AQ] drm: Connector HDMI-A-1 connected
[LOG] [AQ] drm: Connecting connector HDMI-A-1, CRTC ID 43
[LOG] [AQ] drm: Dumping detected modes:
[LOG] [AQ] drm: Mode 0: 1920x1080@60.00Hz  (preferred)
[LOG] [AQ] drm: Mode 1: 1920x1080@144.01Hz 
[LOG] [AQ] drm: Mode 2: 1920x1080@119.88Hz 
[LOG] [AQ] drm: Mode 3: 1920x1080@59.94Hz 
[LOG] [AQ] drm: Mode 4: 1920x1080@50.00Hz 
[LOG] [AQ] drm: Mode 5: 1680x1050@59.95Hz 
[LOG] [AQ] drm: Mode 6: 1280x1024@75.03Hz 
[LOG] [AQ] drm: Mode 7: 1280x1024@60.02Hz 
[LOG] [AQ] drm: Mode 8: 1440x900@59.89Hz 
[LOG] [AQ] drm: Mode 9: 1280x960@60.00Hz 
[LOG] [AQ] drm: Mode 10: 1152x864@75.00Hz 
[LOG] [AQ] drm: Mode 11: 1280x720@60.00Hz 
[LOG] [AQ] drm: Mode 12: 1280x720@59.94Hz 
[LOG] [AQ] drm: Mode 13: 1280x720@50.00Hz 
[LOG] [AQ] drm: Mode 14: 1440x576@50.00Hz 
[LOG] [AQ] drm: Mode 15: 1024x768@75.03Hz 
[LOG] [AQ] drm: Mode 16: 1024x768@70.07Hz 
[LOG] [AQ] drm: Mode 17: 1024x768@60.00Hz 
[LOG] [AQ] drm: Mode 18: 1440x480@59.94Hz 
[LOG] [AQ] drm: Mode 19: 800x600@75.00Hz 
[LOG] [AQ] drm: Mode 20: 800x600@72.19Hz 
[LOG] [AQ] drm: Mode 21: 800x600@60.32Hz 
[LOG] [AQ] drm: Mode 22: 800x600@56.25Hz 
[LOG] [AQ] drm: Mode 23: 720x576@50.00Hz 
[LOG] [AQ] drm: Mode 24: 720x480@59.94Hz 
[LOG] [AQ] drm: Mode 25: 640x480@75.00Hz 
[LOG] [AQ] drm: Mode 26: 640x480@72.81Hz 
[LOG] [AQ] drm: Mode 27: 640x480@59.94Hz 
[LOG] [AQ] drm: Mode 28: 640x480@59.93Hz

**Comment by SealProgrammer** [comment] 2024-09-16 02:51
Having a similar issue, for a while it was very slow and using up 90% cpu and had a lot of graphical errors and now it won’t load at all. This started after updating it today. My logs are at https://0x0.st/X3HH.txt

**Comment by dottorblaster** [comment] 2024-09-16 07:44
For what it's worth I have an almost identical crash report.
My setup is an openSUSE Tumbleweed with updated nvidia drivers and a dual monitor.

```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
"stable"

Hyprland received signal 11(SEGV)
Version: 0000000000000000000000000000000000000000
Tag: 0.43.0
Date: Thu Jan 01 00:00:00 1970
Flags:

System info:
	System name: Linux
	Node name: gandalf
	Release: 6.10.9-1-default
	Version: #1 SMP PREEMPT_DYNAMIC Sun Sep  8 13:43:05 UTC 2024 (5af7788)

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME="openSUSE Tumbleweed"
	# VERSION="20240913"
	ID="opensuse-tumbleweed"
	ID_LIKE="opensuse suse"
	VERSION_ID="20240913"
	PRETTY_NAME="openSUSE Tumbleweed"
	ANSI_COLOR="0;32"
	# CPE 2.3 format, boo#1217921
	CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240913:*:*:*:*:*:*:*"
	#CPE 2.2 format
	#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240913"
	BUG_REPORT_URL="https://bugzilla.opensuse.org"
	SUPPORT_URL="https://bugs.opensuse.org"
	HOME_URL="https://www.opensuse.org"
	DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
	LOGO="distributor-logo-Tumbleweed"
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x5b) [0x55ca5fa24e1b]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xaa1) [0x55ca5f9ba8c1]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x5c) [0x55ca5f95a56c]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /lib64/libc.so.6(+0x41290) [0x7f52cae41290]
		??
		??:0
	#4 | /lib64/libaquamarine.so.2(+0x104430) [0x7f52cbe78430]
		??
		??:0


Log tail:
[LOG] [AQ] drm: Plane 73 has 8 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Basic init pass for gpu /dev/dri/card1
[LOG] [AQ] drm: Scanning connectors for /dev/dri/card1
[LOG] [AQ] drm: Scanning connector id 77
[LOG] [AQ] drm: Initializing connector id 77
[LOG] [AQ] drm: Connector gets name DVI-D-1
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 77 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 79
[LOG] [AQ] drm: Initializing connector id 79
[LOG] [AQ] drm: Connector gets name HDMI-A-4
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 79 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 82
[LOG] [AQ] drm: Initializing connector id 82
[LOG] [AQ] drm: Connector gets name DP-2
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 82 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 86
[LOG] [AQ] drm: Initializing connector id 86
[LOG] [AQ] drm: Connector gets name DP-3
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 86 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 90
[LOG] [AQ] drm: Initializing connector id 90
[LOG] [AQ] drm: Connector gets name DP-4
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 90 because it has no CRTC
[LOG] [AQ] drm: Rechecking CRTCs
[LOG] [AQ] drm: connector DVI-D-1, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector HDMI-A-4, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector DP-2, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector DP-3, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector DP-4, has crtc -1, will be rechecked
[LOG] [AQ] drm: connected slot 0 crtc 42 assigned to DP-3
[LOG] [AQ] drm: connected slot 1 crtc 52 assigned to DP-4
[LOG] [AQ] drm: slot 2 crtc 62 unassigned
[LOG] [AQ] drm: slot 3 crtc 72 unassigned
[LOG] [AQ] drm: Connector DVI-D-1 is not connected
[LOG] [AQ] drm: Connector HDMI-A-4 is not connected
[LOG] [AQ] drm: Connector DP-2 is not connected
[LOG] [AQ] drm: rescanning after realloc
[LOG] [AQ] drm: Scanning connectors for /dev/dri/card1
[LOG] [AQ] drm: Scanning connector id 77
[LOG] [AQ] drm: Connector id 77 already initialized
[LOG] [AQ] drm: Ignoring connector 77 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 79
[LOG] [AQ] drm: Connector id 79 already initialized
[LOG] [AQ] drm: Ignoring connector 79 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 82
[LOG] [AQ] drm: Connector id 82 already initialized
[LOG] [AQ] drm: Ignoring connector 82 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 86
[LOG] [AQ] drm: Connector id 86 already initialized
[LOG] [AQ] drm: Connector 86 connection state: 1
[LOG] [AQ] drm: Connector DP-3 connected
[LOG] [AQ] drm: Connecting connector DP-3, CRTC ID 42
[LOG] [AQ] drm: Dumping detected modes:
[LOG] [AQ] drm: Mode 0: 2560x1440@59.95Hz  (preferred)
[LOG] [AQ] drm: Mode 1: 2048x1152@60.00Hz 
[LOG] [AQ] drm: Mode 2: 1920x1200@59.88Hz 
[LOG] [AQ] drm: Mode 3: 1920x1080@60.00Hz 
[LOG] [AQ] drm: Mode 4: 1920x1080@59.94Hz 
[LOG] [AQ] drm: Mode 5: 1920x1080@50.00Hz 
[LOG] [AQ] drm: Mode 6: 1920x1080@29.97Hz 
[LOG] [AQ] drm: Mode 7: 1920x1080@25.00Hz 
[LOG] [AQ] drm: Mode 8: 1920x1080@23.98Hz 
[LOG] [AQ] drm: Mode 9: 1600x1200@60.00Hz 
[LOG] [AQ] drm: Mode 10: 1680x1050@59.95Hz 
[LOG] [AQ] drm: Mode 11: 1280x1024@75.03Hz 
[LOG] [AQ] drm: Mode 12: 1280x1024@60.02Hz 
[LOG] [AQ] drm: Mode 13: 1200x960@59.90Hz 
[LOG] [AQ] drm: Mode 14: 1152x864@75.00Hz 
[LOG] [AQ] drm: Mode 15: 1280x720@60.00Hz 
[LOG] [AQ] drm: Mode 16: 1280x720@59.94Hz 
[LOG] [AQ] drm: Mode 17: 1280x720@50.00Hz 
[LOG] [AQ] drm: Mode 18: 1024x768@75.03Hz 
[LOG] [AQ] drm: Mode 19: 1024x768@60.00Hz 
[LOG] [AQ] drm: Mode 20: 800x600@75.00Hz 
[LOG] [AQ] drm: Mode 21: 800x600@60.32Hz 
[LOG] [AQ] drm: Mode 22: 720x576@50.00Hz 
[LOG] [AQ] drm: Mode 23: 720x480@59.94Hz 
[LOG] [AQ] drm: Mode 24: 640x480@75.00Hz 
[LOG] [AQ] drm: Mode 25: 640x480@59.94Hz 
[LOG] [AQ] drm: Mode 26: 640x480@59.93Hz 
```

**Comment by Fuzzy-Math** [comment] 2024-09-16 13:30
Also present on an intel card with openSUSE Tumbleweed/MicroOS so not just Nvidia:
```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Maybe you should try dusting your PC in the meantime?

Hyprland received signal 11(SEGV)
Version: 0000000000000000000000000000000000000000
Tag: 0.43.0
Date: Thu Jan 01 00:00:00 1970
Flags:

System info:
	System name: Linux
	Node name: vortexcp
	Release: 6.10.9-1-default
	Version: #1 SMP PREEMPT_DYNAMIC Sun Sep  8 13:43:05 UTC 2024 (5af7788)

GPU:
	24:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])
2f:00.0 VGA compatible controller [0300]: Intel Corporation DG2 [Arc A770] [8086:56a0] (rev 08) (prog-if 00 [VGA controller])


os-release:
	NAME="openSUSE MicroOS"
	# VERSION="20240913"
	ID="opensuse-microos"
	ID_LIKE="suse opensuse opensuse-tumbleweed microos sl-micro"
	VERSION_ID="20240913"
	PRETTY_NAME="openSUSE MicroOS"
	ANSI_COLOR="0;32"
	CPE_NAME="cpe:/o:opensuse:microos:20240913"
	BUG_REPORT_URL="https://bugzilla.opensuse.org"
	SUPPORT_URL="https://bugs.opensuse.org"
	HOME_URL="https://www.opensuse.org/"
	DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
	LOGO="distributor-logo-MicroOS"
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x5b) [0x564b06ba0e1b]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xaa1) [0x564b06b368c1]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x5c) [0x564b06ad656c]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /lib64/libc.so.6(+0x41290) [0x7fdc9c641290]
		??
		??:0
	#4 | /lib64/libaquamarine.so.2(+0x104430) [0x7fdc9d659430]
		??
		??:0


Log tail:
[LOG] [AQ] drm: Plane 102 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 111 has type 0
[LOG] [AQ] drm: Plane 111 has 21 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 120 has type 0
[LOG] [AQ] drm: Plane 120 has 21 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 129 has type 2
[LOG] [AQ] drm: Plane 129 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 136 has type 1
[LOG] [AQ] drm: Plane 136 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 145 has type 0
[LOG] [AQ] drm: Plane 145 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 154 has type 0
[LOG] [AQ] drm: Plane 154 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 163 has type 0
[LOG] [AQ] drm: Plane 163 has 21 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 172 has type 0
[LOG] [AQ] drm: Plane 172 has 21 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 181 has type 2
[LOG] [AQ] drm: Plane 181 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 188 has type 1
[LOG] [AQ] drm: Plane 188 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 197 has type 0
[LOG] [AQ] drm: Plane 197 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 206 has type 0
[LOG] [AQ] drm: Plane 206 has 29 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 215 has type 0
[LOG] [AQ] drm: Plane 215 has 21 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 224 has type 0
[LOG] [AQ] drm: Plane 224 has 21 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Plane 233 has type 2
[LOG] [AQ] drm: Plane 233 has 1 formats
[LOG] [AQ] drm: Plane: checking for modifiers
[LOG] [AQ] drm: Basic init pass for gpu /dev/dri/card1
[LOG] [AQ] drm: Scanning connectors for /dev/dri/card1
[LOG] [AQ] drm: Scanning connector id 241
[LOG] [AQ] drm: Initializing connector id 241
[LOG] [AQ] drm: Connector gets name DP-1
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Ignoring connector 241 because it has no CRTC
[LOG] [AQ] drm: Scanning connector id 254
[LOG] [AQ] drm: Initializing connector id 254
[LOG] [AQ] drm: Connector gets name DP-2
[LOG] [AQ] drm: Connector 254 connection state: 1
[LOG] [AQ] drm: Connector DP-2 connected
[LOG] [AQ] drm: Connecting connector DP-2, CRTC ID 82
[LOG] [AQ] drm: Dumping detected modes:
[LOG] [AQ] drm: Mode 0: 2560x1440@75.00Hz  (preferred)
[LOG] [AQ] drm: Mode 1: 2560x1440@59.95Hz 
[LOG] [AQ] drm: Mode 2: 1920x1080@60.00Hz 
[LOG] [AQ] drm: Mode 3: 1920x1080@60.00Hz 
[LOG] [AQ] drm: Mode 4: 1920x1080@59.94Hz 
[LOG] [AQ] drm: Mode 5: 1920x1080@50.00Hz 
[LOG] [AQ] drm: Mode 6: 1680x1050@59.95Hz 
[LOG] [AQ] drm: Mode 7: 1600x900@60.00Hz 
[LOG] [AQ] drm: Mode 8: 1280x1024@75.03Hz 
[LOG] [AQ] drm: Mode 9: 1280x1024@60.02Hz 
[LOG] [AQ] drm: Mode 10: 1440x900@59.89Hz 
[LOG] [AQ] drm: Mode 11: 1280x800@59.81Hz 
[LOG] [AQ] drm: Mode 12: 1152x864@75.00Hz 
[LOG] [AQ] drm: Mode 13: 1280x720@60.00Hz 
[LOG] [AQ] drm: Mode 14: 1280x720@60.00Hz 
[LOG] [AQ] drm: Mode 15: 1280x720@59.94Hz 
[LOG] [AQ] drm: Mode 16: 1280x720@50.00Hz 
[LOG] [AQ] drm: Mode 17: 1024x768@75.03Hz 
[LOG] [AQ] drm: Mode 18: 1024x768@70.07Hz 
[LOG] [AQ] drm: Mode 19: 1024x768@60.00Hz 
[LOG] [AQ] drm: Mode 20: 832x624@74.55Hz 
[LOG] [AQ] drm: Mode 21: 800x600@75.00Hz 
[LOG] [AQ] drm: Mode 22: 800x600@72.19Hz 
[LOG] [AQ] drm: Mode 23: 800x600@60.32Hz 
[LOG] [AQ] drm: Mode 24: 800x600@56.25Hz 
[LOG] [AQ] drm: Mode 25: 720x576@50.00Hz 
[LOG] [AQ] drm: Mode 26: 720x480@60.00Hz 
[LOG] [AQ] drm: Mode 27: 720x480@59.94Hz 
[LOG] [AQ] drm: Mode 28: 640x480@75.00Hz 
[LOG] [AQ] drm: Mode 29: 640x480@72.81Hz 
[LOG] [AQ] drm: Mode 30: 640x480@66.67Hz 
[LOG] [AQ] drm: Mode 31: 640x480@60.00Hz 
[LOG] [AQ] drm: Mode 32: 640x480@59.94Hz 
[LOG] [AQ] drm: Mode 33: 720x400@70.08Hz 

```

**Comment by OnyxAbove** [comment] 2024-09-16 23:13
Hello, I am having a similar issue on openSUSE Tumbleweed. I have tried starting from SDDM (like usual) and it shows a black screen with cursor blinking in top left. Tried launching from TTY and faced the same problem except it never goes to the black screen, just drops me back onto a prompt.

I am unsure about how to get the logs, I set debug:disable_logs to false and then used `cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 1)/hyprland.log` from my TTY,  but it just gives me the usual log that doesnt say anything about drm, it seems like a silent falure. 

If anyone could send the command to get the log, that would be great.

**Comment by tradiff** [comment] 2024-09-17 04:36
duplicate of https://github.com/hyprwm/Hyprland/issues/7759
more info: https://forums.opensuse.org/t/cant-launch-hyprland-after-update/178514

Seems like it's because the aquamarine build is still 0.3.0, which is incompatible with Hyprland 0.43.0
https://build.opensuse.org/package/show/X11:Wayland/aquamarine

**Comment by dottorblaster** [comment] 2024-09-17 09:26
I just created a submit request to Factory with the new 0.4.1

https://build.opensuse.org/request/show/1201553

**Comment by vaxerski** [comment] 2024-09-17 10:21
please don't report problems with downstream packagers here, we can't do much

**Closed by vaxerski** 2024-09-17 10:21 UTC

**Comment by dottorblaster** [comment] 2024-09-17 13:40
@vaxerski we just noticed it was a downstream problem after a while, sorry for the noise and keep up the awesome work :smile:
