### ISSUE TITLE
Intellij IDEA's tooltip focus flicker

### ISSUE THREAD

**Issue by Nyayurn** [hyprwm/Hyprland#4838] opened 2024-02-25 14:47 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
❯ hyprctl version
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Watch video

### How to reproduce

Move the mouse over the file tab or sidebar icon in IDEA and wait for 1 second

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/132195516/194cb3a3-e5f6-4a88-b0c6-58db22506dfd

**Comment by romanstingler** [comment] 2024-02-25 16:09
duplicate of https://github.com/hyprwm/Hyprland/issues/4396

**Closed** 2024-02-25 23:09 UTC
Labels: bug
