### ISSUE TITLE
all sub window/layer selection

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#8001] opened 2024-10-06 09:23 UTC
### Description

for example. I want all popup window or window that is spawned by another program to be float

**Comment by vaxerski** [comment] 2024-10-06 23:14
what?

**Comment by littleblack111** [comment] 2024-10-07 08:35
like if in a file manager, i double click a file, and it opened something. I want to select that thing

**Comment by vaxerski** [comment] 2024-10-07 12:24
just match whatever properties it has, there isnt much we can do here? otherwise if you want by pid thats a dupe of #7861

**Closed by vaxerski** 2024-10-07 12:24 UTC
Labels: enhancement
