### ISSUE TITLE
On hybrid graphics, blacklisting NVIDIA modules causes delay in windows opening

### ISSUE THREAD

**Issue by OctarineSourcerer** [hyprwm/Hyprland#1065] opened 2022-11-21 13:11 UTC
I have a laptop with inegrated graphics (Intel UHD 630) and discrete graphics (renderer: NVIDIA GeForce GTX with Max-Q Design/PCIe/SSE2).
NVIDIA's power management for this card is... not particularly good, so if I want to save power, I sometimes blacklist the following modules on boot via kernel parameters: `nvidia,nvidia_drm,nvidia_modeset`. This usually means it doesn't turn on at all, giving me 5-8W idle power usage instead of 15-18W.

However, when running Hyprland with these modules blacklisted, window creation is delayed by more than 2 seconds. 
Without blacklisting these modules, 

## Steps to reproduce
* Boot with the following kernel parameters added: `module_blacklist=nvidia,nvidia_drm,nvidia_modeset`
* Run Hyprland
* Attempt to open windows

Different applications seem to act differently. I tested a couple, with the results below.
## Window creation testing
Large (~2.3-2.5s) delay? Appears to vary
* Kitty (any window)
* Firefox (first opened window)
* Waybar (first time)

Small (noticeable though) delay:
* Thunar
* Firefox's second window
* running kitty with `KITTY_DISABLE_WAYLAND=1 kitty`

running `kitty` from a kitty window within Hyprland has the same delay, and gives:
```
[glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

Hitting ctrl+enter (my keybind to launch kitty) continuously does nothing until the delay is up, and then they _all appear at the same time_.

## Related packages, config
`hyprland-git`: r2060.250d61e-1, apparently release `6.0.9-arch1-1`, 
`xdg-desktop-portal`: 1.15.0-1
`xdg-desktop-portal-gtk`: 1.14.0-1

NVIDIA modules are not in my `mkinitcpio` precisely so I can do this hacky powersaving, though my Hyprland wrapper does have the lines specified at https://wiki.hyprland.org/Nvidia/

## Logs
I redirected Hyprland's output to a file (as well as current kernel parameters) so you can see what might be up. In each session, I run a script (`runKittiesAndThunar`) to launch 3 kitty instances and 1 thunar instance. Knda wish the logs had timestamps, happy to rerun with those enabled if there's a way. These are attached.
[intel.log](https://github.com/hyprwm/Hyprland/files/10056766/intel.log): followed the steps to reproduce
[intelNVIDIABlacklist.log](https://github.com/hyprwm/Hyprland/files/10056768/intelNVIDIABlacklist.log): did not blacklist any modules.

Whew. Sorry for that wall of text.

**Comment by vaxerski** [comment] 2022-11-21 13:50
The problem with nvidia is that I do not offer any official support for such issues. They are mostly a lottery (because of nvidia's shit drivers) and if you're lucky it works, if you aren't it doesn't. Have you tried `hyprland-nvidia-git` from the AUR?

I don't even have a machine to test, as I have not touched nvidia in ages due to their drivers.

Apart from that, you can join the discord server and ask around for similiar issues, maybe someone else had this.

**Comment by OctarineSourcerer** [comment] 2022-11-21 14:12
Unfortunately, my worry is that the bug is happening with the NVIDIA drivers specifically _not_ launched, so I don't think it's the drivers' work. I'm wondering if it might be the case with any hybrid machine? I can try the `hyprland-nvidia-git` package and report though.

**Comment by Aqa-Ib** [comment] 2022-11-22 00:09
Now that you tell, I noticed it on my laptop, I have the nvidia card blacklisted too.
Just thinking... it might not be because of the nvidia card blacklisting? It could be just the intel graphics itself... I have an 11th gen intel.

**Comment by Aqa-Ib** [comment] 2022-11-22 03:40
I am testing the open source Nvidia drivers. Now I can black list the nvidia card and have 0 lag using the integrated intel card alone. WTF is going on with the black listing? Why does the drivers have an impact although you have black listed them?

**Comment by Aqa-Ib** [comment] 2022-11-22 22:51
Other strange thing is that using the "hybrid graphics mode", which should be using just the intel graphics card unless told otherwise, there is no lag.  Something odd is going on here, at least looking at it from my little knowledge of the graphics stack.
Regards.

**Comment by Aqa-Ib** [comment] 2022-11-23 21:50
> Could you, using hybrid graphics mode, run `inxi -G` to check what's rendering for you?

`renderer: Mesa Intel Xe Graphics
    (TGL GT2)`

**Comment by OctarineSourcerer** [comment] 2022-11-26 10:47
I seem to have the same issue with `nouveau` - delays that feel like anywhere between 0.5 and 2 seconds, though it's worth noting `inxi -G` has my renderer as "N/A" , and glxgears will not run.
Blacklisted nvidia modules on boot, and had uncommented nouveau blacklistings in `/usr/lib/modprobe.d`. 

`inxi -G` output:
```
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA GP104M [GeForce GTX 1070 Mobile] driver: nouveau
    v: kernel
  Device-3: Sunplus Innovation HD WebCam type: USB driver: uvcvideo
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.5
    compositor: Hyprland driver: X: loaded: intel unloaded: modesetting
    dri: i965 gpu: i915,nouveau resolution: 1920x1080
  API: OpenGL v: N/A renderer: N/A
```
Kernel parameters: `vmlinuz-linux module_blacklist=nvidia,nvidia_drm,nvidia_modeset root=/dev/nvme1n1p1 rw add_efi_memmap initrd=intel-ucode.img initrd=initramfs-linux.img nopti intel_iommu=on iommu=on sysrq_always_enabled=1 quiet splash loglevel=3 rd.udev.log_priority=3 i915.fastboot=1 i915.enable_guc=2 i915.modeset=1`

**Comment by vaxerski** [comment] 2022-11-26 10:56
yeah because
a) doesnt seem like a hyprland issue
b) I've not had a single nvidia product for ages.

**Comment by Aqa-Ib** [comment] 2022-11-26 16:24
The same shit is going on sway too. Maybe we can find some help in Archlinux forums or reddit.

**Comment by Aqa-Ib** [comment] 2022-11-26 16:32
Something worth nothing:
- Plasma Wayland has this bug too.
- Plasma X11 has not this bug.
- Plasma does not use wlroots.
So the problem is something wrong with Wayland itself.

**Comment by vaxerski** [comment] 2022-11-26 18:49
if wayland plasma has the exact bug, then I will close this, as it's not a hl issue. Most likely a driver one.

**Closed by vaxerski** 2022-11-26 18:49 UTC
Labels: bug

**Comment by Parmjot-Singh** [comment] 2023-07-26 06:15
Occurs even when modules `nvidia`, `nvidia_modeset`, `nvidia_uvm` and `nvidia_drm` aren't added to the initramfs on Arch Linux. Adding them fixes the issue.

**Comment by xcpky** [comment] 2023-09-01 15:10
![image](https://github.com/hyprwm/Hyprland/assets/52552971/f5f898ad-2eb9-4334-8296-839c647b4bd2)
I seems to find a clue. through lsof we can see the libnvidia is opened for all apps after hyprland is launched, but I don't know how to prevent that

**Comment by xcpky** [comment] 2023-09-01 17:40
Solved

https://wiki.archlinux.org/title/wayland#Avoid_loading_NVIDIA_modules
