### ISSUE TITLE
Hyprland crashed when moving file with mouse in Obsidian

### ISSUE THREAD

**Issue by jiiiijiij** [hyprwm/Hyprland#2098] opened 2023-04-19 05:15 UTC
This is my log and crash report. I just simply try to move a file with mouse, and freeze then crashed. Haven't notice the problem elsewhere because I only use browser and Obsidian.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/11268862/hyprland.log)
[hyprlandCrashReport9148.txt](https://github.com/hyprwm/Hyprland/files/11268877/hyprlandCrashReport9148.txt)

Obsidian work fine when I use Cage to test, and drag n drop file work well in qutebrowser upload promt.

**Comment by vaxerski** [comment] 2023-04-19 08:04
dupe of #2069

it's fixed in -git

**Closed by vaxerski** 2023-04-19 08:04 UTC
Labels: enhancement
