### ISSUE TITLE
Dispatcher `movewindoworgroup` to move into/out-of an unlocked group

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#2851] opened 2023-07-31 00:26 UTC
### Description

I would like a dispatcher to move windows into/out-of groups when the window is not in a locked group.

This effectively combines `moveintogroup` and `moveoutofgroup`, but allows using the same bind for both dispatchers. This would work because groups can be locked, in which case this dispatcher would move the group rather than a window.

```
bindm = mouse:276, movewindoworgroup
bind = SUPER_SHIFT, left, movewindoworgroup, l
bind = SUPER_SHIFT, right, movewindoworgroup, r
bind = SUPER_SHIFT, up, movewindoworgroup, u
bind = SUPER_SHIFT, down, movewindoworgroup, d
```

Maybe name it one of these:
- `movewindowmaybegroup`
- `moveunlockedwindow` (Makes less sense when a window outside of a group)
- `movewindoworgroup` (I like this one best)

**Comment by spikespaz** [comment] 2023-07-31 07:51
This does not work because all dispatchers are triggered, and they conflict.
```
bindm = , mouse:276, moveintogroup
bindm = , mouse:276, moveoutofgroup
bindm = , mouse:276, movewindow
```
Is there some magical order in which these work?

**Comment by spikespaz** [comment] 2023-07-31 16:27
I just realized that when using `bindm` the `movewindow` dispatcher can behave like `moveintogroup` (drop a window into a group), but when used with regular `bind` a window will swap positions with the entire group instead of joining it.

**Comment by memchr** [comment] 2023-08-16 20:11
> This does not work because all dispatchers are triggered, and they conflict.
> 
> ```
> bindm = , mouse:276, moveintogroup
> bindm = , mouse:276, moveoutofgroup
> bindm = , mouse:276, movewindow
> ```
> 
> Is there some magical order in which these work?

Doesn't `CKeybindManager::mouse` only support `movewindow' and `resizewindow'?

https://github.com/memchr/Hyprland/blob/4986d74ef201171a930c312a8e3b72a22d9b84ee/src/managers/KeybindManager.cpp#L1948

**Comment by spikespaz** [comment] 2023-08-16 20:42
> Doesn't CKeybindManager::mouse only support movewindow' and resizewindow'?

It's been a while so I'm not sure how clearly I remember, but I'm quite sure having those three dispatchers made it behave really weirdly. Like it would pick up the window and put it back, for an example of the behavior of one particular order.

I'm trying to remember if that was my testing with the keyboard but I don't think so, because I remember walking away and forgetting about it, then coming back and thinking "what the heck is happening to my mouse 5".

**Comment by spikespaz** [comment] 2023-08-16 20:56
≥ Does this mean moving the container like what swapActive or moveActiveTo does?

Yes for the former, but what is`moveactiveto` again? Not looking at the wiki ATM.

> moving the active window outside its group in another direction when the dispatcher is called on a group, and behaving like moveintogroup when called on a window

That sounds exactly like the behavior I'm after.

> the dispatcher

I assume you're talking about a new one, `movewindoworgroup`?

**Comment by memchr** [comment] 2023-08-16 21:34
> I assume you're talking about a new one, movewindoworgroup?

Yes, by **the dispatcher** I mean the hypothetical new dispatcher who will move the window or group.

> Row number 4: active is window, direction is window --do nothing. I don't think that's what I want, that should behave as movewindow or swapactive, unless I'm misunderstanding again.

Having the new dispatcher swap window position movewindow or swapactive would be inconsistent with how the dispatcher it is supposed to combine works.

The existing dispatchers, namely `moveintogroup` and `moveoutofgroup`, operate on at least one group by adding or removing window in the group(s). In addition, these dispatchers typically increase or decrease the total number of containers in a workspace, but never swap containers.

This inconsistent behaviour could confuse users who are familiar with the current functionality and defaults.

Therefore, in my opinion, the new dispatcher should not swap container positions by default when both the active and target containers are windows. Instead, it would be better to provide an option to enable container swapping via a configuration flag, for those who want that behavior.

**Comment by memchr** [comment] 2023-08-16 21:55
> That sounds exactly like the behavior I'm after

Please note that this behaviour **ignores** `m_sGroupData.locked` and **does not swap group containers** like `movewindow` does, in the same light of maintaining consistency, with the additional reason being that **`moveintogroup` also ignores `m_sGroupData.locked` by default.**

**Comment by memchr** [comment] 2023-08-17 01:13
The current `onWindowCreatedTiling()` methods do not currently allow you to move the window out of a group in a specific direction from any built-in layout. It only respects the mouse position or `force_split` for dwindle.

**Comment by spikespaz** [comment] 2023-08-17 03:53
My idea for the `movewindoworgroup` was for it to always have a reasonable behavior (always move) if at all possible.

> Having the new dispatcher swap window position movewindow or swapactive would be inconsistent with how the dispatcher it is supposed to combine works.

Two thoughts on this. This is inherently rather complicated, and therefore just calling the functions of other dispatchers or combining them would not be appropriate. For brevity, I use terms like `AND` and `THEN` below to describe behaviors; however this is not actually what I think should happen. We need unique code.

Because you wish to remain "consistent" with how these work (and this consistency does not adhere to my ideal functionality) I have introduced two behavioral "modes", A and B. Behavior A is essentially "this dispatcher is generic and dispatches other behaviors, and Behavior B is "move the window if it is possible".


| Active Tile | Direction/Target Tile | Behavior A | Behavior B | Reason |
| ----------- | --------------------- | -------- | ------- | ------ |
| Window in Group | Group | `moveoutofgroup` THEN `moveintogroup` | `moveoutofgroup` | May want `moveoutofgroup` **only** because it is more versatile. The window can be moved a second time if `moveintogroup` is desired. Which dispatcher behavior is selected could be a choice. |
| Window in Group | Window | `moveoutofgroup` | `moveoutofgroup` | Self-evident. |
| Window in Group | `null` | `moveoutofgroup` | `moveoutofgroup` | Self-evident. |
| Window | Group | `moveintogroup` | `moveintogroup` | Self-evident. |
| Window | Window | Do nothing. | `swapactive` | Self-evident. |
| Window | `null` | Do nothing. | Do nothing. | Self-evident. |
| Window in Floating Group | `null` | `moveoutofgroup` | `moveoutofgroup` AND `float` | Which behavior depends on if the user wants a window which is already in a floating group to remain floating, or if it should find a position in the tiled layout. Choice. |
| Floating Window | `null` | Do nothing. | Do nothing. | Self-evident. |

Now, I would like to see something very similar to work with `bindm`, because that is how I intend to use it. I will make a new table with my ideas after a short break.

**Comment by spikespaz** [comment] 2023-08-17 04:34
For another new dispatcher to work with `bindm` (and probably a control key):

| Hovered Tile | Behavior A | Behavior B | Reason |
| ------------ | ---------- | ---------- | ------ |
| Window in a Group | `moveoutofgroup` THEN `movewindow` | " | Self-evident. |
| Window | `movewindow` | " | Self-evident. |
| Window in Floating Group | `moveoutofgroup` THEN `movewindow` | `moveoutofgroup` AND `float` THEN `movewindow` | The original `movewindow` can always move the group itself, so no special behavior (option or C) is necessary. |
| Floating Window | `movewindow` | " | Self-evident. |

**Comment by memchr** [comment] 2023-08-17 08:50
> I'm annoyed, because you didn't read the preface.


I am truly sorry for the frustration, but this is to clear up any confusion about what the dispatcher actually does, So we can cooperate more effectively.

If you prefer, we can stop this conversation.

https://github.com/hyprwm/Hyprland/blob/7155b4c26606d7681bacb2517b1d19495336c6c3/src/managers/KeybindManager.cpp#L2036-L2069

**Comment by memchr** [comment] 2023-08-17 12:25
@spikespaz Hi, sorry for the intrusion, would you mind testing this PR? #3006

**Comment by memchr** [comment] 2023-08-17 12:33
The new dispatcher is currently (temporarily) named `chicken`, a new configuration variable `chicken_checkgrouplock` has been added which causes the dispatcher to behave alternatively around looked windows.


The dispatcher accepts any args that moveintogroup accepts. 

For example, you can test it like this

```conf
bind = SHIFT, h, chicken, l
bind = SHIFT, l, chicken, r
bind = SHIFT, k, chicken, u
bind = SHIFT, j, chicken, d
 
binds {
        chicken_checkgrouplock = true
}
```

**Comment by memchr** [comment] 2023-08-17 12:34
Other changes to the behaviour of existing dispersers are

- Moveoutofgroup will now focus and move the cursor to the moved window instead of the previous group.

**Comment by fleurc** [comment] 2023-09-26 21:25
Hi, I have no way to meaningfully make this enhancement any better, but I'd like to enter the discussion by pointing out that I've found this Issue thread when trying to implement a dispatcher of the name "movewindoworgroup" described in [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Dispatchers/#list-of-dispatchers)

If this is not an implemented feature or a feature in testing only, why have it be described as available to use inside of the Wiki?

**Comment by memchr** [comment] 2023-09-27 04:35
Already implemented and merged: #3006 (with the exception of the mouse bindings)

and the wiki, to my knowledge, always documents the last git main branch.

---

@vaxerski Should this be closed?

**Comment by fleurc** [comment] 2023-09-27 13:10
Is it implemented as of version 0.29.1-1?

**Comment by fleurc** [comment] 2023-09-27 13:11
I ask because in said version, hyprland told me no such dispatcher existed

**Comment by memchr** [comment] 2023-09-27 13:13
> I ask because in said version, hyprland told me no such dispatcher existed

> Already implemented and merged: https://github.com/hyprwm/Hyprland/pull/3006 (with the exception of the mouse bindings), **released in v0.30**

### released in v0.30

**Comment by fleurc** [comment] 2023-09-27 13:18
Ah thank you, I hadn't read that, very sorry for the inconvenience.

**Comment by spikespaz** [comment] 2023-10-23 02:08
@memchr 

> I'm annoyed

I apologize for this interaction.

**Comment by izmyname** [comment] 2024-07-24 18:58
Wasn't this implemented already, btw? I mean, there's a dispatcher, but the issue is still open.

**Closed** 2024-07-24 21:19 UTC
Labels: enhancement
