### ISSUE TITLE
Hyprland crash when launching modded Genshin Impact

### ISSUE THREAD

**Issue by Slimemaster0** [hyprwm/Hyprland#1940] opened 2023-04-03 16:38 UTC
[hyprlandCrashReport712.txt](https://github.com/hyprwm/Hyprland/files/11140524/hyprlandCrashReport712.txt)
I had Discord and a terminal, that i run my launch script from, running when the crash happend.
The game usually launches just fine, but this time Hyprland crashes.

**Comment by vaxerski** [comment] 2023-04-03 17:50
dupe of #1890

**Closed by vaxerski** 2023-04-03 17:50 UTC
Labels: bug
