### ISSUE TITLE
Random Crashes When a Window is Closed and Huge Cursor in Apps

### ISSUE THREAD

**Issue by emrakyz** [hyprwm/Hyprland#2409] opened 2023-06-01 04:37 UTC
- Closing a Window (for example pressing ESC on Rofi) crashes Hyprland.
- Some apps, (for example Firefox) make the cursor huge.

I normally update daily with the latest git commits. I also update other dependencies with git versions except wlroots.
 
The problem started when I updated on 31.05.2023, Wednesday night.

```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
*thud*

Hyprland received signal 6 (Aborted)

Version: e76bd43f53197af2c64608ba6b0792326e79db07

System info:
	System name: Linux
	Node name: (none)
	Release: 6.3.4-gentoo-r1
	Version: #1 SMP PREEMPT Mon May 29 08:12:38 +03 2023

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080 Rev. A] [10de:1e87] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME=Gentoo
	ID=gentoo
	PRETTY_NAME="Gentoo Linux"
	ANSI_COLOR="1;32"
	HOME_URL="https://www.gentoo.org/"
	SUPPORT_URL="https://www.gentoo.org/support/"
	BUG_REPORT_URL="https://bugs.gentoo.org/"
	VERSION_ID="2.13"
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x70f) [0x4d28cf]
		_ZN13CrashReporter18createAndSaveCrashEi
		??:?
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x47037c]
		_Z25handleUnrecoverableSignali
		??:?
	#2 | /lib64/libc.so.6(+0x37f20) [0x7fa06986bf20]
		??
		??:0
	#3 | /lib64/libc.so.6(+0x83b0c) [0x7fa0698b7b0c]
		??
		??:0
	#4 | /lib64/libc.so.6(gsignal+0x12) [0x7fa06986be82]
		??
		??:0
	#5 | /lib64/libc.so.6(abort+0xc5) [0x7fa06985649f]
		??
		??:0
	#6 | /lib64/libc.so.6(+0x223d5) [0x7fa0698563d5]
		??
		??:0
	#7 | /lib64/libc.so.6(+0x30ef2) [0x7fa069864ef2]
		??
		??:0
	#8 | /usr/lib64/libwlroots.so.12032(+0x39721) [0x7fa06a19b721]
		??
		??:0
	#9 | /usr/lib64/libwlroots.so.12032(+0x3876e) [0x7fa06a19a76e]
		??
		??:0
	#10 | /usr/lib64/libwlroots.so.12032(wlr_render_texture_with_matrix+0x36) [0x7fa06a196266]
		??
		??:0
	#11 | /usr/lib64/libwlroots.so.12032(wlr_output_render_software_cursors+0x288) [0x7fa06a1b4048]
		??
		??:0
	#12 | Hyprland(_ZN13CHyprRenderer13renderMonitorEP8CMonitor+0x574) [0x5880c4]
		_ZN13CHyprRenderer13renderMonitorEP8CMonitor
		??:?
	#13 | Hyprland(_Z13handleWrappedP11wl_listenerPv+0x2b) [0x50c21b]
		_Z13handleWrappedP11wl_listenerPv
		??:?
	#14 | /usr/lib64/libwayland-server.so.0(wl_signal_emit_mutable+0x6c) [0x7fa06a1407ac]
		??
		??:0
	#15 | /usr/lib64/libwayland-server.so.0(wl_event_loop_dispatch_idle+0x1b) [0x7fa06a1424ab]
		??
		??:0
	#16 | /usr/lib64/libwayland-server.so.0(wl_event_loop_dispatch+0x21e) [0x7fa06a1426ee]
		??
		??:0
	#17 | /usr/lib64/libwayland-server.so.0(wl_display_run+0x25) [0x7fa06a140275]
		??
		??:0
	#18 | Hyprland(main+0x421) [0x462181]
		main
		??:?
	#19 | /lib64/libc.so.6(+0x238b7) [0x7fa0698578b7]
		??
		??:0
	#20 | /lib64/libc.so.6(__libc_start_main+0x85) [0x7fa069857975]
		??
		??:0
	#21 | Hyprland(_start+0x21) [0x470231]
		_start
		??:?


Log tail:
[LOG] Callback 860960 -> 860958, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 1d01840 -> 1d01838, Toplevel removed.
[LOG] Callback 1d017d8 -> 1d017d0, Toplevel removed.
[LOG] Callback 1d018a8 -> 1d018a0, Toplevel removed.
[LOG] Callback 1d01980 -> 1d01978, CWLSurface removed.
[LOG] CWLSurface 1d01950 called destroy()
[LOG] Callback 1d012f8 -> 1d012f0, CWindow removed.
[LOG] Window 1d01200 destroyed, queueing. (class )
[LOG] Callback 1d01290 -> 1d01288, XDG Window removed.
[LOG] Callback 1d01360 -> 1d01358, XDG Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Showing the cursor (timeout)
[LOG] Cleanup: destroyed a window
[LOG] Keybind triggered, calling dispatcher (64, , 96)
[LOG] Executing WAYLAND_DISPLAY=wayland-1 bookmark
[LOG] Process Created with pid 6619
[LOG] New LayerSurface has no preferred monitor. Assigning Monitor DP-2
[LOG] Registered signal for owner 85db10: c10d18 -> 85dcf0 (owner: layerSurface)
[LOG] Registered signal for owner 85db10: c4b950 -> 85dbb8 (owner: layerSurface)
[LOG] Registered signal for owner 85db10: c4b960 -> 85dc20 (owner: layerSurface)
[LOG] Registered signal for owner 85db10: c4b970 -> 85dc88 (owner: layerSurface)
[LOG] Registered signal for owner 85db10: c4b980 -> 85dd58 (owner: layerSurface)
[LOG] LayerSurface c4b890 (namespace rofi layer 3) created on monitor DP-2
[LOG] LayerSurface 1c5cb20 arranged: x: 0 y: 0 w: 1280 h: 720 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 1cae690 arranged: x: 0 y: 0 w: 1280 h: 720 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] LayerSurface c4b890 mapped
[LOG] Registered signal for owner 85db30: c10d38 -> 85db38 (owner: CWLSurface)
[LOG] CWLSurface 85db30 called init()
[LOG] LayerSurface 1c5cb20 arranged: x: 0 y: 0 w: 1280 h: 720 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 1cae690 arranged: x: 320 y: 177 w: 640 h: 366 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Set keyboard focus to surface c10a50
[LOG] LayerSurface 1c5cb20 arranged: x: 0 y: 0 w: 1280 h: 720 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 1cae690 arranged: x: 320 y: 177 w: 640 h: 366 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] LayerSurface c4b890 unmapped
[LOG]  [hookSystem] New hook event registered: closeLayer
[LOG] Framebuffer created, status 36053
[LOG] Callback 85db60 -> 85db58, CWLSurface removed.
[LOG] CWLSurface 85db30 called destroy()
[LOG] LayerSurface c4b890 destroyed
[LOG] Callback 85dd18 -> 85dd10, layerSurface removed.
[LOG] Callback 85dbe0 -> 85dbd8, layerSurface removed.
[LOG] Callback 85dc48 -> 85dc40, layerSurface removed.
[LOG] Callback 85dcb0 -> 85dca8, layerSurface removed.
[LOG] Callback 85dd80 -> 85dd78, layerSurface removed.
[LOG] LayerSurface 1c5cb20 arranged: x: 0 y: 0 w: 1280 h: 720 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
```

**Comment by emrakyz** [comment] 2023-06-01 06:55
Probably. I use below Hyprland version now without a problem:
51a930f802c71a0e67f05e7b176ded74e8e95f87 dirty ().
Tag: v0.26.0

**Comment by vaxerski** [comment] 2023-06-01 07:45
wlr issue and dupe of #2404

**Closed by vaxerski** 2023-06-01 07:45 UTC
Labels: bug
