### ISSUE TITLE
Annoying SIGBUS.

### ISSUE THREAD

**Issue by nimaaskarian** [hyprwm/Hyprland#2970] opened 2023-08-14 10:21 UTC
### Hyprland Version

Hyprland, built from branch main at commit 46cf4eb837c39255f24fa32b5a740c28ce1a324f dirty (Nix: bump wlroots).

### Bug or Regression?

Bug

### Description

I use [lbonn's rofi](https://github.com/lbonn/rofi). After a while of using it with my scripts (some of them are python scripts), I get this `zsh: bus error (core dumped)  rofi` when I try to run rofi.
Same error (`zsh: bus error (core dumped)  hyprpicker -r -z`) when I try to run `hyprpicker -r -z`.
 I can't trace the root of this issue, I have no idea how to reproduce it. It's been happening since 0.26 I think.
 I've googled a **** ton and haven't find the answer.
 I tried these and they didn't work:
- restarting Hyprland
- not using any DM (I use ly usually)
and these ones "fix" the issue:
- rebooting
- using Xorg (there is no problem inside Xorg, but when I kill it and run Hyprland again, same issue)

### How to reproduce

NO IDEA

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12333741/hyprland.log)
[script that I think it might be the cause of this issue](https://raw.githubusercontent.com/nimaaskarian/dotfiles/master/.config/hypr/scripts/wall/theme-selector.py)
[hyprland config](https://raw.githubusercontent.com/nimaaskarian/dotfiles/master/.config/hypr/hyprland.conf)
[portal.sh (exec onced in hyprland config)](https://raw.githubusercontent.com/nimaaskarian/dotfiles/master/.config/hypr/scripts/portal.sh)

**Comment by vaxerski** [comment] 2023-08-14 12:35
build hyprpicker in debug and provide a stacktrace

**Comment by nimaaskarian** [comment] 2023-08-14 13:08
built it in debug mode. How can I provide a stacktrace?

**Comment by nimaaskarian** [comment] 2023-08-17 16:18
Sorry for the late response.
- Output of `coredumpctl info [PID]`
[coredumpctl-info.txt](https://github.com/hyprwm/Hyprland/files/12371512/coredumpctl-info.txt)
- Two last lines of `coredumpctl debug [PID]`
[coredumpctl-debug.txt](https://github.com/hyprwm/Hyprland/files/12371530/coredumpctl-debug.txt)

**Comment by nimaaskarian** [comment] 2023-08-18 07:21
I try not to shutdown/reboot so I can include any further info that can help as soon as possible

**Comment by memchr** [comment] 2023-08-20 05:47
> Annoying issue of dbus

@nimaaskarian Are you sure it is dbus that is causing the problem? `SIGBUS` is **utterly unrelated** to `dbus`. It is a hardware induced error. 

> notifying an operating system (OS) that a process is trying to access memory that the CPU cannot physically address: an invalid address for the address bus

Please see 
- https://en.wikipedia.org/wiki/Bus_error
- https://stackoverflow.com/a/212585/20494689

**Comment by memchr** [comment] 2023-08-20 05:55
Would you mind checking what the average memory usage is compared to the total available memory (excluding swap)? Does this happen when your system is close to OOM?

**Comment by nimaaskarian** [comment] 2023-08-20 21:36
> > Annoying issue of dbus
> 
> @nimaaskarian Are you sure it is dbus that is causing the problem? `SIGBUS` is **utterly unrelated** to `dbus`. It is a hardware induced error.
> 
> > notifying an operating system (OS) that a process is trying to access memory that the CPU cannot physically address: an invalid address for the address bus
> 
> Please see
> 
> * https://en.wikipedia.org/wiki/Bus_error
> * https://stackoverflow.com/a/212585/20494689

I didn't know that. So I'm changing the issues title. guess its never late to learn!

**Comment by nimaaskarian** [comment] 2023-08-20 21:38
> Would you mind checking what the average memory usage is compared to the total available memory (excluding swap)? Does this happen when your system is close to OOM?

I will monitor with this in mind and share the results.

**Comment by memchr** [comment] 2023-08-21 04:15
> I will monitor with this in mind and share the results.

One common such tool is `atop`, which continuously tracks your memory usage. After installation, you can start it by `systemctl start atop`

Another method is to log the output of vmstat
```bash
vmstat -n 1 43200 | systemd-cat -t vmstat
```
- This command will check memory usage, etc. for exactly 1 second, 43200 times (12 hours), and pipe the output to journald, which can be viewed with `journalctl -t vmstat'.

**Comment by memchr** [comment] 2023-09-04 16:11
In that case, the problem is not related to Hyprland. If you wish, I think it would be appropriate to close this issue and take the discussion of memory issues elsewhere.

The most obvious answer is: **Increase physical memory**. Softare solution is no ultimate salvation to memory predicament.

Increasing the swap size might also save the day, depending on your workload. However, swap is not extra memory.

Another thing you can try is to use an OOM deamon, such as [earlyoom](https://github.com/rfjakob/earlyoom), and configure it to kill insignificant peasants such as web browser or emacs, before the system OOM kicks in, thus saving the compositor from its doomed fate where all children are killed.

earlyoom can be configured to inform you via a notification demon when it has killed a process.

**Comment by vaxerski** [comment] 2023-09-04 16:22
closing, oom

**Closed by vaxerski** 2023-09-04 16:22 UTC
Labels: bug

**Comment by nimaaskarian** [comment] 2023-09-09 09:53
I was running a script with fcron and that was the problem it seems. 
It had nothing to do with OOM.
