### ISSUE TITLE
Issue with Window Dragging: Not as Smooth as in Sway

### ISSUE THREAD

**Issue by Edgars-Cirulis** [hyprwm/Hyprland#2223] opened 2023-05-03 17:12 UTC
Hello there, upon closer looking, it seems that the window dragging is experiencing frame skips. It also feels like there are skipped frames when dragging the windows. 

I am not experiencing this issue in Sway.

Hyprland version; v0.25.0

**Comment by vaxerski** [comment] 2023-05-03 17:31
what if you disable animations on them with `misc:animate_mouse_windowdragging = false`

**Comment by Edgars-Cirulis** [comment] 2023-05-03 19:21
> what if you disable animations on them with `misc:animate_mouse_windowdragging = false`

Doesn't disabling animations in general wouldn't it disables this too?

**Comment by vaxerski** [comment] 2023-05-03 20:04
I think it would, but try disabling that explicitly too, we're debugging here.

**Comment by romanstingler** [comment] 2023-06-30 08:47
I can't reproduce it as well. 
@Edgars-Cirulis can you build the latest version and test again?

**Comment by MightyPlaza** [comment] 2023-09-04 18:05
@vaxerski this should have been fixed with the performance improvements, right?

**Comment by vaxerski** [comment] 2023-09-04 19:47
no clue. maybe. I think it's safe to close this

**Closed by vaxerski** 2023-09-04 19:47 UTC
Labels: bug
