### ISSUE TITLE
Mouse disappears with camera ungrab in WoW

### ISSUE THREAD

**Issue by umop3plsdn** [hyprwm/Hyprland#6188] opened 2024-05-22 12:19 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit fd35b35000fa11ce540d944966ff17c71c31fd27  (keybinds: fix pass).
Date: Sun May 12 11:01:01 2024
Tag: v0.40.0-72-gfd35b350, commits: 4678

flags: (if any)


System Information:
System name: Linux
Node name: hyperion
Release: 6.9.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When clicking and grabbing the screen to move the camera in WoW either with double click grab or single left click grab and hold when you release the mouse the cursor stays in a disappeared state. The mouse is still working though because the invisible cursor highlights over things and briefly bringing the mouse out of the WoW window and directly back brings it right back. This isn't that big of deal it doesn't happen in Sway and I can just open that if I want to play just thought it should be reported

### How to reproduce

Left click grab to adjust camera view or Double click Grab to walk while adjusting the camera and it happens with the release.

**Comment by BenCarmichael01** [comment] 2024-05-22 14:35
Duplicate of #5975. Fixed in git

**Closed** 2024-05-22 19:47 UTC
Labels: bug

**Comment by Thrithralas** [comment] 2024-05-23 02:14
The issue still persists (at least in the case of WoW) on NixOS even after building from master as a flake input.
