### ISSUE TITLE
Maximizing a window with noborder window rule does not update the gap

### ISSUE THREAD

**Issue by wxlyyy** [hyprwm/Hyprland#7141] opened 2024-08-01 18:46 UTC
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ab0a3268e04f2295ec4455be90ce8d0c2b107b8d  ().
Date: 2024-08-01
Tag: , commits: ab0a3268e04f2295ec4455be90ce8d0c2b107b8d

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.10.1-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  560.28.03  Release Build  (nixbld@)  Tue Jul 30 13:38:34 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240731.9f918d6"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:

======Config-Start======


Config File: /home/super6/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/j8l2v22xypah1srykhwjlkgwwgdxnnpw-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$layers=^(wleave|swaync-control-center)$
$mainMod=SUPER
animations {
  bezier=overshot, 0.05, 0.7, 0.1, 1
  animation=windows, 1, 3, overshot, popin 60%
  animation=fade, 1, 2.5, overshot
  animation=workspaces, 1, 3.5, overshot, slide
}

decoration {
  blur {
    brightness=1
    contrast=1
    noise=0.01
    passes=4
    size=5
  }
  col.shadow=rgba(00000044)
  rounding=10
  shadow_offset=0 2
  shadow_range=15
  shadow_render_power=6
}

dwindle {
  preserve_split=true
}

general {
  border_size=3
  col.active_border=rgb(bd93f9)
  col.inactive_border=rgba(44475aaa)
  gaps_in=3
  gaps_out=5
  resize_on_border=true
}

gestures {
  workspace_swipe=true
}

misc {
  animate_manual_resizes=true
  animate_mouse_windowdragging=true
  disable_autoreload=true
  disable_hyprland_logo=true
  force_default_wallpaper=0
  no_direct_scanout=false
  vrr=1
}

xwayland {
  force_zero_scaling=true
}
bind=$mainMod, Q, killactive
bind=$mainMod, F, fullscreen
bind=$mainMod, W, fullscreen, 1
bind=$mainMod, S, togglesplit
bind=$mainMod, T, togglefloating
bind=$mainMod, Escape, exec, wleave -fp layer-shell
bind=$mainMod, Return, exec, kitty
bind=$mainMod, D, exec, thunar
bind=$mainMod, A, exec, walker
bind=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=, XF86MonBrightnessUp, exec, busctl --user call rs.wl-gammarelay / rs.wl.gammarelay UpdateBrightness d 0.05
bind=, XF86MonBrightnessDown, exec, busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateBrightness d -0.05
bind=, XF86AudioPlay, exec, playerctl play-pause
bind=, XF86AudioNext, exec, playerctl next
bind=, XF86AudioPrev, exec, playerctl previous
bind=, Print, exec, wlr-which-key
bind=, Pause, exec, hyprfreeze -a
bind=$mainMod, left, movefocus, l
bind=$mainMod, right, movefocus, r
bind=$mainMod, up, movefocus, u
bind=$mainMod, down, movefocus, d
bind=$mainMod+SHIFT, left, movewindow, l
bind=$mainMod+SHIFT, right, movewindow, r
bind=$mainMod+SHIFT, up, movewindow, u
bind=$mainMod+SHIFT, down, movewindow, d
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod+SHIFT, 1, movetoworkspace, 1
bind=$mainMod+SHIFT, 2, movetoworkspace, 2
bind=$mainMod+SHIFT, 3, movetoworkspace, 3
bind=$mainMod+SHIFT, 4, movetoworkspace, 4
bind=$mainMod+SHIFT, 5, movetoworkspace, 5
bind=$mainMod+SHIFT, 6, movetoworkspace, 6
bind=$mainMod+SHIFT, 7, movetoworkspace, 7
bind=$mainMod+SHIFT, 8, movetoworkspace, 8
bind=$mainMod+SHIFT, 9, movetoworkspace, 9
bind=$mainMod+SHIFT, 0, movetoworkspace, 10
bind=$mainMod, mouse_up, workspace, e-1
bind=$mainMod, mouse_down, workspace, e+1
binde=$mainMod+CTRL, left, resizeactive, -20 0
binde=$mainMod+CTRL, right, resizeactive, 20 0
binde=$mainMod+CTRL, up, resizeactive, 0 -20
binde=$mainMod+CTRL, down, resizeactive, 0 20
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow
env=MOZ_USE_XINPUT2, 1
env=SWWW_TRANSITION, grow
env=RUNEWIDTH_EASTASIAN, 0
env=TERMINAL_COMMAND, kitty
env=ELECTRON_OZONE_PLATFORM_HINT, auto
env=HYPRCURSOR_THEME, bibata-hyprcursor
env=HYPRCURSOR_SIZE, 24
env=NVD_BACKEND, direct
env=MOZ_DISABLE_RDD_SANDBOX, 1
env=AQ_DRM_DEVICES, /dev/dri/card1
exec-once=waybar
exec-once=fcitx5
exec-once=swww-daemon
exec-once=blueman-applet
exec-once=solaar -w hide
exec-once=nm-applet --indicator
exec-once=wl-clip-persist -c regular
exec-once=/nix/store/190746d1p2k5y9md9d25fx25a980l9b9-polkit-gnome-0.105/libexec/polkit-gnome-authentication-agent-1
layerrule=blur, $layers
layerrule=ignorezero, $layers
monitor=eDP-1, preferred, auto, 1, bitdepth, 10
monitor=desc:ICD Inc GE278URX 1234567890123, preferred, auto, 2, bitdepth, 10
windowrulev2=noborder, fullscreen:1
windowrulev2=bordercolor rgb(ff5555), xwayland:1
windowrulev2=dimaround, class:^(ssh-askpass)$
windowrulev2=dimaround, class:^(xdg-desktop-portal-gtk)$
windowrulev2=dimaround, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2=pin, class:^(wl-gammarelay-applet)$
windowrulev2=float, class:^(wl-gammarelay-applet)$
windowrulev2=noborder, class:^(wl-gammarelay-applet)$
windowrulev2=move cursor -50% 10%, class:^(wl-gammarelay-applet)$
windowrulev2=pin, title:^(Picture-in-Picture|画中画)$
windowrulev2=float, title:^(Picture-in-Picture|画中画)$

======Config-End========
```

</details>

### Description

Maximizing a window with noborder window rule does not update the gap

### How to reproduce

windowrulev2=noborder, fullscreen:1
bind=$mainMod, W, fullscreen, 1

**Comment by MightyPlaza** [comment] 2024-08-01 19:57
very likely dupe of https://github.com/hyprwm/Hyprland/issues/7138

**Comment by MightyPlaza** [comment] 2024-08-01 20:15
should work after 8c02b3c267198541dd03601e4c7ff7d870197728
so it's likely dupe https://github.com/hyprwm/Hyprland/issues/7138

**Closed** 2024-08-01 21:16 UTC
Labels: bug

**Comment by wxlyyy** [comment] 2024-08-02 02:00
> should work after [8c02b3c](https://github.com/hyprwm/Hyprland/commit/8c02b3c267198541dd03601e4c7ff7d870197728) so it's likely dupe #7138

No, it doesn't work.

**Comment by wxlyyy** [comment] 2024-08-02 05:36
Maybe it’s more intuitive to express it with a video

https://github.com/user-attachments/assets/a0752c37-5303-4f97-b623-5971cef7c2cd

**Comment by MightyPlaza** [comment] 2024-08-02 10:51
> > should work after [8c02b3c](https://github.com/hyprwm/Hyprland/commit/8c02b3c267198541dd03601e4c7ff7d870197728) so it's likely dupe #7138
> 
> No, it doesn't work.

what version did you test?

**Comment by wxlyyy** [comment] 2024-08-02 10:54
> > > 之后工作 [应该在8c02b3c ](https://github.com/hyprwm/Hyprland/commit/8c02b3c267198541dd03601e4c7ff7d870197728)，所以它可能是骗人的 [#7138 ](https://github.com/hyprwm/Hyprland/issues/7138)
> > 
> > 
> > 不，这不起作用。
> 
> 你测试了什么版本？

Hyprland, built from branch  at commit 09bb5658b7fa6c0dc4e2744797e51ad4dd25af42  ().
Date: 2024-08-01
Tag: , commits: 09bb5658b7fa6c0dc4e2744797e51ad4dd25af42

**Comment by MightyPlaza** [comment] 2024-08-02 11:08
> > > > 之后工作 [应该在8c02b3c ](https://github.com/hyprwm/Hyprland/commit/8c02b3c267198541dd03601e4c7ff7d870197728)，所以它可能是骗人的 [#7138 ](https://github.com/hyprwm/Hyprland/issues/7138)
> > > 
> > > 
> > > 不，这不起作用。
> > 
> > 
> > 你测试了什么版本？
> 
> ```
> Hyprland, built from branch  at commit 09bb5658b7fa6c0dc4e2744797e51ad4dd25af42  ().
> Date: 2024-08-01
> Tag: , commits: 09bb5658b7fa6c0dc4e2744797e51ad4dd25af42
> ```

like I said it has to be either 8c02b3c267198541dd03601e4c7ff7d870197728 or 95959789b7667172b2b2f37f78fe96ac196e9cd3, both should work
after that it will be broken like described in the other issue
