### ISSUE TITLE
special workspace missing some fundamental usecases of scratchpads

### ISSUE THREAD

**Issue by Aneeqasif** [hyprwm/Hyprland#1119] opened 2022-11-27 19:23 UTC
so the current behavior of **putting any number of  windows** in **only one** special workspace that can float in or out , that hyprland's special workspace provide can be really really useful no doubts in that , but its is not  very usual or natural use-case, if some one would want to have a bunch of different windows they can just use another workspace , the use-case where scratchpads really shines is it gives you ability to have different programs in different scratchpads that someone can access with different key binding. if we can have similar functionality in hyprland it would be very very nice.

for example i put my note taking app , a terminal , a file browser, and ncmpcpp in different scratchpads and i does not want any of them to be coupled in same scratchpad or (painfully) all in one scratchpad.
i hope  i explained my point as well as my broken english allow me to do so.
at the end i want to say thanks for developing this software :heart:

**Comment by vaxerski** [comment] 2022-11-27 21:26
dupe of #612

**Closed by vaxerski** 2022-11-27 21:26 UTC
Labels: enhancement
