### ISSUE TITLE
Hyprland breaks Waybar IPC(?)

### ISSUE THREAD

**Issue by flippette** [hyprwm/Hyprland#5841] opened 2024-05-02 13:57 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 56de72f357222beca94e3d4f8152e2523a22c0b3  (internal: store matched windowrules and emit event).
Date: Thu May 2 03:18:01 2024
Tag: v0.39.1-124-g56de72f3, commits: 4584

flags: (if any)


System Information:
System name: Linux
Node name: okinawa
Release: 6.8.8-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:30 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

I have `hyprland/workspaces` and `hyprland/window` in my Waybar config.

With the AUR `hyprland-git` package version `0.39.1.r124.56de72f3-1`, starting Waybar from a terminal running on Hyprland does not show the modules, and logs this into the terminal:

```
~ ❯ waybar
[2024-05-02 20:52:52.060] [info] Using configuration file /home/flippette/.config/waybar/config
[2024-05-02 20:52:52.061] [info] Discovered appearance 'dark'
[2024-05-02 20:52:52.061] [info] Using CSS file /home/flippette/.config/waybar/style.css
[2024-05-02 20:52:52.063] [info] Hyprland IPC starting
[2024-05-02 20:52:52.063] [error] Hyprland IPC: Unable to connect?
[2024-05-02 20:52:52.064] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/56de72f357222beca94e3d4f8152e2523a22c0b3_1714657518_92406599/.socket.sock. (3)
[2024-05-02 20:52:52.064] [warning] module hyprland/workspaces: Disabling module "hyprland/workspaces", Error parsing JSON: * Line 1, Column 1
  Syntax error: value, object or array expected.

[2024-05-02 20:52:52.064] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/56de72f357222beca94e3d4f8152e2523a22c0b3_1714657518_92406599/.socket.sock. (3)
[2024-05-02 20:52:52.064] [warning] module hyprland/window: Disabling module "hyprland/window", Error parsing JSON: * Line 1, Column 1
  Syntax error: value, object or array expected.

[2024-05-02 20:52:52.179] [info] Bar configured (width: 1920, height: 36) for output: DP-2

** (waybar:4606): WARNING **: 20:52:52.179: Status Notifier Item with bus name ':1.16' and object path '/org/ayatana/NotificationItem/udiskie' is already registered

** (waybar:4606): WARNING **: 20:52:52.179: Status Notifier Item with bus name ':1.14' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered

** (waybar:4606): WARNING **: 20:52:52.458: Status Notifier Item with bus name ':1.16' and object path '/org/ayatana/NotificationItem/udiskie' is already registered

** (waybar:4606): WARNING **: 20:52:52.458: Status Notifier Item with bus name ':1.14' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
^C[2024-05-02 20:52:53.539] [info] Quitting.
```

Inspection of `$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/` shows that `.socket.sock` does not exist:

```
~ ❯ ll $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE
.rw-r--r--   15 flippette  2 May 20:45  hyprland.lock
.rw-r--r-- 3.0k flippette  2 May 20:45  hyprland.log
```

### How to reproduce

This is the relevant section of my Waybar config:

```
{
  "modules-left": [
    "hyprland/workspaces",
    "hyprland/window"
  ]
}
```

Here are the package versions I'm using (`pacman -Qi <pkg>`):

- `waybar`: `0.10.2-1`
- `hyprland-git`: `0.39.1.r124.56de72f3-1` (from Chaotic AUR)

**Comment by fufexan** [comment] 2024-05-02 14:03
Duplicate of https://github.com/hyprwm/Hyprland/issues/5825. Use waybar-git until a new release is made.

**Closed** 2024-05-02 14:03 UTC
Labels: bug
