### ISSUE TITLE
weird mouse issues in games after update to 0.29

### ISSUE THREAD

**Issue by loissascha** [hyprwm/Hyprland#3109] opened 2023-08-30 07:35 UTC
### Hyprland Version

0.29.0

### Bug or Regression?

Bug

### Description

I realised after updating to the newest version I encounter some mouse issues for some games especially with fullscreen window mode. 

For example:
In World of Warcraft when in fullscreen window mode holding down the right or left mouse button (to move the camera) doesn't keep the mouse cursor to the game. As soon as I release the mouse button the cursor goes off to some other screen and the game loses focus. This only happens in fullscreen window, in normal window mode it works. 

In Minecraft (entered fullscreen mode with F11) I can move around freely without the mouse going off to another screen but as soon as I enter any menu where the mouse is visible (escape menu, inventory, etc) the mouse goes off to another screen.

I also briefly tried cyberpunk to see how it would react in a "real" fullscreen game and I didn't notice any issues there. Pressing escape keeps my mouse in game no matter how much I moved it before. 

### How to reproduce

Test with any of the above mentioned games or probably any other with fullscreen window mode (not sure about that one)

**Comment by dev-null-undefined** [comment] 2023-08-30 11:14
I had been experiencing the same issue with minecraft as well.
Interesting note: as long as you don't move your mouse when in game and immediately jump out to some menu (inventory, escape menu) the mouse stays where it was with no issue.
As soon as you move even a little it jumps at least for me to the primary monitor (0x0) and moves by the amount that I moved in the game.

**Comment by dev-null-undefined** [comment] 2023-08-30 11:16
Probably related to #3028

**Comment by vaxerski** [comment] 2023-08-30 11:32
dupe of #3028

**Closed by vaxerski** 2023-08-30 11:32 UTC
Labels: bug
