### ISSUE TITLE
AQ HL doesn't start on my ancient Notebook [ERR] [EGL] Command eglCreateContext errored out with EGL_BAD_ATTRIBUTE (0x12292): eglCreateContext

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#6973] opened 2024-07-22 11:01 UTC
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
5979ceb56b165ee35809a0eeda5f4be1aedbb7b6
```

</details>

### Description

I installed hyprland-git via AUR and on my old notebook it fails to start.

### How to reproduce

It has only a dedicated GPU no intel GPU

### Crash reports, logs, images, videos

[hyprlandCrashReport635.txt](https://github.com/user-attachments/files/16331917/hyprlandCrashReport635.txt)

**Comment by vaxerski** [comment] 2024-07-22 11:19
is this legacy_renderer?

**Comment by vaxerski** [comment] 2024-07-22 11:19
[patch.txt](https://github.com/user-attachments/files/16332107/patch.txt)
try this

**Comment by romanstingler** [comment] 2024-07-22 12:37
Unfortunately, no
[hyprlandCrashReport12833.txt](https://github.com/user-attachments/files/16333080/hyprlandCrashReport12833.txt)
[inxi.txt](https://github.com/user-attachments/files/16333081/inxi.txt)

**Comment by vaxerski** [comment] 2024-07-22 14:40
again, is this legacy renderer?

also try this
[patch.txt](https://github.com/user-attachments/files/16335554/patch.txt)

**Comment by ShadowS0ng** [comment] 2024-07-22 17:53
> again, is this legacy renderer?
> 
> also try this [patch.txt](https://github.com/user-attachments/files/16335554/patch.txt)

Hello vaxry, I tried both these patches on integrated and nvidia without success. 
i'm have a intel HD4000 
and nvidia GT740m GPUs

**Comment by vaxerski** [comment] 2024-07-22 17:54
can someone answer my damn question

**Comment by romanstingler** [comment] 2024-07-22 18:14
in my case I didn't build with legacyrenderer, I can try 

I just 
```
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
make all && sudo make install
```

**Comment by ShadowS0ng** [comment] 2024-07-22 20:23
> can someone answer my damn question

ok , i tried the second patch with a manual legacyrenderer build and it worked

**Comment by vaxerski** [comment] 2024-07-22 20:29
what if you comment out lines 137 and 138 in opengl.cpp?

**Comment by Micovec** [comment] 2024-07-22 21:00
> what if you comment out lines 137 and 138 in opengl.cpp?

I got very similar error on newer commit.

I can confirm that the second patch and commenting out those two lines works. I can run Hyprland. I still got some errors in the log about drm but nothing critical.

**Comment by vaxerski** [comment] 2024-07-22 21:04
odd, why doesn't your EGL impl not support debug true? anyways, gpu drivers...

**Comment by vaxerski** [comment] 2024-07-22 21:05
please check if it works now

**Comment by romanstingler** [comment] 2024-07-22 21:43
without the patch and removing these 2 lines 
```
    attrs.push_back(EGL_CONTEXT_OPENGL_DEBUG);
    attrs.push_back(ISDEBUG ? EGL_TRUE : EGL_FALSE);
```
it fails
 `[ERR] [EGL] Command eglCreateContext errored out with EGL_BAD_MATCH (0x12297): dri2_create_context`
[hyprlandCrashReport3406.txt](https://github.com/user-attachments/files/16339669/hyprlandCrashReport3406.txt)

When I apply the second patch (patch-3.txt) and remove the 2 lines and build the legacyrenderer then HL starts.

strange, because `hyperland-git` from before AQ worked on this machine and there shouldn't be the legacyrenderer build as far as I know. 

for now, it doesn't matter, Vaxry we still love you :P

**Comment by Micovec** [comment] 2024-07-22 21:53
I don't know what happened but commit [7c68236](https://github.com/hyprwm/Hyprland/commit/7c68236a51291e71db04233d04eae65f4ebd594f) doesn't work. I tried to rebuild it twice and the result is still the same.

[hyprlandCrashReport569.txt](https://github.com/user-attachments/files/16340080/hyprlandCrashReport569.txt)

**Comment by ShadowS0ng** [comment] 2024-07-22 21:58
> please check if it works now

in my case it doesn't work when i comment out the mentioned lines. 
with the patch, it works but some things like blur doesn't work . also i get this error in logs when i exit hyprland:
> IOT instruction (core dump) Hyprlandrom display: Broken pipeadd_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group) could not connect to wayland server 
i think it may be related to AGS and not Hyprland

**Comment by Micovec** [comment] 2024-07-22 22:01
It seems like I commented different lines. I commented out 

> I don't know what happened but commit [7c68236](https://github.com/hyprwm/Hyprland/commit/7c68236a51291e71db04233d04eae65f4ebd594f) doesn't work. I tried to rebuild it twice and the result is still the same.
> 
> [hyprlandCrashReport569.txt](https://github.com/user-attachments/files/16340080/hyprlandCrashReport569.txt)

I commented out [these lines](https://github.com/hyprwm/Hyprland/blob/3c758db95c129ed6ca7ce0c1b5b82ad6e189488d/src/render/OpenGL.cpp#L136-L137)

**Comment by vaxerski** [comment] 2024-07-22 22:02
legacyrenderer is broken thats why blur no work

@Micovec odd... does your driver support gles3.2?

**Comment by Micovec** [comment] 2024-07-22 22:08
Not sure how to check that. glxinfo says:

```
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 24.1.4-arch1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

If you could please direct me where to check that.

**Comment by romanstingler** [comment] 2024-07-22 22:12
to add more info, my card /driver is 3.1, as I said for me, it is not crucial

**Comment by vaxerski** [comment] 2024-07-22 22:18
yea both of you have drivers too old for gles3.2, I'm confused as to how it worked before

**Comment by Micovec** [comment] 2024-07-22 22:22
I've had some problems with blurs not working. For example in hyprlock or special workspaces, there was no blur. But I didn't think much of it since I'm using arch only because I want to check out Hyprland (on which I'm almost a year on) and I'm not skilled in linux world.

**Comment by vaxerski** [comment] 2024-07-23 11:44
both of you have GPUs too old to run hyprland without legacy_renderer, and on legacy IIRC blur is broken. Life is life. Closing as solved

**Closed by vaxerski** 2024-07-23 11:44 UTC
Labels: bug

**Comment by ShadowS0ng** [comment] 2024-07-23 12:54
> both of you have GPUs too old to run hyprland without legacy_renderer, and on legacy IIRC blur is broken. Life is life. Closing as solved

is there any chance you can make this work later? i mean it was working before moving to aquamarine :(

**Comment by vaxerski** [comment] 2024-07-23 14:12
no clue.

**Comment by ShadowS0ng** [comment] 2024-07-23 14:51
> no clue.

ok , I hope you fine a way, ty for great work btw.

**Comment by romanstingler** [comment] 2024-07-23 16:28
wlroots has a GLES2 renderer which was used, and on my machine it detected EGL1.4 correctly, 
sorry but I have no deep knowledge about wlroots internals. 
And on my side I am using my machines for work, so I have all animations and blur disabled. 
One could argue that I could use something else, but we love Vaxry.  :P 

[hyprland.log](https://github.com/user-attachments/files/16351644/hyprland.log)

**Comment by vaxerski** [comment] 2024-07-23 16:29
but hyprland always used GLES3.2, so I am confused as to how that worked.

**Comment by romanstingler** [comment] 2024-07-23 16:50
Could it be that for soem reason, magically it fallbacks to GLES2 (legacy)? 
Is there a way to find out what renderer is used?

**Comment by ShadowS0ng** [comment] 2024-07-23 17:41
> Could it be that, for some reason, magically it fallbacks to GLES2 (legacy)? Is there a way to find out what renderer is used?

this or maybe there's some translation going on in wlroots?(i'm not familiar with rendering stuff so maybe the translation thing is stupid)

**Comment by vaxerski** [comment] 2024-07-23 20:51
no, we use gles3 extensions...

**Comment by ShadowS0ng** [comment] 2024-07-24 11:57
> Changing OpenGL.cpp L137
> 
> ```
>     attrs.push_back(EGL_CONTEXT_MINOR_VERSION);
>     attrs.push_back(2);
> ```
> 
> to 0 works for me (3.0 support), I don't know how "correct" it is to do that, but i guess not specifying it before is how it worked? (Mesa/OpenGL fallbacks??)

I commented out these two lines and normal release build now works without problem.(L136,  L137). nice job
@vaxerski

**Comment by vaxerski** [comment] 2024-07-24 12:03
Generally, I always check what I use for compatibilty against GLES3.2. If anything breaks, you're on your own.

**Comment by Dickby** [comment] 2024-07-29 12:11
@vaxerski  before the switch to aquamarine, my laptop would run hyprland without problem.
It's EGL version 3.0
Setting Minor version to 0 works, but if that's not garanteed for the future, do we really want to restrict hyprland to newer hardware?

**Comment by vaxerski** [comment] 2024-07-29 12:21
EGL has no 3.0, pretty sure you mean GLES 3.0

3.2 is already almost 10 years old... I can roll back the needed ver to 3.0 but I am unsure about what might break due to this. I don't check extensions for 3.0 compat, only 3.2

**Comment by vaxerski** [comment] 2024-07-29 12:23
there, rolled it back. For 3.2-compliant drivers this shouldn't change anything AFAIK

**Comment by Dickby** [comment] 2024-07-29 12:42
Love you, thanks

**Comment by Micovec** [comment] 2024-07-29 16:39
Thanks Vaxry, you're the best.
