### ISSUE TITLE
Hyprland crash after systemctl suspend on nvidia

### ISSUE THREAD

**Issue by IronRevelation** [hyprwm/Hyprland#2228] opened 2023-05-03 20:17 UTC
Hyprland does crash after doing systemctl suspend.
I have a nvidia gpu and I'm using the hyprland-nvidia-git package.
This is the last part of the hyprland log:
```
[LOG] Callback 555df68f32b0 -> 555df68f32a8, layerSurface removed.
[LOG] Callback 555df68f3178 -> 555df68f3170, layerSurface removed.
[LOG] Callback 555df68f31e0 -> 555df68f31d8, layerSurface removed.
[LOG] Callback 555df68f3248 -> 555df68f3240, layerSurface removed.
[LOG] Callback 555df68f3318 -> 555df68f3310, layerSurface removed.
[LOG] LayerSurface 555df9c7b8a0 arranged: x: 0 y: 0 w: 1920 h: 50 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 555df6c35470 arranged: x: 0 y: 0 w: 1920 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-1 layers arranged: reserved: 0.000000 50.000000 0.000000 0.000000
[LOG] Searching for matching rules for org.telegram.desktop (title: Telegram (1865119))
[LOG] Window rule monitor HDMI-A-1 ->  class: ^(org.telegram.desktop)$ matched 555df6ba3dd0 [Telegram (1865119)]
[LOG] Window rule workspace 25 ->  class: ^(org.telegram.desktop)$ matched 555df6ba3dd0 [Telegram (1865119)]
[LOG] Window rule opacity 0.8 0.8 ->  class: ^(org.telegram.desktop)$ matched 555df6ba3dd0 [Telegram (1865119)]
[LOG] Window 555df6ba3dd0 set title to Telegram (1865119)
[LOG] Callback 555df69f63a8 -> 555df69f63a0, Keyboard removed.
[LOG] Callback 555df69f6270 -> 555df69f6268, Keyboard removed.
[LOG] Callback 555df69f62d8 -> 555df69f62d0, Keyboard removed.
[LOG] Callback 555df69f6340 -> 555df69f6338, Keyboard removed.
[LOG] Destroyed keyboard 555df69f6240
[LOG] Callback 555df69facf8 -> 555df69facf0, Mouse removed.
[LOG] Callback 555df6834b18 -> 555df6834b10, Keyboard removed.
[LOG] Callback 555df68349e0 -> 555df68349d8, Keyboard removed.
[LOG] Callback 555df6834a48 -> 555df6834a40, Keyboard removed.
[LOG] Callback 555df6834ab0 -> 555df6834aa8, Keyboard removed.
[LOG] Destroyed keyboard 555df68349b0
[LOG] Callback 555df6ada538 -> 555df6ada530, Keyboard removed.
[LOG] Callback 555df6ada400 -> 555df6ada3f8, Keyboard removed.
[LOG] Callback 555df6ada468 -> 555df6ada460, Keyboard removed.
[LOG] Callback 555df6ada4d0 -> 555df6ada4c8, Keyboard removed.
[LOG] Destroyed keyboard 555df6ada3d0
[LOG] Callback 555df5cbc3c8 -> 555df5cbc3c0, Keyboard removed.
[LOG] Callback 555df5cbc290 -> 555df5cbc288, Keyboard removed.
[LOG] Callback 555df5cbc2f8 -> 555df5cbc2f0, Keyboard removed.
[LOG] Callback 555df5cbc360 -> 555df5cbc358, Keyboard removed.
[LOG] Destroyed keyboard 555df5cbc260
[LOG] Callback 555df68da368 -> 555df68da360, Mouse removed.
[LOG] Callback 555df69bc138 -> 555df69bc130, Keyboard removed.
[LOG] Callback 555df69bc000 -> 555df69bbff8, Keyboard removed.
[LOG] Callback 555df69bc068 -> 555df69bc060, Keyboard removed.
[LOG] Callback 555df69bc0d0 -> 555df69bc0c8, Keyboard removed.
[LOG] Destroyed keyboard 555df69bbfd0
[LOG] Callback 555df694f028 -> 555df694f020, Mouse removed.
[LOG] Callback 555df6aa15f8 -> 555df6aa15f0, Keyboard removed.
[LOG] Callback 555df6aa14c0 -> 555df6aa14b8, Keyboard removed.
[LOG] Callback 555df6aa1528 -> 555df6aa1520, Keyboard removed.
[LOG] Callback 555df6aa1590 -> 555df6aa1588, Keyboard removed.
[LOG] Destroyed keyboard 555df6aa1490
[LOG] Callback 555df6a2f918 -> 555df6a2f910, Keyboard removed.
[LOG] Callback 555df6a2f7e0 -> 555df6a2f7d8, Keyboard removed.
[LOG] Callback 555df6a2f848 -> 555df6a2f840, Keyboard removed.
[LOG] Callback 555df6a2f8b0 -> 555df6a2f8a8, Keyboard removed.
[LOG] Destroyed keyboard 555df6a2f7b0
[LOG] Callback 555df681fd38 -> 555df681fd30, Keyboard removed.
[LOG] Callback 555df681fc00 -> 555df681fbf8, Keyboard removed.
[LOG] Callback 555df681fc68 -> 555df681fc60, Keyboard removed.
[LOG] Callback 555df681fcd0 -> 555df681fcc8, Keyboard removed.
[LOG] Destroyed keyboard 555df681fbd0
[LOG] Callback 555df6a688e8 -> 555df6a688e0, Keyboard removed.
[LOG] Callback 555df6a687b0 -> 555df6a687a8, Keyboard removed.
[LOG] Callback 555df6a68818 -> 555df6a68810, Keyboard removed.
[LOG] Callback 555df6a68880 -> 555df6a68878, Keyboard removed.
[LOG] Destroyed keyboard 555df6a68780
[LOG] Callback 555df69831c8 -> 555df69831c0, Keyboard removed.
[LOG] Callback 555df6983090 -> 555df6983088, Keyboard removed.
[LOG] Callback 555df69830f8 -> 555df69830f0, Keyboard removed.
[LOG] Callback 555df6983160 -> 555df6983158, Keyboard removed.
[LOG] Destroyed keyboard 555df6983060
[LOG] Callback 555df6734738 -> 555df6734730, Keyboard removed.
[LOG] Callback 555df6734600 -> 555df67345f8, Keyboard removed.
[LOG] Callback 555df6734668 -> 555df6734660, Keyboard removed.
[LOG] Callback 555df67346d0 -> 555df67346c8, Keyboard removed.
[LOG] Destroyed keyboard 555df67345d0
[LOG] Session got activated!
[LOG] Session got activated!
[LOG] Applying monitor rule for HDMI-A-1
[LOG] Not applying a new rule to HDMI-A-1 because it's already applied!
[LOG] LayerSurface 555df9c77c30 arranged: x: 1920 y: 170 w: 1920 h: 50 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 555df6c35490 arranged: x: 1920 y: 170 w: 1920 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor HDMI-A-1 layers arranged: reserved: 0.000000 50.000000 0.000000 0.000000
[LOG] Applying monitor rule for DP-1
[LOG] Not applying a new rule to DP-1 because it's already applied!
[LOG] LayerSurface 555df9c7b8a0 arranged: x: 0 y: 0 w: 1920 h: 50 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 555df6c35470 arranged: x: 0 y: 0 w: 1920 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-1 layers arranged: reserved: 0.000000 50.000000 0.000000 0.000000
[LOG] Cleanup: destroyed a layersurface
[CRITICAL] Hyprland has crashed :( Consult the crash report at /home/mattia/.hyprland/hyprlandCrashReport1671.txt for more information.
```
This is the crash report:
[hyprlandCrashReport1671.txt](https://github.com/hyprwm/Hyprland/files/11390879/hyprlandCrashReport1671.txt)

This is my config:
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/11390883/hyprland.txt)

**Comment by vaxerski** [comment] 2023-05-03 20:26
dupe of #1728

**Closed by vaxerski** 2023-05-03 20:26 UTC
Labels: bug
