### ISSUE TITLE
Hyprland crashes after turning monitor off and on

### ISSUE THREAD

**Issue by wotikama** [hyprwm/Hyprland#3619] opened 2023-10-19 20:42 UTC
### Hyprland Version

Hyprland, built from branch main at commit 54e1c2ccbdfa6dfade63221b5df02bf8578d96a6 dirty (fix(build): do not include wlr headers directly, use includes.hpp instead. (3587)). Tag: v0.31.0-1-g54e1c2cc  flags: (if any)

### Bug or Regression?

Bug

### Description

Simple: 
I turn monitor off
OR 
swayidle -w t
            timeout 600 'hyprctl dispatch dpms off'  \
            resume 'hyprctl dispatch dpms on'  &

and hyprland crashes 

### How to reproduce

-Turn monitor off 

### Crash reports, logs, images, videos

[hyprlandCrashReport700.txt](https://github.com/hyprwm/Hyprland/files/13047624/hyprlandCrashReport700.txt)

**Comment by andresilva** [comment] 2023-10-30 15:30
This is very likely a duplicate of #3637 and #3422. IMO you should close this issue and post your report in one of those issues.

**Comment by vaxerski** [comment] 2023-10-30 16:11
ye

**Closed by vaxerski** 2023-10-30 16:11 UTC
Labels: bug
