### ISSUE TITLE
drop-down list disappears immediately

### ISSUE THREAD

**Issue by nikalexey** [hyprwm/Hyprland#6698] opened 2024-06-28 10:14 UTC
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit b7f42a1e88a5b6c9d2dbdba31e0f35f6a02461e7  (keybinds: fix move to prev ws, moved to same mon (6688)).
Date: Fri Jun 28 01:20:50 2024
Tag: v0.41.2-7-gb7f42a1e, commits: 4893

flags: (if any)


System Information:
System name: Linux
Node name: kntspc
Release: 6.9.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/knt/.config/hypr/hyprland.conf: Read Succeeded
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/myprograms.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/look_and_feel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindingss.conf
source = ~/.config/hypr/conf/windows.conf

Config File: /home/knt/.config/hypr/conf/monitors.conf: Read Succeeded
################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1


Config File: /home/knt/.config/hypr/conf/myprograms.conf: Read Succeeded
###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = terminator
$fileManager = thunar # dolphin
$menu = wofi --show drun


Config File: /home/knt/.config/hypr/conf/autostart.conf: Read Succeeded
#################
### AUTOSTART ###
#################

# Core components (authentication, lock screen, notification daemon)
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
exec-once = hyprpm reload

#exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

exec-once = swaybg -i ~/.config/archlinux_wp.jpg
exec-once = waybar
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = [workspace 1 silent;noanim] firefox
exec-once = [workspace 3 silent;noanim] $terminal
exec-once = [workspace 9 silent;noanim] ticktick
exec-once = [workspace 9 silent;noanim] obsidian.sh
exec-once = swaync
# exec-once = nextcloud --background

Config File: /home/knt/.config/hypr/conf/environment.conf: Read Succeeded
#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland,x11
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland



Config File: /home/knt/.config/hypr/conf/look_and_feel.conf: Read Succeeded
#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 0
    gaps_out = 0

    border_size = 1

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        
        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
#animations {
#    enabled = true
#    bezier = linear, 0, 0, 1, 1
#    bezier = md3_standard, 0.2, 0, 0, 1
#    bezier = md3_decel, 0.05, 0.7, 0.1, 1
#    bezier = md3_accel, 0.3, 0, 0.8, 0.15
#    bezier = overshot, 0.05, 0.9, 0.1, 1.1
#    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92 
#    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
#    bezier = fluent_decel, 0.1, 1, 0, 1
#    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
#    bezier = easeOutCirc, 0, 0.55, 0.45, 1
#    bezier = easeOutExpo, 0.16, 1, 0.3, 1
#    animation = windows, 1, 3, md3_decel, popin 60%
#    animation = border, 1, 10, default
#    animation = fade, 1, 2.5, md3_decel
#    animation = workspaces, 1, 3.5, easeOutExpo, slide
#    animation = specialWorkspace, 1, 3, md3_decel, slidevert
#}


animations {
    enabled = false
}

#
#    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
#
#    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
#
#    animation = windows, 1, 7, myBezier
#    animation = windowsOut, 1, 7, default, popin 80%
#    animation = border, 1, 10, default
#    animation = borderangle, 1, 8, default
#    animation = fade, 1, 7, default
#    animation = workspaces, 1, 6, default
#}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

#gestures {
#    workspace_swipe = false
#}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
#master {
#    new_is_master = true
#}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}


Config File: /home/knt/.config/hypr/conf/input.conf: Read Succeeded
#############
### INPUT ###
#############

input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle,grp_led:caps,grp:switch
}

# https://wiki.hyprland.org/Configuring/Variables/#input
# input {
#   kb_layout = us,ru
#    kb_variant =
#    kb_model =
#    kb_options =
#    kb_rules =

#    follow_mouse = 1

#    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

#    touchpad {
#        natural_scroll = false
#    }
#}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


Config File: /home/knt/.config/hypr/conf/keybindingss.conf: Read Succeeded
####################
### KEYBINDINGSS ###
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal 
bind = $mainMod, C, killactive,
bind = $mainMod SHIFT CTRL, Q, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = , Print, exec, XDG_CURRENT_DESKTOP=sway flameshot gui 
bind = SHIFT, Print, exec, ~/.config/hypr/scripts/screenshot.sh
bind = CTRL, Print, exec, grim -g "$(slurp)" - | tee >(swappy -f - -o "$(xdg-user-dir PICTURES)/ss/$(date +'%I:%M_%b_%d-Sel.png')") | wl-copy
bind = $mainMod ALT, V, exec, ~/.config/hypr/scripts/toggle_vpn.sh


bind = $mainMod SHIFT, B, exec, killall -SIGUSR2 waybar # Reload waybar

bind = $mainMod, L, exec, hyprlock # Lock the screen
bind = $mainMod, F, fullscreen, 2
bind = $mainMod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind = $mainMod, W, exec, swaync-client -t -sw


# Move focus with mainMod + arrow keys
#bind = $mainMod, left, movefocus, l
#bind = $mainMod, right, movefocus, r
#bind = $mainMod, up, movefocus, u
#bind = $mainMod, down, movefocus, d
bind = ALT, TAB, cyclenext, next
bind = ALT SHIFT, TAB, cyclenext, prev
bind = $mainMod, TAB, cyclenext, next
bind = $mainMod SHIFT, TAB, cyclenext, prev

#Volume
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% # Increase volume by 5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% # Reduce volume by 5%
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle # Toggle mute


# resize
bind = $mainMod ALT, left, resizeactive,-100 0
bind = $mainMod ALT, right, resizeactive,100 0
bind = $mainMod ALT, up, resizeactive,0 -40
bind = $mainMod ALT, down, resizeactive, 0 40

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod, left, workspace, e-1
bind = $mainMod, right, workspace, e+1
bind = $mainMod, grave, workspace, previous

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# resize submap (mode)
bind = $mainMod,T,submap,resize
submap = resize
binde = $mainMod, SHIFT L,resizeactive,40 0
binde = ,H,resizeactive,-40 0
binde = ,K,resizeactive,0 -40
binde = ,J,resizeactive,0 40
bind = ,escape,submap,reset
bind = ,Return,submap,reset
submap = reset


Config File: /home/knt/.config/hypr/conf/windows.conf: Read Succeeded
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# firefox Picture-in-Picture
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = pin,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = fakefullscreen,class:^(firefox)$,title:^(Picture-in-Picture)$
# firefox figma micro indicator
windowrulev2 = fakefullscreen,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$
windowrulev2 = float,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$

windowrulev2 = float,class:^(doublecmd)$,title:^(Options)$
windowrulev2 = float,class:^(doublecmd)$,title:^([0-9]*% Copying.*)$
windowrulev2 = float,title:^(.*)(Deleting)(.*)$


# Dialogs
windowrule=float,title:^(Open File)(.*)$
windowrule=float,title:^(Select a File)(.*)$
windowrule=float,title:^(Choose wallpaper)(.*)$
windowrule=float,title:^(Open Folder)(.*)$
windowrule=float,title:^(Save As)(.*)$
windowrule=float,title:^(Library)(.*)$
windowrule=float,title:^(File Upload)(.*)$
windowrulev2 = float,title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

windowrule=float,title:^(galculator)(.*)$
windowrule=float,title:^(Qalculate!)(.*)$

# No shadow for tiled windows
windowrulev2 = noshadow,floating:0

# Telegram media viewer
windowrulev2 = fullscreen,class:^(org.telegram.desktop)$,title:^(Media viewer)$
# windowrulev2 = workspace unset,class:^(org.telegram.desktop)$,title:^(Media viewer)$
# windowrulev2 = monitor 1,class:^(org.telegram.desktop)$,title:^(Media viewer)$

======Config-End========
```

</details>

### Description

The drop-down list appears for a moment and then disappears immediately.

I tried to run it on plasma (wayland) where everything works as it should.
### How to reproduce

run orca-slicer and try open any dropdown list

### Crash reports, logs, images, videos

[2024-06-28_13-06-1719569272.webm](https://github.com/hyprwm/Hyprland/assets/6259541/1e741803-d868-471a-b6e1-eeb88122cea3)

**Comment by vaxerski** [comment] 2024-06-28 16:47
is it running in xwayland

**Comment by MagneFire** [comment] 2024-06-29 10:56
Yes, it seems they are forcing this: https://github.com/SoftFever/OrcaSlicer/blob/v2.1.1/src/OrcaSlicer.cpp#L1049

**Comment by nikalexey** [comment] 2024-06-29 12:47
Can you please recommend where I should look next?

**Comment by RandomLegend** [comment] 2024-06-29 17:55
I am facing the exact same issue. Running the latest OrcaSlicer 2.1.1 Appimage.

**Comment by MagneFire** [comment] 2024-06-29 20:43
I've done some testing. It seems that https://github.com/hyprwm/Hyprland/commit/2566d818848b58b114071f199ffe944609376270 introduced this behaviour.

**Comment by MightyPlaza** [comment] 2024-07-02 13:41
additionally dupe of https://github.com/hyprwm/Hyprland/issues/6616

**Comment by RandomLegend** [comment] 2024-07-02 16:13
> not sure about the regression but you could try `noinitialfocus` window rule for the popup

Can you help me to set this up?

i put this into my windowrules.conf
windowrulev2 = noinitialfocus, class:^(OrcaSlicer)$

but the behavior is the same.

**Comment by MightyPlaza** [comment] 2024-07-02 16:15
check the class/title with `socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock`

**Comment by RandomLegend** [comment] 2024-07-02 17:18
did that and the result is:

```
activewindow>>OrcaSlicer,
activewindowv2>>56100cfcd260
windowtitle>>56100e44f1d0
openwindow>>56100e44f1d0,2,OrcaSlicer,orca-slicer
activewindow>>,
activewindowv2>>
closewindow>>56100e44f1d0
openwindow>>56100cfcf2a0,2,OrcaSlicer,orca-slicer
```

but with both of them ruled via:
```
windowrulev2 = noinitialfocus, class:^(OrcaSlicer)$
windowrulev2 = noinitialfocus, class:^(orca-slicer)$
```

it still doesn't work

**Comment by MagneFire** [comment] 2024-07-02 17:43
> did that and the result is:
> 
> ```
> activewindow>>OrcaSlicer,
> activewindowv2>>56100cfcd260
> windowtitle>>56100e44f1d0
> openwindow>>56100e44f1d0,2,OrcaSlicer,orca-slicer
> activewindow>>,
> activewindowv2>>
> closewindow>>56100e44f1d0
> openwindow>>56100cfcf2a0,2,OrcaSlicer,orca-slicer
> ```
> 
> but with both of them ruled via:
> 
> ```
> windowrulev2 = noinitialfocus, class:^(OrcaSlicer)$
> windowrulev2 = noinitialfocus, class:^(orca-slicer)$
> ```
> 
> it still doesn't work

I can't get this to work either. I've tried variations of the following window rules:
```
windowrulev2 = nofocus,title:^(.*orca-slicer.*)$
windowrulev2 = noinitialfocus,title:^(.*orca-slicer.*)$
windowrulev2 = suppressevent activate,title:^(.*orca-slicer.*)$
windowrulev2 = suppressevent activatefocus,title:^(.*orca-slicer.*)$
windowrulev2 = stayfocused,title:^(.*orca-slicer.*)$
windowrulev2 = focusonactivate,title:^(.*orca-slicer.*)$
```

**Comment by ssvx** [comment] 2024-07-04 14:48
Same issue present in the **Swiftpoint X1 Control Panel - EXPERIMENTAL LINUX VERSION 3.0.7.2**

AppImage can be acquired here:
https://support.swiftpoint.com/portal/en/community/topic/x1-control-panel-experimental-linux-version-18-7-2023

The Hyprland IPC provides only empty strings on the popup:

```
activewindow>>x1cp,Swiftpoint X1 Control Panel - EXPERIMENTAL LINUX VERSION 3.0.7.2
activewindowv2>>5f6a7a6b7650
windowtitle>>5f6a7a729780
windowtitle>>5f6a7a729780
urgent>>5f6a7a729780
activewindow>>,
activewindowv2>>
windowtitle>>5f6a7a729780
windowtitle>>5f6a7a729780
openwindow>>5f6a7a729780,10,x1cp,x1cp
closewindow>>5f6a7a729780
```

The openwindow "x1cp" part usually says "Swiftpoint X1 Control Panel" but i've renamed that binary to "x1cp".

Looking at https://github.com/hyprwm/Hyprland/commit/2566d818848b58b114071f199ffe944609376270 i see "activate" being added there: `g_pXWayland->pWM->activateSurface(self.lock(), activate);`

So i've added this to my hyprland.conf
`windowrulev2 = suppressevent activate,class:x1cp`

At least in the X1 Control Panel the popups now seem to work - not _always_, but _most_ of the time. If i'm not mistaken, the first click never works but the second one on the same drop down does. On the click that works these two lines seem to be missing on the socat output:

```
activewindow>>,
activewindowv2>>
```

Maybe this can be fixed by making sure there's no empty _stuff_ being worked on?

**Comment by xdevs23** [comment] 2024-07-06 16:31
I'm on Orca Slicer 2.1.1 and just encountered this issue today.
![image](https://github.com/hyprwm/Hyprland/assets/6959245/1fbf21c3-f996-42ec-9b7d-47c32f0ca511)

```
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)
```

This is super annoying as I can't change the profiles anymore.

**Comment by Notarin** [comment] 2024-07-07 18:47
Been messing with this, this is the solution I have so far, buggy, but technically works:
```
windowrulev2 = stayfocused, class:^(OrcaSlicer)$,title:^()$
```
I will inform if I discover anything else

**Comment by Notarin** [comment] 2024-07-07 19:38
It appears I was slightly wrong, so slight correction, pressing the button to open the drop-down for whatever reason de-focuses the window, before then focusing the drop-down menu, therefore as previously stated, preventing the drop-down from being focused yields no results.
```
# Focusing Orca Slicer
activewindow>>OrcaSlicer,
activewindowv2>>6319a55d78a0
# Window Defocused, IOW now nothing is focused (This is what makes the mother window decide to close all drop-downs)
activewindow>>,
activewindowv2>>
# The drop-down menu is focused
activewindow>>OrcaSlicer,orca-slicer
activewindowv2>>6319a5361cf0
# The drop-down menu is spawned
openwindow>>6319a5361cf0,2,OrcaSlicer,orca-slicer
# The drop-down menu is instantly killed (As a result of the mother window losing focus earlier, its just now caught up)
closewindow>>6319a5361cf0
# Focus returns to Orca Slicer
activewindow>>OrcaSlicer,
activewindowv2>>6319a55d78a0
```
So the solution isn't preventing focus from *moving*, but rather preventing whatever's causing the total loss of focus during the transition of focus from the mother window to the drop-down.

**Comment by Notarin** [comment] 2024-07-07 21:57
Update, found some neat tidbits.
The reason it is deselecting the mother window is because it is trying to focus the window before it exists, which fails a logic check, and it proceeds to instead focus *nothing*, or more accurately, `XCB_WINDOW_NONE`.
https://github.com/hyprwm/Hyprland/blob/22138ac259b2f4253be29311f6b60fbd675074b4/src/Compositor.cpp#L914
https://github.com/hyprwm/Hyprland/blob/22138ac259b2f4253be29311f6b60fbd675074b4/src/xwayland/XWM.cpp#L880-L882
If you ask me, it should abort the activate operation leaving it how it was before rather than deselecting everything.
I'll have to poke around and see if I can find out why it's attempting to activate the window before it exists.

**Comment by xdevs23** [comment] 2024-07-21 10:31
I still keep having to install 0.41.1 just to use OrcaSlicer. Is this fixable? Is it maybe possible to just revert the change that broke it or does it introduce other regressions?

**Comment by vaxerski** [comment] 2024-07-21 14:56
as you can see, it's marked for fixing for 0.42, be patient.

**Comment by xdevs23** [comment] 2024-07-21 15:04
> as you can see, it's marked for fixing for 0.42, be patient.

Oh I didn't see that, I apologize for the impatience.

**Comment by tradiff** [comment] 2024-07-21 15:23
@xdevs23 while you wait, there is another work around if you need it, but it comes with it's own problems. I believe discovered by MPDarkGuy on discord, you can run OrcaSlicer using gamescope and dropdowns will work.

For me this has additional problems though, it crashes pretty soon, I believe with an OOM. So my strategy has been to juggle between OrcaSlicer and gamescope OrcaSlicer depending on whether I need to use a menu. Saving often because of the crash. Very much looking forward to running 0.42 :smile:

**Closed** 2024-07-21 15:27 UTC
Labels: bug
