### ISSUE TITLE
System crashed randomly

### ISSUE THREAD

**Issue by rustysys-dev** [hyprwm/Hyprland#4615] opened 2024-02-04 13:42 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Not actually sure why it happened, went to get coffee after printing a page successfully (likely not related) and then when i came back I was met with my login screen. 

### How to reproduce

not sure, I didn't really do anything major... 

### Crash reports, logs, images, videos

```
Stack trace of thread 1024:
#0  0x00007f15459cd834 __pthread_kill_implementation (libc.so.6 + 0x90834)
#1  0x00007f154597b8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007f15459638ff abort (libc.so.6 + 0x268ff)
#3  0x00005605d3340082 _Z25handleUnrecoverableSignali (Hyprland + 0xcf082)
#4  0x00007f154597b9a0 __restore_rt (libc.so.6 + 0x3e9a0)
#5  0x00007f153f072301 crocus_emit_mi_flush (crocus_dri.so + 0x1672301)
#6  0x00007f153f0e4b65 crocus_state_finish_batch (crocus_dri.so + 0x16e4b65)
#7  0x00007f153f07e198 _crocus_batch_flush (crocus_dri.so + 0x167e198)
#8  0x00007f153f06f32c crocus_fence_flush (crocus_dri.so + 0x166f32c)
#9  0x00007f153e0e62de tc_flush (crocus_dri.so + 0x6e62de)
#10 0x00007f153dbc0207 st_glFlush (crocus_dri.so + 0x1c0207)
#11 0x00007f153dd07102 _mesa_make_current (crocus_dri.so + 0x307102)
#12 0x00007f153dbdbc1b st_api_make_current (crocus_dri.so + 0x1dbc1b)
#13 0x00007f153db0accf dri_unbind_context (crocus_dri.so + 0x10accf)
Module libwayland-client.so.0 from rpm wayland-1.22.0-2.fc39.x86_64
Module libwayland-server.so.0 from rpm wayland-1.22.0-2.fc39.x86_64
Module Hyprland from rpm hyprland-0.34.0-4.fc39.x86_64
Module Hyprland from rpm hyprland-0.34.0-4.fc39.x86_64
Stack trace of thread 1024:
#0  0x00007f15459cd834 __pthread_kill_implementation (libc.so.6 + 0x90834)
#1  0x00007f154597b8ee raise (libc.so.6 + 0x3e8ee)
Stack trace of thread 1024:
Stack trace of thread 1024:
#0  0x00007f15459cd834 __pthread_kill_implementation (libc.so.6 + 0x90834)
#1  0x00007f154597b8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007f15459638ff abort (libc.so.6 + 0x268ff)
#3  0x00005605d3340082 _Z25handleUnrecoverableSignali (Hyprland + 0xcf082)
#4  0x00007f154597b9a0 __restore_rt (libc.so.6 + 0x3e9a0)
#5  0x00007f153f072301 crocus_emit_mi_flush (crocus_dri.so + 0x1672301)
#6  0x00007f153f0e4b65 crocus_state_finish_batch (crocus_dri.so + 0x16e4b65)
#7  0x00007f153f07e198 _crocus_batch_flush (crocus_dri.so + 0x167e198)
#8  0x00007f153f06f32c crocus_fence_flush (crocus_dri.so + 0x166f32c)
#9  0x00007f153e0e62de tc_flush (crocus_dri.so + 0x6e62de)
#10 0x00007f153dbc0207 st_glFlush (crocus_dri.so + 0x1c0207)
#11 0x00007f153dd07102 _mesa_make_current (crocus_dri.so + 0x307102)
#12 0x00007f153dbdbc1b st_api_make_current (crocus_dri.so + 0x1dbc1b)
#13 0x00007f153db0accf dri_unbind_context (crocus_dri.so + 0x10accf)
#14 0x00007f153db0e762 driUnbindContext (crocus_dri.so + 0x10e762)
#15 0x00007f154443b9b9 dri2_make_current (libEGL_mesa.so.0 + 0x209b9)
#16 0x00007f154442bf03 eglMakeCurrent (libEGL_mesa.so.0 + 0x10f03)
#17 0x00007f154635c42d InternalLoseCurrent (libEGL.so.1 + 0x542d)
#18 0x00005605d3490a99 wlr_egl_restore_context (Hyprland + 0x21fa99)
#19 0x00005605d3497961 gles2_texture_update_from_buffer.lto_priv.0 (Hyprland + 0x226961)
#20 0x00005605d34d118c surface_commit_state (Hyprland + 0x26018c)
#21 0x00007f1545e81056 ffi_call_unix64 (libffi.so.8 + 0x9056)
#22 0x00007f1545e7d5ef ffi_call_int.lto_priv.0 (libffi.so.8 + 0x55ef)
#23 0x00007f1545e803fe ffi_call (libffi.so.8 + 0x83fe)
#24 0x00007f1546493843 wl_closure_invoke.constprop.0 (libwayland-server.so.0 + 0x9843)
#25 0x00007f15464980b4 wl_client_connection_data (libwayland-server.so.0 + 0xe0b4)
#26 0x00007f15464968e2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xc8e2)
#27 0x00007f1546497125 wl_display_run (libwayland-server.so.0 + 0xd125)
#28 0x00005605d3329425 main (Hyprland + 0xb8425)
#29 0x00007f154596514a __libc_start_call_main (libc.so.6 + 0x2814a)
#30 0x00007f154596520b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
#31 0x00005605d333de35 _start (Hyprland + 0xcce35)

Stack trace of thread 1056:
#0  0x00007f15459c8169 __futex_abstimed_wait_common (libc.so.6 + 0x8b169)
#1  0x00007f15459cab09 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8db09)
#2  0x00007f1545cdc1e0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0xdc1e0)
#3  0x00005605d33fc65f _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN9CWatchdogC4EvEUlvE_EEEEE6_M_runEv >
#4  0x00007f1545ce31e3 execute_native_thread_routine (libstdc++.so.6 + 0xe31e3)
#5  0x00007f15459cb897 start_thread (libc.so.6 + 0x8e897)
#6  0x00007f1545a526fc __clone3 (libc.so.6 + 0x1156fc)

Stack trace of thread 1063:
#0  0x00007f15459c8169 __futex_abstimed_wait_common (libc.so.6 + 0x8b169)
#1  0x00007f15459cab09 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8db09)
#2  0x00007f153db6e53d cnd_wait (crocus_dri.so + 0x16e53d)
#3  0x00007f153db4d3ab util_queue_thread_func (crocus_dri.so + 0x14d3ab)
#4  0x00007f153db6e46c impl_thrd_routine (crocus_dri.so + 0x16e46c)
#5  0x00007f15459cb897 start_thread (libc.so.6 + 0x8e897)
#6  0x00007f1545a526fc __clone3 (libc.so.6 + 0x1156fc)

Stack trace of thread 1065:
#0  0x00007f15459c8169 __futex_abstimed_wait_common (libc.so.6 + 0x8b169)
#1  0x00007f15459cab09 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8db09)
#2  0x00007f153db6e53d cnd_wait (crocus_dri.so + 0x16e53d)
#3  0x00007f153db4d3ab util_queue_thread_func (crocus_dri.so + 0x14d3ab)
#4  0x00007f153db6e46c impl_thrd_routine (crocus_dri.so + 0x16e46c)
#5  0x00007f15459cb897 start_thread (libc.so.6 + 0x8e897)
#6  0x00007f1545a526fc __clone3 (libc.so.6 + 0x1156fc)

Stack trace of thread 1064:
#0  0x00007f15459c8169 __futex_abstimed_wait_common (libc.so.6 + 0x8b169)
#1  0x00007f15459cab09 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8db09)
#2  0x00007f153db6e53d cnd_wait (crocus_dri.so + 0x16e53d)
#3  0x00007f153db4d3ab util_queue_thread_func (crocus_dri.so + 0x14d3ab)
#4  0x00007f153db6e46c impl_thrd_routine (crocus_dri.so + 0x16e46c)
#5  0x00007f15459cb897 start_thread (libc.so.6 + 0x8e897)
#6  0x00007f1545a526fc __clone3 (libc.so.6 + 0x1156fc)

Stack trace of thread 1066:
#0  0x00007f1545a54304 accept4 (libc.so.6 + 0x117304)
#1  0x00005605d341ba97 _ZZN13CEventManager11startThreadEvENKUlvE_clEv (Hyprland + 0x1aaa97)
#2  0x00007f1545ce31e3 execute_native_thread_routine (libstdc++.so.6 + 0xe31e3)
#3  0x00007f15459cb897 start_thread (libc.so.6 + 0x8e897)
#4  0x00007f1545a526fc __clone3 (libc.so.6 + 0x1156fc)
ELF object binary architecture: AMD x86-64
```

**Comment by vaxerski** [comment] 2024-02-04 15:44
looks like a mesa bug to me?

**Comment by killown** [comment] 2024-02-05 23:11
First, make sure to test kernel LTS, kernel 6.7.x is very unstable with amd gpu for some people.

**Comment by umop3plsdn** [comment] 2024-02-14 22:55
> First, make sure to test kernel LTS, kernel 6.7.x is very unstable with amd gpu for some people.

Ya I can confirm with my rx 590 the kernel upgrade is constantly dumping core

**Comment by vaxerski** [comment] 2024-02-14 22:56
closing

**Closed by vaxerski** 2024-02-14 22:56 UTC
Labels: bug
