### ISSUE TITLE
hyprland-session.service broken

### ISSUE THREAD

**Issue by mylinuxforwork** [hyprwm/Hyprland#8515] opened 2024-11-18 19:17 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Just installed yay -S hyprland to 0.45.1
Hyprland isn't starting anymore. 

The reason is the broken /usr/lib/systemd/usr/hyprland-session.service

[Service]
Type=notify
ExecStart=/usr//usr/bin/Hyprland
ExecStop=/usr//usr/bin/hyprctl dispatch exit
ExecStopPost=systemctl --user unset-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP
Restart=on-failure
Slice=session.slice

The ExecStart and ExecStop paths are wrong. 

### How to reproduce

Install 0.45.1 and try to start Hyprland with sddm or Hyprland command.

**Comment by mylinuxforwork** [comment] 2024-11-18 19:26
Changed the paths to /usr/bin/ but Hyprland isn't starting anymore. Works perfectly with 045.1-1. Any ideas?

**Comment by fufexan** [comment] 2024-11-18 19:28
Duplicate of https://github.com/hyprwm/Hyprland/issues/8340. Use [UWSM](https://wiki.hyprland.org/Useful-Utilities/Systemd-start/) instead.

Also 0.45.1 no longer contains the service file. That may be a leftover from previous versions.

**Closed by fufexan** 2024-11-18 19:28 UTC
Labels: bug

**Comment by mylinuxforwork** [comment] 2024-11-18 19:33
> Duplicate of #8340. Use [UWSM](https://wiki.hyprland.org/Useful-Utilities/Systemd-start/) instead.
> 
> Also 0.45.1 no longer contains the service file. That may be a leftover from previous versions.

Thanks. I will test it. But this has a really big impact. Especially if only Hyprland is installed as the one DE. 

I think, a super easy step by step guide is required to explain this new setup. I am receiving many requests from users with completely broken systems.

**Comment by Neo-29** [comment] 2024-11-18 19:38
What a ridiculous choice they made.
Especially for previous install using sddm
And they are a lot.

**Comment by mylinuxforwork** [comment] 2024-11-18 19:47
Followed your guide in [UWSM](https://wiki.hyprland.org/Useful-Utilities/Systemd-start/) but cannot find the uwsm session for Hyprland in /usr/share/wayland-sessions

How to start Hyprland after installing uwsm with sddm?

**Comment by fufexan** [comment] 2024-11-18 19:55
Make sure Hyprland has been built with systemd support. For some reason it's not automatically detected by meson (iirc the Arch package uses meson), so the flag has to be passed explicitly `-Dsystemd=enabled`, and also `-Duwsm=enabled`. The latter should be auto-enabled if systemd is also enabled though.

**Comment by mylinuxforwork** [comment] 2024-11-18 20:06
> Make sure Hyprland has been built with systemd support. For some reason it's not automatically detected by meson (iirc the Arch package uses meson), so the flag has to be passed explicitly `-Dsystemd=enabled`, and also `-Duwsm=enabled`. The latter should be auto-enabled if systemd is also enabled though.

This is not for beginners. How does existing Hyprland users know that? Arch users are installing or updating Hyprland with sudo pacman -S hyprland resulting in a broken system.  

All of my test systems are broken after running just yay.

Is there a way to make the update to 0.45.1 more user friendly fro Arch and Endeavour users?

**Comment by mylinuxforwork** [comment] 2024-11-18 20:20
Just restarted my Laptop with 0.45.1 with no issues. 

Maybe it's only a KVM VM issue?

**Comment by Neo-29** [comment] 2024-11-18 20:29
> Just restarted my Laptop with 0.45.1 with no issues.
> 
> Maybe it's only a KVM VM issue?

Could be.
I'm on kvm too.
Something to investigate.

**Comment by mylinuxforwork** [comment] 2024-11-18 20:36
> > Is there a way to make the update to 0.45.1 more user friendly fro Arch and Endeavour users?
> 
> Check whether the PKGBUILDS are wrong, and if so, contact the package maintainers. However the systemd meson feature has been available for a long time now, shouldn't cause issues. The `uwsm` feature was added and enabled by default, so that also shouldn't cause issues.
> 
> I have no experience with KVM VMs, so I can't assist there.

Thank you for your feedback. I will create a new Arch Linux VM with Hyprland profile in a VM and will try again.

**Comment by fufexan** [comment] 2024-11-19 06:01
There is a similar report in Nixpkgs https://github.com/hyprwm/aquamarine/issues/109
This seems to be a Hyprland issue related to VMs rather than a service issue.
@gulafaran @UjinT34 can you take a look at the above? Seems it references your commits.

**Comment by Stewart86** [comment] 2024-11-19 06:52
Looks more likely to be a VM issue. I am running @mylinuxforwork dotfiles and install script, with fully updated Arch OS on bare metal without any problem. Was trying to fix a problem that wasn't on my system for the past hours. Here's what I've got.

1. Hyprland Version I am running:
![image](https://github.com/user-attachments/assets/2707488f-6a4c-4006-af25-7215c1ad365d)
2. `uwsm` was not installed
3. installing `uwsm` did nothing.
4. tried 'Hyprland (systemd)` option in sddm, did not load (black screen).
5. however, the normal `Hyprland` option in sddm properly started as usual.

**Comment by Stewart86** [comment] 2024-11-19 07:05
update:
added an entry into sddm `.desktop` file like so:
![image](https://github.com/user-attachments/assets/be5943f2-f54e-494a-a894-6bcc00a403bf)

and started with the new option in sddm without an issue too.
