### ISSUE TITLE
Hyprland crashes / freezes at startup

### ISSUE THREAD

**Issue by Jadefalke256** [hyprwm/Hyprland#2535] opened 2023-06-17 08:15 UTC
Hyprland seems to freeze and/or crash at startup with no error logs. 
I have an nvidia GPU and was told that the driver might be the issue, but downgrading to `530` from `535` did not fix the issue.

The coredump seems to be from killing it manually.
When running in a tty it first stops after loading the config - I use the default one for testing - and then when switching ttys shows these in the logs repeatedly
```
[LOG] Destroyed keyboard 564054d9bd50
[LOG] Callback 564054fb09c8 -> 564054fb09c0, Keyboard removed.
[LOG] Callback 564054fb0890 -> 564054fb0888, Keyboard removed.
[LOG] Callback 564054fb08f8 -> 564054fb08f0, Keyboard removed.
[LOG] Callback 564054fb0960 -> 564054fb0958, Keyboard removed.
[LOG] Destroyed keyboard 564054fb0860
[LOG] Callback 56405507aa48 -> 56405507aa40, Keyboard removed.
[LOG] Callback 56405507a910 -> 56405507a908, Keyboard removed.
[LOG] Callback 56405507a978 -> 56405507a970, Keyboard removed.
[LOG] Callback 56405507a9e0 -> 56405507a9d8, Keyboard removed.
```

coredump:
```
           PID: 625 (Hyprland)
           UID: 1000 (jade)
           GID: 1000 (jade)
        Signal: 6 (ABRT)
     Timestamp: Sat 2023-06-17 09:04:20 CEST (1h 7min ago)
  Command Line: Hyprland
    Executable: /usr/bin/Hyprland
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (jade)
       Boot ID: f2bdd23ca0e647fa80f526a8d4a4dd8f
    Machine ID: ebd10197bdc04483be671a1091ce2097
      Hostname: archlinux
       Storage: /var/lib/systemd/coredump/core.Hyprland.1000.f2bdd23ca0e647fa80f526a8d4a4dd8f.625.1686985460000000.zst (present)
  Size on Disk: 2.7M
       Message: Process 625 (Hyprland) of user 1000 dumped core.

                Stack trace of thread 625:
                #0  0x00007f6b055b226c n/a (libc.so.6 + 0x8926c)
                #1  0x00007f6b05562a08 raise (libc.so.6 + 0x39a08)
                #2  0x00007f6b0554b538 abort (libc.so.6 + 0x22538)
                #3  0x000055df9aa7def1 _Z25handleUnrecoverableSignali (Hyprland + 0x9cef1)
                #4  0x00007f6b05562ab0 n/a (libc.so.6 + 0x39ab0)
                #5  0x00007f6b055b226c n/a (libc.so.6 + 0x8926c)
                #6  0x00007f6b05562a08 raise (libc.so.6 + 0x39a08)
                #7  0x00007f6b0554b538 abort (libc.so.6 + 0x22538)
                #8  0x00007f6b0589ca6f _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9ca6f)
                #9  0x00007f6b058b011c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb011c)
                #10 0x00007f6b058b0189 _ZSt9terminatev (libstdc++.so.6 + 0xb0189)
                #11 0x00007f6b058b03ed __cxa_throw (libstdc++.so.6 + 0xb03ed)
                #12 0x000055df9aa4a6a2 _ZN11CCompositor10initServerEv.cold (Hyprland + 0x696a2)
                #13 0x000055df9aa6e9ee main (Hyprland + 0x8d9ee)
                #14 0x00007f6b0554c850 n/a (libc.so.6 + 0x23850)
                #15 0x00007f6b0554c90a __libc_start_main (libc.so.6 + 0x2390a)
                #16 0x000055df9aa7dd95 _start (Hyprland + 0x9cd95)
                ELF object binary architecture: AMD x86-64
```

**Comment by skulwicki** [comment] 2023-06-17 14:00
Probably a dupe of #2525. Should rollback your Hyprland install to d768226 (commit before the problem started) for the time being until vaxerski gets a chance to look at things.

**Comment by shemig** [comment] 2023-06-17 17:23
Issues 2537 / 2525 where fixed and merged. From the logs you supplied I am not sure this is related. 
Can you update and verify it is fixed, or supply a hyprland.log so we can verify it is related? 
If your log has the following line then it is probably related:
New monitor has no dimensions?? Ignoring

**Closed** 2023-09-16 09:06 UTC
Labels: bug
