### ISSUE TITLE
When moving a window to another workspace using "movetoworkspace", the window has problems.

### ISSUE THREAD

**Issue by counhopig** [hyprwm/Hyprland#5749] opened 2024-04-25 17:55 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ecf282d331a8aa19c0fe10c739cd31d3b3ab64a2 dirty (wlr-foreign-toplevel: move to new impl).
Date: Thu Apr 25 08:10:43 2024
Tag: v0.39.1-77-gecf282d3, commits: 4537

flags: (if any)


System Information:
System name: Linux
Node name: counhopig
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB] [10de:24dc] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c4) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I have archlinux and hyprland installed on my laptop and everything else works fine, but when I try to use "movetoworkspace" to move a window to a specific workspace, I get the following problems:
1: The window disappears from the original workspace and appears in the specified workspace, but its window size does not change.
2: The window will not interact with any windows in the new workspace after it is moved to the new workspace, no matter they are already there or newly added.
3: When I try to use togglefloating to change its style, the first two commands do not respond. It doesn't respond until the third time. At that point, the window returns to normal.
4: If I run togglefloating in the original workspace directly after the movetoworkspace command, the window jumps back.

### How to reproduce

I really dont know how it happen. but I know that it is not happen in my nuc10.
the monitor for my laptop is 2560*1600@165
the monitor for my nuc10 is 1920*1080@60

### Crash reports, logs, images, videos

Uploading 2024-04-26 01-29-45.mp4…

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15118788/hyprland.log)

**Comment by counhopig** [comment] 2024-04-25 17:55
https://github.com/hyprwm/Hyprland/assets/108390459/bb308b25-f6d1-43d6-8a91-64bedd41dc1c

**Comment by bubba-champion** [comment] 2024-04-25 18:08
Dupe of https://github.com/hyprwm/Hyprland/issues/5746. Already fixed in https://github.com/hyprwm/Hyprland/commit/9fc3cb5629bcc006603e4f2f7906c75d393798dc.

**Closed** 2024-04-25 18:32 UTC
Labels: bug
