### ISSUE TITLE
drag and drop doesn't seem to work with applications running under xwayland

### ISSUE THREAD

**Issue by quantenzitrone** [hyprwm/Hyprland#1083] opened 2022-11-23 02:40 UTC
I tested this in sway briefly, and it works, so this must be a Hyprland issue.

**Comment by vaxerski** [comment] 2022-11-24 13:09
what application to test? filezilla works for me perfectly fine.

**Comment by Quantenzitrone** [comment] 2022-11-24 13:17
i tested rox-filer and dolphin (running under xwayland)

**Comment by vaxerski** [comment] 2022-11-24 13:18
works for me, dragged a file in dolphin to a different tab and it allowed me to copy it

**Comment by Quantenzitrone** [comment] 2022-11-24 13:20
are you sure you ran dolphin under xwayland?

**Comment by vaxerski** [comment] 2022-11-24 13:20
yep

**Comment by Quantenzitrone** [comment] 2022-11-24 13:22
hmm i'll have to try that again

**Comment by n3oney** [comment] 2022-12-02 17:35
I can reproduce this, I used dragon-drop to drag a file into Caprine and Discord, both running in XWayland, and both ended up freezing for a while (Caprine froze for 40s and Discord for 10s), and the drop didn't have any effect on the app.

However, when running dragon-drop in XWayland (`GDK_BACKEND=x11 dragon-drop`), the drag-and-drop worked just fine! (apart from the file getting lost often when changing focus)

Also, when running dragon-drop in XWayland and dropping to a Wayland app, the dragged file would just start floating in the air on the last cursor position when dragon-drop was focused when the focus switches, so it's not actually possible to drag a file from XWayland to Wayland either.

When I ran dragon-drop as a source and as a target, it worked fine, as long as both were running either in Wayland or XWayland.

**Comment by BrodieRobertson** [comment] 2023-03-25 04:19
I use PCManFM as my file manager and the instant I get to edge of the window the file is dropped, this problem doesn't occur over on Sway

**Comment by vaxerski** [comment] 2023-03-25 13:26
doesn't pcmanfm run on native wayland?

**Comment by BrodieRobertson** [comment] 2023-03-25 23:28
There's 3 different versions of it, the one I'm using is running through Xwayland

**Comment by vaxerski** [comment] 2023-03-26 00:35
That's an interesting one. Tried myself and pcmanfm-gtk2 is indeed broken, but pcmanfm-qt can dnd onto both wayland and xwayland apps. Odd.

**Comment by BrodieRobertson** [comment] 2023-03-27 02:18
Dolphin is producing the exact same result as pcmanfm-qt and pcmanfm-gtk3 for me, I can't drag onto Xwayland windows

**Comment by vaxerski** [comment] 2023-03-27 06:33
huh. odd. I certainly seem to be able to. Since it works on sway, I'll look into it.

**Comment by vaxerski** [comment] 2023-03-29 23:35
@BrodieRobertson Are you using `follow_mouse` of `!= 1`? In that case I managed to repro and noticed that it's just a months-old feature that broke at some point lul

fixed in b88de63abb41bfb8c07638e6277982503638c29d

**Comment by Quantenzitrone** [comment] 2023-03-29 23:49
i had `follow_mouse=true` when i had the issue

btw sorry for not replying, i started using i3 again, because i can use proprietary nvidia drivers on xorg, and i haven't had the motivation to fix my hyprland configuration to adapt to other changes i made for my nixos configuration

**Comment by vaxerski** [comment] 2023-03-29 23:50
that was to brodie, cuz he couldn't dnd from wl -> xwl

xwl -> * is still broken even on follow mouse 1

**Comment by Quantenzitrone** [comment] 2023-03-29 23:51
oh ok

**Comment by zenzoa** [comment] 2023-04-02 22:02
I'm seeing this behavior too, but so far only in one scenario: dragging files from file-roller to thunar. The panel in thunar is highlighted when the file is dragged over, but when I let go, the file is not extracted. When I run both programs from terminals, I don't get any error output. However if I drag the file in reverse - from thunar to file-roller - the file is successfully added to the archive. And selecting "extract here" from thunar's context menu works fine. I tried this with follow_mouse = 0, 1, and 2 with the same results.

**Comment by BrodieRobertson** [comment] 2023-04-04 02:45
follow_mouse has always been set to 1 for me

wl -> wl works
wl -> xwl upon further testing half works

If I drag a file into discord, discord doesn't do anything with it, if I drag a video into my youtube studio to upload it does. So it may actually be a completely seperate issue with discord

xwl -> * doesn't work

**Comment by themvl** [comment] 2023-04-04 21:13
can confirm that dragging from discord to firefox does not work.

**Comment by vaxerski** [comment] 2023-04-05 11:56
idk what the hell happened but I am suddenly now able to drag xwl->xwl?

xwl->wl doesn't work to me even on sway though

**Comment by NoEnd-yt** [comment] 2023-06-29 10:51
> follow_mouse has always been set to 1 for me
> 
> wl -> wl works wl -> xwl upon further testing half works
> 
> If I drag a file into discord, discord doesn't do anything with it, if I drag a video into my youtube studio to upload it does. So it may actually be a completely seperate issue with discord/electron
> 
> xwl -> * doesn't work

i personally fixed that issue by launching discord with electron wayland flags:
`/usr/bin/discord --enable-features=UseOzonePlatform --ozone-platform=wayland`
there was an experimental flag for pipewire screenshare but it doesn't work

**Comment by tralph3** [comment] 2023-09-27 00:55
> I'm seeing this behavior too, but so far only in one scenario: dragging files from file-roller to thunar. The panel in thunar is highlighted when the file is dragged over, but when I let go, the file is not extracted. When I run both programs from terminals, I don't get any error output. However if I drag the file in reverse - from thunar to file-roller - the file is successfully added to the archive. And selecting "extract here" from thunar's context menu works fine. I tried this with follow_mouse = 0, 1, and 2 with the same results.

I can replicate this exact issue. From file-roller to nautilus in my case. It works for adding to the archive, but not for extracting. `follow_mouse` is set to 1.

**Comment by jcelerier** [comment] 2024-07-09 16:29
Hello, I'm having a weird case here in my app https://ossia.io related to this bug : 

- I am running Archlinux. When I build my app against my system Qt libraries (latest Qt, 6.7.1), and run it in Xwayland with QT_QPA_PLATFORM=xcb, drag and drop works in Hyprland. (It also works on other Wayland compositors, e.g. kwin)

- When I build my app in Nix and run it (E.g. it runs against Nix-provided Qt libraries of the same version), suddenly drag'n'drop does not work with xwayland. It works under normal wayland but then a lot of features are broken (and will never work, for instance the app can load some audio plug-ins that will only ever support X11).

- An user reports the same under plain NixOS.

**Comment by vaxerski** [comment] 2024-07-10 18:40
dnd for xwayland support has been dropped, your archlinux mirror is likely mega old and still has some old version

Closing this as wontfix there is also a newer issue for this iirc

**Closed as not planned by vaxerski** 2024-07-10 18:40 UTC
Labels: bug

**Comment by kRHYME7** [comment] 2024-10-10 05:23
Now I see why I can't DND for reaper DAW.
