### ISSUE TITLE
Since aquamarine: cursor super small over some windows 

### ISSUE THREAD

**Issue by ninelore** [hyprwm/Hyprland#7060] opened 2024-07-26 23:15 UTC
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
~ 
❯ hyprctl systeminfo -c
Hyprland, built from branch  at commit 57371b93a058d17affb0ca92f13b8d40582b3ea0  ().
Date: 2024-07-26
Tag: , commits: 57371b93a058d17affb0ca92f13b8d40582b3ea0

flags: (if any)


System Information:
System name: Linux
Node name: 9l-zephyr
Release: 6.10.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun Jul 14 22:43:32 UTC 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c2) (prog-if 00 [VGA controller])
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240725.5ad6a14"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:

======Config-Start======


Config File: /home/9l/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/wbqwrp6gpf31acmdchik5lsj8zdw2z24-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
animations {
  bezier=myBezier, 0.05, 0.9, 0.1, 1.05
  animation=windows, 1, 5, myBezier
  animation=windowsOut, 1, 7, default, popin 80%
  animation=border, 1, 10, default
  animation=fade, 1, 7, default
  animation=workspaces, 1, 6, default
  enabled=yes
}

binds {
  allow_workspace_cycles=true
}

decoration {
  blur {
    brightness=0.800000
    contrast=0.900000
    enabled=false
    new_optimizations=on
    noise=0.010000
    passes=3
    popups=true
    size=8
  }
  dim_inactive=false
  drop_shadow=false
  rounding=0
}

dwindle {
  preserve_split=yes
  pseudotile=yes
}

general {
  border_size=1
  col.active_border=rgba(dadadaee)
  col.inactive_border=rgba(595959aa)
  gaps_in=0
  gaps_out=0
  layout=dwindle
}

gestures {
  workspace_swipe=true
  workspace_swipe_forever=true
}

input {
  touchpad {
    clickfinger_behavior=true
    drag_lock=true
    natural_scroll=true
    scroll_factor=0.500000
    tap-and-drag=true
  }
  accel_profile=flat
  follow_mouse=1
  kb_layout=de
  numlock_by_default=1
  sensitivity=0.800000
}

misc {
  disable_splash_rendering=true
  vfr=true
}

xwayland {
  force_zero_scaling=true
}
bind=SUPER, return, exec, kitty
bind=SUPER, E, exec, nautilus
bind=SUPER, D, exec, anyrun
bind=SUPER, L, exec, hyprlock
bind=SUPER, N, exec, /nix/store/nfh7zfnh3g9bnp6ywvmaak9ph6i5zz33-togglewaybar
bind=SUPER, M, exec, /nix/store/5ywbyyqbc039mrvsc95fwsn53dkaa56f-hyprpowermenu
bind=SUPER, V, exec, cliphist list | anyrun --hide-icons true --hide-plugin-info true --show-results-immediately true --plugins libstdin.so | cliphist decode | wl-copy
bind=SUPER CTRL, V, exec, cliphist wipe
bind=SUPER SHIFT, S, exec, grimblast copy area
bind=SUPER SHIFT, W, exec, hyprpicker | tr -d '\n' | wl-copy
bind=SUPER SHIFT, Q, killactive, 
bind=SUPER, space, togglefloating, 
bind=SUPER, P, pseudo, 
bind=SUPER, O, togglesplit, 
bind=SUPER, F, fullscreen,
bind=SUPER, G, exec, /nix/store/wkidl1kj50ks8lyn100v1jahkk26ll6c-hyprprodmode
bind=, XF86ScreenSaver, exec, hyprlock
bind=SUPER, A, togglespecialworkspace, magic
bind=SUPER SHIFT, A, movetoworkspace, special:magic
bind=SUPER, 0, workspace, 10
bind=SUPER, code:20, workspace, 11
bind=SUPER, code:21, workspace, 12
bind=SUPER SHIFT, 0, movetoworkspace, 10
bind=SUPER SHIFT, code:20, movetoworkspace, 11
bind=SUPER SHIFT, code:21, movetoworkspace, 12
bind=SUPER, 1, workspace, 1
bind=SUPER, 2, workspace, 2
bind=SUPER, 3, workspace, 3
bind=SUPER, 4, workspace, 4
bind=SUPER, 5, workspace, 5
bind=SUPER, 6, workspace, 6
bind=SUPER, 7, workspace, 7
bind=SUPER, 8, workspace, 8
bind=SUPER, 9, workspace, 9
bind=SUPER SHIFT, 1, movetoworkspace, 1
bind=SUPER SHIFT, 2, movetoworkspace, 2
bind=SUPER SHIFT, 3, movetoworkspace, 3
bind=SUPER SHIFT, 4, movetoworkspace, 4
bind=SUPER SHIFT, 5, movetoworkspace, 5
bind=SUPER SHIFT, 6, movetoworkspace, 6
bind=SUPER SHIFT, 7, movetoworkspace, 7
bind=SUPER SHIFT, 8, movetoworkspace, 8
bind=SUPER SHIFT, 9, movetoworkspace, 9
binde=SUPER, k, movefocus, u
binde=SUPER, j, movefocus, d
binde=SUPER, l, movefocus, r
binde=SUPER, h, movefocus, l
binde=SUPER, up, movefocus, u
binde=SUPER, down, movefocus, d
binde=SUPER, right, movefocus, r
binde=SUPER, left, movefocus, l
binde=SUPER SHIFT, k, movewindow, u
binde=SUPER SHIFT, j, movewindow, d
binde=SUPER SHIFT, l, movewindow, r
binde=SUPER SHIFT, h, movewindow, l
binde=SUPER SHIFT, up, movewindow, u
binde=SUPER SHIFT, down, movewindow, d
binde=SUPER SHIFT, right, movewindow, r
binde=SUPER SHIFT, left, movewindow, l
binde=SUPER CTRL, k, resizeactive, 0 -2%
binde=SUPER CTRL, j, resizeactive, 0 2%
binde=SUPER CTRL, l, resizeactive, 2% 0
binde=SUPER CTRL, h, resizeactive, -2% 0
binde=SUPER CTRL, up, resizeactive, 0 -2%
binde=SUPER CTRL, down, resizeactive, 0 2%
binde=SUPER CTRL, right, resizeactive, 2% 0
binde=SUPER CTRL, left, resizeactive, -2% 0
binde=SUPER ALT, k, moveactive, 0 -2%
binde=SUPER ALT, j, moveactive, 0 2%
binde=SUPER ALT, l, moveactive, 2% 0
binde=SUPER ALT, h, moveactive, -2% 0
binde=SUPER ALT, up, moveactive, 0 -2%
binde=SUPER ALT, down, moveactive, 0 2%
binde=SUPER ALT, right, moveactive, 2% 0
binde=SUPER ALT, left, moveactive, -2% 0
bindl=,XF86AudioPlay,    exec, /nix/store/h7pjaqchnf21m5mqafgj93z1vrjndpm4-playerctl-2.4.1/bin/playerctl play-pause
bindl=,XF86AudioStop,    exec, /nix/store/h7pjaqchnf21m5mqafgj93z1vrjndpm4-playerctl-2.4.1/bin/playerctl pause
bindl=,XF86AudioPause,   exec, /nix/store/h7pjaqchnf21m5mqafgj93z1vrjndpm4-playerctl-2.4.1/bin/playerctl pause
bindl=,XF86AudioPrev,    exec, /nix/store/h7pjaqchnf21m5mqafgj93z1vrjndpm4-playerctl-2.4.1/bin/playerctl previous
bindl=,XF86AudioNext,    exec, /nix/store/h7pjaqchnf21m5mqafgj93z1vrjndpm4-playerctl-2.4.1/bin/playerctl next
bindl=,XF86AudioMute, exec, /nix/store/4axbbzrxffpb06zyqzg6yjx30g7xcsai-wireplumber-0.5.5/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindle=,XF86MonBrightnessUp,   exec, /nix/store/1s6yzqwmjjj6j38zbpdx22a41h03fp20-brightnessctl-0.5.1/bin/brightnessctl set +5%
bindle=,XF86MonBrightnessDown, exec, /nix/store/1s6yzqwmjjj6j38zbpdx22a41h03fp20-brightnessctl-0.5.1/bin/brightnessctl set  5%-
bindle=,XF86KbdBrightnessUp,   exec, /nix/store/1s6yzqwmjjj6j38zbpdx22a41h03fp20-brightnessctl-0.5.1/bin/brightnessctl -d *::kbd_backlight set +1
bindle=,XF86KbdBrightnessDown, exec, /nix/store/1s6yzqwmjjj6j38zbpdx22a41h03fp20-brightnessctl-0.5.1/bin/brightnessctl -d *::kbd_backlight set  1-
bindle=,XF86AudioRaiseVolume,  exec, /nix/store/4axbbzrxffpb06zyqzg6yjx30g7xcsai-wireplumber-0.5.5/bin/wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindle=,XF86AudioLowerVolume,  exec, /nix/store/4axbbzrxffpb06zyqzg6yjx30g7xcsai-wireplumber-0.5.5/bin/wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-
bindm=SUPER, mouse:273, resizewindow
bindm=SUPER, mouse:272, movewindow
exec-once=sleep 1 && waybar
exec-once=swww-daemon
exec-once=swww img $(cat ~/.wallpaper)
exec-once=hyprctl setcursor Qogir 24
exec-once=transmission-gtk
exec-once=/nix/store/licz9xp7nk49xg68wz06ikvf0lnwm8s4-hypreventhandler
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=hypridle
monitor=desc:Thermotrex Corporation TL140ADXP01,preferred,0x0,1.6
monitor=desc:AU Optronics 0x662D, preferred, 0x0,1.25
monitor=desc:HP Inc. HP X34 6CM25210CS,preferred,-3440x-250,1
monitor=desc:GWD ARZOPA 000000000000,preferred,0x1000,1.25
monitor=,preferred,auto,auto
windowrule=float, ^(org.gnome.Calculator)$
windowrule=float, ^(pavucontrol)$
windowrule=float, ^(nm-connection-editor)$
windowrule=float, ^(blueberry)$
windowrule=float, ^(Color Picker)$
windowrule=float, ^(xdg-desktop-portal)$
windowrule=float, ^(xdg-desktop-portal-gnome)$
windowrulev2=opacity 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2=noanim,class:^(xwaylandvideobridge)$
windowrulev2=noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2=maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2=noblur,class:^(xwaylandvideobridge)$

======Config-End========
```

</details>

### Description

My cursor gets really small over some windows and over an empty workspace down from 24px to maybe 10-12px

Examples cases where cursor is small (non-exhaustive:
- Electron apps
- empty workspace

Examples where the cursor is normal
- Firefox
- GTK windows in general
- Waybar

### How to reproduce

Use a flake-build version after the aquamarine merge

### Crash reports, logs, images, videos

n/a

**Comment by ninelore** [comment] 2024-07-26 23:16
possibly related to #7056

**Comment by nktnet1** [comment] 2024-07-27 03:38
Duplicate of #6983 (many suggestions there, including patches).

I also left the steps I took to I fix it [here](https://github.com/hyprwm/Hyprland/issues/6320#issuecomment-2243109637).

**Closed** 2024-07-27 11:12 UTC
Labels: bug
