### ISSUE TITLE
XWayland not starting

### ISSUE THREAD

**Issue by ChromMob** [hyprwm/Hyprland#7125] opened 2024-07-31 18:40 UTC
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 8a5f9bbb394ddeb4be9a9df6248b41b07d84ea66  (keybinds: handle null monitor in pinActive (7122)).
Date: Wed Jul 31 17:54:07 2024
Tag: v0.41.2-144-g8a5f9bbb, commits: 5030

flags: (if any)


System Information:
System name: Linux
Node name: Filip-ARCH
Release: 6.10.2-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:32 +0000


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c3) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/chrommob/.config/hypr/hyprland.conf: Read Succeeded
#AUTOGENERATED HYPR CONFIG.
#PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
#OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

# Please note not all available settings / options are set here.
# For a full list, see the wiki
# autogenerated = 1 # remove this line to remove the warning



# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor = ,preferred,auto,auto



# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Execute your favorite apps at launch

$scrPath = ~/.config/hyprdots/scripts
exec-once = hypridle
exec-once = $scrPath/resetxdgportal.sh # reset XDPH for screenshare
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = dbus-update-activation-environment --systemd --all # for XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # authentication dialogue for GUI apps
exec-once = waybar # launch the system panel
exec-once = blueman-applet # systray app for BT
exec-once = nm-applet --indicator # systray app for Network/Wifi
exec-once = dunst # start notification demon
exec-once = wl-paste --type text --watch cliphist store # clipboard store text data
exec-once = wl-paste --type image --watch cliphist store # clipboard store image data
exec-once = $scrPath/swwwallpaper.sh # start wallpaper daemon
exec-once = $scrPath/batterynotify.sh # battery notification



# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# Some default env vars.

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
#env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1



# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = cz,us
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 1

    numlock_by_default = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more


# See https://wiki.hyprland.org/Configuring/Variables/ for more

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}



# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more



# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

# See https://wiki.hyprland.org/Configuring/Variables/ for more

misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}


general {
    allow_tearing = true
}

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/themes/common.conf # shared theme settings
source = ~/.config/hypr/themes/theme.conf # theme specific settings
source = ~/.config/hypr/themes/colors.conf # wallbash color override
source = ~/.config/hypr/monitors.conf # initially empty, to be configured by user and remains static
source = ~/.config/hypr/userprefs.conf # initially empty, to be configured by user and remains static

# Note: as userprefs.conf is sourced at the end, settings configured in this file will override the defaults



Config File: /home/chrommob/.config/hypr/animations.conf: Read Succeeded

# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█


# Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

animations {
    enabled = yes
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}



Config File: /home/chrommob/.config/hypr/keybindings.conf: Read Succeeded

# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

# Main modifier
$mainMod = SUPER # windows key

# assign apps
$term = kitty
$editor = code --ozone-platform-hint=wayland
$file = thunar
$browser = firefox-nightly

# Window/Session actions
bind = $mainMod, Q, exec, $scrPath/dontkillsteam.sh # killactive, kill the window on focus
bind = ALT, F4, exec, $scrPath/dontkillsteam.sh # killactive, kill the window on focus
bind = $mainMod, delete, exit, # kill hyperland session
bind = $mainMod, W, togglefloating, # toggle the window on focus to float
bind = $mainMod, G, togglegroup, # toggle the window on focus to group (tab mode)
bind = ALT, return, fullscreen, # toggle the window on focus to fullscreen
bind = $mainMod, L, exec, hyprlock # lock screen
bind = $mainMod SHIFT, F, exec, $scrPath/windowpin.sh # toggle pin on focused window
bind = $mainMod, backspace, exec, $scrPath/logoutlaunch.sh 1 # logout menu
bind = $CONTROL, ESCAPE, exec, killall waybar || waybar # toggle waybar

# Application shortcuts
bind = $mainMod, T, exec, $term  # open terminal
bind = $mainMod, E, exec, $file # open file manager
bind = $mainMod, C, exec, $editor # open vscode
bind = $mainMod, F, exec, $browser # open browser
bind = $CONTROL SHIFT, ESCAPE, exec, $scrPath/sysmonlaunch.sh  # open htop/btop if installed or default to top (system monitor)

# Rofi is toggled on/off if you repeat the key presses
bind = $mainMod, A, exec, pkill -x rofi || $scrPath/rofilaunch.sh d # launch desktop applications
bind = $mainMod, tab, exec, pkill -x rofi || $scrPath/rofilaunch.sh w # switch between desktop applications
bind = $mainMod, R, exec, pkill -x rofi || $scrPath/rofilaunch.sh f # browse system files

# Audio control
bindl  = , F10, exec, $scrPath/volumecontrol.sh -o m # toggle audio mute
bindel = , F11, exec, $scrPath/volumecontrol.sh -o d # decrease volume
bindel = , F12, exec, $scrPath/volumecontrol.sh -o i # increase volume
bindl  = , XF86AudioMute, exec, $scrPath/volumecontrol.sh -o m # toggle audio mute
bindl  = , XF86AudioMicMute, exec, $scrPath/volumecontrol.sh -i m # toggle microphone mute
bindel = , XF86AudioLowerVolume, exec, $scrPath/volumecontrol.sh -o d # decrease volume
bindel = , XF86AudioRaiseVolume, exec, $scrPath/volumecontrol.sh -o i # increase volume
bindl  = , XF86AudioPlay, exec, playerctl play-pause
bindl  = , XF86AudioPause, exec, playerctl play-pause
bindl  = , XF86AudioNext, exec, playerctl next
bindl  = , XF86AudioPrev, exec, playerctl previous

# Brightness control
bindel = , XF86MonBrightnessUp, exec, $scrPath/brightnesscontrol.sh i # increase brightness
bindel = , XF86MonBrightnessDown, exec, $scrPath/brightnesscontrol.sh d # decrease brightness

# Screenshot/Screencapture
bind = $mainMod, P, exec, $scrPath/screenshot.sh s # drag to snip an area / click on a window to print it
bind = $mainMod CTRL, P, exec, $scrPath/screenshot.sh sf # frozen screen, drag to snip an area / click on a window to print it
bind = $mainMod ALT, P, exec, $scrPath/screenshot.sh m # print focused monitor
bind = ,print, exec, $scrPath/screenshot.sh p  # print all monitor outputs

# Exec custom scripts
bind = $mainMod ALT, G, exec, $scrPath/gamemode.sh # disable hypr effects for gamemode
bind = $mainMod ALT, right, exec, $scrPath/swwwallpaper.sh -n # next wallpaper
bind = $mainMod ALT, left, exec, $scrPath/swwwallpaper.sh -p # previous wallpaper
bind = $mainMod ALT, up, exec, $scrPath/wbarconfgen.sh n # next waybar mode
bind = $mainMod ALT, down, exec, $scrPath/wbarconfgen.sh p # previous waybar mode
bind = $mainMod SHIFT, D, exec, $scrPath/wallbashtoggle.sh  # toggle wallbash on/off
bind = $mainMod SHIFT, T, exec, pkill -x rofi || $scrPath/themeselect.sh # theme select menu
bind = $mainMod SHIFT, A, exec, pkill -x rofi || $scrPath/rofiselect.sh # rofi style select menu
bind = $mainMod SHIFT, W, exec, pkill -x rofi || $scrPath/swwwallselect.sh # rofi wall select menu
bind = $mainMod, V, exec, pkill -x rofi || $scrPath/cliphist.sh c  # open Pasteboard in screen center
bind = $mainMod, K, exec, $scrPath/keyboardswitch.sh # change keyboard layout

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = ALT, Tab, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Switch workspaces relative to the active workspace with mainMod + CTRL + [←→]
bind = $mainMod CTRL, right, workspace, r+1 
bind = $mainMod CTRL, left, workspace, r-1
bind = $mainMod, B, togglesplit

# move to the first empty workspace instantly with mainMod + CTRL + [↓]
bind = $mainMod CTRL, down, workspace, empty 

# Resize windows
binde = $mainMod SHIFT, right, resizeactive, 30 0
binde = $mainMod SHIFT, left, resizeactive, -30 0
binde = $mainMod SHIFT, up, resizeactive, 0 -30
binde = $mainMod SHIFT, down, resizeactive, 0 30

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Move active window to a relative workspace with mainMod + CTRL + ALT + [←→]
bind = $mainMod CTRL ALT, right, movetoworkspace, r+1
bind = $mainMod CTRL ALT, left, movetoworkspace, r-1

# Move active window around current workspace with mainMod + SHIFT + CTRL [←→↑↓]
bind = $mainMod SHIFT $CONTROL, left, movewindow, l
bind = $mainMod SHIFT $CONTROL, right, movewindow, r
bind = $mainMod SHIFT $CONTROL, up, movewindow, u
bind = $mainMod SHIFT $CONTROL, down, movewindow, d

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/Resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = Super, Z, movewindow
bindm = Super, X, resizewindow

# Special workspaces (scratchpad)
bind = $mainMod ALT, S, movetoworkspacesilent, special
bind = $mainMod, S, togglespecialworkspace,

# Toggle Layout
bind = $mainMod, J, togglesplit, # dwindle

# Move window silently to workspace Super + Alt + [0-9]
bind = $mainMod ALT, 1, movetoworkspacesilent, 1
bind = $mainMod ALT, 2, movetoworkspacesilent, 2
bind = $mainMod ALT, 3, movetoworkspacesilent, 3
bind = $mainMod ALT, 4, movetoworkspacesilent, 4
bind = $mainMod ALT, 5, movetoworkspacesilent, 5
bind = $mainMod ALT, 6, movetoworkspacesilent, 6
bind = $mainMod ALT, 7, movetoworkspacesilent, 7
bind = $mainMod ALT, 8, movetoworkspacesilent, 8
bind = $mainMod ALT, 9, movetoworkspacesilent, 9
bind = $mainMod ALT, 0, movetoworkspacesilent, 10

# Trigger when the switch is turning off, Might cause bugs. Recommend to use logind instead.
#bindl= , switch:on:Lid Switch, exec, swaylock && systemctl suspend


Config File: /home/chrommob/.config/hypr/windowrules.conf: Read Succeeded

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = opacity 0.90 0.90,class:^(Brave-browser)$
windowrulev2 = opacity 0.80 0.80,class:^(Steam)$
windowrulev2 = opacity 0.80 0.80,class:^(steam)$
windowrulev2 = opacity 0.80 0.80,class:^(steamwebhelper)$
windowrulev2 = opacity 0.80 0.80,class:^(Spotify)$
windowrulev2 = opacity 0.80 0.80,class:^(Code)$
windowrulev2 = opacity 0.80 0.80,class:^(code-url-handler)$
windowrulev2 = opacity 0.80 0.80,class:^(kitty)$
windowrulev2 = opacity 0.80 0.80,class:^(org.kde.dolphin)$
windowrulev2 = opacity 0.80 0.80,class:^(org.kde.ark)$
windowrulev2 = opacity 0.80 0.80,class:^(nwg-look)$
windowrulev2 = opacity 0.80 0.80,class:^(qt5ct)$
windowrulev2 = opacity 0.80 0.80,class:^(qt6ct)$
windowrulev2 = opacity 0.80 0.80,class:^(kvantummanager)$

windowrulev2 = opacity 0.90 0.90,class:^(com.github.rafostar.Clapper)$ #Clapper-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(com.github.tchx84.Flatseal)$ #Flatseal-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(hu.kramo.Cartridges)$ #Cartridges-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(com.obsproject.Studio)$ #Obs-Qt
windowrulev2 = opacity 0.80 0.80,class:^(gnome-boxes)$ #Boxes-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(discord)$ #Discord-Electron
windowrulev2 = opacity 0.80 0.80,class:^(WebCord)$ #WebCord-Electron
windowrulev2 = opacity 0.80 0.80,class:^(ArmCord)$ #ArmCord-Electron
windowrulev2 = opacity 0.80 0.80,class:^(app.drey.Warp)$ #Warp-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(net.davidotek.pupgui2)$ #ProtonUp-Qt
windowrulev2 = opacity 0.80 0.80,class:^(yad)$ #Protontricks-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(Signal)$ #Signal-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(io.github.alainm23.planify)$ #planify-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(io.gitlab.theevilskeleton.Upscaler)$ #Upscaler-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(com.github.unrud.VideoDownloader)$ #VideoDownloader-Gtk

windowrulev2 = opacity 0.80 0.70,class:^(pavucontrol)$
windowrulev2 = opacity 0.80 0.70,class:^(blueman-manager)$
windowrulev2 = opacity 0.80 0.70,class:^(nm-applet)$
windowrulev2 = opacity 0.80 0.70,class:^(nm-connection-editor)$
windowrulev2 = opacity 0.80 0.70,class:^(org.kde.polkit-kde-authentication-agent-1)$

windowrulev2 = float,class:^(org.kde.dolphin)$,title:^(Copying — Dolphin)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(firefox)$,title:^(Library)$
windowrulev2 = float,class:^(vlc)$
windowrulev2 = float,class:^(kvantummanager)$
windowrulev2 = float,class:^(qt5ct)$
windowrulev2 = float,class:^(qt6ct)$
windowrulev2 = float,class:^(nwg-look)$
windowrulev2 = float,class:^(org.kde.ark)$
windowrulev2 = float,class:^(Signal)$ #Signal-Gtk
windowrulev2 = float,class:^(com.github.rafostar.Clapper)$ #Clapper-Gtk
windowrulev2 = float,class:^(app.drey.Warp)$ #Warp-Gtk
windowrulev2 = float,class:^(net.davidotek.pupgui2)$ #ProtonUp-Qt
windowrulev2 = float,class:^(yad)$ #Protontricks-Gtk
windowrulev2 = float,class:^(eog)$ #Imageviewer-Gtk
windowrulev2 = float,class:^(io.github.alainm23.planify)$ #planify-Gtk
windowrulev2 = float,class:^(io.gitlab.theevilskeleton.Upscaler)$ #Upscaler-Gtk
windowrulev2 = float,class:^(com.github.unrud.VideoDownloader)$ #VideoDownloader-Gkk
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-applet)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$

windowrulev2 = immediate, class:^(cs2)$

Config File: /home/chrommob/.config/hypr/themes/common.conf: Read Succeeded

#█▀▀ █░█ █▀█ █▀ █▀█ █▀█
#█▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

#env = XCURSOR_THEME,Bibata-Modern-Ice
#env = XCURSOR_SIZE,20

exec = hyprctl setcursor Bibata-Modern-Ice 20
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec = gsettings set org.gnome.desktop.interface cursor-size 20


#█▀▀ █▀█ █▄░█ ▀█▀
#█▀░ █▄█ █░▀█ ░█░

exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 9'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'


#█▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
#▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

decoration {
    dim_special = 0.3
    blur {
        special = true
    }
}



Config File: /home/chrommob/.config/hypr/themes/theme.conf: Read Succeeded
exec = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-purple'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Tokyo-Night'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(bb9af7ff) rgba(b4f9f8ff) 45deg
    col.inactive_border = rgba(565f89cc) rgba(9aa5cecc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(bb9af7ff) rgba(b4f9f8ff) 45deg
    col.border_inactive = rgba(565f89cc) rgba(9aa5cecc) 45deg
    col.border_locked_active = rgba(bb9af7ff) rgba(b4f9f8ff) 45deg
    col.border_locked_inactive = rgba(565f89cc) rgba(9aa5cecc) 45deg
}

decoration {
    rounding = 10
    drop_shadow = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar


Config File: /home/chrommob/.config/hypr/themes/colors.conf: Read Succeeded


Config File: /home/chrommob/.config/hypr/monitors.conf: Read Succeeded

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/


Config File: /home/chrommob/.config/hypr/userprefs.conf: Read Succeeded

#█░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
#█▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█


# Set your personal hyprland configuration here
# for sample file, please refer https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2


======Config-End========
```

</details>

### Description

Sorry I am still kinda not sure how to get any debug for that but XWayland applications are not launching at all.
Vesktop: 
APPIMAGE env is not defined, current application is not an AppImage
Vesktop is already running. Quitting...
checkForUpdatesAndNotify called, downloadPromise is null
[32306:0731/203939.561909:ERROR:ozone_platform_x11.cc(245)] Missing X server or $DISPLAY
[32306:0731/203939.561945:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
fish: Job 1, 'vesktop' terminated by signal SIGSEGV (Address boundary error)
Heroic:
[32598:0731/203947.561477:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[32598:0731/203947.561538:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
fish: Job 1, 'heroic' terminated by signal SIGSEGV (Address boundary error)

### How to reproduce

Launch any XWayland app (heroic, vscode and vesktop tested)

**Comment by vaxerski** [comment] 2024-07-31 18:42
attach the hyprland log

**Comment by ChromMob** [comment] 2024-07-31 18:44
[hyprland.log](https://github.com/user-attachments/files/16445975/hyprland.log)

**Comment by ChromMob** [comment] 2024-07-31 18:44
I am sorry for being kinda unprofessional it is my first time having similar kind of issue.

**Comment by vaxerski** [comment] 2024-07-31 18:51
```
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
```

enable logging first, see the linked wiki

> I am sorry for being kinda unprofessional about it, it is my first time having similar kind of issue.

we all start somewhere

**Comment by ChromMob** [comment] 2024-07-31 19:08
[hyprland (kopie 1).log](https://github.com/user-attachments/files/16446160/hyprland.kopie.1.log)

**Comment by ChromMob** [comment] 2024-07-31 19:10
Only mention of xwayland I found in the log:
![image](https://github.com/user-attachments/assets/f2bc8aef-388f-4a54-865e-44efeca912a0)
Probably important to mention it started happening right after aquamarine merge.

**Comment by vaxerski** [comment] 2024-07-31 19:13
some logs are missing that surely should be present... are you sure you started hyprland with logs enabled? or did you enable them via some exec

**Comment by ChromMob** [comment] 2024-07-31 19:15
Doesnt hyprland auto reload configs, I just put the var in config?

**Comment by ChromMob** [comment] 2024-07-31 19:25
[hyprland (kopie 1).log](https://github.com/user-attachments/files/16446300/hyprland.kopie.1.log)
Here is the one where I restarted hyprland completely

**Comment by vaxerski** [comment] 2024-07-31 19:42
thanks, that's better

**Comment by ChromMob** [comment] 2024-07-31 19:45
> Can you bisect?
Should I install the normal version instead of the git?
> Are you sure it's from the aq merge?
Well it didnt happen before it.

**Comment by vaxerski** [comment] 2024-07-31 19:48
does xwayland leave a coredump in `coredumpctl`?

**Comment by ChromMob** [comment] 2024-07-31 19:50
WUT
```sh
Mon 2024-07-01 19:19:16 CEST    1152 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Mon 2024-07-01 19:31:40 CEST  114639 1000 1000 SIGABRT missing      /usr/bin/Xwayland                                                                                     >
Mon 2024-07-01 19:31:41 CEST  114579 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Tue 2024-07-02 10:05:22 CEST  131292 1000 1000 SIGABRT missing      /usr/lib/xdg-desktop-portal-hyprland                                                                  >
Mon 2024-07-08 19:40:32 CEST    1177 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Mon 2024-07-01 19:31:40 CEST  114639 1000 1000 SIGABRT missing      /usr/bin/Xwayland                                                                                     >
Mon 2024-07-01 19:31:41 CEST  114579 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Tue 2024-07-02 10:05:22 CEST  131292 1000 1000 SIGABRT missing      /usr/lib/xdg-desktop-portal-hyprland                                                                  >
Mon 2024-07-08 19:40:32 CEST    1177 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Mon 2024-07-08 19:40:49 CEST    1269 1000 1000 SIGABRT missing      /usr/bin/Xwayland                                                                                     >
Sun 2024-07-14 19:26:12 CEST 1017833 1000 1000 SIGTRAP missing      /opt/visual-studio-code/code                                                                          >
Mon 2024-07-15 21:38:11 CEST    5670 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Mon 2024-07-15 21:38:21 CEST  120610 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Mon 2024-07-15 21:41:58 CEST  121526 1000 1000 SIGABRT missing      /usr/bin/Hyprland                                                                                     >
Mon 2024-07-15 22:05:30 CEST  192503 1000 1000 SIGABRT missing      /usr/bin/hyprpm                        
```

**Comment by ChromMob** [comment] 2024-07-31 19:53
> does xwayland leave a coredump in `coredumpctl`? (press end to go to the end)

I know how to use vim :D

**Comment by vaxerski** [comment] 2024-07-31 19:57
I dont see any entries from today though, so it's not coredumping.

Go to src/xwayland/server.cpp in hyprland
edit line 302 to have `"WAYLAND_DEBUG=1 Xwayland {} ....... -wm {} |& tee /home/you/xwayland.log"` (put a valid path)

compile and attach the outputted log

**Comment by ChromMob** [comment] 2024-07-31 20:01
I should have properly clarified before but I am using the chaotic-aur version

**Comment by ChromMob** [comment] 2024-07-31 20:39
> I dont see any entries from today though, so it's not coredumping.
> 
> Go to src/xwayland/server.cpp in hyprland edit line 302 to have `"WAYLAND_DEBUG=1 Xwayland {} -rootless -core -listenfd {} -listenfd {} -displayfd {} -wm {} |& tee /home/you/xwayland.log"` (put a valid path)
> 
> compile and attach the outputted log

[xwayland.log](https://github.com/user-attachments/files/16446920/xwayland.log)

**Comment by vaxerski** [comment] 2024-07-31 21:34
.......

but it did connect to a wayland server...? I have no clue whats wrong here.

> Also if this is actually something caused by aquamarine I am surprised there is no issue about it yet. Or are X11 just that uncommon now?

Everyone else seems to be having no problems with xwayland, me included.

**Comment by ChromMob** [comment] 2024-08-01 03:14
> but it did connect to a wayland server...?

It didn't according to the log.

**Comment by ChromMob** [comment] 2024-08-01 17:58
@vaxerski

**Comment by vaxerski** [comment] 2024-08-01 17:59
I see your message, I am not blind.

I have no clue why this happens and don't have a fix.

It clearly does connect to the wayland server because of the wayland logs showing communication

**Comment by ChromMob** [comment] 2024-08-01 18:01
Sorry for ping. Would you recommend me going somewhere with it?

**Comment by vaxerski** [comment] 2024-08-01 18:02
maybe the xwayland people will know something about this

**Comment by ChromMob** [comment] 2024-08-01 18:06
Sadly they don't use git so i gotta figure out their mailing stuff :D

**Comment by ChromMob** [comment] 2024-08-01 18:07
I tried reverting to the arch packages release and it is still happening so probably not related to aquamarine

**Comment by vaxerski** [comment] 2024-08-01 21:15
it's probably not related to hyprland either if I was to guess :P

**Comment by ChromMob** [comment] 2024-08-04 16:22
It suddenly loaded

**Comment by ChromMob** [comment] 2024-08-04 16:28
So now even the latest AUR works so I guess it was fixed by reinstalling the mesa package

**Comment by vaxerski** [comment] 2024-08-04 20:56
closing then

**Closed by vaxerski** 2024-08-04 20:56 UTC
Labels: bug

**Comment by ChromMob** [comment] 2024-08-07 15:42
Ok so I verified my thorougly and I can confirm that it is in fact bug in aquamarine. It is still happening in the git version but not in the normal extra package one.

**Comment by vaxerski** [comment] 2024-08-07 15:46
it's only happening to you though, and I have no clue what the issue is

**Comment by vfosterm** [comment] 2024-08-14 19:59
I encountered the same issue when upgrading to version 42.0 from 41.2, I have a bit more info to add.

If I downgrade only Hyprland back to 41.2 Xwayland starts fine, or if I unplug my VR headset (Valve Index) on version 42.0 Xwayland also starts fine. So there is some issue lurking, not sure if @ChromMob happens to have a VR headset plugged in as well.

**Comment by ChromMob** [comment] 2024-08-14 20:15
Yep I got my VR headset plugged in.

**Comment by ChromMob** [comment] 2024-08-29 06:27
@vfosterm Any luck getting it work again?

**Comment by vfosterm** [comment] 2024-08-31 09:47
@ChromMob Nope it hasn't been fixed yet. You can follow the issue # that I linked above for updates.

**Comment by ChromMob** [comment] 2024-09-05 08:22
Thank you for linking the related issue.

**Comment by NotWinder** [comment] 2025-03-10 04:26
same problem on nixos 25.05
on version 0.47.0(using flakes)
it doesn't run xwayland after a full restart i have to restart hyprland one or two time for it to run xwayland
and i get the same "[ERR] Xwayland: startup failed, not setting up xwm" line in the log file
