### ISSUE TITLE
movewindow leaves artifacts of the moved window ontop of other windows

### ISSUE THREAD

**Issue by japrogramer** [hyprwm/Hyprland#98] opened 2022-05-20 06:28 UTC
**Describe the bug**
when movewindow is triggered and the moved window moves over other windows artifacts of the moved window remain drawn over the windows that weren't moved

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

** possible solution **

force a redraw on all windows after the animation ends

**Comment by vaxerski** [comment] 2022-05-20 12:56
cant reproduce

**Comment by japrogramer** [comment] 2022-05-20 18:44
I was able to replicate but this time the artifacts are around the edges near the bottom of the screen, where the wallpaper show

https://user-images.githubusercontent.com/1387859/169592454-6aa68c4f-a27d-4add-a488-708af90e0794.mp4

s

**Comment by vaxerski** [comment] 2022-05-20 20:07
ah, its firefox again. right. It's that issue.

**Comment by japrogramer** [comment] 2022-05-22 05:02
@vaxerski when I have terminal windows with an opacity of .75 and I replicate the movement shown in the video the artifacts now happen on the transparent window and not just at the bottom part of the screen

https://user-images.githubusercontent.com/1387859/169679487-515f8a5f-ae9a-4dd9-97a6-23cfc17607a6.mp4

**Comment by vaxerski** [comment] 2022-05-22 07:39
well, yeah. It's an issur with firefox, as I've said.

**Comment by siemato** [comment] 2022-06-12 06:18
i have the same issue with alacritty, foot and pretty much everything i tried when closing the last window of a workspace,

**Comment by vaxerski** [comment] 2022-06-12 07:20
video please?

**Comment by japrogramer** [comment] 2022-06-12 18:18
I'm also using alacritty, may be the same issue.

**Comment by vaxerski** [comment] 2022-07-11 21:38
should be fixed in f461ea3105fbe7979a44d702bd9b2f7ee46a9441

**Closed by vaxerski** 2022-07-11 21:38 UTC
Labels: bug, damage tracking
