### ISSUE TITLE
Hyprland is very gpu heavy

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#4779] opened 2024-02-21 10:42 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.17-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 08:28:50 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:
```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

![image](https://github.com/hyprwm/Hyprland/assets/5684325/a4ab7bf1-2d6a-46ac-862b-932367346c19)

The above is a screenshot from nvtop of Hyprlands resource usage in nvtop. I am using a radeon 680m igpu (that is on par with a GTX 1050 for those unfamiliar) and at 2560x1440 resolution.

Note if I plug in an extra monitor that's at standard UHD (4k) resolution all of Hyprland will turn laggy.

Even if  I disable compositing with this:

```
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:passes 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
```

it'll only drop by maybe 20% or so, it's still using about half of the igpu. This is **extremely** gpu heavy, it isn't hard to find 3D games that are less heavy than this.

### How to reproduce

N/A (Seems like a general issue)

**Comment by vaxerski** [comment] 2024-02-21 11:01
yeah just like your mom

on a real note this was fixed in -git dupe of #4670

**Closed by vaxerski** 2024-02-21 11:01 UTC
Labels: bug

**Comment by vaxerski** [comment] 2024-02-21 11:19
_disable compositing_? That's not a thing...

**Comment by Rabcor** [comment] 2024-02-21 11:20
> _disable compositing_? That's not a thing...

I'm quite sure you know what I mean. animations and other desktop effects, I mean it's been called compositing for a lot longer than wayland has existed. Besides, you can see the actual command.

**Comment by vaxerski** [comment] 2024-02-21 11:22
Well, no, disabling compositing in X works differently.

In hyprland you do not disable compositing, ever, unless you are in active direct-scanout or tearing.

anyways can you test on e.g. sway or wayfier?

**Comment by Rabcor** [comment] 2024-02-21 12:55
> Well, no, disabling compositing in X works differently.
> 
> In hyprland you do not disable compositing, ever, unless you are in active direct-scanout or tearing.
> 
> anyways can you test on e.g. sway or wayfier?

I couldn't get wayfire to compile yet, but I tried with sway, GPU use on Sway, was actually 0% and graphical ram use was 3mb, it was using basically nothing; there were perhaps a couple more things running on hyprland like waybar and swww (I mean sway was with no config at all, I just launched it, then launched discord, kitty and steam to make sure atl east something was running on it, didn't seem to affect the numbers any)

**Comment by Rabcor** [comment] 2024-02-21 14:25
> 🤔 odd

I managed to compile and run wayfire, and well it used some more graphical memory than sway, around 128mb which is about half of what I've come to expect Hyprland to use.

But mind you this was entirely unconfigured wayfire, I have no idea how to configure it either. It used 0% gpu when it was idle, but if I opened the desktop selector and closed it it jumped to around 8%.

Since it was unconfigured thuogh there were no active effects meaning it's not exactly a fair comparison. However, i could note perhaps that when I switch workspaces on Hyprland utilization goes up by 20% during the switch. It's probably just the animation though.

**Comment by Rabcor** [comment] 2024-02-21 14:30
[hypr.tar.gz](https://github.com/hyprwm/Hyprland/files/14360764/hypr.tar.gz)

Also I decided to zip up my hyprland config if you would like to take a look, it's a bit of amess since I downloaded jakoolit's arch hyprland git and then modified it myself (mostly modified it to make it less messy lol, my configs are better organized, but the scripts are still a mess)

See if you can replicate it, I wonder if there's a way to run hyprland without config somehow, like a --no-config option? I should probably test that and see the gpu use that way as well just to see if something in my config is causing it or not.

**Comment by vaxerski** [comment] 2024-02-21 15:01
nvidia being nvidia? no way.

>  I wonder if there's a way to run hyprland without config somehow,

move your hyprland.conf elsweyr and hyprland will autogen the default config.

**Comment by Rabcor** [comment] 2024-02-21 15:06
> nvidia being nvidia? no way.
> 
> > I wonder if there's a way to run hyprland without config somehow,
> 
> move your hyprland.conf elsweyr and hyprland will autogen the default config.

I'm not using an nvidia gpu, I have one, but i'm running hyprland on my amd gpu I'm pretty certain. nvtop shows all gpus. I have a display for my nvidia gpu utilization in waybar anyhow, it's been sitting at a 0% this whole time, it only changes when I use prime-run, so I believe you might be misunderstanding something, try reading the op again i specified my gpu.

**Comment by Rabcor** [comment] 2024-02-21 19:05
ok, I reset the config and tried again, new default wall is awesome. 

Out the gate Hyprland is using 0% gpu and 300MB vram. tells me that the high idle gpu use was something in my config, (I wonder if it's maybe attributing anything launched in my hyprland autostart options like waybar to hyprland or something, or it might just be some effect :thinking: gonna be fun to figure out what this is.)

If I switch between desktops a couple times it spikes all the way up to40% though which is quite massive and could probably lead to issues on weaker igpus.

Now for the ultimate test. adding a 4k screen to the mix...

And well, it feels somehow less bad than before, but it still causes all of hyprland to lag, it's particularly noticeable when I am switching workspaces, and it is a bit up and down, it's like it comes in waves, I start switching workspaces and it's super juddery, then I keep doing it and in a few seconds it becomes smooth again, then a few seconds more and it's lagging again....

What's interesting is that the GPU utilization doesn't appreciably rise any more than before I plugged in the 4k display, so it's not like it's resource starved this is something else.

I should probably also add in some notes about the TV, i've played games on it using mangohud, the game said 60fps, but it was super juddery on the tv, it was like it was 30fps. So I'm thinking maybe my HDMI cable isn't good enough or something (I'm not sure how best to check what the actual frequency of the tv is)? (It works completely fine if I'm watching something on it in MPV though)

But like i said, all of hyprland becomes laggy it's not just the tv, i'm mostly experiencing the lag on my main 1440p monitor, not really doing much on the tv, I just plugged it in and it has this effect.

It could be this is related to the frequency differences between the displays, my main display is 240hz the tv is at best 60hz at worst 30, maybe it's a corner case where the frequency difference is too high? maybe it's because a bad hdmi cable thrown in the mix is messing it up? I don't know i'm just making wild guesses here.

But at the final result at least is that the gpu use when idling on stock hyprland is fine, it's use for rendering effects like workspace switching is quite high though but nothing overly alarming really, still under 50%; but if I plug in the 4K tv, all Hyprland still starts lagging from it for some reason.

**Comment by vaxerski** [comment] 2024-02-21 19:24
since you are on an iGPU I am assuming clocks aren't ramping up high enough to support your 4k screen (on top of 4k animations being really tough to run on an igpu)

try forcing your igpu to high clocks.

Something that could be improved when I rework the frame scheduler

**Comment by Rabcor** [comment] 2024-02-21 20:15
> since you are on an iGPU I am assuming clocks aren't ramping up high enough to support your 4k screen (on top of 4k animations being really tough to run on an igpu)
> 
> try forcing your igpu to high clocks.
> 
> Something that could be improved when I rework the frame scheduler

Yeah, i ran `echo profile_peak | sudo tee /sys/class/drm/card1/device/power_dpm_force_performance_level` and it seems to have fixed the issue. So it's to do with clock speed.

**Comment by vaxerski** [comment] 2024-02-21 22:33
well then you gotta wait for me to implement a new frame scheduler (and hope it fixes the issue xd)

**Comment by Rabcor** [comment] 2024-02-22 01:42
> well then you gotta wait for me to implement a new frame scheduler (and hope it fixes the issue xd)

On the high idle gpu use, I've discovered that it is indeed caused by a Hyprland setting and not by anything i autostarted. Here are my findings.

Removing the following snippet:
```
  rounding = 8
         
  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.1

  drop_shadow=true
  shadow_range=6
  shadow_render_power = 1
  col.shadow = $color2
  col.shadow_inactive = 0x50000000
```
Increased the gpu utilization of hyprland by 30%, I didn't dig deeper because this isn't my actual issue (since i'm using this snippet anyways)

Removing this snippet:

```
animations {
  enabled = yes

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  bezier = linear, 0.0, 0.0, 1.0, 1.0
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = slow, 0, 0.85, 0.3, 1
  bezier = overshot, 0.7, 0.6, 0.1, 1.1
  bezier = bounce, 1.1, 1.6, 0.1, 0.85
  bezier = sligshot, 1, -1, 0.15, 1.25
  bezier = nice, 0, 6.9, 0.5, -4.20
  
  animation = windowsIn, 1, 5, slow, popin
  animation = windowsOut, 1, 5, winOut, popin
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 10, linear
  animation = borderangle, 1, 180, linear, loop #used by rainbow borders and rotating colors
  animation = fade, 1, 5, overshot
  animation = workspaces, 1, 5, wind
  animation = windows, 1, 5, bounce, popin
}
```
Changed the gpu utilization from 11/12% to 0/1% while idle.

disabling animations seemed to have absolutely no effect on gpu utilization (honestly seemed like it was just not doing anything)

removing the bezier lines had no effect

This line
`animation = borderangle, 1, 180, linear, loop #used by rainbow borders and rotating colors`

Was the culprit, shaved off 10+% off my gpu utilization (e.g. set it to 0-1% while idling)
