### ISSUE TITLE
Hyprland/Aquamarine fails to start wayland backend

### ISSUE THREAD

**Issue by bangconghuynh** [hyprwm/Hyprland#8685] opened 2024-12-09 11:07 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit 0a27af8cd190315c1f13363ebd11e83d30455d48  (crashreporter: avoid clang warning).
Date: Sun Dec 8 18:52:39 2024
Tag: v0.45.0-92-g0a27af8c, commits: 5525
built against:
 aquamarine 0.5.0
 hyprlang 0.5.3
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: lumen
Release: 6.12.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770] [8086:a780] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime
```

</details>

### Description

Hyprland no longer starts either from SDDM or from TTY. This is similar to what has been reported in #8676 but despite having the latest Linux kernel 6.12.3 (as of today, according to https://github.com/hyprwm/Hyprland/issues/8676#issuecomment-2526554011), the issue still remains. The attached crash report shows

```
[ERR] [AQ] Wayland backend cannot start: wl_display_connect failed (is a wayland compositor running?)
[ERR] [AQ] Requested backend (wayland) could not start, enabling fallbacks
[ERR] [AQ] Implementation wayland failed, erasing.
```

Both the latest upstream release (0.45.2-3) and the latest git commit as shown above give the same error.

Any help is much appreciated!

### How to reproduce

Launch Hyprland from TTY or SDDM with the packages and kernel as shown above

### Crash reports, logs, images, videos

[hyprlandCrashReport1486.txt](https://github.com/user-attachments/files/18060330/hyprlandCrashReport1486.txt)

**Comment by vaxerski** [comment] 2024-12-10 00:04
can you bisect?

**Comment by bangconghuynh** [comment] 2024-12-10 01:21
I can confirm that downgrading `mesa` from `24.3.1-1` to `24.2.7-1` allows Hyprland to be launched normally, so this issue seems to be the same as that in #8666.

I have attached the full debug stacktrace of the crash below if this helps.

[hyprland.log](https://github.com/user-attachments/files/18070119/hyprland.log)

**Comment by vaxerski** [comment] 2024-12-11 16:03
dupe of 8666 then and not our problem

**Closed by vaxerski** 2024-12-11 16:03 UTC
Labels: bug
