### ISSUE TITLE
Brave Browser sizing issue on launch

### ISSUE THREAD

**Issue by Ay1tsMe** [hyprwm/Hyprland#3472] opened 2023-10-02 07:13 UTC
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1  flags: (if any)

### Bug or Regression?

Bug

### Description

https://www.reddit.com/r/hyprland/comments/15daw1t/brave_browser_strange_size_problem/

This exact problem in this reddit post. When I launch brave browser for the first time on an empty screen, it has sizing issues and moving the window around fixes it.

### How to reproduce

Launch brave browser on wayland rather than x11

**Comment by vaxerski** [comment] 2023-10-02 11:21
dupe of #2588

**Closed by vaxerski** 2023-10-02 11:21 UTC
Labels: bug
