### ISSUE TITLE
EAC crash

### ISSUE THREAD

**Issue by patrulhasirius** [hyprwm/Hyprland#3956] opened 2023-11-25 17:48 UTC
### Hyprland Version

Hyprland, built from branch main at commit 3fe6162af1904f15fc5526c179c06a48265bdbff dirty (opengl: fix xray modes in introspection checks for ls). Tag: v0.32.3-68-g3fe6162a  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Hyprland crashes when trying to open EAC games with proton, tested with Squad and Battlebit, both on proton experimental and proton GE 8-23.

Following this [reddit post](https://www.reddit.com/r/hyprland/comments/13ke072/eac_launch_error_with_shatterline_squad/) I noticed that setting SDL_VIDEODRIVER,x11 prevents the crashes but also prevents eac from starting, removing this from the config reintroduces the crashes.

As a sanity check I disabled vrr and the crash still ocurred.

### How to reproduce

Open EAC game from steam with proton.

### Crash reports, logs, images, videos

[hyprlandCrashReport30187.txt](https://github.com/hyprwm/Hyprland/files/13464829/hyprlandCrashReport30187.txt)
[hyprlandCrashReport21115.txt](https://github.com/hyprwm/Hyprland/files/13464830/hyprlandCrashReport21115.txt)
[hyprlandCrashReport16358.txt](https://github.com/hyprwm/Hyprland/files/13464831/hyprlandCrashReport16358.txt)
[hyprlandCrashReport12667.txt](https://github.com/hyprwm/Hyprland/files/13464832/hyprlandCrashReport12667.txt)
[hyprlandCrashReport7684.txt](https://github.com/hyprwm/Hyprland/files/13464833/hyprlandCrashReport7684.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464840/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464841/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464842/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464843/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464844/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464845/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13464846/hyprland.log)

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/13464855/hyprland.conf.txt)

**Comment by vaxerski** [comment] 2023-11-25 19:42
dupe of #3937

**Closed by vaxerski** 2023-11-25 19:42 UTC
Labels: bug
