### ISSUE TITLE
Jetbrians IDEA miss focus very often while code completion popup appeares

### ISSUE THREAD

**Issue by firedes** [hyprwm/Hyprland#3012] opened 2023-08-18 09:59 UTC
### Hyprland Version

Hyprland, built from branch main at commit 7155b4c26606d7681bacb2517b1d19495336c6c3 dirty (renderer: Border improvements (2986)). Tag: v0.28.0-64-g7155b4c2

### Bug or Regression?

Bug

### Description

When this issue happens, I have to switch to some other windows and then switch back, or move cursor upon the popup, thus idea got focused again. This issue happens very often, especially when typing quickly.

BTW, this issue has been there for months, probably not raised by recent commits.

https://github.com/hyprwm/Hyprland/assets/16650765/2325f25d-bfee-4f04-9ca9-23381f66a388

### How to reproduce

Follow the video.
All rules for idea: 
```
windowrulev2 = forceinput,class:^(jetbrains-.*)$
windowrulev2 = windowdance,class:^(jetbrains-.*)$
```
IDEA setting: 
Editor -> general -> Code Completion -> unselect the Match case
Vim plugin installed

**Comment by pltanton** [comment] 2023-08-28 19:53
Still no workaround?

**Comment by vaxerski** [comment] 2023-08-28 22:18
No. My deepest apologies for not being a chatgpt powered AI that can work 24/7 at a speed of 10 humans combined.

**Comment by pltanton** [comment] 2023-08-28 22:38
We all truly appreciate your efforts!

While I understand that a workaround isn't an ultimate solution, there might be something we can do to enhance the usability of JetBrains xwaylandish products. It's possible that the author of the issue has already implemented a temporary fix to address the bug, which is why I'm asking.

As a suggestion one can use rule: `noinitialfocus,class:^(jetbrains-.*),title:^(win.*)`. This can make IDEA more usable, although you may need to manually focus on some inputs in popups from time to tim

**Comment by vaxerski** [comment] 2023-09-02 18:15
![image](https://github.com/hyprwm/Hyprland/assets/43317083/2cdfadd0-2fe1-4699-8503-aae874b37af6)
![image](https://github.com/hyprwm/Hyprland/assets/43317083/963eae6d-6be4-4034-9a8a-190e9d0731bc)

This looks like an intellij issue. It's saying that `winN` is a DIALOG. Dialogs get initial focus. That is NOT a dialog. It's a tooltip.

**Comment by woojiq** [comment] 2023-09-09 10:04
I know it's a crutch, but I'm just turning off the borders for intellij-idea. In any case, I almost always use intellij as the only application in the workspace, so I don't need to know what the current focus is.
``` conf
# Autocompletion, etc, take hyprland focus
windowrulev2 = noborder, class:^(jetbrains-idea)(.*)$
```

**Comment by Lassebq** [comment] 2023-09-13 18:58
Intellij is using swing/awt as window toolkit. This API is a default Java API, so unless it's fixed on the JVM side, intellij is not getting a fix.

**Comment by firedes** [comment] 2023-10-19 04:45
It seems that java native Wayland support leading by Jetbrains is making significant progress. Completely understanding that `vaxerski` is so annoyed by the maintenance of Xwayland, and feeling sorry that I don’t have time to contribute. So, maybe we just need to give Jetbrains some more time, thanks to Jetbrains for their efforts.
[Jetbrains Native Wayland support](https://youtrack.jetbrains.com/issue/JBR-3206)

**Comment by romanstingler** [comment] 2023-12-10 17:15
You guys can test wayland in jetbrains (test not officially launched yet) 
just use java 21 
SHIFT+CTRL+A => search for JAVA (Choose Boot Java Runtime) 
Select 21, it will be downloaded in the background 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/23abf6b6-0d12-474b-b4e5-ba7a64ba098f)

Help>Edit Custom VM Options 
add 
`-Dawt.toolkit.name=WLToolkit`
restart IDE 

PLEASE BE AWARE THIS IS EXPERIMENTAL

**Comment by vaxerski** [comment] 2023-12-11 17:41
how did you get 212? I only get `21+9-126.4`, which crashes if I add the wayland flag.

**Comment by vaxerski** [comment] 2023-12-11 17:54
although usable, has some issues. For example, shift+shift menu has no input.

**Comment by romanstingler** [comment] 2023-12-11 18:04
yes and clipboard doesn't work. 
They said the SHIFT SHIFT should be sorted out.
https://youtrack.jetbrains.com/issue/JBR-6145/Wayland-toolkit-Popup-windows-arent-focusable
https://youtrack.jetbrains.com/issue/JBR-3206/Native-Wayland-support

**Comment by vaxerski** [comment] 2023-12-11 18:20
is it a runtime issue or ij? dunno which to grab the -git of :P

**Comment by romanstingler** [comment] 2023-12-11 19:08
I just compiled the latest 21.b310 runtime https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jb21.0.1-b310.2
![2023-12-11-12:31:23](https://github.com/hyprwm/Hyprland/assets/5576250/7a9350b5-6132-4cc8-9f51-424c3ac588e5)

the stupid header is better now (not perfect but better) 
SHIFT SHIFT works. 
Clipboard works also 
I will test that further

**Comment by vaxerski** [comment] 2023-12-11 19:09
sounds promising. If IJ could get their shit together to work on wayland properly I might even consider CLion over VSC.

**Comment by romanstingler** [comment] 2024-07-25 11:03
not reproducible anymore

**Closed** 2024-07-25 11:13 UTC
Labels: bug
