### ISSUE TITLE
Support virtual keyboards: Steam

### ISSUE THREAD

**Issue by appsforartists** [hyprwm/Hyprland#3945] opened 2023-11-25 04:51 UTC
### Description

Steam exposes the Steam Deck's keyboard at menu+x on a gamepad when it's running in the background (e.g. via `steam -silent`).

It is not currently usable in Hyprland because it dispatches its events for X11.  [extest](https://github.com/Supreeeme/extest/) can be used as a workaround (but it's not yet packaged for NixOS, so I haven't been able to test it).

Unlike [maliit](https://github.com/hyprwm/Hyprland/issues/3943), it does draw an interactive keyboard on the screen.  However, it draws on a layer above Hyprland.  It would be nice if Hyprland could reflow its layout to acommodate the keyboard.

I don't know how much of these virtual keyboard feature requests are to be handled in code vs. configuration, but since so little is written about them on the internet, it behooves Hyprland touch users to have them tracked here.

**Comment by vaxerski** [comment] 2023-11-25 14:22
dupe of #3943

**Closed by vaxerski** 2023-11-25 14:22 UTC
Labels: enhancement
