### ISSUE TITLE
Workspace rule to set name of workspace

### ISSUE THREAD

**Issue by tmccombs** [hyprwm/Hyprland#4492] opened 2024-01-21 08:15 UTC
### Description

Basically, be able to do something like:

```
workspace = 1, name:default
```

So that you can associate a name with a specific workspace id, without having to have something that triggers a dispatch to rename it somehow.

**Comment by pdf** [comment] 2024-01-23 06:45
Duplicate of #665

**Closed** 2024-02-27 22:42 UTC
Labels: enhancement
