### ISSUE TITLE
Copy/Paste functionality not working

### ISSUE THREAD

**Issue by Jsinisin** [hyprwm/Hyprland#6148] opened 2024-05-19 03:21 UTC
### Hyprland Version

hyprland-git 0.40.0^42.gitf8857e6-1.fc40

### Bug or Regression?

Bug

### Description

I had hyprland-git installed. Updated to hyprland-git 0.40.0^42.gitf8857e6-1.fc40 and copy/paste functionality stopped working.
Uninstalled hyprland-git and installed hyprland 0.40.0-1 and copy/paste functionality returned.

Something in that 0.40.0^42 broke copy/paste.

### How to reproduce

Every time I install hyprland-git and upgrade to 0.40.0^42 I lose copy/paste functionality.

**Comment by gksudolol** [comment] 2024-05-19 06:08
duplicate of https://github.com/hyprwm/Hyprland/issues/6132 + no logs anyway

**Closed** 2024-05-19 06:11 UTC
Labels: bug

**Comment by ShelpAm** [comment] 2025-05-14 05:29
I can confirm this issue has been fixed in 0.49.0
