### ISSUE TITLE
Hold Down of key after running ModKey + key

### ISSUE THREAD

**Issue by techyporcupine** [hyprwm/Hyprland#2021] opened 2023-04-10 21:46 UTC
After running any bind that involves my mod key, and another key, it will continually spam the key until another is pressed.

* Steps to reproduce: Bind an action to your modkey + another key, and press those keys
* Expected outcome: Does what it is supposed to and nothing else; run that action (ex: pressing Mod + 1 to go to the first workspace)
* Noted outcome: Does what it is supposed to, but continues thinking the key (not mod key) is being pressed (ex: pressing Mod + 1 to go to the first workspace, having a text entry area highlighted, and getting many 1's continually being typed)

Doesn't crash anything, just is annoying.

**Comment by vaxerski** [comment] 2023-04-10 21:51
> Doesn't crash anything, just is annoying.

yeah no you are annoying I just closed this issue 10 minutes ago because I fixed it. Dupe of #2010

**Closed by vaxerski** 2023-04-10 21:51 UTC
Labels: bug
