### ISSUE TITLE
waybar select workspace regression since commit 287e6c

### ISSUE THREAD

**Issue by ElJeffe** [hyprwm/Hyprland#2101] opened 2023-04-19 13:02 UTC
I use waybar workspace module to switch between workspaces with my mouse. Since commit 287e6c4ede30c8e5e85863cd85f157e17e24879c this does not go as smooth as before. Sometimes I have to click two times or mode the mouse a bit before the click registers. The hover animation also does not seem to start immediately.

**Comment by tchofy** [comment] 2023-04-19 15:36
I can reproduce it as well, this behavior seems to be related to #1348, since right clicking somewhere on the bar "fixes" it for the next click.

**Comment by vaxerski** [comment] 2023-04-19 20:37
fixed in f914a5a06d75fcbdf53a03b820fcc8c0ff822b15

**Closed by vaxerski** 2023-04-19 20:37 UTC
Labels: bug
