### ISSUE TITLE
Random crash at exit

### ISSUE THREAD

**Issue by Edgars-Cirulis** [hyprwm/Hyprland#1975] opened 2023-04-07 11:01 UTC
Some apps are crashing when being exited, and are displaying a strange warning message. You can view an example of this at https://hastebin.com/share/itabimatid.ruby under MozCrashReason.

The same issue is occurring with QT apps, with the output being displayed in the console. This crash seems to be happening randomly, occurring whenever any app is closed using a keybind (killactive), such as when using Firefox or opening any app via terminal.

This bug appeared after a recent repository update.

https://user-images.githubusercontent.com/58264013/230597843-3cdd8898-2272-4525-87ae-bfb337ec2c83.png

**Comment by vaxerski** [comment] 2023-04-07 11:20
do a `git bisect` please if this is a regression

**Comment by Edgars-Cirulis** [comment] 2023-04-07 11:25
> do a `git bisect` please if this is a regression

Unfortunately, I cannot provide the information as my .cache has been cleared and I compiled it using the AUR Helper YAY. However, I can confirm that I did not compile hyprland from the AUR two days ago. Today, when I compiled it, this issue occurred.

**Comment by vaxerski** [comment] 2023-04-07 11:31
what's the problem in cloning the repo and using that?

**Comment by Edgars-Cirulis** [comment] 2023-04-07 11:34
> what's the problem in cloning the repo and using that?

lazy af, also, some weird backtrace when exiting hyprland

https://hastebin.com/share/asopunifik.less

**Comment by vaxerski** [comment] 2023-04-07 11:35
thats a dupe of #1965

**Comment by Edgars-Cirulis** [comment] 2023-04-07 11:38
> thats a dupe of #1965



> 1965

alright, what about this

Apr 07 14:28:40 arch systemd-coredump[28964]: Process 1510 (Hyprland) of user 1000 dumped core.
                                              
                                              Stack trace of thread 1510:
                                              #0  0x00007f1e25ea08ec n/a (libc.so.6 + 0x878ec)
                                              #1  0x00007f1e25e51ea8 raise (libc.so.6 + 0x38ea8)
                                              #2  0x00007f1e25e3b53d abort (libc.so.6 + 0x2253d)
                                              #3  0x00007f1e2609a833 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9a833)
                                              #4  0x00007f1e260a6d0c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa6d0c)
                                              #5  0x00007f1e260a6d79 _ZSt9terminatev (libstdc++.so.6 + 0xa6d79)
                                              #6  0x00007f1e260a6fdd __cxa_throw (libstdc++.so.6 + 0xa6fdd)
                                              #7  0x00007f1e2609fdb0 _ZNSt10filesystem9canonicalERKNS_7__cxx114pathE (libstdc++.so.6 + 0x9fdb0)
                                              #8  0x000056555284a82b _ZN13CrashReporter18createAndSaveCrashEi (/usr/bin/Hyprland (deleted) + 0xf882b)
                                              #9  0x00005655527e6c9c _ZZN11CCompositor26getLayerSurfaceFromSurfaceEP11wlr_surfaceENUlS1_iiPvE_4_FUNES1_iiS2_ (/usr/bin/Hyprland (deleted) + 0x94c9c)
                                              #10 0x0000565554d57f40 n/a (n/a + 0x0)
                                              #11 0x0000565555cf3080 n/a (n/a + 0x0)
                                              ELF object binary architecture: AMD x86-64
Apr 07 14:28:40 arch systemd[1]: systemd-coredump@1-28963-0.service: Deactivated successfully.

**Comment by Edgars-Cirulis** [comment] 2023-04-07 11:40
Just in case Firefox crashes when exiting the app, it shows me a bug report to Mozilla. The same thing happens with Qt apps with the same error (warning).

**Comment by vaxerski** [comment] 2023-04-07 11:56
Well I can't repro so I'll need a `git bisect`.

**Comment by Edgars-Cirulis** [comment] 2023-04-07 11:58
> Well I can't repro so I'll need a `git bisect`.

As I previously mentioned, can't help with that. So I'm assuimg issue is closed?

**Comment by vaxerski** [comment] 2023-04-07 11:58
keep it open, since it's not fixed, I'll wait for someone who can.

**Comment by Edgars-Cirulis** [comment] 2023-04-07 13:06
> keep it open, since it's not fixed, I'll wait for someone who can.

Seens like wayland issue, the same happened on kde by enabling wayland support.

AdapterDeviceID: 0x15d8
AdapterDriverVendor: mesa/radeonsi
AdapterDriverVersion: 23.0.1.0
AdapterVendorID: 0x1002
Add-ons: uBlock0%40raymondhill.net:1.48.4,formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,screenshots%40mozilla.org:39.0.1,webcompat%40mozilla.org:111.0.0,default-theme%40mozilla.org:1.3,addons-search-detection%40mozilla.com:2.0.0,google%40search.mozilla.org:1.3,amazondotcom%40search.mozilla.org:1.4,wikipedia%40search.mozilla.org:1.2,bing%40search.mozilla.org:1.4,ddg%40search.mozilla.org:1.3
AvailablePageFile: 759189504
AvailablePhysicalMemory: 5335613440
AvailableSwapMemory: 0
AvailableVirtualMemory: 5910233088
BackgroundTaskMode: 0
BuildID: 20230322001219
ContentSandboxCapabilities: 119
ContentSandboxCapable: 1
ContentSandboxLevel: 4
CrashTime: 1680872684
DOMFissionEnabled: 1
DOMIPCEnabled: 1
DesktopEnvironment: kde
EMCheckCompatibility: true
ExperimentalFeatures: devtools.inspector.compatibility.enabled
GpuSandboxLevel: 0
GraphicsNumActiveRenderers: 1
GraphicsNumRenderers: 0
HeadlessMode: 0
InstallTime: 1680871881
IsWayland: 1
LinuxUnderMemoryPressure: 0
MozCrashReason: warning: queue 0x7f1723ef8730 destroyed while proxies still attached:

Notes: FP(D00-L1000-W0000000-T010) WR? WR+ EGL? EGL- GL Context? GL Context+ WebGL? WebGL+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
ShutdownProgress: xpcom-shutdown
StartupCrash: 0
StartupTime: 1680872302
SubmittedFrom: Client
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20230322001219","version":"111.0.1","vendor":"Mozilla","displayVersion":"111.0.1","platformVersion":"111.0.1","xpcomAbi":"x86_64-gcc3","updaterAvailable":false},"partner":{"distributionId":"archlinux","distributionVersion":"1.0","partnerId":null,"distributor":"archlinux","distributorChannel":"firefox","partnerNames":["archlinux"]},"system":{"memoryMB":6871,"virtualMaxMB":null,"cpu":{"count":8,"cores":4,"vendor":"AuthenticAMD","name":"AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx","family":23,"model":24,"stepping":1,"l2cacheKB":512,"l3cacheKB":4096,"speedMHz":2100,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4A","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Linux","version":"6.2.9-zen1-1-zen","locale":"en-US"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"adapters":[{"description":"AMD Radeon Vega 8 Graphics (raven, LLVM 15.0.7, DRM 3.49, 6.2.9-zen1-1-zen)","vendorID":"0x1002","deviceID":"0x15d8","subsysID":null,"RAM":0,"driver":null,"driverVendor":"mesa/radeonsi","driverVersion":"23.0.1.0","driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1080}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"webrender":{"status":"available"},"wrCompositor":{"status":"blocked:FEATURE_FAILURE_DISABLE_RELEASE_OR_BETA"},"openglCompositing":{"status":"available"},"omtp":{"status":"unused"}}},"appleModelId":null,"hasWinPackageId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["en-US"],"regionalPrefsLocales":["en-US"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":false,"background":false},"userPrefs":{"app.shield.optoutstudies.enabled":false,"browser.fixup.alternate.enabled":false,"browser.search.region":"LV","browser.search.widget.inNavBar":false,"browser.urlbar.autoFill":true,"browser.urlbar.autoFill.adaptiveHistory.enabled":false,"browser.urlbar.dnsResolveSingleWordsAfterSearch":0,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":false,"browser.urlbar.suggest.quicksuggest.sponsored":false,"browser.urlbar.suggest.bestmatch":true,"media.gmp-gmpopenh264.lastInstallStart":1680871940,"media.gmp-gmpopenh264.lastDownload":1680871940,"media.gmp-gmpopenh264.lastUpdate":1680871940,"media.gmp-manager.lastCheck":1680871940,"network.trr.strict_native_fallback":false,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":4,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"loadPath":"[addon]google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="}},"profile":{"creationDate":19454,"firstUseDate":19454},"addons":{"activeAddons":{"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19437,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19437},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19437,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19437},"screenshots@mozilla.org":{"version":"39.0.1","scope":1,"type":"extension","updateDay":19437,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19437},"webcompat@mozilla.org":{"version":"111.0.0","scope":1,"type":"extension","updateDay":19437,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19437},"uBlock0@raymondhill.net":{"version":"1.48.4","scope":1,"type":"extension","updateDay":19454,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Finally, an efficient blocker. Easy on CPU and memory.","name":"uBlock Origin","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19454,"signedState":2}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"Follow the operating system setting for buttons, menus, and windows.","name":"System theme — auto","userDisabled":false,"appDisabled":false,"version":"1.3","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19454,"updateDay":19454},"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.8.1.2","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.2557.0","userDisabled":false,"applyBackgroundUpdates":1}}},"services":{"accountEnabled":true,"syncEnabled":true}}
Throttleable: 1
TotalPageFile: 7204982784
TotalPhysicalMemory: 7204982784
URL: about:newtab
UptimeTS: 381.979239
UtilityProcessStatus: Destroyed
Vendor: Mozilla
Version: 111.0.1
XPCOMSpinEventLoopStack: default: nsThread::Shutdown: Renderer
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by Edgars-Cirulis** [comment] 2023-04-07 13:10
https://archlinux.org/packages/extra/x86_64/wayland/ had update 1 dy ago.

**Comment by Edgars-Cirulis** [comment] 2023-04-07 13:12
this bug can be optined by setting thoes env flags on hyprland

GDK_BACKEND,wayland,x11
QT_QPA_PLATFORM,wayland;xcb

**Comment by Edgars-Cirulis** [comment] 2023-04-07 13:23
Made bug report on Wayland side
https://gitlab.freedesktop.org/wayland/wayland/-/issues/374

**Comment by vaxerski** [comment] 2023-04-07 13:59
alright, closing here then, issue upstream

**Closed by vaxerski** 2023-04-07 13:59 UTC
Labels: bug
