### ISSUE TITLE
Hyprland Crashes to Login Manager During Sleep/Sleep

### ISSUE THREAD

**Issue by jrock2004** [hyprwm/Hyprland#1531] opened 2023-02-12 00:53 UTC
When my computer locks via swaylock and I come back a few hours later, I move the mouse and the computer wakes up and I am at the GDM login screen. I am able to log back in fine but I think I should not be logged out

# Hyprland Log
What is the best way to upload log as lines are too long??????

# Core Dump
           PID: 1499 (Hyprland)
           UID: 1000 (jcostanzo)
           GID: 1000 (jcostanzo)
        Signal: 11 (SEGV)
     Timestamp: Thu 2023-02-09 09:30:14 EST (2 days ago)
  Command Line: Hyprland
    Executable: /usr/bin/Hyprland
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (jcostanzo)
       Boot ID: 5074e0d78f1f4cca8f743c67b07887ed
    Machine ID: c84ac3582aaa4fa190caa585ceab6ff9
      Hostname: system76
       Storage: /var/lib/systemd/coredump/core.Hyprland.1000.5074e0d78f1f4cca8f743c67b07887ed.1499.1675953014000000.zst (present)
  Size on Disk: 12.9M
       Message: Process 1499 (Hyprland) of user 1000 dumped core.

                Stack trace of thread 1499:
                #0  0x00007fa6439f874d wlr_addon_find (libwlroots.so.12032 + 0xa074d)
                #1  0x00007fa643a02299 wlr_xwayland_surface_try_from_wlr_surface (libwlroots.so.12032 + 0xaa299)
                #2  0x000055bc1618ede5 _ZN20CHyprXWaylandManager15activateSurfaceEP11wlr_surfaceb (Hyprland + 0x100de5)
                #3  0x000055bc160d16de _ZN11CCompositor12focusSurfaceEP11wlr_surfaceP7CWindow (Hyprland + 0x436de)
                #4  0x000055bc1618d1c0 _ZL16handleSurfaceMapPvS_ (Hyprland + 0xff1c0)
                #5  0x000055bc1615eadc _Z13handleWrappedP11wl_listenerPv (Hyprland + 0xd0adc)
                #6  0x00007fa64385ff6e wl_signal_emit_mutable (libwayland-server.so.0 + 0x9f6e)
                #7  0x00007fa6439d5a0b surface_commit_state (libwlroots.so.12032 + 0x7da0b)
                #8  0x00007fa642cc64f6 n/a (libffi.so.8 + 0x74f6)
                #9  0x00007fa642cc2f5e n/a (libffi.so.8 + 0x3f5e)
                #10 0x00007fa642cc5b73 ffi_call (libffi.so.8 + 0x6b73)
                #11 0x00007fa64385eada n/a (libwayland-server.so.0 + 0x8ada)
                #12 0x00007fa64386301c n/a (libwayland-server.so.0 + 0xd01c)
                #13 0x00007fa6438619e2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xb9e2)
                #14 0x00007fa643862197 wl_display_run (libwayland-server.so.0 + 0xc197)
                #15 0x000055bc160c440d main (Hyprland + 0x3640d)
                #16 0x00007fa643134790 n/a (libc.so.6 + 0x23790)
                #17 0x00007fa64313484a __libc_start_main (libc.so.6 + 0x2384a)
                #18 0x000055bc160cdf15 _start (Hyprland + 0x3ff15)

                Stack trace of thread 1523:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)
                Stack trace of thread 1519:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1528:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1522:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1517:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1531:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1521:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1524:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1530:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1520:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1527:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1532:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1532:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1533:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1529:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1534:
                #0  0x00007fa64321a8bf accept (libc.so.6 + 0x1098bf)
                #1  0x000055bc16179f93 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN13CEventManager11startThreadEvEUlvE_EEEEE6_M_runEv (Hyprland + 0xebf93)
                #2  0x00007fa6434d72c3 execute_native_thread_routine (libstdc++.so.6 + 0xd72c3)
                #3  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #4  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 1518:
                #0  0x00007fa643193766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fa643195f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fa63d50c47e n/a (iris_dri.so + 0x10c47e)
                #3  0x00007fa63d4bc84c n/a (iris_dri.so + 0xbc84c)
                #4  0x00007fa63d50c3ac n/a (iris_dri.so + 0x10c3ac)
                #5  0x00007fa643196bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fa643218d90 n/a (libc.so.6 + 0x107d90)
                ELF object binary architecture: AMD x86-64

# Hyprland Configfile

[Hyprland.config](https://raw.githubusercontent.com/jrock2004/dotfiles/main/files/.config/hypr/hyprland.conf)

**Comment by vaxerski** [comment] 2023-02-12 10:35
dupe of #1519

**Closed by vaxerski** 2023-02-12 10:35 UTC
Labels: bug
