### ISSUE TITLE
when in group, open float window will be auto grouped, lost the float state

### ISSUE THREAD

**Issue by mogamireiki** [hyprwm/Hyprland#8089] opened 2024-10-12 02:28 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: noire
Release: 6.10.13-ml3-125
Version: #1 SMP PREEMPT_DYNAMIC Tue Oct  8 22:51:32 CST 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2070] [10de:1f02] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  550.107.02  Wed Jul 24 23:53:00 UTC 2024


os-release: NAME="Mogami Linux"
PRETTY_NAME="Mogami Linux"
VERSION="3"
VERSION_ID="3"
ID="mogami-linux"
ANSI_COLOR="1;36"


plugins:
  hyprfocus by Vortex ver 2.0

```

</details>

### Description

After update to 0.44.0
when the focus in a window in some group,
use shortcut open another float window,
the new window will be grouped, this time its **float** status is lost,
before 0.44.0 its just floated

the new window's float attr is controlled by:
`windowrulev2 = float,class:^(pavucontrol(-qt)?)$`

if the focus is not in some grouped window,
this time open some float window by shortcut is like before hyprland version

I know 0.44.0 add option **group:auto_group = true**,
but when turn it off, **all window** opened will not be grouped,
not just the **float window** I needed,

or does there are other options i dont find?

### How to reproduce

* open a window(e.g. konsole), and create group on it
* move focus to the grouped konsole window
* use keyboard shortcut open another float window

**Comment by Aqa-Ib** [comment] 2024-10-12 07:11
if I understand you correctly, this rule is what you want:
` windowrulev2 = group barred,floating:1`

**Comment by izmyname** [comment] 2024-10-12 07:46
> if I understand you correctly, this rule is what you want: `windowrulev2 = group barred,floating:1` this will prevent new floating windows from being auto grouped.

IMO, this should be a default behaviour for floating windows.

**Comment by Aqa-Ib** [comment] 2024-10-12 07:54
> IMO, this should be a default behaviour for floating windows.

That would be bad and non-consistent for people that like to work with floating groups.

> UPD. And this doesn't work. Floating protonup-qt windows opens in a group, regardless.

I don't know what you are doing but it does work indeed.

**Comment by izmyname** [comment] 2024-10-12 07:58
> I don't know what you are doing but it does work as expected on my end.

1. add a windowrule you mentioned, or the same, but with group deny instead of barred
2. Open protonup-qt

```
windowrulev2=float,class:(net.davidotek.pupgui2)$
windowrulev2=size 600 600,  class:(net.davidotek.pupgui2)$
windowrulev2=center, class:(net.davidotek.pupgui2)$
```

3. Protonup-Qt opens in a group, regardless, windowrule ignored.

This is the case with any floating window.

**Comment by Aqa-Ib** [comment] 2024-10-12 08:00
you are using `class` instead of `initialClass` for that program

**Comment by Aqa-Ib** [comment] 2024-10-12 08:05
You are messing up somehow, it is working for me as expected (I tried protonup-qt also).

> I think people, who expect a floating window float under any circumstances, are the majority .

We could check that if the target group is tiled, and the new window is floated, dont autogroup though.

**Comment by izmyname** [comment] 2024-10-12 08:09
> You are messing up somehow, it is working for me as expected (I tried protonup-qt also with your rules).

This doesn't help, unfortunately.

Also, iirc, floating windows didn't behave, like that, back on 0.43

**Comment by Aqa-Ib** [comment] 2024-10-12 08:11
> This doesn't help, unfortunately.

Are you using this rule as-is or else? `windowrulev2 = group barred,floating:1`

> Also, iirc, floating windows didn't behave, like that, back on 0.43

Correct.

**Comment by izmyname** [comment] 2024-10-12 08:13
> Are you using this rule as-is or else? `windowrulev2 = group barred,floating:1`

Yes. Also, i tried group deny and  adding `class:^$,title:^$,` to no avail

**Comment by Aqa-Ib** [comment] 2024-10-12 08:14
Paste your rule here as-is please.

**Comment by izmyname** [comment] 2024-10-12 08:16
> Paste your rule here as-is please.

`windowrulev2 = group barred,floating:1 `

`windowrulev2 = group den ,floating:1 `

`windowrulev2 = group barred,class:^$,title:^$,floating:1 `

That I tried so far.

**Comment by Aqa-Ib** [comment] 2024-10-12 08:20
You may have some other rule in your config file that is messing up things. It is working for me as expected with the rules that you have pasted until now. Except this rule of yours is bad though` windowrulev2 = group barred,class:^$,title:^$,floating:1 ` it is targetting a window with no class and no titlte.

**Comment by izmyname** [comment] 2024-10-12 08:23
> You may have some other rule in your config file

<details>
```
 Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

#layer rules
layerrule = blur,launcher
layerrule = ignorezero, launcher
layerrule = dimaround, launcher
layerrule = blur, notifications
layerrule = ignorezero, notifications
layerrule = blur, bar
layerrule = ignorezero, bar

#all windows
windowrulev2=suppressevent maximize, class:.* # You'll probably like this.
windowrulev2=nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0 #Fix some dragging issues with XWayland
windowrulev2=idleinhibit fullscreen, fullscreen:1 #do not idleinhibit if there's a fullscreen window
windowrulev2=dimaround, floating:1 #force focus on a last opened floating window and dim the screen around it

#single rule windows
windowrulev2=nodim,title:(tty-clock)$ #never dim tty-clock terminal window

#Appimage - ProtonUp-Qt
windowrulev2=float,class:(net.davidotek.pupgui2)$
windowrulev2=size 600 600,  class:(net.davidotek.pupgui2)$
windowrulev2=center, class:(net.davidotek.pupgui2)$

#bluetoothctl, if launched by clicking on waybar bluetooth module
windowrulev2=float,title:(bluetooth control)$
windowrulev2=size 800 800,title:(bluetooth control)$
windowrulev2=center,title:(bluetooth control)$

#nnn preview-tui plugin
windowrulev2=nofocus, title:(preview-tui)$ 
windowrulev2=nodim, title:(preview-tui)$ 
windowrulev2=group deny, title:(preview-tui)$

#xdg-desktop-portal-gtk
windowrulev2=float, class:(xdg-desktop-portal-gtk)$
windowrulev2=size 800 600,  class:(xdg-desktop-portal-gtk)$

#htop
windowrulev2=float, title:(htop)$
windowrulev2=size 1400 800, title:(htop)$
windowrulev2=center,title:(htop)$
```</details>

**Comment by Aqa-Ib** [comment] 2024-10-12 08:25
Paste your entire config file if you want me to help you.

**Comment by izmyname** [comment] 2024-10-12 08:29
> **Attach** your config file if you want me to help you.

I can't, because of this
![slurp_screenshot](https://github.com/user-attachments/assets/ea8ecf63-29d2-423f-a105-41b223f413f5)


I can suggest you to check my dotfiles, in this case.
https://github.com/izmyname/home-backup-main/tree/main/.config/hypr

**Comment by Aqa-Ib** [comment] 2024-10-12 08:55
I will make a pull request resolving this in a way that benefits everyone.

**Comment by Aqa-Ib** [comment] 2024-10-12 09:10
Nevermind, I thought about it and it is not possible to benefit everyone.

I think that using `windowrulev2 = group barred,floating:1` is the best approach here.

**Comment by izmyname** [comment] 2024-10-12 09:28
> I think that using `windowrulev2 = group barred,floating:1` is the best approach here.

Not for everyone, as we can see.  Especially, as I previously said, floating windows being always floating is the most logical and expected behaviour by the majority of people, just like it was on 0.43.

**Comment by Aqa-Ib** [comment] 2024-10-12 09:33
What you don't want is a floated window automatically merging into a tiled group. That behavior can be resolved with `windowrulev2 = group barred,floating:1`.

If we go back to 0.43 behavior, people would not be able to create new windows into a floating group, which is a good feature to have for a lot of people, and that behavior can't be achieved with any window rule.

**Comment by izmyname** [comment] 2024-10-12 09:41
> What you don't want is a new floated window automatically merging into a tiled group. That behavior can be achieved with `windowrulev2 = group barred,floating:1`.

Or can't, in my case.



> If we go back to 0.43 behavior, people would not be able to create new windows into a floating group, which is a good feature to have for a lot of people, and that behavior couldn't be achieved by any window rule.

Good, but adds extra complexity to recreate expected behaviour for people, who want to use a tiling compositor as a stacking one.

The compromise would be adding that windowrule to the default hyprland.conf, like supressevent and that weird Xwayland windows fix, but since the rule does not work for me  (and, probably, for someone else) for no apparent reason - I'm not sure.

**Comment by Aqa-Ib** [comment] 2024-10-12 09:43
> The compromise would be adding that windowrule to the default hyprland.conf

That would add a non-consistent behavior with floating groups that is not intuitive at all.

**Comment by izmyname** [comment] 2024-10-12 09:47
> That would add a non-consistent behavior with floating groups that is not intuitive at all.
And the new floating windows default behaviour is unintuitive, either, and this issue is a living proof to it. At least, with the default config solution, it can be briefly explained with a commit.

**Comment by Aqa-Ib** [comment] 2024-10-12 09:57
> And the new floating windows default behaviour is unintuitive, either, and this issue is a living proof to it.

This is a niche issue that only reproduce if:
1. you have a tiled group focused and unlocked.
2. you create a new floated window using a window rule
3. you don't want it to be merged into the group.

Having a default consistent behavior between floated and tiled groups is better in my opinion.

**Comment by Aqa-Ib** [comment] 2024-10-12 10:07
Another fix to this issue is locking the focused tiled group before you open your new floating window.

**Comment by izmyname** [comment] 2024-10-12 10:09
I think, 2 and 3 are rather standard conditions and the whole point of having some windows floating, in the first place.

Consistency is good, but since Hyprland is a tiling compositor, and I dare to suggest - there are not too many people, using floated groups because of this (they'd rather choose to use something with stacking layout), altering the default and predictable windows behaviour for a niche usecase wasn't worth it. But this is my opinion.



> Another fix to this issue is locking the focused tiled group before you open your new floating window.

I already fixed it, by adding group deny rule for each floating windows. Thankfully, I don't have too many.

**Comment by Aqa-Ib** [comment] 2024-10-12 10:13
Also another fix would be to just focus another window that is not a unlocked group. This is a consistent behavior in Hyprland, I think that the default is actually good.

**Comment by izmyname** [comment] 2024-10-12 10:17
It's not good, by judging - how many workarounds and fixes have been suggested just to make groups and floating windows behave in the most logical way, like they always behaved in the past, without any extra steps.

**Comment by Aqa-Ib** [comment] 2024-10-12 10:19
They are not workarounds, I am just pointing at the default behavior that Hyprland has since the first group rework that happened in early 2023. Version 0.44 just added consistency for floating groups.

**Comment by mogamireiki** [comment] 2024-10-13 00:59
> if I understand you correctly, this rule is what you want: `windowrulev2 = group barred,floating:1` this will prevent new floating windows from being auto grouped.

that's it!
this worked for me, Thank you very much!

**Closed** 2024-10-13 01:00 UTC
Labels: bug

**Comment by Aqa-Ib** [comment] 2024-10-13 17:12
@izmyname I am sorry, yesterday my mind was not clear. This PR fixes this issue without using any window rule and without harming any workflow: https://github.com/hyprwm/Hyprland/pull/8108

**Comment by izmyname** [comment] 2024-10-13 17:49
> @izmyname I am sorry, yesterday my mind was not clear. This PR fixes this issue without using any window rule and without harming any workflow: https://github.com/hyprwm/Hyprland/pull/8108

All good. Thank you for the pr!

**Comment by Aqa-Ib** [comment] 2024-10-14 09:01
@mogamireiki with commit [e7fd0f5](https://github.com/hyprwm/Hyprland/commit/e7fd0f5aec85c11a8eaf5e1abf8504f0a6d0710e) you don't need any window rule to fix this issue.

**Comment by mogamireiki** [comment] 2024-10-15 21:52
@Aqa-Ib Thank you!
