### ISSUE TITLE
Artifacts in blur when bitdepth set to 10

### ISSUE THREAD

**Issue by ronasimi** [hyprwm/Hyprland#3822] opened 2023-11-10 23:37 UTC
### Hyprland Version

Hyprland, built from branch HEAD at commit 751d2851cc270c3322ffe2eb83c156e4298a0c0e  (props: bump ver to 0.32.0). Tag: v0.32.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Since upgrading to 0.32, when bitdepth is set to 10 I get weird artifacts on blurred surfaces.  Setting bitdepth to 8 fixes the issue.
![2023-11-10T18:32:21,846319302-05:00](https://github.com/hyprwm/Hyprland/assets/3991859/576fdfbb-3b83-4418-a69b-f9e0ea5c2c43)

### How to reproduce

Install 0.32, set bitdepth to 10

**Comment by vaxerski** [comment] 2023-11-10 23:42
shadows were fixed in 14195835ef1dd25e10b0d873ec75c004b238ccba

can you check on -git?

I am unsure what would be the case with the bar, though.

**Comment by ronasimi** [comment] 2023-11-10 23:46
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/13323795/hyprland.conf.txt)

Also noticed that transparent borders in 0.32 have a weird outline and are totally visible...  Can post screenshot if needed

**Comment by vaxerski** [comment] 2023-11-10 23:58
we migrated to `GL_RGB10_A2` (aka `GL_UNSIGNED_INT_2_10_10_10_REV`) in 0.32.0, which means everything is now _actually_ rendered in 10-bit (it wasn't truly before)

However, 10-bit formats are annoying a bit with the alpha channel, thus such errors.

Please check on -git, as I've fixed a few since 0.32.0. Generally 32.1 should come some time soon.

**Comment by ronasimi** [comment] 2023-11-10 23:58
Same issue on -git, new screenshot showing issue with transparent border as well
![2023-11-10T18:56:13,570583627-05:00](https://github.com/hyprwm/Hyprland/assets/3991859/79c4be43-f5be-4173-ada7-8cb991a3924b)

**Comment by vaxerski** [comment] 2023-11-10 23:58
hey but the shadow is fixed!

What's that bar?

**Comment by ronasimi** [comment] 2023-11-10 23:59
waybar

**Comment by vaxerski** [comment] 2023-11-10 23:59
and what's wrong with the borders? they look just fine to me?

**Comment by ronasimi** [comment] 2023-11-11 00:00
They're transparent (#27272700) and the shadow isn't drawn under them? weird outline

**Comment by vaxerski** [comment] 2023-11-11 00:01
ah, yes. That's been changed recently, on purpose. Shadows now render around the borders.

**Comment by vaxerski** [comment] 2023-11-11 00:06
![image](https://github.com/hyprwm/Hyprland/assets/43317083/f82a9c92-22d7-427b-9b5f-d2d63d50119a)
hm, can't repro with waybar. Any other setting that affects this?

**Comment by vaxerski** [comment] 2023-11-11 00:36
it's backwards compatible. Both do the same. FYI blurls is the old one.

**Comment by ronasimi** [comment] 2023-11-11 00:37
On igpu, broadwell

**Comment by vaxerski** [comment] 2023-11-11 00:37
broadwell?

**Comment by ronasimi** [comment] 2023-11-11 00:37
5th gen core, if gpu matters

**Comment by vaxerski** [comment] 2023-11-11 00:38
ah, no. Shouldn't.

**Comment by ronasimi** [comment] 2023-11-11 00:42
[config.txt](https://github.com/hyprwm/Hyprland/files/13323950/config.txt)
[style.css.txt](https://github.com/hyprwm/Hyprland/files/13323951/style.css.txt)
[waybar.sh.txt](https://github.com/hyprwm/Hyprland/files/13323952/waybar.sh.txt)

Doesn't happen with windows, although shadows have some artifacts as well

**Comment by vaxerski** [comment] 2023-11-11 00:44
shadow artifacts should be fixed on -git, and your screenshot did show that.

**Comment by ronasimi** [comment] 2023-11-11 00:45
Attaching a screenshot of 0.32, and you're right about the shadows on -git, I forgot.  I've included transparent kitty windows and wofi as well, they don't seem to have the issue...
![2023-11-10T19:43:30,940681077-05:00](https://github.com/hyprwm/Hyprland/assets/3991859/22932f68-4c22-4e15-948f-690f7b231250)

**Comment by vaxerski** [comment] 2023-11-11 00:47
![image](https://github.com/hyprwm/Hyprland/assets/43317083/0bd2ad2a-f362-4b6f-9847-80bf192ce89c)

¯\_(ツ)_/¯

![image](https://github.com/hyprwm/Hyprland/assets/43317083/d072aaaa-f762-4a46-aa71-9b590c5eb765)

all your configs, bitdepth 10

**Comment by ronasimi** [comment] 2023-11-11 00:49
Well that's certainly odd

**Comment by vaxerski** [comment] 2023-11-11 00:53
are you on legacy_renderer?

**Comment by ronasimi** [comment] 2023-11-11 00:54
no

**Comment by vaxerski** [comment] 2023-11-11 00:58
No clue. You'll have to narrow down the behavior more. I can whip up a dirty patch for you that will fix it at the cost of vram and a bit of performance, but it's not an ideal solution.

it'd be great if I could reproduce, too. I might check on my laptop to be sure tomorrow, it's 10 bit too. Maybe in a nest this doesn't manifest but does on a real session?

**Comment by vaxerski** [comment] 2023-11-11 00:59
[patch.txt](https://github.com/hyprwm/Hyprland/files/13323993/patch.txt)

here, I am pretty sure this will fix it. Hacky as fuck.

**Comment by ronasimi** [comment] 2023-11-11 01:08
I'll give it a shot in a bit

**Comment by ronasimi** [comment] 2023-11-11 01:28
Still getting artifacts, but I've discovered that it must be an interaction with shadows. I've attached a screenshot with a window and without a window
![2023-11-10T20:26:18,073300276-05:00](https://github.com/hyprwm/Hyprland/assets/3991859/d6a3cc5a-bc4c-4e82-9936-cbf26f929a15)
![2023-11-10T20:26:20,508583770-05:00](https://github.com/hyprwm/Hyprland/assets/3991859/d07857de-b57b-4163-afc4-aa56a89e34ac)

**Comment by vaxerski** [comment] 2023-11-11 14:44
I still can't repro :/

You seeing the artifacts *WITH* the patch????

are you sure you are running the correct hyprland binary? AUR installs to a different place than manual builds IIRC, so you might have duplicate. Check with `whereis Hyprland`

**Comment by shot-codes** [comment] 2023-12-07 22:20
> ah, yes. That's been changed recently, on purpose. Shadows now render around the borders.

Heya @vaxerski, just to be clear, the behavior of shadows being drawn outside of the borders (even when they are transparent) as they appear in the above screenshots is intended?

**Comment by vaxerski** [comment] 2023-12-08 15:46
why not change the border size to 0?

**Comment by shot-codes** [comment] 2023-12-08 16:17
Because I want a border for the active window

**Comment by vaxerski** [comment] 2023-12-08 16:45
`windowrule = bordersize 0, focus: 0`?

**Comment by Eclextic** [comment] 2023-12-08 21:53
Here a video caused by the same issue...

Happens with bitdepth set to 10 and when entering a special workspace with blur enabled!

https://github.com/hyprwm/Hyprland/assets/81909104/97dc0362-9d5e-4e11-a059-6db7f7cde9c5


See the weird flickering? Yea...
Also the video doesn't really correctly capture how bad this actually looks...


So here's a picture!
![screenshot tmp](https://github.com/hyprwm/Hyprland/assets/81909104/b91f34cb-d907-4dcd-a472-88a3b3f1852b)
(Shouldn't look like this...)

**Comment by shot-codes** [comment] 2023-12-09 00:56
> `windowrule = bordersize 0, focus: 0`?

Hmm, I must be missing something. This doesn't seem to have any effect for me.

**Comment by vaxerski** [comment] 2023-12-09 04:01
make sure you're on -git, focus: was added today

**Comment by Eclextic** [comment] 2023-12-09 12:47
> Here a video caused by the same issue...
> 
> Happens with bitdepth set to 10 and when entering a special workspace with blur enabled!
> output.mp4
> 
> See the weird flickering? Yea... Also the video doesn't really correctly capture how bad this actually looks...
> 
> So here's a picture! ![screenshot tmp](https://private-user-images.githubusercontent.com/81909104/289197639-b91f34cb-d907-4dcd-a472-88a3b3f1852b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjYzMTAsIm5iZiI6MTcwMjEyNjAxMCwicGF0aCI6Ii84MTkwOTEwNC8yODkxOTc2MzktYjkxZjM0Y2ItZDkwNy00ZGNkLWE0NzItODhhM2IzZjE4NTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEyNDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZjI3ZDg3MmZhMmM4OTBhNzFlYzI2NzM1Zjc1ZTc3OTFiMzhjZWY5YTA0MjMyZTkzYmVkZDUxZDUxNTk1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h95jIAPwnqDg4eFWf0GJLCteBoDpSnt6w_RSi2weyF0) (Shouldn't look like this...)

Video is now up!

**Comment by shot-codes** [comment] 2023-12-09 14:11
> make sure you're on -git, focus: was added today
Thanks, I wasn't on -git but am now. Unfortunately this isn't a good solution as it causes a resize to the windows when changing focus that is very jarring. I didn't mean to highjack this issue so I will create a new one

**Comment by vaxerski** [comment] 2024-05-15 23:32
is this still a thing?

**Comment by ronasimi** [comment] 2024-05-16 00:10
I'm not seeing the issue on recent releases

**Comment by vaxerski** [comment] 2024-05-16 01:14
closing then

**Closed by vaxerski** 2024-05-16 01:14 UTC
Labels: bug
