### ISSUE TITLE
on-created-empty doesn't respect movetoworkspace special (maybe wanted behaviour)

### ISSUE THREAD

**Issue by h0useofdupree** [hyprwm/Hyprland#5721] opened 2024-04-23 19:26 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ea47e8c92ae283c4b41be0aafbdad9b0701a1624  (Fractional-scale: move to new impl).
Date: Sat Apr 20 15:19:16 2024
Tag: v0.39.1-13-gea47e8c9, commits: 4473

flags: (if any)


System Information:
System name: Linux
Node name: nexus
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
12:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev cb) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
  hyprbars by Vaxry ver 1.0
  hyprexpo by Vaxry ver 1.0
  Hyprspace by KZdkm ver 0.1
  hyprfocus by Vortex ver 2.0
```

</details>

### Bug or Regression?

Bug

### Description

When a window is moved to special workspace with the on-created-empty rule, the command specified executes anyway.

This could be the expected behaviour, but to me, it's not. So I don't know if I should make this a feature request. For me, the workspace should not "be created empty" when a window is moved there, as that window should be the first window.

### How to reproduce

1. Set workspace rule 
```workspace = special, on-created-empty:kitty```
2. Move window to special workspace  
```bind = $MAIN_MOD SHIFT, code:20, movetoworkspace, special```

**Comment by yassineibr** [comment] 2024-04-28 12:23
i think this issues is a duplicate of https://github.com/hyprwm/Hyprland/issues/5663

**Comment by vaxerski** [comment] 2024-04-28 22:11
ya

**Closed by vaxerski** 2024-04-28 22:11 UTC
Labels: bug
