### ISSUE TITLE
When you sleep/suspend and wake up sometimes hyprland changes workspace

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#2055] opened 2023-04-14 11:36 UTC
When I sleep my system with systemctl if I am on the first workspace then when I resume Hyprland is on the 3rd (which in this case is the fisst workspace without application windows open), their is no animation shown both when sleeping and resuming.
I would expect Hyprland to stay on the workspace that it was on when I suspended.
**Config file:**
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11232283/hyprland.conf.txt)
**Log file:**
[hyprland.log](https://github.com/hyprwm/Hyprland/files/11232305/hyprland.log)

**Comment by vaxerski** [comment] 2023-04-14 12:35
dupe of #1980

**Closed by vaxerski** 2023-04-14 12:35 UTC
Labels: bug

**Comment by LucasTran380381** [comment] 2024-11-12 02:54
Still have this problem. I use 1 monitor

**Comment by oluijks** [comment] 2024-12-25 07:03
Imy having this issue as well. When waking up it starts on ws5 and I only have 4 configured. Also the apps on the first ws are gone but that is another issue I think...
