### ISSUE TITLE
Different size of gaps_out on all sides

### ISSUE THREAD

**Issue by smravec** [hyprwm/Hyprland#768] opened 2022-10-03 14:40 UTC
It would be nice if you could specify size of gaps_out on each side separately e.g. (gap_out left could be 20, gap_out down 10...).
In the config file you could do gaps_out=5,10,10,8

**Comment by vaxerski** [comment] 2022-10-03 14:42
dupe of #148

**Closed by vaxerski** 2022-10-03 14:42 UTC
Labels: enhancement
