### ISSUE TITLE
Fullscreen apps cap to refresh rate when tearing is enabled

### ISSUE THREAD

**Issue by ethanh20009** [hyprwm/Hyprland#8482] opened 2024-11-15 19:19 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit 098e491a43e8b26f4382b48651a4131464bf6a2f  (protocols: mark primarySelection as not privileged).
Date: Fri Nov 15 00:47:34 2024
Tag: v0.45.0-23-g098e491a, commits: 5456
built against aquamarine 0.4.5


flags set:
debug


System Information:
System name: Linux
Node name: archlinux
Release: 6.12.0-rc7-1-cachyos-rc
Version: #1 SMP PREEMPT_DYNAMIC Mon, 11 Nov 2024 13:14:27 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD103 [GeForce RTX 4080] [10de:2704] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  565.57.01  Release Build  (cachyos-builder@)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/ethan/.config/hypr/hyprland.conf: Read Succeeded
#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
#  
# ----------------------------------------------------- 

# ----------------------------------------------------- 
# Monitor
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/monitor.conf

# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/autostart.conf

# ----------------------------------------------------- 
# Cursor
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/cursor.conf

# ----------------------------------------------------- 
# Environment
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/environment.conf

# ----------------------------------------------------- 
# Keyboard
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/keyboard.conf

# ----------------------------------------------------- 
# Load pywal color file
# ----------------------------------------------------- 
source = ~/.cache/wal/colors-hyprland.conf

# ----------------------------------------------------- 
# Load configuration files
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/window.conf
source = ~/dotfiles/hypr/conf/decoration.conf
source = ~/dotfiles/hypr/conf/layout.conf
source = ~/dotfiles/hypr/conf/misc.conf
source = ~/dotfiles/hypr/conf/keybinding.conf
source = ~/dotfiles/hypr/conf/windowrule.conf

# ----------------------------------------------------- 
# Animation
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/animation.conf

# ----------------------------------------------------- 
# Custom
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/custom.conf

# ----------------------------------------------------- 
# Custom
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/ml4w.conf

# ----------------------------------------------------- 
# Environment for xdg-desktop-portal-hyprland
# ----------------------------------------------------- 
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# ----------------------------------------------------- 
# Workspace Rules
# ----------------------------------------------------- 
source = ~/dotfiles/hypr/conf/workspace.conf

# ----------------------------------------------------- 
# Autoload apps on start
# ----------------------------------------------------- 

source = ~/dotfiles/hypr/conf/start-apps.conf


Config File: /home/ethan/dotfiles/hypr/conf/monitor.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/monitors/default.conf

Config File: /home/ethan/dotfiles/hypr/conf/monitors/default.conf: Read Succeeded
# ----------------------------------------------------- 
# Monitor Setup
# name: "Default"
# ----------------------------------------------------- 

monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000A46,highrr,0x0,1,vrr,2
monitor=desc:Microstep MSI G24C4 0x00000336,highrr,2560x250,1
monitor = , preferred, auto, 1

exec-once=hyprctl dispatch exec ~/dotfiles/hypr/scripts/xwayland-primary.sh



Config File: /home/ethan/dotfiles/hypr/conf/autostart.conf: Read Succeeded
# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# Setup XDG for screen sharing
exec-once = ~/dotfiles/hypr/scripts/xdg.sh

# Start Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Dunst Notification Manager
# exec-once = dunst
# exec-once = swaync

# Load GTK settings
exec-once = ~/dotfiles/hypr/scripts/gtk.sh

# Using hypridle to start hyprlock
exec-once = hypridle
# Or use Swayidle to start swaylock, config is ~/.config/swayidle/config
# exec-once = swayidle -w

# Load network manager applet
# START NM APPLET
# exec-once = nm-applet --indicator
# END NM APPLET

# Hyprpaper
exec-once = hyprpaper

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize Wallpaper Engine and Waybar or AGS
# exec-once = ~/dotfiles/hypr/scripts/init-wallpaper-engine.sh
exec-once = agsv1

# Start ML4W Welcome App
exec-once = ~/dotfiles/hypr/scripts/ml4w-welcome-autostart.sh

# Load bluetooth applet
# exec-once = blueman-applet
# exec-once = blueman-tray

# Load OTD tablet driver
exec-once = otd-daemon


Config File: /home/ethan/dotfiles/hypr/conf/cursor.conf: Read Succeeded
exec-once = hyprctl setcursor Bibata-Modern-Ice 24


Config File: /home/ethan/dotfiles/hypr/conf/environment.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/environments/nvidia.conf

Config File: /home/ethan/dotfiles/hypr/conf/environments/nvidia.conf: Read Succeeded
# ----------------------------------------------------- 
# Environment Variables
# name: "Nvidia"
# ----------------------------------------------------- 

# https://wiki.hyprland.org/Nvidia/
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
# env = WLR_NO_HARDWARE_CURSORS,1
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,1
# env = WLR_DRM_NO_ATOMIC,1
env = NVD_BACKEND,direct
# env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = __GL_GSYNC_ALLOWED,1

cursor {
    use_cpu_buffer = true
#   no_hardware_cursors = true
# no_break_fs_vrr = true
# min_refresh_rate = 48
}

render {
  direct_scanout = true
}

# render:explicit_sync = 0
# render:explicit_sync_kms = 0


Config File: /home/ethan/dotfiles/hypr/conf/keyboard.conf: Read Succeeded
# ----------------------------------------------------- 
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = gb
    kb_variant = 
    kb_model =
    kb_options =
    numlock_by_default = true
    mouse_refocus=false
    
    # For United States
    # kb_layout = us
    # kb_variant = intl
    # kb_model = pc105
    # kb_options =

    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = -0.7 # -1.0 - 1.0, 0 means no modification.
}



Config File: /home/ethan/.cache/wal/colors-hyprland.conf: Read Succeeded
$background = rgb(08031F)
$foreground = rgb(dcdad9)
$color0 = rgb(08031F)
$color1 = rgb(1168A3)
$color2 = rgb(4C6597)
$color3 = rgb(B36F99)
$color4 = rgb(09ABDB)
$color5 = rgb(35AED5)
$color6 = rgb(62D6EF)
$color7 = rgb(dcdad9)
$color8 = rgb(9a9897)
$color9 = rgb(1168A3)
$color10 = rgb(4C6597)
$color11 = rgb(B36F99)
$color12 = rgb(09ABDB)
$color13 = rgb(35AED5)
$color14 = rgb(62D6EF)
$color15 = rgb(dcdad9)

Config File: /home/ethan/dotfiles/hypr/conf/window.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/windows/default.conf

Config File: /home/ethan/dotfiles/hypr/conf/windows/default.conf: Read Succeeded
# ----------------------------------------------------- 
# General window layout and colors
# name: "Default"
# ----------------------------------------------------- 

general {
    gaps_in = 10
    gaps_out = 14
    border_size = 2
    col.active_border = $color3 $color4 $color3 30deg
    col.inactive_border = $background
    layout = dwindle
}


Config File: /home/ethan/dotfiles/hypr/conf/decoration.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/decorations/default.conf

Config File: /home/ethan/dotfiles/hypr/conf/decorations/default.conf: Read Succeeded
# ----------------------------------------------------- 
# General window decoration
# name: "Default"
# ----------------------------------------------------- 

decoration {
  shadow {
    enabled = true
    range = 30
    render_power = 4
    color = rgba(0,0,0,0.6)
  }
  rounding = 10
  blur {
      enabled = true
      size = 6
      passes = 2
      new_optimizations = on
      ignore_opacity = truegly advised to do a full system upgrade right away if your system 
      xray = true
      # blurls = waybar
  }
  active_opacity = 1.0
  inactive_opacity = 0.8
  fullscreen_opacity = 1.0

}


Config File: /home/ethan/dotfiles/hypr/conf/layout.conf: Read Succeeded
# ----------------------------------------------------- 
# Layouts
# ----------------------------------------------------- 

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

gestures {
    workspace_swipe = false
}


Config File: /home/ethan/dotfiles/hypr/conf/misc.conf: Read Succeeded
# ----------------------------------------------------- 
# Misc settings
# ----------------------------------------------------- 

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    allow_session_lock_restore = true
    focus_on_activate = true
}


Config File: /home/ethan/dotfiles/hypr/conf/keybinding.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/keybindings/default.conf

Config File: /home/ethan/dotfiles/hypr/conf/keybindings/default.conf: Read Succeeded
# ----------------------------------------------------- 
# Key bindings
# name: "Default"
# ----------------------------------------------------- 

# SUPER KEY
$mainMod = SUPER

# Applications
bind = $mainMod, RETURN, exec, ~/dotfiles/.settings/terminal.sh
bind = $mainMod, B, exec, ~/dotfiles/.settings/browser.sh
bind = $mainMod, period, exec, emote

# Windows
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, E, exec, ~/dotfiles/.settings/filemanager.sh
bind = $mainMod, T, togglefloating
bind = $mainMod SHIFT, T, exec, ~/dotfiles/hypr/scripts/toggleallfloat.sh
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod CTRL, right, resizeactive, 100 0
bind = $mainMod CTRL, left, resizeactive, -100 0
bind = $mainMod CTRL, up, resizeactive, 0 -100
bind = $mainMod CTRL, down, resizeactive, 0 100
bind = $mainMod CTRL, L, resizeactive, 100 0
bind = $mainMod CTRL, H, resizeactive, -100 0
bind = $mainMod CTRL, K, resizeactive, 0 -100
bind = $mainMod CTRL, J, resizeactive, 0 100
bind = $mainMod SHIFT, G, togglegroup
bind = $mainMod SHIFT, P, togglesplit
bind = $mainMod SHIFT, S, swapsplit

# Actions
bind = $mainMod, PRINT, exec, ~/dotfiles/hypr/scripts/screenshot.sh
bind = $mainMod CTRL, Q, exec, wlogout
bind = $mainMod SHIFT, W, exec, ~/dotfiles/hypr/scripts/wallpaper.sh
bind = $mainMod CTRL, W, exec, ~/dotfiles/hypr/scripts/wallpaper.sh select
bind = $mainMod, SPACE, exec, rofi -show drun -replace -i
# bind = $mainMod CTRL, H, exec, ~/dotfiles/hypr/scripts/keybindings.sh
bind = $mainMod SHIFT, B, exec, ~/dotfiles/waybar/launch.sh
bind = $mainMod SHIFT, R, exec, ~/dotfiles/hypr/scripts/loadconfig.sh
bind = $mainMod CTRL, F, exec, ~/dotfiles/scripts/filemanager.sh
bind = $mainMod CTRL, C, exec, ~/dotfiles/scripts/cliphist.sh
# bind = $mainMod, V, exec, ~/dotfiles/scripts/cliphist.sh
bind = $mainMod CTRL, T, exec, ~/dotfiles/waybar/themeswitcher.sh
bind = $mainMod CTRL, S, exec, ~/dotfiles/apps/ML4W_Dotfiles_Settings-x86_64.AppImage
bind = $mainMod, N, exec, ags -t notificationsmenu
bind = $mainMod SHIFT, N, exec, ags -r "clearAllNotifications()"
bind = $mainMod CTRL, 0, exec, sleep 1 && hyprctl dispatch dpms off DP-1
bind = $mainMod CTRL, 9, exec, sleep 1 && hyprctl dispatch dpms on DP-1


# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod CTRL, down, workspace, empty

# Special Workspace
bind = $mainMod, V, togglespecialworkspace

# Fn keys
bind = , XF86MonBrightnessUp, exec, brightnessctl -q s +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl -q s 10%-
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind = , XF86Calculator, exec, qalculate-gtk
bind = , XF86Lock, exec, hyprlock
bind = , XF86Tools, exec, alacritty --class dotfiles-floating -e ~/dotfiles/hypr/settings/settings.sh

# Passthrough SUPER KEY to Virtual Machine
bind = $mainMod, P, submap, passthru
submap = passthru
bind = SUPER, Escape, submap, reset
submap = reset

# Custom remap
input {
    # kb_options = caps:swapescape
}


Config File: /home/ethan/dotfiles/hypr/conf/windowrule.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/windowrules/default.conf

Config File: /home/ethan/dotfiles/hypr/conf/windowrules/default.conf: Read Succeeded
# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile,^(Microsoft-edge)$
windowrule = tile,^(Brave-browser)$
windowrule = tile,^(firefox)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(qalculate-gtk)$

# Games

general {
    allow_tearing = true
}

windowrulev2 = immediate, title:^(Cyberpunk 2077)
windowrulev2 = immediate, class:^(steam_app)
windowrulev2 = immediate, class:^()$


Config File: /home/ethan/dotfiles/hypr/conf/animation.conf: Read Succeeded
source = ~/dotfiles/hypr/conf/animations/default.conf

Config File: /home/ethan/dotfiles/hypr/conf/animations/default.conf: Read Succeeded
# ----------------------------------------------------- 
# Animations
# name "Default"
# ----------------------------------------------------- 
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 6, myBezier
    animation = windowsOut, 1, 6, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, default
    animation = specialWorkspaceIn, 1, 5, default, slidefadevert -100%
    animation = specialWorkspaceOut, 1, 5, default, slidefadevert -100%
}


Config File: /home/ethan/dotfiles/hypr/conf/custom.conf: Read Succeeded
# Add your additional Hyprland configurations here
# 
# This is an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
# 
# Example for xwayland
xwayland {
  force_zero_scaling = true
}

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

env = MOZ_ENABLE_WAYLAND,1


Config File: /home/ethan/dotfiles/hypr/conf/ml4w.conf: Read Succeeded
# ----------------------------------------------------- 
# ML4W configurations
# ----------------------------------------------------- 

windowrulev2 = float,class:(com.ml4w.welcome)
windowrulev2 = size 700 600,class:(com.ml4w.welcome)
windowrulev2 = center,class:(com.ml4w.welcome)

windowrulev2 = float,class:(ml4w-welcome.py)
windowrulev2 = size 400 500,class:(ml4w-welcome.py)
windowrulev2 = center,class:(ml4w-welcome.py)

windowrulev2 = float,class:(com.ml4w.dotfilessettings)
windowrulev2 = size 700 600,class:(com.ml4w.dotfilessettings)
windowrulev2 = move 10% 20%,class:(com.ml4w.dotfilessettings)

windowrulev2 = float,class:(ml4w-dotfiles-settings.py)
windowrulev2 = size 400 500,class:(ml4w-dotfiles-settings.py)
windowrulev2 = move 10% 20%,class:(ml4w-dotfiles-settings.py)

windowrulev2 = float,class:(dotfiles-floating)
windowrulev2 = size 1000 800,class:(dotfiles-floating)
windowrulev2 = center,class:(dotfiles-floating)

env = APPIMAGELAUNCHER_DISABLE,1

Config File: /home/ethan/dotfiles/hypr/conf/workspace.conf: Read Succeeded

# ----------------------------------------------------- 
# Workspace config
# ----------------------------------------------------- 

workspace = 1, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000A46, default: true
workspace = 2, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000A46
workspace = 3, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000A46
workspace = 4, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000A46
workspace = 5, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000A46

workspace = 6, monitor:desc:Microstep MSI G24C4 0x00000336
workspace = 7, monitor:desc:Microstep MSI G24C4 0x00000336
workspace = 8, monitor:desc:Microstep MSI G24C4 0x00000336
workspace = 9, monitor:desc:Microstep MSI G24C4 0x00000336
workspace = 10, monitor:desc:Microstep MSI G24C4 0x00000336



Config File: /home/ethan/dotfiles/hypr/conf/start-apps.conf: Read Succeeded
exec-once=[workspace 1 silent] ~/dotfiles/.settings/terminal.sh
exec-once=[workspace 2 silent] ~/dotfiles/.settings/browser.sh
exec-once=[workspace 6 silent] webcord
exec-once=[workspace special silent] ~/dotfiles/.settings/terminal.sh


======Config-End========


```

</details>

### Description

All apps are capped to the refresh rate to 165 (which is the refresh rate of my monitor).
I have tearing enabled (via immediate) and vrr enabled.

Expected behavior: monitor syncs to vrr range inside vrr range, and tears (more fps than rr) when range exceeds monitor refresh rate.
Actual: FPS will cap to rr of monitor..

### How to reproduce

run vkcube fullscreen with vrr on nvidia. With immediate being true (tearing enabled), frame rate is still capped to refresh rate of monitor.

### Crash reports, logs, images, videos

![image](https://github.com/user-attachments/assets/c429b600-e5d3-494f-899f-4c5b7f1df018)

![image](https://github.com/user-attachments/assets/5a464f05-bb13-4234-b911-bb037aeb3c85)

**Comment by ethanh20009** [comment] 2024-11-15 21:16
For reference, when I use goverlay and disable vulkan vsync explicitly, And then I window the app,
![image](https://github.com/user-attachments/assets/6f7c5983-90be-4116-a388-ef08d4ac95c3)

When the same app and configuration is fullscreen:

https://github.com/user-attachments/assets/e080c7ed-8328-4d89-8def-2579641dff19

**Comment by ferrreo** [comment] 2024-11-19 13:30
I am getting this now too, it is a regression though as it was working fine on 0.45.0

**Comment by gulafaran** [comment] 2024-11-19 20:34
@UjinT34 any ideas? seeing the bad commit comes from 967fe76a60ec6b2928b495ed202f772beca05275

**Comment by UjinT34** [comment] 2024-11-19 23:12
Looks like tearing means that kms explicit sync should be disabled.  Or at least explicit out fence should not be used. 
`render:explicit_sync_kms` controls both fences: in fence goes into video driver and makes it wait till HL finishes work on a frame, out fence comes from the video driver and should be waited by HL.
Does it make sense to have half of the explicit sync with tearing enabled?

**Comment by ferrreo** [comment] 2024-11-19 23:19
Putting a !pMonitor->tearingState.canTear check around the fence call does work and I think that is maybe correct because with tearing you want to render as fast as possible waiting for no sync. But disabling explicit sync globally doesn't make sense because having tearing enabled doesn't mean it can tear right now (might not have a fullscreen app up etc).

**Comment by Fxzzi** [comment] 2024-11-24 21:07
imo it should just disable the explicit out fence when the monitor is being actively teared. Having to disable kms expl sync causes stutters in foot term and other apps for me, making it not a viable solution

**Comment by wwxiaoqi** [comment] 2024-11-25 00:55
Is there a solution to this problem?

**It causes the screen to flicker.**

```
cursor {
    # Makes HW cursors use a CPU buffer.
    # Required on Nvidia to have HW cursors.
    # Experimental
    # use_cpu_buffer = true
    allow_dumb_copy = true
    
    no_hardware_cursors = true
}

env = AQ_NO_MODIFIERS,1

render {
    # Whether explicit sync support is enabled
    explicit_sync = 1
    # Whether explicit synchronization support is enabled for the KMS tier
    explicit_sync_kms = 0
    # Enable direct scanning
    # Try to reduce latency when there is only one full-screen application on the screen
    direct_scanout = false
}

#  tail -f $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log
debug {
    enable_stdout_logs = true
    disable_logs = false
}
```

**Comment by vaxerski** [comment] 2024-12-06 14:16
should be fixed in git

**Closed by vaxerski** 2024-12-06 14:16 UTC
Labels: bug
