### ISSUE TITLE
Mouse Cursor invisible all of the time

### ISSUE THREAD

**Issue by erdnuesse** [hyprwm/Hyprland#7625] opened 2024-09-02 12:27 UTC
### Regression?

Yes

### System Info and Version

Hi, 
Environment:
Arch(eneavourOS)+hyprland+AMD 570
Dual Monitors, mixed resolutions, 4k+1440p, both on DPs

```
yprctl systeminfo -c
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: REDACTED
Release: 6.10.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000


GPU information:
2d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.03.26"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:

======Config-Start======


Config File: /home/REDACTED/.config/hypr/hyprland.conf: Read Succeeded
# #######################################################################################
# AUTOGENERATED HYPR CONFIG.
# PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
# OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
# #######################################################################################
#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#
# BULLSHIT WARNING
# autogenerated = 1 # remove this line to remove the warning

# See https://wiki.hyprland.org/Configuring/Monitors/
# default:
# monitor=,preferred,auto,auto

# for no fractional scaling:
# monitor=DP-1, 3840x2160, 0x0, 1, bitdepth,10, vrr,1
# monitor=DP-3, 2560x1440, 3840x0, 1, bitdepth,10, vrr,1

# 1.25 fractionally scaled: (3072 = 3840 / 1.25 - when it'll be supported anyhow)
monitor=DP-1, 3840x2160, 0x0,    1.25, bitdepth,10, vrr,1
monitor=DP-3, 2560x1440, 3072x0, 1,    bitdepth,10, vrr,1

# workspace binding
workspace=1, monitor:DP-1, default:true
workspace=2, monitor:DP-1
workspace=3, monitor:DP-1
workspace=4, monitor:DP-1
workspace=5, monitor:DP-1
workspace=6, monitor:DP-3, default:true
workspace=7, monitor:DP-3
workspace=8, monitor:DP-3
workspace=9, monitor:DP-3


# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
#env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRCURSOR_SIZE,24
env = WLR_NO_HARDWARE_CURSORS,1
env = hide_on_touch,1

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
#    kb_layout = us
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

#    follow_mouse = 0
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

# █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 0
    # this seems no longer existing
    # blur_new_optimizations = on
    # blur_passes = 1
    # blur_size = 3
    # blur = yes
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

animations {
    enabled = yes
    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
#    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# commented KU
# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
# device:epic-mouse-v1 {
#     sensitivity = -0.5
# }

# WINDOW RULES

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule=float,org.kde.polkit-kde-authentication-agent-1
windowrulev2=float,title:^(.Authentication required.*)$
windowrulev2=float,class:^(polkit-agent-helper-1)$
# windowrule=float,<XFCE ID - currently unknown>

# EXECS

# REDACTED1
# Waybar
exec-once=waybar
# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
# polkits seem to be necessary, no? lol fml
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# random bgr in folder
exec-once = bash ~/.config/hypr/random_bgr.sh
# exec-once = /usr/lib/xfce-polkit/xfce-polkit



# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# ###

# CUSTOM KEYBINDS
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
#bind = $mainMod, Q, exec, kitty
bind = $mainMod, Q, killactive,
# bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
# bind = $mainMod, E, exec, dolphin
bind = $mainMod, E, exec, pcmanfm
bind = $mainMod, F, togglefloating,
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, SPACE, exec, fuzzel
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, RETURN, exec, alacritty# dwindle
# bind = $mainMod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

# ###
# AUDIO
# ###
bind = $mainMod, F12, exec, pactl set-sink-volume alsa_output.usb-Burr-Brown_from_TI_USB_Audio_DAC-00.pro-output-0 +3%
bind = $mainMod, F11, exec, pactl set-sink-volume alsa_output.usb-Burr-Brown_from_TI_USB_Audio_DAC-00.pro-output-0 -3%
bind = $mainMod, F10, exec, pactl set-sink-mute alsa_output.usb-Burr-Brown_from_TI_USB_Audio_DAC-00.pro-output-0 toggle
bind = $mainMod, F8, exec, playerctl play-pause
bind = $mainMod, F9, exec, playerctl next
bind = $mainMod, F7, exec, playerctl previous
#bind = , XF86AudioPlay, exec, playerctl play-pause
#bind = , XF86AudioPause, exec, playerctl play-pause
#bind = , XF86AudioNext, exec, playerctl next
#bind = , XF86AudioPrev, exec, playerctl previous

# ###kh
# BIND FOR Windows, Workspaces, Desktops
# ###

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Screenshots
# bind = ,         PRINT, exec, hyprshot -m window -o ~/Pictures/screenshots/
# bind = $mainMod, PRINT, exec, hyprshot -m region -o ~/Pictures/screenshots/
bind = $mainMod SHIFT, S, exec, hyprshot -m region -o ~/Pictures/screenshots/
# hyprshot -m region -o ~/Pictures/screenshots/

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Windowrules
# windowrulev2=move 0 0,title:^(flameshot)
# windowrulev2=nofullscreenrequest,title:^(flameshot)
# windowrulev2=float,title:(flameshot)

======Config-End========
```

### Description

Hi, 
Environment:
Arch(eneavourOS)+hyprland+AMD 570
Dual Monitors, mixed resolutions, 4k+1440p, both on DPs

I can no longer see my cursor at all. 
Not app specific, it's totally invisible at all times.

Previously it worked with 
```
env = XCURSOR_SIZE,24
```
in hyprland.conf, now have tried some of the suggested fixes found elsewhere step by step like (including installing rose-pine, and copying the folder to ~/.local/share/icons and setcursoring the theme): 

```
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRCURSOR_SIZE,24
env = WLR_NO_HARDWARE_CURSORS,1
env = hide_on_touch,1
``
but to no avail. 

before I did that I first tried the xcursor prefs and switching to a different xcursor theme, also nothing. 

Cursor is there in SDDM though, and also my fallback solution of awesomeWM (which isn't really configured)
I have no clue on what to try next, (for me I probably need to install a DE to get that machine in a workable state again.)
I also don't know what was updated in my latest package update, the only thing I could remember from the output was that libwacom received an update, but so have dozens other packages. 

### How to reproduce

Reproducing for sounds is tricky, I can't un-reproduce it now, so for me it's omnipresent. Sorry for being of so little help here.

### Crash reports, logs, images, videos

_No response_

**Comment by erdnuesse** [comment] 2024-09-02 12:30
Sry for the horrible formatting, but - 
I do have no mouse and it already took forever to open this.

**Comment by MightyPlaza** [comment] 2024-09-02 12:57
dupe of many issues and fixed on https://github.com/hyprwm/aquamarine/commit/e12b0a9c67a56b0a81421d63c63f533bd70e7e9b

**Comment by vaxerski** [comment] 2024-09-02 17:49
ye use git

**Closed by vaxerski** 2024-09-02 17:49 UTC
Labels: bug

**Comment by erdnuesse** [comment] 2024-09-03 07:05
> ye use git

Git version from AUR now prevents Hyprland from launching at all, making the problem even worse, so not helpful at all.

**Comment by Honkazel** [comment] 2024-09-03 07:13
> > ye use git
> 
> Git version from AUR aquamarine-git now prevents Hyprland from launching at all, making the problem even worse, so not helpful at all.

Remove and install(NOT REINSTALL) aquamarine-git again
and after that rebuild hyprland-git

**Comment by erdnuesse** [comment] 2024-09-03 07:37
> Remove and install(NOT REINSTALL) aquamarine-git again and after that rebuild hyprland-git

Thanks for clarification. I was hoping for a single updated package*, not necessarily fully building hyprland. So while appreciate this approach as a potential solution, I think I'm gonna wait for aqua to make it to my repos and use something else as DE/WM/Compositor instead as I need my time to work.
I'll probably circle back to hypr when I see them* in my upgraded pkgs. Thanks everyone for helping.

**Comment by MightyPlaza** [comment] 2024-09-03 12:33
> > Remove and install(NOT REINSTALL) aquamarine-git again and after that rebuild hyprland-git
> 
> Thanks for clarification. I was hoping for a single updated package*, not necessarily fully building hyprland. So while appreciate this approach as a potential solution, I think I'm gonna wait for aqua to make it to my repos and use something else as DE/WM/Compositor instead as I need my time to work. I'll probably circle back to hypr when I see them* in my upgraded pkgs. Thanks everyone for helping.

it's already on https://archlinux.org/packages/extra/x86_64/aquamarine/ 0.4.0
