### ISSUE TITLE
Keyboard losing focus, after using a floating popup (IntelliJ / Java?)

### ISSUE THREAD

**Issue by psobiech** [hyprwm/Hyprland#1947] opened 2023-04-04 20:45 UTC
Hi,
when using a floating popup in IntelliJ (like 'Generate' popup), I am losing keyboard focus completely when the popup closes. I need to focus some other window (or change workspace) and refocus the original window to be able to type again. Mouse clicks within the application do not help. 

PS: The issue does not happen if I use mouse to close the popup, only if I'm using keyboard.

I've tried changing the follow_mouse option, but the behavior is the same. 
I will not post the config, since I was able to reproduce the issue even without the config (with the yellow banner on top ;-))

It might be easier to show on a video: https://youtu.be/HVOS8_YDTDo (I am clicking the mouse and typing after the popup closes multiple times), but no keyboard input goes through.

Thank you for your time!

Versions:
hyprland-git r2689.6519c030-1
wlroots-git 0.17.0.r6182.835208db-1

openjdk 19.0.2
IntelliJ IDEA 2023.1 (Same behaviour on the New UI and Old UI)

hyprctl clients:
```
Window 7b93aa0 -> root – TestClass.java [shared.simple-shared]:
        mapped: 1
        hidden: 0
        at: 961,5
        size: 954,1044
        workspace: 1 (1)
        floating: 0
        monitor: 0
        class: jetbrains-idea
        title: root – TestClass.java [shared.simple-shared]
        initialClass: jetbrains-idea
        initialTitle:
        pid: 629620
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        swallowing: 0

Window 7e9d7a0 -> Select Fields to Generate Getters:
        mapped: 1
        hidden: 0
        at: 1196,160
        size: 387,584
        workspace: 1 (1)
        floating: 1
        monitor: 0
        class: jetbrains-idea
        title: Select Fields to Generate Getters
        initialClass: jetbrains-idea
        initialTitle: Select Fields to Generate Getters
        pid: 629620
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        swallowing: 0
```

Here are the logs:
```
[LOG] Searching for matching rules for org.wezfurlong.wezterm (title: sobiechp@rip /tmp/hypr/6519c0308c4dd6ab484c7854e1eca2dc8f400485_1680638702 % tail -n 0 -f hyprland.log)
[LOG] Window 7b9e930 set title to sobiechp@rip /tmp/hypr/6519c0308c4dd6ab484c7854e1eca2dc8f400485_1680638702 % tail -n 0 -f hyprland.log
[LOG] Set keyboard focus to surface 7d71ff0, with window name: root – TestClass.java [shared.simple-shared]
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] New XWayland Surface created (class jetbrains-idea).
[LOG] Window parent data: jetbrains-idea at 7e62b00
[LOG] Registered signal for owner 7e321c0: 7e8b7a8 -> 7e32228 (owner: XWayland Window)
[LOG] Registered signal for owner 7e321c0: 7e8b728 -> 7e322f8 (owner: XWayland Window)
[LOG] Registered signal for owner 7e321c0: 7e8b868 -> 7e328a8 (owner: XWayland Window)
[LOG] Registered signal for owner 7e321c0: 7e8b738 -> 7e32708 (owner: XWayland Window)
[LOG] Registered signal for owner 7e32910: 7e94a08 -> 7e32918 (owner: CWLSurface)
[LOG] CWLSurface 7e32910 called init()
[LOG] Registered signal for owner 7e321c0: 7e8b7b8 -> 7e32290 (owner: CWindow)
[LOG] Searching for matching rules for jetbrains-idea (title: win4)
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 7e321c0: 7e8b788 -> 7e32430 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e321c0: 7e8b798 -> 7e326a0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e321c0: 7e8b7c8 -> 7e32360 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e321c0: 7e8b768 -> 7e32568 (owner: Xwayland Window Late)
[ERR] Tried to connect a listener twice?!
[LOG] Registered signal for owner 7e321c0: 7e8b878 -> 7e323c8 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e8a400: 7e949f8 -> 7e8a478 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e8a400: 7e949e8 -> 7e8a4e0 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e8a400: 7e94a08 -> 7e8a548 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 7e321c0)
[LOG] Map request dispatched, monitor HDMI-A-1, xywh: 1082.000000 512.000000 233.000000 241.000000
[LOG] Window 7e321c0 unmapped (class jetbrains-idea)
[LOG] Unregistered late callbacks XWL
[LOG] Callback 7e32458 -> 7e32450, XWayland Window Late removed.
[LOG] Callback 7e326c8 -> 7e326c0, XWayland Window Late removed.
[LOG] Callback 7e32388 -> 7e32380, XWayland Window Late removed.
[LOG] Callback 7e323f0 -> 7e323e8, XWayland Window Late removed.
[LOG] Callback 7e32590 -> 7e32588, Xwayland Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] Unmapped was not focused, ignoring a refocus.
[LOG] Destroying the SubSurface tree of unmapped window 7e321c0
[LOG] Callback 7e8a508 -> 7e8a500, SurfaceTreeNode removed.
[LOG] Callback 7e8a570 -> 7e8a568, SurfaceTreeNode removed.
[LOG] Callback 7e8a4a0 -> 7e8a498, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 7e32940 -> 7e32938, CWLSurface removed.
[LOG] CWLSurface 7e32910 called destroy()
[LOG] Callback 7e322b8 -> 7e322b0, CWindow removed.
[LOG] Window 7e321c0 destroyed, queueing. (class )
[LOG] XWayland class raw: jetbrains-idea
[LOG] Callback 7e32250 -> 7e32248, XWayland Window removed.
[LOG] Callback 7e32320 -> 7e32318, XWayland Window removed.
[LOG] Callback 7e32730 -> 7e32728, XWayland Window removed.
[LOG] Callback 7e328d0 -> 7e328c8, XWayland Window removed.
[LOG] New XWayland Surface created (class jetbrains-idea).
[LOG] Window parent data: jetbrains-idea at 7e62b00
[LOG] Registered signal for owner 7e95100: 7e8b7a8 -> 7e95168 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7e8b728 -> 7e95238 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7e8b868 -> 7e957e8 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7e8b738 -> 7e95648 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7db6b60 -> 7e95718 (owner: Toplevel)
[LOG] Registered signal for owner 7e95100: 7db6b70 -> 7e95780 (owner: Toplevel)
[LOG] Registered signal for owner 7e95100: 7db6b80 -> 7e956b0 (owner: Toplevel)
[LOG] Registered signal for owner 7e95850: 7e94a08 -> 7e95858 (owner: CWLSurface)
[LOG] CWLSurface 7e95850 called init()
[LOG] Registered signal for owner 7e95100: 7e8b7b8 -> 7e951d0 (owner: CWindow)
[LOG] Searching for matching rules for jetbrains-idea (title: Select Fields to Generate Getters)
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 7e95100: 7e8b788 -> 7e95370 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e95100: 7e8b798 -> 7e955e0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e95100: 7e8b7c8 -> 7e952a0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e95100: 7e8b768 -> 7e954a8 (owner: Xwayland Window Late)
[ERR] Tried to connect a listener twice?!
[LOG] Registered signal for owner 7e623e0: 7e949f8 -> 7e62458 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e623e0: 7e949e8 -> 7e624c0 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e623e0: 7e94a08 -> 7e62528 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 7e95100)
[LOG] Map request dispatched, monitor HDMI-A-1, xywh: 766.000000 248.000000 387.000000 584.000000
[LOG] Cleanup: destroyed a window
[LOG] Window 7e95100 unmapped (class jetbrains-idea)
[LOG] Unregistered late callbacks XWL
[LOG] Callback 7e95398 -> 7e95390, XWayland Window Late removed.
[LOG] Callback 7e95608 -> 7e95600, XWayland Window Late removed.
[LOG] Callback 7e952c8 -> 7e952c0, XWayland Window Late removed.
[LOG] Callback 7e954d0 -> 7e954c8, Xwayland Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] Unmapped was not focused, ignoring a refocus.
[LOG] Destroying the SubSurface tree of unmapped window 7e95100
[LOG] Callback 7e624e8 -> 7e624e0, SurfaceTreeNode removed.
[LOG] Callback 7e62550 -> 7e62548, SurfaceTreeNode removed.
[LOG] Callback 7e62480 -> 7e62478, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 7e95740 -> 7e95738, Toplevel removed.
[LOG] Callback 7e956d8 -> 7e956d0, Toplevel removed.
[LOG] Callback 7e957a8 -> 7e957a0, Toplevel removed.
[LOG] Callback 7e95880 -> 7e95878, CWLSurface removed.
[LOG] CWLSurface 7e95850 called destroy()
[LOG] Callback 7e951f8 -> 7e951f0, CWindow removed.
[LOG] Window 7e95100 destroyed, queueing. (class )
[LOG] XWayland class raw: jetbrains-idea
[LOG] Callback 7e95190 -> 7e95188, XWayland Window removed.
[LOG] Callback 7e95260 -> 7e95258, XWayland Window removed.
[LOG] Callback 7e95670 -> 7e95668, XWayland Window removed.
[LOG] Callback 7e95810 -> 7e95808, XWayland Window removed.
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] Cleanup: destroyed a window
[LOG] Keybind triggered, calling dispatcher (8, , 65362)
```

**Comment by psobiech** [comment] 2023-04-11 18:48
For those that have the same issue (and maybe it will help to trace the issue), I had found a partial workaround.

With adding the following winow rule:
`windowrule=noanim,^(jetbrains-idea)$`

I reduced the chance of the above happening from ~99-100% to mostly it does no longer happen. 
And curiously with this rule, even if it does happen, a mouse click seems to be able to fix the keyboard focus.

**Comment by psobiech** [comment] 2023-04-19 07:05
Hi, thank you! I was watching the commit history, but missed this one, it seems.

I have updated to the latest HEAD (e446db02f69ba7f3b3eea42a25f5de2c333bf0cddirty) and the issue is much less common and the workaround above does not seem to be necessary. I was able to trigger it at some point though, but its hard to do now. :D

Now it seems (I will need to downgrade to check if it was like this originally, because I might have missed that previously), that the special buttons do seem to go through (enter, backspace, arrows move the highlighted line color, CTRL+A selects all text, etc), I just cant type anything (A-Z0-9). 
For me, some buttons going through looks like it would be the application issue, but something in the commit history made the issue much less common.

**Comment by Person1873** [comment] 2023-04-19 23:55
> Hi, thank you! I was watching the commit history, but missed this one, it seems.
> 
> I have updated to the latest HEAD (e446db02f69ba7f3b3eea42a25f5de2c333bf0cddirty) ~and the issue is much less common and the workaround above does not seem to be necessary. I was able to trigger it at some point though, but its hard to do now. :D~
> 
> ~Now it seems (I will need to downgrade to check if it was like this originally, because I might have missed that previously), that the special buttons do seem to go through (enter, backspace, arrows move the highlighted line color, CTRL+A selects all text, etc), I just cant type anything (A-Z0-9). For me, some buttons going through looks like it would be the application issue, but something in the commit history made the issue much less common.~
> 
> EDIT: Well, actually, the issue still persists in the same way, it just it seems the workaround persists over a hot reload, even if commented out. Only hard restart seems to make the issue appear again.

Have you tested on sway to see if the issue is persistent on other wlroots compositors?
If it works correctly on sway, then we can narrow the issue to the Hyprland codebase rather than Hyprland+wlroots

**Comment by psobiech** [comment] 2023-04-25 05:58
Yes, good catch. I was actually using sway for quite a long time and never had this issue there, but today I checked and its actually there also. 

I remembered that back then I was using non git version of wlroots + sway, so I downgraded to wlroots (0.16.2-1) and sway (1:1.8.1-1) and the issue again disappeared, but even with wlroots downgraded the issue still persists in Hypr. 

I dont see wlroots in hyprland dependencies, but if its bundled then its wlroots issue I think.

**Comment by psobiech** [comment] 2023-04-26 20:36
I think I have 100% reproduction right now.

If the popup appears under a cursor (it has active border), it has both mouse and keyboard focus and is visible via `hyprctl activewindow` and then the issue never happens.

If, on the other hand, the floating popup shows up **not** under a cursor, then it has only the keyboard focus (no active border around it), and when I perform an action and close it then the issue is always triggered.

Its visible here:
https://youtu.be/qClW7Z8uQT8

**Comment by romanstingler** [comment] 2023-06-09 12:43
This works for me (had to replace the idea with phpstorm and remove the title part so crtl+shift+alt+L would work)

I haven't seen the code, but there should be something like a stack per workspace, and if one window closes this is popped from the stack and the next window on top should receive the focus.

**Comment by Person1873** [comment] 2023-06-10 03:49
Not sure if this helps, but there is a guide for Hyprland on gentoo that advises setting _AWT_JAVA_WM_NONREPARENTING=1

Link is here for more details.
https://www.reddit.com/r/Gentoo/comments/11dzcgj/wayland_nvidia_proprietary_driver_guide/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

9 June 2023 10:43:24 pm romanstingler ***@***.***>:

**Comment by romanstingler** [comment] 2023-06-12 06:24
I think it is called `_JAVA_AWT_WM_NONREPARENTING=1`  and I have it already set.

**Comment by TheM1Stery** [comment] 2023-09-13 19:45
> windowrulev2=dimaround,class:^(jetbrains-idea)$,title:^((Select)|(Choose)

Thank you so much! It was driving me crazy in rider, i had to switch workspace to regain focus. This rule fixes it.

**Comment by psobiech** [comment] 2023-10-25 06:35
Hi,
as of now the issue is solved (at least for me, Hyperland v0.31.0-31-g14a3c939, for all jetbrains products) by this window rule:
```windowrulev2=windowdance,class:^(jetbrains-.*)```

With the above, all other rules seem to be unnecessary.

**Comment by gekoke** [comment] 2023-10-25 14:16
> Hi, as of now the issue is solved (at least for me, Hyprland v0.31.0-31-g14a3c939, for all jetbrains products) by this window rule: `windowrulev2=windowdance,class:^(jetbrains-.*)`
> 
> With the above, all other rules seem to be unnecessary.

This did not work for me. What did work, however, was `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.

**Comment by psobiech** [comment] 2023-10-25 14:31
> This did not work for me. What did work, however, was `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.

Hm, strange, i had some input issues, so now I'm testing the combo:
```
windowrulev2=forceinput,class:^(jetbrains-.*)
windowrulev2=windowdance,class:^(jetbrains-.*)
```

I'll check your option too.

**Comment by TwelveNight** [comment] 2023-10-26 13:44
> `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.



> > This did not work for me. What did work, however, was `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.这对我不起作用。然而，真正有效的是 `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$` 。
> 
> Hm, strange, i had some input issues, so now I'm testing the combo:嗯，奇怪的是，我遇到了一些输入问题，所以现在我正在测试组合：
> 
> ```
> windowrulev2=forceinput,class:^(jetbrains-.*)
> windowrulev2=windowdance,class:^(jetbrains-.*)
> ```
> 
> I'll check your option too.我也会检查你的选择。



> > This did not work for me. What did work, however, was `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.这对我不起作用。然而，真正有效的是 `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$` 。
> 
> Hm, strange, i had some input issues, so now I'm testing the combo:嗯，奇怪的是，我遇到了一些输入问题，所以现在我正在测试组合：
> 
> ```
> windowrulev2=forceinput,class:^(jetbrains-.*)
> windowrulev2=windowdance,class:^(jetbrains-.*)
> ```
> 
> I'll check your option too.我也会检查你的选择。

It`s not work for me

**Comment by TwelveNight** [comment] 2023-10-26 14:10
> > `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.
> 
> > > This did not work for me. What did work, however, was `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.这对我不起作用。然而，真正有效的是 `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$` 。
> > 
> > 
> > Hm, strange, i had some input issues, so now I'm testing the combo:嗯，奇怪的是，我遇到了一些输入问题，所以现在我正在测试组合：
> > ```
> > windowrulev2=forceinput,class:^(jetbrains-.*)
> > windowrulev2=windowdance,class:^(jetbrains-.*)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'll check your option too.我也会检查你的选择。
> 
> > > This did not work for me. What did work, however, was `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$`.这对我不起作用。然而，真正有效的是 `windowrulev2 = stayfocused, class:^(.*jetbrains.*)$` 。
> > 
> > 
> > Hm, strange, i had some input issues, so now I'm testing the combo:嗯，奇怪的是，我遇到了一些输入问题，所以现在我正在测试组合：
> > ```
> > windowrulev2=forceinput,class:^(jetbrains-.*)
> > windowrulev2=windowdance,class:^(jetbrains-.*)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'll check your option too.我也会检查你的选择。
> 
> It`s not work for me

I use this rule when I click the  open project  button,the focus have probability lost,maybe 50%?

**Comment by gekoke** [comment] 2023-10-27 14:54
After some experimentation I've landed on the following rules:

```
windowrulev2 = noanim, class:^(.*jetbrains.*)$, title:^(win.*)$
windowrulev2 = windowdance, class:^(.*jetbrains.*)$
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
```

I have yet to find a dialog that misbehaves with these settings (though I don't doubt I will).

**Comment by Theaninova** [comment] 2023-10-30 10:37
> After some experimentation I've landed on the following rules:
> 
> ```
> windowrulev2 = noanim, class:^(.*jetbrains.*)$, title:^(win.*)$
> windowrulev2 = windowdance, class:^(.*jetbrains.*)$
> windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
> ```
> 
> I have yet to find a dialog that misbehaves with these settings (though I don't doubt I will).

This still gave me issues with the search dialog closing when it didn't open below my mouse, because it doesn't have any title.

I'm using this now:
```
windowrulev2=windowdance,class:^(jetbrains-.*)$
# search dialog
windowrulev2=dimaround,class:^(jetbrains-.*)$,floating:1,title:^(?!win)
# autocomplete & menus
windowrulev2=noanim,class:^(jetbrains-.*)$,title:^(win.*)$
windowrulev2=noinitialfocus,class:^(jetbrains-.*)$,title:^(win.*)$
windowrulev2=rounding 0,class:^(jetbrains-.*)$,title:^(win.*)$
```

**Comment by MightyPlaza** [comment] 2024-07-09 20:39
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

**Comment by baronyoung** [comment] 2024-07-12 20:28
> JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/) Please try the versions in their Early Acess Program and see if they fix this issue. Relevant Download links: https://www.jetbrains.com/idea/nextversion/ https://www.jetbrains.com/pycharm/nextversion/ https://www.jetbrains.com/go/nextversion/

I just discovered this thread today so this beta/EAP version of Jetbrains Webstorm is the first solution I've tried.  The issue of losing focus does seem to be resolved, but unfortunately for me there's a few new and worse issues that have been introduced (suggestion windows flickering on and off and leaving artifacts on the screen, menu option highlighting not updating fast enough).  So now I will attempt some of the earlier solutions as I don't think this beta version of Webstorm is usable yet.

**Comment by romanstingler** [comment] 2024-07-25 11:26
@baronyoung do you use zen kernel or have a NVIDIA card? 
which HL version did you test ??

**Comment by baronyoung** [comment] 2024-07-25 16:25
@romanstingler No, to both.  I'm not sure now what my version was.  I used my favorite "ignore this problem until it fixes itself" approach to this issue and that fixed it (truly it just started working and I have no idea why).  However, a few days after posting the above comment, I ditched NixOS and went back to Ubuntu so this is entirely in my rear-view mirror now.  I had too many issues.

**Comment by romanstingler** [comment] 2024-07-25 16:27
so we can close that as well

**Comment by MightyPlaza** [comment] 2024-07-25 16:29
> so we can close that as well

not the OP

**Comment by vaxerski** [comment] 2024-07-25 20:43
op is inactive

**Closed by vaxerski** 2024-07-25 20:43 UTC
Labels: bug

**Comment by vitabis** [comment] 2025-02-28 15:20
FYI `windowdance` has been deprecated/removed. You can use `focusonactivate` instead:

```
windowrulev2 = focusonactivate on,class:^(jetbrains-.*)$
# search dialog
windowrulev2 = dimaround,class:^(jetbrains-.*)$,floating:1,title:^(?!win)
windowrulev2 = center,class:^(jetbrains-.*)$,floating:1,title:^(?!win)
# autocomplete & menus
windowrulev2 = noanim,class:^(jetbrains-.*)$,title:^(win.*)$
windowrulev2 = noinitialfocus,class:^(jetbrains-.*)$,title:^(win.*)$
windowrulev2 = rounding 0,class:^(jetbrains-.*)$,title:^(win.*)$
```

**Comment by dev-hancock** [comment] 2025-06-26 07:09
for me tweaking the input settings to the following worked:

```
input {
    follow_mouse = 0 # requires click to focus window (my preference)
    float_switch_override_focus = 0 # rider popups now maintain focus
}
```

**Comment by maalik-hrm** [comment] 2026-01-01 22:45
For anyone who updated to Hyprland v0.53, here are the updated rules:

```
# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
windowrule = focus_on_activate on,match:class ^(jetbrains-.*)$,float on
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule = center on,match:class ^(jetbrains-.*)$,match:title ^(splash)$,float on
windowrule = no_focus on,match:class ^(jetbrains-.*)$,match:title ^(splash)$,float on
windowrule = border_size 0,match:class ^(jetbrains-.*)$,match:title ^(splash)$,float on

#! Center popups/find windows
windowrule = center on,match:class ^(jetbrains-.*)$,match:title ^( )$,float on
windowrule = stay_focused on,match:class ^(jetbrains-.*)$,match:title ^( )$,float on
windowrule = border_size 0,match:class ^(jetbrains-.*)$,match:title ^( )$,float on
#! Disable window flicker when autocomplete or tooltips appear
windowrule = no_focus on,match:class ^(jetbrains-.*)$,match:title ^(win.*)$,float on
```

**Comment by maalik-hrm** [comment] 2026-01-01 23:04
Since updating to Hyprland 0.53 these settings helped me:

```
# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
#windowrule = focus_on_activate on,match:class ^(jetbrains-.*)$,float on
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule = center on,match:class ^(jetbrains-.*)$,match:title ^(splash)$,float on
windowrule = no_focus on,match:class ^(jetbrains-.*)$,match:title ^(splash)$,float on
windowrule = border_size 0,match:class ^(jetbrains-.*)$,match:title ^(splash)$,float on

#! Center popups/find windows
windowrule = center on,match:class ^(jetbrains-.*)$,match:title ^( )$,float on
windowrule = stay_focused on,match:class ^(jetbrains-.*)$,match:title ^( )$,float on
windowrule = border_size 0,match:class ^(jetbrains-.*)$,match:title ^( )$,float on
#! Disable window flicker when autocomplete or tooltips appear
windowrule = no_focus on,match:class ^(jetbrains-.*)$,match:title ^(win.*)$,float on
```
