### ISSUE TITLE
Hyprland black screen with cursor at start...

### ISSUE THREAD

**Issue by Morphexe** [hyprwm/Hyprland#3119] opened 2023-08-31 13:03 UTC
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12486789/hyprland.log)
### Hyprland Version

Hyprland, built from branch main at commit fc0c1896e097b3c3b2170ae69d38724e43960fe1 dirty (renderer: round coords and size in renderWindow). Tag: v0.29.0-9-gfc0c1896

### Bug or Regression?

Bug

### Description

When starting Hyprland from SDDM I am greeted with a black screen  with a cursor in the middle.

If I wait for a while, it comes back and works flawlessly.

I also found out, that if I move my mouse (the pointer on the screen does not move) - but if I push my mouse to the top border of the screen, where a waybar is the screen comes back every single time., it feels it gets stuck until something forces a rerender. Pressing Hyprland  shortcuts to open windows does nothing either.

I am honstly stuck on what to even start looking.

### How to reproduce

I cant really tell what exactly you can do to reproduce this, this is pretty much a  fresh install of garuda linux if it makes a difference.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12486800/hyprland.log)

**Comment by ferrreo** [comment] 2023-08-31 13:43
Looks like the same issue as https://github.com/hyprwm/Hyprland/issues/3079

wlroots issue upstream has been created

**Comment by Morphexe** [comment] 2023-08-31 13:55
@ferrreo I just looked at that issue, sadly the "fix" does not seem to do anything to me. In my scenario, it seems the only way for it to work is to move the mouse over the waybar at the top.

@MightyPlaza sorry! I forgot to attach a  log file,I cant see anything obvious wrong there - it mentions I am using a Nvidia GPU - the monitor is using a the AMD IGPU, so its not actually using the gpu if it makes sense.

**Comment by memchr** [comment] 2023-08-31 13:57
@Morphexe 

Can you try to rebuild hyprland with wlroots/717ded9b reverted?
```bash
cd subprojects/wlroots
git revert 717ded9b --no-commit
```

**Comment by Morphexe** [comment] 2023-08-31 14:33
@memchr That does work indeed.  So I guess @ferrreo  was correct and it is actually a wl_roots upstream issue?

**Comment by danao81** [comment] 2023-08-31 16:20
I'm facing the same exact issue in the last two devel releases.
Just upgraded to `
hyprland-git 0.29.0.r9.fc0c1896-1` with yay and the problem persist.

I'm NOT using a NVIDIA gpu

**Comment by Morphexe** [comment] 2023-08-31 17:17
@danao81 try doing the revert comit that @memchr mentioned, it solved the issue for me... Now I just need to figure out why I get a black screen coming from sleep :p

**Comment by danao81** [comment] 2023-08-31 17:28
@Morphexe thank you for your suggestion, but I guess I'll wait for the fix to be released (hopefully) in the next version.
I prefer to avoid building it from source for now.
Meanwhile I'll keep shaking the mouse like crazy :D

**Comment by vaxerski** [comment] 2023-09-01 20:22
dupe of https://github.com/hyprwm/Hyprland/issues/3079

**Closed by vaxerski** 2023-09-01 20:22 UTC
Labels: bug
