### ISSUE TITLE
Second monitor flickering

### ISSUE THREAD

**Issue by babaruh** [hyprwm/Hyprland#7748] opened 2024-09-11 18:09 UTC
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
$ hyprctl systeminfo -c
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: gentoo
Release: 6.6.47-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Mon Aug 19 12:01:20 -00 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c6) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  550.107.02  Wed Jul 24 23:53:00 UTC 2024


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:

======Config-Start======


Config File: /home/sova/.config/hypr/hyprland.conf: Read Succeeded
$scrPath = $HOME/.local/share/bin # set scripts path
$dotnetPath = $HOME/.dotnet/tools # set dotnet tools

# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = dbus-update-activation-environment --systemd --all # for XDPH
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = $scrPath/polkitkdeauth.sh # authentication dialogue for GUI apps
exec-once = waybar # launch the system bar 
exec-once = blueman-applet # systray app for Bluetooth
# exec-once = udiskie --no-automount --smart-tray # front-end that allows to manage removable media
exec-once = nm-applet --indicator # systray app for Network/Wifi
exec-once = dunst # start notification demon
exec-once = wl-paste --type text --watch cliphist store # clipboard store text data
exec-once = wl-paste --type image --watch cliphist store # clipboard store image data
exec-once = $scrPath/swwwallpaper.sh # start wallpaper daemon
exec-once = gentoo-pipewire-launcher
exec-once = /usr/libexec/xdg-desktop-portal-gtk -r
exec-once = /usr/libexec/xdg-desktop-portal-wlr -r
exec-once = /usr/libexec/xdg-desktop-portal-hyprland -r
exec-once = /usr/libexec/xdg-desktop-portal -r
# exec-once = /usr/libexec/flatpak-portal -r
# exec-once = sh -c 'sleep 5;exec /usr/libexec/xdg-desktop-portal -r'
# exec-once = ~/.config/hypr/xdg-portal-hyprland

# exec-once = telegram-desktop
# exec-once = librewolf-bin
# exec-once = rider
# exec-once = nemo
# exec-once = kitty


# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = PATH,$PATH:$scrPath
env = PATH,$PATH:$dotnetPath
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,1
env = WLR_DRM_NO_ATOMIC,1

env = PROTON_VERSION,Proton Experimental
env = LD_PRELOAD;/usr/lib/libgamemode.so

# cursor:no_hardware_cursors = true

env = XCURSOR_THEME,catppuccin-mocha-mauve-cursors
env = XCURSOR_SIZE,8

env = BROWSER, librewolf-bin

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# See https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = us,ua
    kb_options=grp:caps_toggle
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
    force_no_accel = 1
    # numlock_by_default = true
}

binds {
  allow_workspace_cycles = true
}

device {
    name = epic mouse V1
    sensitivity = -0.5
}

# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/

dwindle {
    pseudotile = yes
    preserve_split = yes
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/

master {
    new_status = true
}

# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

# See https://wiki.hyprland.org/Configuring/Va1riables/

misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
    force_zero_scaling = true
}

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/themes/common.conf # shared theme settings
source = ~/.config/hypr/themes/theme.conf # theme specific settings
source = ~/.config/hypr/monitors.conf # initially empty, to be configured by user and remains static


Config File: /home/sova/.config/hypr/animations.conf: Read Succeeded

# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

# See https://wiki.hyprland.org/Configuring/Animations/

animations {
    enabled = yes
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

Config File: /home/sova/.config/hypr/keybindings.conf: Read Succeeded

# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# See https://wiki.hyprland.org/Configuring/Keywords/
#  &  https://wiki.hyprland.org/Configuring/Binds/

# Main modifier
$mainMod = Super # super / meta / windows key

# Assign apps
$term = kitty
$editor = code
$file = nemo
$browser = librewolf-bin

# Window/Session actions
bind = SUPER, Q, killactive
bind = $mainMod, Delete, exit, # kill hyprland session
bind = $mainMod, H, togglefloating, # toggle the window between focus and float
bind = $mainMod, G, togglegroup, # toggle the window between focus and group
bind = Alt, Return, fullscreen, # toggle the window between focus and fullscreen
# bind = $mainMod, L, exec, swaylock # launch lock screen
bind = Ctrl+Alt, W, exec, killall waybar || waybar # toggle waybar

# Application shortcuts
bind = $mainMod, Return, exec, $term # launch terminal emulator
bind = $mainMod, F, exec, $file # launch file manager
bind = $mainMod, C, exec, $editor # launch text editor
bind = $mainMod, W, exec, $browser # launch web browser

# Wofi menus
bind = $mainMod, D, exec, wofi --show drun

# Media control
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle # toggle audio mute
bindl  = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle  # toggle microphone mute
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- # decrease volume
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ # increase volume

# Brightness control
bindel = , XF86MonBrightnessUp, exec, light -A 5% # increase brightness
bindel = , XF86MonBrightnessDown, exec, light -U 5% # decrease brightness

# Custom scripts
bind = Alt, Left, exec, $scrPath/swwwallpaper.sh -p # previous wallpaper
bind = Alt, Right, exec, $scrPath/swwwallpaper.sh -n # next wallpaper

# Screenshot/Screencapture
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -

# Move/Change window focus
bind = $mainMod, Left, movefocus, l
bind = $mainMod, Right, movefocus, r
bind = $mainMod, Up, movefocus, u
bind = $mainMod, Down, movefocus, d
bind = Alt, Tab, movefocus, d

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Switch workspaces to a relative workspace
bind = Alt, Tab, workspace, e+1
bind = Alt+Shift, Tab, workspace, e-1

# Move to the first empty workspace
bind = $mainMod+Ctrl, Down, workspace, empty 

# Resize windows
binde = $mainMod+Shift, Right, resizeactive, 30 0
binde = $mainMod+Shift, Left, resizeactive, -30 0
binde = $mainMod+Shift, Up, resizeactive, 0 -30
binde = $mainMod+Shift, Down, resizeactive, 0 30

# Move focused window to a workspace
bind = $mainMod+Shift, 1, movetoworkspace, 1
bind = $mainMod+Shift, 2, movetoworkspace, 2
bind = $mainMod+Shift, 3, movetoworkspace, 3
bind = $mainMod+Shift, 4, movetoworkspace, 4
bind = $mainMod+Shift, 5, movetoworkspace, 5
bind = $mainMod+Shift, 6, movetoworkspace, 6
bind = $mainMod+Shift, 7, movetoworkspace, 7
bind = $mainMod+Shift, 8, movetoworkspace, 8
bind = $mainMod+Shift, 9, movetoworkspace, 9
bind = $mainMod+Shift, 0, movetoworkspace, 10

# Move focused window to a relative workspace
bind = $mainMod+Ctrl+Alt, Right, movetoworkspace, r+1
bind = $mainMod+Ctrl+Alt, Left, movetoworkspace, r-1

# Move focused window around the current workspace
bind = $mainMod+Shift+Ctrl, Left, movewindow, l
bind = $mainMod+Shift+Ctrl, Right, movewindow, r
bind = $mainMod+Shift+Ctrl, Up, movewindow, u
bind = $mainMod+Shift+Ctrl, Down, movewindow, d

# Scroll through existing workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/Resize focused window
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod, Z, movewindow
bindl = $mainMod, X, exec, wlogout

# Toggle focused window split
bind = $mainMod, J, togglesplit

# Move focused window to a workspace silently
bind = $mainMod+Alt, 1, movetoworkspacesilent, 1
bind = $mainMod+Alt, 2, movetoworkspacesilent, 2
bind = $mainMod+Alt, 3, movetoworkspacesilent, 3
bind = $mainMod+Alt, 4, movetoworkspacesilent, 4
bind = $mainMod+Alt, 5, movetoworkspacesilent, 5
bind = $mainMod+Alt, 6, movetoworkspacesilent, 6
bind = $mainMod+Alt, 7, movetoworkspacesilent, 7
bind = $mainMod+Alt, 8, movetoworkspacesilent, 8
bind = $mainMod+Alt, 9, movetoworkspacesilent, 9
bind = $mainMod+Alt, 0, movetoworkspacesilent, 10

bind = $mainMod, Tab, workspace, previous

Config File: /home/sova/.config/hypr/windowrules.conf: Read Succeeded

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# windowrulev2 = opacity 1.00 1.00, class:^(LibreWolf)$
# windowrulev2 = opacity 0.80 0.80, class:^(obsidian)$
# windowrulev2 = opacity 0.90 0.90, class:^(kitty)$
# windowrulev2 = opacity 0.90 0.90, class:^(jetbrains-rider)$
# windowrulev2 = opacity 0.90 0.90, class:^(nemo)$
# windowrulev2 = opacity 0.90 0.90, class:^(code-oss)$
# windowrulev2 = opacity 0.90 0.90, class:^(Code)$
# windowrulev2 = opacity 0.90 0.90, class:^(discord)$
# windowrulev2 = opacity 0.90 0.90, class:^(heroic)$ 
# windowrulev2 = opacity 0.90 0.90, class:^(org.qbittorrent.qBittorrent)$ 

windowrulev2 = workspace 1, class:^(LibreWolf)$
windowrulev2 = workspace 2, class:^(kitty)$
windowrulev2 = workspace 4, class:^(nemo)$
windowrulev2 = workspace 8, class:^(code-oss)$
windowrulev2 = workspace 8, class:^(Code)$
windowrulev2 = workspace 9, class:^(org.telegram.desktop)$
# windowrulev2 = workspace 10, class:^(discord)$

windowrulev2=float,class:^(org.telegram.desktop|telegramdesktop)$,title:^(Media viewer)$

# windowrulev2 = opacity 0.90 0.90,class:^(jetbrains-rustrover)$
# windowrulev2 = opacity 0.80 0.80,class:^(code-url-handler)$
# windowrulev2 = opacity 0.80 0.80,class:^(code-insiders-url-handler)$
# windowrulev2 = opacity 0.80 0.80,class:^(org.kde.dolphin)$
# windowrulev2 = opacity 0.80 0.80,class:^(org.kde.ark)$
# windowrulev2 = opacity 0.80 0.80,class:^(nwg-look)$
# windowrulev2 = opacity 0.80 0.80,class:^(qt5ct)$
# windowrulev2 = opacity 0.80 0.80,class:^(qt6ct)$
# windowrulev2 = opacity 0.80 0.80,class:^(kvantummanager)$
# windowrulev2 = opacity 0.80 0.70,class:^(pavucontrol)$
# windowrulev2 = opacity 0.80 0.70,class:^(blueman-manager)$
# windowrulev2 = opacity 0.80 0.70,class:^(nm-applet)$
# windowrulev2 = opacity 0.80 0.70,class:^(nm-connection-editor)$
# windowrulev2 = opacity 0.80 0.70,class:^(org.kde.polkit-kde-authentication-agent-1)$
# windowrulev2 = opacity 0.80 0.70,class:^(polkit-gnome-authentication-agent-1)$
# windowrulev2 = opacity 0.80 0.70,class:^(org.freedesktop.impl.portal.desktop.gtk)$
# windowrulev2 = opacity 0.80 0.70,class:^(org.freedesktop.impl.portal.desktop.hyprland)$
# windowrulev2 = opacity 0.70 0.70,class:^([Ss]team)$
# windowrulev2 = opacity 0.70 0.70,class:^(steamwebhelper)$
# windowrulev2 = opacity 0.70 0.70,class:^(Spotify)$
# windowrulev2 = opacity 0.70 0.70,initialTitle:^(Spotify Free)$

windowrulev2 = opacity 0.90 0.90,class:^(com.github.rafostar.Clapper)$ # Clapper-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(com.github.tchx84.Flatseal)$ # Flatseal-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(hu.kramo.Cartridges)$ # Cartridges-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(com.obsproject.Studio)$ # Obs-Qt
windowrulev2 = opacity 0.80 0.80,class:^(gnome-boxes)$ # Boxes-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(WebCord)$ # WebCord-Electron
windowrulev2 = opacity 0.80 0.80,class:^(ArmCord)$ # ArmCord-Electron
windowrulev2 = opacity 0.80 0.80,class:^(app.drey.Warp)$ # Warp-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(net.davidotek.pupgui2)$ # ProtonUp-Qt
windowrulev2 = opacity 0.80 0.80,class:^(yad)$ # Protontricks-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(Signal)$ # Signal-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(io.github.alainm23.planify)$ # planify-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(io.gitlab.theevilskeleton.Upscaler)$ # Upscaler-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gtk
windowrulev2 = opacity 0.80 0.80,class:^(io.gitlab.adhami3310.Impression)$ # Impression-Gtk

windowrulev2 = float,class:^(LibreWolf)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(LibreWolf)$,title:^(Library)$
windowrulev2 = float,class:^(vlc)$
windowrulev2 = float,class:^(kvantummanager)$
windowrulev2 = float,class:^(qt5ct)$
windowrulev2 = float,class:^(qt6ct)$
windowrulev2 = float,class:^(nwg-look)$
windowrulev2 = float,class:^(org.kde.ark)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-applet)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$

windowrulev2 = float,class:^(Signal)$ # Signal-Gtk
windowrulev2 = float,class:^(com.github.rafostar.Clapper)$ # Clapper-Gtk
windowrulev2 = float,class:^(app.drey.Warp)$ # Warp-Gtk
windowrulev2 = float,class:^(net.davidotek.pupgui2)$ # ProtonUp-Qt
windowrulev2 = float,class:^(yad)$ # Protontricks-Gtk
windowrulev2 = float,class:^(eog)$ # Imageviewer-Gtk
windowrulev2 = float,class:^(io.github.alainm23.planify)$ # planify-Gtk
windowrulev2 = float,class:^(io.gitlab.theevilskeleton.Upscaler)$ # Upscaler-Gtk
windowrulev2 = float,class:^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gkk
windowrulev2 = float,class:^(io.gitlab.adhami3310.Impression)$ # Impression-Gtk


# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur,rofi
layerrule = ignorezero,rofi
layerrule = blur,notifications
layerrule = ignorezero,notifications
layerrule = blur,swaync-notification-window
layerrule = ignorezero,swaync-notification-window
layerrule = blur,swaync-control-center
layerrule = ignorezero,swaync-control-center
layerrule = blur,logout_dialog

Config File: /home/sova/.config/hypr/themes/common.conf: Read Succeeded

# █▀▀ █░█ █▀█ █▀ █▀█ █▀█
# █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

exec = hyprctl setcursor catppuccin-mocha-mauve-cursors 8
exec = gsettings set org.gnome.desktop.interface cursor-theme 'catppuccin-mocha-mauve-cursors'
exec = gsettings set org.gnome.desktop.interface cursor-size 8


# █▀▀ █▀█ █▄░█ ▀█▀
# █▀░ █▄█ █░▀█ ░█░

exec = gsettings set org.gnome.desktop.interface font-name 'Nunito 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'Nunito 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMono Nerd Font 9'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'


# █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

decoration {
    dim_special = 0.3
    blur {
        special = true
    }
}

Config File: /home/sova/.config/hypr/themes/theme.conf: Read Succeeded
exec = gsettings set org.gnome.desktop.interface icon-theme ePapirus-Dark
exec = gsettings set org.gnome.desktop.interface gtk-theme catppuccin-mocha-mauve-standard+default
exec = gsettings set org.gnome.desktop.interface color-scheme prefer-dark

general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.inactive_border = rgba(b4befecc) rgba(6c7086cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
    col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}

decoration {
    rounding = 0
    drop_shadow = false

    blur {
        enabled = yes
        size = 2
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

Config File: /home/sova/.config/hypr/monitors.conf: Read Succeeded

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# See https://wiki.hyprland.org/Configuring/Monitors/

# monitor = ,preferred,auto,auto
monitor = eDP-1, 1920x1080@144, 1920x0, 1
monitor = HDMI-A-1, 1920x1080@180, 0x0, 1
======Config-End========
```

</details>

### Description

The second monitor(HDMI) is flickering. Tried switching between 0.42.0-r1 and 0.43.0 but no success. It starts today after some hypr-related packages update(i don't remember which one). Maybe related to #7724

edit: fixes it if I stop the session and start it again

### How to reproduce

1. Start hyprland(I do it from tty).
2. Flickering starts.

### Crash reports, logs, images, videos

![image](https://github.com/user-attachments/assets/7b260ab8-dc66-40c9-99d1-b070b67c380f)

**Comment by vaxerski** [comment] 2024-09-12 16:31
looks like a dupe of the issue you linked

**Closed by vaxerski** 2024-09-12 16:31 UTC
Labels: bug

**Comment by vaxerski** [comment] 2024-09-12 19:10
not planned = dupe
