### ISSUE TITLE
GPU memory leak when opening/closing windows

### ISSUE THREAD

**Issue by ralgar** [hyprwm/Hyprland#7704] opened 2024-09-08 18:56 UTC
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 09:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: gaming-desktop
Release: 6.6.49-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 13:18:51 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/ralgar/.config/hypr/hyprland.conf: Read Succeeded
# ########################################################################### #
# #   ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗    # #
# #   ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗   # #
# #   ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║   # #
# #   ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║   # #
# #   ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝   # #
# #   ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝    # #
# ########################################################################### #

# Refer to https://wiki.hyprland.org for more information.

# Keep the primary monitor at its highest refresh rate.
monitor = DP-1,preferred,0x0,1

# Keep a large buffer zone for the auxilliary, so that the mouse doesn't traverse displays.
# Mouse can be switched to the aux display using workspace keybinds.
monitor = DP-2,highres,3840x0,1

input {
    # Keyboard Options
    numlock_by_default = 1

    # Mouse/Touchpad Options
    sensitivity = 0.0           # Mouse sensitivity (range -1.0 to 1.0)
    accel_profile = flat        # Mouse acceleration (adaptive, flat, or custom)

    touchpad {
        disable_while_typing = true
    }

    follow_mouse = 1            # Window focus follows mouse
}

general {
    gaps_in=5
    gaps_out=10
    border_size=2
    col.active_border=0xff5c6370
    col.inactive_border=0xff3e4452
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

decoration {
    rounding=9      # Use an odd value here for perfect symmetry.

    blur {
        enabled=0    # 0 to disable, 1 to enable.
        size=3       # Minimum 1, high values (5+) may cause artifacts.
        passes=1     # Minimum 1, more passes = more resource intensive.
    }

    drop_shadow = true
    shadow_range = 10
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = true

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = false     # Initialize with pseudotiling off
    force_split = 2        # Always split towards the right/bottom
    preserve_split = true  # You probably want this on
}

# #################### #
# #   WINDOW RULES   # #
# #################### #
windowrule=workspace 2,^(firefox)$
windowrule=fullscreen,^(gamescope)$

# Inhibit idle when the primary display has a fullscreen window
windowrulev2 = idleinhibit focus,monitor: 1,fullscreen: 1

# Fullscreen Discord on the auxilliary display
windowrule=monitor 2,^(discord)$
windowrule=fullscreen,^(discord)$

# ################ #
# #   KEYBINDS   # #
# ################ #
# General
bind=SUPER,Return,exec,alacritty
bind=SUPER,Q,killactive,
bind=SUPERSHIFT,Q,exit,
bind=SUPER,E,exec,wofi
bind=SUPER,V,togglefloating,
bind=SUPER,L,exec,hyprlock
bind=SUPER,F,fullscreen

# Window focus
bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

# Window Move and Resize
bindm=SUPER,mouse:272,movewindow      # Left Mouse
bindm=SUPER,mouse:273,resizewindow    # Right Mouse

# Workspaces
bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=SUPERSHIFT,1,movetoworkspace,1
bind=SUPERSHIFT,2,movetoworkspace,2
bind=SUPERSHIFT,3,movetoworkspace,3
bind=SUPERSHIFT,4,movetoworkspace,4
bind=SUPERSHIFT,5,movetoworkspace,5
bind=SUPERSHIFT,6,movetoworkspace,6
bind=SUPERSHIFT,7,movetoworkspace,7
bind=SUPERSHIFT,8,movetoworkspace,8
bind=SUPERSHIFT,9,movetoworkspace,9
bind=SUPERSHIFT,0,movetoworkspace,10

# Media keys
bind=,XF86AudioPlay,exec,mpc toggle
bind=,XF86AudioMute,exec,amixer -q set Master toggle
binde=,XF86AudioLowerVolume,exec,amixer -q set Master 5%-
binde=,XF86AudioRaiseVolume,exec,amixer -q set Master 5%+

# Screenshots and Recordings
bind=,Print,exec,grim -o $(hyprctl -j activeworkspace | jq -r .monitor)
bind=SUPERSHIFT,R,exec,save-replay.sh

# ####################### #
# #   Workspace Rules   # #
# ####################### #

# Bind workspace 0 to auxilliary monitor
workspace = 1,  monitor:DP-1
workspace = 2,  monitor:DP-1
workspace = 3,  monitor:DP-1
workspace = 4,  monitor:DP-1
workspace = 5,  monitor:DP-1
workspace = 10, monitor:DP-2

# ################# #
# #   Autostart   # #
# ################# #
exec-once=hyprpaper
exec-once=waybar
exec-once=mpd
exec-once=gammastep
exec-once=mako
exec-once=hypridle
exec-once=yubikey-touch-detector --libnotify
#exec-once=sh -c "ssh-agent -D -a $XDG_RUNTIME_DIR/ssh-agent.socket"

======Config-End========
```

</details>

### Description

When a native Wayland or Xwayland window is opened and then closed, total Hyprland vRAM usage for the session is permanently increased. I've seen it reach nearly a gigabyte over the course of a day.

I'm not sure if it's related, but the Xwayland server also seems to be leaking GPU memory in the same manner, often reaching nearly half a gig itself after using Steam and playing games for a while.

I first noticed the behavior around v0.41 and it's been consistent ever since, I just hadn't gotten around to opening an issue until now. If you can't repro, or need me to bisect, let me know and I'll get to it when I have a moment.

### How to reproduce

Simply open and close any application window while monitoring Hyprland's GPU memory usage. Usage increases by about 10-20MiB every time.

For the Xwayland server, do the same but with an Xwayland app such as Steam. You don't need to exit Steam each time, just open and close the window.

### Crash reports, logs, images, videos

```
Sun Sep  8 11:49:04 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB    Off |   00000000:01:00.0  On |                  N/A |
|  0%   59C    P0             23W /  150W |    1457MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      9023      G   Hyprland                                      787MiB |
|    0   N/A  N/A      9157      G   Xwayland                                      440MiB |
|    0   N/A  N/A     10092      G   /usr/lib/firefox/firefox                      103MiB |
|    0   N/A  N/A     13492      G   ...local/share/Steam/ubuntu12_32/steam          2MiB |
|    0   N/A  N/A     13867      G   ./steamwebhelper                               27MiB |
|    0   N/A  N/A     14076      G   alacritty                                      40MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by 3ri4nG0ld** [comment] 2024-09-08 23:59
![imagen](https://github.com/user-attachments/assets/f5158d67-b743-48e7-b8b4-12c486862746)

._.

**Comment by vaxerski** [comment] 2024-09-09 09:13
curious. Can you bisect this? I assume 0.42 did not exhibit this.

**Comment by HakaishinShwet** [comment] 2024-09-09 10:02
![image](https://github.com/user-attachments/assets/44a0ea66-aefa-4909-a549-e4f96c14478f)
same here i am using hyprland latest 0.43 on arch based linux garuda with latest kernel normal linux kernel 6.10 and i tested by opening and closing kitty again and again and again and it keeps on consuming more and more and more you can test yourself and will observe same behavior so yeah please fix this as soon as possible . Because at this rate i wont be able to run my local llm and keep closing and opening stuff :-((

**Comment by ralgar** [comment] 2024-09-09 15:27
> curious. Can you bisect this? I assume 0.42 did not exhibit this.

The issue was definitely present in 0.42, and I'm pretty sure 0.41 as well. I just didn't get around to opening an issue.

I'll see about bisecting it today.

**Comment by ralgar** [comment] 2024-09-09 17:45
This is what I landed on when bisecting for the Hyprland process leak:

```
2d552fbaa25f1457c3819521a2750dd30820271b is the first bad commit
commit 2d552fbaa25f1457c3819521a2750dd30820271b
Author: Vaxry <vaxry@vaxry.net>
Date:   Wed Aug 7 18:54:45 2024 +0200

    renderer: fixup nvidia driver version checks

 src/render/Renderer.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

As for the Xwayland leak, it does appear to be a Hyprland issue, but it was introduced in a different commit. Would you like me to open a separate issue for that one @vaxerski? I'm happy to bisect that as well, but it probably won't be today.

**Comment by vaxerski** [comment] 2024-09-10 10:02
maybe thats an nvidia bug? I mean, it doesnt seem to leak on intel/amdeeznuts

**Comment by ralgar** [comment] 2024-09-10 17:03
> maybe thats an nvidia bug? I mean, it doesnt seem to leak on intel/amdeeznuts

Yeah, that seems likely then. If that's the case, we would probably expect to see leaks in other OpenGL applications as well, no?

**Comment by vaxerski** [comment] 2024-09-10 22:19
closing then, good luck with nvidia I guess

**Closed by vaxerski** 2024-09-10 22:19 UTC
Labels: bug

**Comment by HakaishinShwet** [comment] 2024-09-11 07:09
dayumm

> > maybe thats an nvidia bug? I mean, it doesnt seem to leak on intel/amdeeznuts
> 
> Yeah, that seems likely then. If that's the case, we would probably expect to see leaks in other OpenGL (and possibly Vulkan) applications as well, no?
> 
> Edit: [Yeah, not exactly inspiring confidence here lol](https://forums.developer.nvidia.com/t/560-release-feedback-discussion/300830/165). I swear, an AMD GPU is the next thing on my shopping list.

dayummm that is the reason again nvidia shi*** driver issues . I can confirm that it doesnt happen in amd igpu atleast

**Comment by 3ri4nG0ld** [comment] 2024-09-14 09:13
My new AMD PC arrives on the 26th, fuck NVIDIA

**Comment by vfosterm** [comment] 2024-10-31 10:50
Hey everyone. Found a fix for the NVIDIA VRAM leak (besides buying an AMD GPU :D)
https://github.com/NVIDIA/egl-wayland/issues/126#issuecomment-2379945259

just replace kwin_wayland with Hyprland in the file. I'll upload my working one here as well. Just place it in /etc/nvidia/nvidia-application-profiles-rc.d and logout and back in again.
[50-limit-free-buffer-pool-in-wayland-compositors.json](https://github.com/user-attachments/files/17586630/50-limit-free-buffer-pool-in-wayland-compositors.json)

**Comment by haras-unicorn** [comment] 2025-01-31 13:29
> Hey everyone. Found a fix for the NVIDIA VRAM leak (besides buying an AMD GPU :D) [NVIDIA/egl-wayland#126 (comment)](https://github.com/NVIDIA/egl-wayland/issues/126#issuecomment-2379945259)
> 
> just replace kwin_wayland with Hyprland in the file. I'll upload my working one here as well. Just place it in /etc/nvidia/nvidia-application-profiles-rc.d and logout and back in again. [50-limit-free-buffer-pool-in-wayland-compositors.json](https://github.com/user-attachments/files/17586630/50-limit-free-buffer-pool-in-wayland-compositors.json)

idk what happened but the above doesnt work for me

my specs

```
Hyprland 0.45.2 built from branch v0.45.2-b at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: 2024-11-19
Tag: v0.45.2, commits: 12f9a0d0b93f691d4d9923716557154d74777b0a
built against aquamarine 0.4.4


flags set:
debug


System Information:
System name: Linux
Node name: hearth
Release: 6.12.2-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
29:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] [10de:2504] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  565.77  Release Build  (nixbld@)  Wed Jan  1 04:00:21 UTC 2025


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20250112.635e887"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_END="2025-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
```

not expecting any fix here but in case anyone else is scratching their head over this maybe another fix is needed for the 565 drivers

proof that the application profile is loaded correctly

![Image](https://github.com/user-attachments/assets/4daa4c42-b18d-4f90-be6f-c4825d0e97eb)

**Comment by DaRacci** [comment] 2025-02-06 09:03
> > Hey everyone. Found a fix for the NVIDIA VRAM leak (besides buying an AMD GPU :D) [NVIDIA/egl-wayland#126 (comment)](https://github.com/NVIDIA/egl-wayland/issues/126#issuecomment-2379945259)
> > just replace kwin_wayland with Hyprland in the file. I'll upload my working one here as well. Just place it in /etc/nvidia/nvidia-application-profiles-rc.d and logout and back in again. [50-limit-free-buffer-pool-in-wayland-compositors.json](https://github.com/user-attachments/files/17586630/50-limit-free-buffer-pool-in-wayland-compositors.json)
> 
> idk what happened but the above doesnt work for me
> 
> my specs
> 
> ```
> Hyprland 0.45.2 built from branch v0.45.2-b at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
> Date: 2024-11-19
> Tag: v0.45.2, commits: 12f9a0d0b93f691d4d9923716557154d74777b0a
> built against aquamarine 0.4.4
> 
> 
> flags set:
> debug
> 
> 
> System Information:
> System name: Linux
> Node name: hearth
> Release: 6.12.2-zen1
> Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980
> 
> 
> GPU information: 
> 29:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] [10de:2504] (rev a1) (prog-if 00 [VGA controller])
> NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  565.77  Release Build  (nixbld@)  Wed Jan  1 04:00:21 UTC 2025
> 
> 
> os-release: ANSI_COLOR="1;34"
> BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
> BUILD_ID="24.11.20250112.635e887"
> CPE_NAME="cpe:/o:nixos:nixos:24.11"
> DEFAULT_HOSTNAME=nixos
> DOCUMENTATION_URL="https://nixos.org/learn.html"
> HOME_URL="https://nixos.org/"
> ID=nixos
> ID_LIKE=""
> IMAGE_ID=""
> IMAGE_VERSION=""
> LOGO="nix-snowflake"
> NAME=NixOS
> PRETTY_NAME="NixOS 24.11 (Vicuna)"
> SUPPORT_END="2025-06-30"
> SUPPORT_URL="https://nixos.org/community.html"
> VARIANT=""
> VARIANT_ID=""
> VENDOR_NAME=NixOS
> VENDOR_URL="https://nixos.org/"
> VERSION="24.11 (Vicuna)"
> VERSION_CODENAME=vicuna
> VERSION_ID="24.11"
> 
> 
> plugins:
> ```
> 
> not expecting any fix here but in case anyone else is scratching their head over this maybe another fix is needed for the 565 drivers
> 
> proof that the application profile is loaded correctly
> 
> ![Image](https://github.com/user-attachments/assets/4daa4c42-b18d-4f90-be6f-c4825d0e97eb)
> 
> ```
> File: /etc/nvidia/nvidia-application-profiles-rc.d/50-limit-free-buffer-pool-in-wayland-compositors.json
>   {
>     "rules": [
>       {
>         "pattern": {
>           "feature": "procname",
>           "matches": "Hyprland"
>         },
>         "profile": "Limit Free Buffer Pool On Wayland Compositors"
>       }
>     ],
>     "profiles": [
>       {
>         "name": "Limit Free Buffer Pool On Wayland Compositors",
>         "settings": [
>           {
>             "key": "GLVidHeapReuseRatio",
>             "value": 1
>           }
>         ]
>       }
>     ]
>   }
> ```

I had this fail to work for me too on NixOS until i changed it to check the cmdline instead of procname, assuming that it may also work with procname set to .Hyprland-Wrapped as thats the actual binary that is executed.
