### ISSUE TITLE
non-resizable windows can be resized

### ISSUE THREAD

**Issue by exoess** [hyprwm/Hyprland#4589] opened 2024-02-02 01:24 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c51b3fb06f48657bcf66a92eca3de04066a9c8ef dirty (events: ignore sending mouse enter to focused if a constraint is active).
Date: Tue Jan 30 08:24:41 2024
Tag: v0.34.0-84-gc51b3fb0

flags: (if any)


System Information:
System name: Linux
Node name: warren
Release: 6.7.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 26 Jan 2024 19:10:20 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="OccultOS"
PRETTY_NAME="OccultOS"
ID="occultos"
ID_LIKE="arch"
ANSI_COLOR="1;0"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO="occultos"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

windows that shouldn't be resizable are still resizable inward, more specifically gtk windows with `resizable: false`

### How to reproduce

use a gtk application that shouldn't be resizable or run this python and try resizing inward
```py
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

def on_destroy(widget):
    Gtk.main_quit()

def main():
    Gtk.init()

    window = Gtk.Window()
    window.set_default_size(250, 250)
    window.set_resizable(False)

    window.connect("destroy", on_destroy)

    window.show_all()

    Gtk.main()

if __name__ == "__main__":
    main()
```

**Comment by vaxerski** [comment] 2024-02-02 01:52
set `minsize` and `maxsize` to the same size.

`set_resizable` is most likely x11 only

**Comment by exoess** [comment] 2024-02-02 01:53
i can't set minsize/maxsize on all windows that shouldn't be resized, and resizable works on other wayland compositors

**Comment by vaxerski** [comment] 2024-02-02 01:55
mhm, including sway?

I'll ask for a WAYLAND_DEBUG then from the app.

**Comment by exoess** [comment] 2024-02-02 01:59
never tested on sway, but on river and wayfire it works as expected

WAYLAND_DEBUG dumps a lot of info, anything specific i should be looking for?

**Comment by vaxerski** [comment] 2024-02-02 02:03
post entire thang

**Comment by exoess** [comment] 2024-02-02 02:06
here
[debug.txt](https://github.com/hyprwm/Hyprland/files/14133168/debug.txt)

**Comment by vaxerski** [comment] 2024-02-02 02:11
```
[2288234.228]  -> xdg_toplevel@32.set_min_size(250, 250)
[2288234.243]  -> xdg_toplevel@32.set_max_size(250, 250)
```
mhm so it does exactly that. 

I assume you can't resize _past_ the size? Now that I think about it I think we check max but not min size

**Comment by exoess** [comment] 2024-02-02 02:12
that would explain it

**Comment by exoess** [comment] 2024-02-06 01:41
seems like something's changed, you can still resize inward, but now if you stop resizing it'll snap back to the specified size

**Comment by vaxerski** [comment] 2024-02-06 01:43
![image](https://github.com/hyprwm/Hyprland/assets/43317083/812f89dc-7877-4f05-a7d0-120e0adcf7b1)

snap back to reality

**Comment by exoess** [comment] 2024-02-06 01:44
lol

**Comment by exoess** [comment] 2024-03-19 21:14
i have a development, this doesn't just apply to gtk windows, sdl windows that have fixed size can also still be resized, other compositors eg. wayfire and sway don't have this issue. is there possibly something that those compositors are getting that hyprland is not

**Comment by vaxerski** [comment] 2024-03-20 01:33
this should be fixed on latest hyprland.

**Comment by exoess** [comment] 2024-03-20 02:17
well its definitely working on gtk windows, but there's also a slightly related but also different issue with sdl windows

**Comment by vaxerski** [comment] 2024-03-20 02:20
and you won't be so nice to explain what the issue is?

**Comment by exoess** [comment] 2024-03-20 02:25
well it seems to be that the window has a set width and height, it's not non-resizable but it instead has a forced specific width and height which should prevent it from being resized

**Comment by vaxerski** [comment] 2024-03-20 17:57
wat?

**Comment by exoess** [comment] 2024-03-21 16:19
https://github.com/hyprwm/Hyprland/assets/102400503/48665065-9bbd-4d31-af30-f15ce7ed4f3a

https://github.com/hyprwm/Hyprland/assets/102400503/f6168d1b-4f2a-4cbd-b20f-440d21f6d2b5

first one is wayfire, second is hyprland, these are sdl windows that have a set size and resizable is false, but as you can see on hyprland the window can still be resized

**Comment by vaxerski** [comment] 2024-03-21 18:07
the game doesn't set itself as non-resizable properly then, and it's the game's fault.

**Closed** 2024-03-21 18:07 UTC
Labels: bug

**Comment by exoess** [comment] 2024-03-21 18:10
not a game, and how tf am i supposed to set the size then, sdl only has a few options for setting size and none of them work on hl

**Comment by exoess** [comment] 2024-03-21 18:14
interesting, thanks

**Comment by exoess** [comment] 2024-03-21 19:04
would it be possible to add a noresize window rules or smthn?

**Comment by vaxerski** [comment] 2024-03-21 19:24
minsize and maxsize exist

**Comment by exoess** [comment] 2024-03-21 19:42
yes, but that's not really the same, i could have two windows under the same class with radically different sizes

**Comment by vaxerski** [comment] 2024-03-21 19:44
then no

**Comment by exoess** [comment] 2024-03-21 19:45
hm, okay

**Comment by sr-tream** [comment] 2024-11-02 11:33
> set minsize and maxsize to the same size.

@vaxerski its not work with 4520b30d498daca8079365bdb909a8dea38e8d55 (0.44.1)

**Comment by sr-tream** [comment] 2024-11-02 12:33
```
windowrulev2 = tag +telegram, class:^(org\.telegram\.desktop)$
$telegramPos = 22 46
$telegramSize = 1160 1372
windowrulev2 = move $telegramPos, tag:telegram
windowrulev2 = size $telegramSize, tag:telegram
windowrulev2 = minsize $telegramSize, tag:telegram
windowrulev2 = maxsize $telegramSize, tag:telegram
```

Window creates on 22x46 with size 1160x1372, but I can resize them with `bindm = $mainMod, mouse:273, resizewindow`

**Comment by vaxerski** [comment] 2024-11-02 15:25
thats not what this issue is about
