### ISSUE TITLE
Windows zoom in for a second second when opening or switching between windows in fullscreen mode with no animations

### ISSUE THREAD

**Issue by Aaron-Speedy** [hyprwm/Hyprland#2647] opened 2023-07-04 22:48 UTC
Hi. I disabled animations recently, and I went to open a terminal when an existing terminal was already open. This caused both terminals to zoom in for a microsecond. I then opened a bunch of terminals in fullscreen mode, and switched between then, and had the visible terminal zoom in as well. I tested this in Firefox as well, and it also happened.

Steps to reproduce:
 - Disable animations. 
 - Open window on a workspace with a window already there.
 - Switch to fullscreen mode.
 - Switch between windows with cyclenext
Expected outcome:
 - Windows transition sharply and immediately with no zooming
Noted outcome:
 - Windows zoom in for a very short period of time when windows transition

**Comment by vaxerski** [comment] 2023-07-04 22:51
dupe of #683

**Closed by vaxerski** 2023-07-04 22:51 UTC
Labels: bug
