### ISSUE TITLE
Crashes when trying to start

### ISSUE THREAD

**Issue by antichriist** [hyprwm/Hyprland#2455] opened 2023-06-07 00:22 UTC
Fresh hyprland install on EndeavourOS.
AMD Ryzen 5 5600x + AMD RX 6700 XT

Log + Crash Report: 
```

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
*thud*

Hyprland received signal 11 (Segmentation fault)

Version: 4afeedbd567ca2114f682f14a6de26d4a8188878

System info:
	System name: Linux
	Node name: amethyst
	Release: 6.1.32-1-lts
	Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 18:23:39 +0000

GPU:
	09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release:
	NAME=EndeavourOS
	PRETTY_NAME=EndeavourOS
	ID=endeavouros
	ID_LIKE=arch
	BUILD_ID=2023.03.26
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL='https://endeavouros.com'
	DOCUMENTATION_URL='https://discovery.endeavouros.com'
	SUPPORT_URL='https://forum.endeavouros.com'
	BUG_REPORT_URL='https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports'
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=endeavouros
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x78e) [0x55c2f419e66e]
		??
		??:0
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x55c2f4139eac]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x39ab0) [0x7f742924fab0]
		??
		??:0
	#3 | Hyprland(_Z6wlTickPv+0x22) [0x55c2f41f8352]
		??
		??:0
	#4 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x2e7) [0x7f7429e4ad27]
		??
		??:0
	#5 | /usr/lib/libwlroots.so.12032(+0x52651) [0x7f7429ee4651]
		??
		??:0
	#6 | /usr/lib/libwlroots.so.12032(wlr_backend_autocreate+0x6a6) [0x7f7429ee5066]
		??
		??:0
	#7 | Hyprland(_ZN11CCompositor10initServerEv+0xbf) [0x55c2f4148bef]
		??
		??:0
	#8 | Hyprland(main+0x498) [0x55c2f412a9f8]
		??
		??:0
	#9 | /usr/lib/libc.so.6(+0x23850) [0x7f7429239850]
		??
		??:0
	#10 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f742923990a]
		??
		??:0
	#11 | Hyprland(_start+0x25) [0x55c2f4139d55]
		??
		??:0


Log tail:
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: amethyst
[LOG] Release: 6.1.32-1-lts
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 18:23:39 +0000


[LOG] GPU information:
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME=EndeavourOS
PRETTY_NAME=EndeavourOS
ID=endeavouros
ID_LIKE=arch
BUILD_ID=2023.03.26
ANSI_COLOR="38;2;23;147;209"
HOME_URL='https://endeavouros.com'
DOCUMENTATION_URL='https://discovery.endeavouros.com'
SUPPORT_URL='https://forum.endeavouros.com'
BUG_REPORT_URL='https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports'
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=endeavouros

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: I'm still standing, better than I ever did


[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 14.63µs. Estimated average calc time: 0.00µs.
[LOG] Creating the ConfigManager!
[LOG] Creating the CHyprError!
[LOG]  [hookSystem] New hook event registered: focusedMon
[LOG]  [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 7.11µs. Estimated average calc time: 0.00µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.98µs. Estimated average calc time: 0.00µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
[LOG] Disabling stdout logs! Check the log for further logs.

```

**Comment by romanstingler** [comment] 2024-03-09 22:05
is this resolved for you??

**Comment by vaxerski** [comment] 2024-03-09 22:30
not a hyprland issue, looks like a dupe of something ages ago

**Closed by vaxerski** 2024-03-09 22:30 UTC
Labels: bug
