### ISSUE TITLE
Mouse pointer jumps to center in Blender

### ISSUE THREAD

**Issue by niklasw** [hyprwm/Hyprland#6173] opened 2024-05-20 20:42 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: helm
Release: 6.8.9-100.fc38.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Thu May  2 18:50:49 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev d1) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

The behaviour is so far only encountered in Blender, not running Xwayland: On middle mouse click, eg for panning and rotating view the mouse pointer immediately jumps to the window center. Same thing when left click on a numeric input, the latter making it impossible to edit numeric inputs.

This has been tested with several blender versions (3.11 to latest build).

The issue does not appear on other Wayland WMs such as Sway or Gnome (on Wayland).

### How to reproduce

Start blender and try to select any input widget to edit it manually.
Try rotating the default scene in blender.

**Comment by Agent00Ming** [comment] 2024-05-20 20:50
it's fixed in git... dupe of #5881

**Comment by niklasw** [comment] 2024-05-20 21:02
> it's fixed in git... dupe of #5881. Numeric input one is tracked at #6035

OK, closing. Sorry for not finding the dupe.

**Closed** 2024-05-20 21:03 UTC
Labels: bug
