### ISSUE TITLE
Focus (Mouse + hyprctl)

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#1292] opened 2022-12-28 13:44 UTC
Hyprland focus pattern needs a bit changes.

e.g 

if using `follow_mouse=0` or `1` 
then `hyprctl kill` will kill the desired window else will not.

if every window on the workspace is in floating mode then using `cyclenext` should get the final focused window on top.
kindda possible by bash script but then `cyclenext prev` gives unpredicted behaviour.

**Comment by vaxerski** [comment] 2022-12-28 13:52
cyclenext doesnt bring the focused window on top, there's another dispatcher for bringing a window to top. Define 
"unpredicted behaviour"

**Comment by niksingh710** [comment] 2022-12-28 14:26
yep i had tried `bringactivetotop`

let's take a example if i have 4 windows open `discord, telegram, filemanager, terminal` in this order.
if i use script that brings the focused window on top as soon as it gets focused. 
cyclenext work as expected.

but for `cyclenext prev` as soon as i do that now the order is `telegram,discord,filemanager,terminal`  and using `cyclenext prev` again makes the order `discord, telegram, filemanager, terminal` it is kindda annoying as it is not cycling back but cycling between last two application as it makes the window on top of stack.

tried bindr so that `bringactivetotop` executes when the key gets released but that is not what i want.

[script](http://ix.io/4jMv) that i use to focus. uncomment line 22 to get floating on top.

**Comment by vaxerski** [comment] 2022-12-28 15:41
I see, and makes sense. Alr.

**Comment by vaxerski** [comment] 2022-12-28 15:42
shouldnt this be a dupe of #1290 then?

**Comment by niksingh710** [comment] 2022-12-29 05:58
> shouldnt this be a dupe of #1290 then?

yes it is been discussed there.

what about `hyprctl kill` ?

**Comment by vaxerski** [comment] 2022-12-29 10:53
fixed in 3e2200ed90b1e4451955f8391bfdc8dcb3d8c887

closing then in favor of #1290

**Closed by vaxerski** 2022-12-29 10:53 UTC
Labels: bug
