### ISSUE TITLE
Build fails on NixOS

### ISSUE THREAD

**Issue by WilliamBehrens** [hyprwm/Hyprland#2225] opened 2023-05-03 18:43 UTC
`nixos-rebuild test --flake .#framework`
![image](https://user-images.githubusercontent.com/35979547/236013122-34efbf11-48b5-4957-aac8-620811d570f8.png)

Here's my flake https://gitlab.com/pixqw/dotfiles/-/tree/v2?ref_type=heads

**Comment by vaxerski** [comment] 2023-05-03 18:50
pretty sure it's a dupe of #2120

**Closed by vaxerski** 2023-05-03 18:50 UTC
Labels: bug
