### ISSUE TITLE
Drop down windows and dialogue boxes are being centered and misplaced

### ISSUE THREAD

**Issue by sweetbbak** [hyprwm/Hyprland#3335] opened 2023-09-17 02:10 UTC
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

A lot of applications with floating dialogue boxes and menus are being spawned and placed in the center of the desktop.
I've noticed this with Godot, Blender, Brave, Qbittorrent (qt5 in general) and almost every XWayland window. Sometimes the menu's are usable in the center of the screen (video 1), and other times it is offset where you can move your mouse around and highlight parts of the menu when your mouse is not over the menu (video 2)

https://github.com/hyprwm/Hyprland/assets/75046310/143c8f1b-16aa-4d6a-9e37-195a7de0acac

https://github.com/hyprwm/Hyprland/assets/75046310/f73255f3-6158-465f-9071-8b4c0e0fa595

Rules I've tried: 
```
## Godot
windowrulev2 = noblur, class:^(.*Godot.*)$, title:^(.*Godot.*)$,
windowrulev2 = noborder, class:^(Godot.*)$, title:^(Godot.*)$,
windowrulev2 = noshadow, class:^(Godot.*)$, title:^(Godot.*)$,
windowrulev2 = opacity 1.0, class:^(Godot.*)$, title:^(Godot.*)$,
windowrulev2 = opaque, class:^(Godot.*)$, title:^(Godot.*)$,
windowrulev2 = float, class:^(Godot.*)$,
windowrulev2 = noanim, class:^(Godot.*)$,
windowrulev2 = float,floating:0,class:^(Godot*)
windowrulev2 = forceinput,class:^(Godot*)
windowrulev2 = windowdance,class:^(Godot*) # allows Godot to move child windows
windowrulev2 = nofocus,class:^(Godot*) # allows Godot to move child windows
# windowrulev2 = forcergbx, class:^(Godot.*)$, title:^(Godot.*)$,
# windowrulev2 = noinitialfocus, class:^(Godot.*)$, title:^(Godot.*)$,

```
Another issue with Godot specifically is that the class and title are always dynamic according to the project title or pop dialogue. The only parameter that is consistent is "InitialTitle" or "InitialClass"

### How to reproduce

Open godot and scroll through the menus. This behavior is noticeable in brave-bin from the AUR, Qbittorrent and some specific parts of Blender.

**Comment by MightyPlaza** [comment] 2023-09-17 12:43
likely dupe of https://github.com/hyprwm/Hyprland/issues/3150, update

**Comment by sweetbbak** [comment] 2023-09-17 19:30
I dont see how they are related, windows are being centered when they shouldn't be and then behaving weirdly. It's also not an issue with file pickers but with drop down menu's that are inside another client.

**Comment by MightyPlaza** [comment] 2023-09-17 19:36
you're not on latest build from git, you're on latest release (0.29.1)
yes, window placement is an issue for most xwayland programs
but wayland native programs shouldn't cause issues (after updating)

**Comment by sweetbbak** [comment] 2023-09-17 20:04
Switched to hyprland-git

hyprctl version:
Hyprland, built from branch main at commit b0a82c04dfc3f08183d68318a1d0eb4001c99559 dirty (bezier: Remove Todo about N-Point bezier curves. (3352)).
Tag: v0.29.1-88-gb0a82c04

Same issue persisting. Or is there an even newer version?

**Comment by MightyPlaza** [comment] 2023-09-17 20:07
make sure the applications are not running under xwayland (`hyprctl clients`)

**Comment by sweetbbak** [comment] 2023-09-17 20:20
In Blender, Hyprland will allow the drop down menu to be put into the correct position, but when moving the mouse into the zone of the drop down menu the menu just disappears as if it isn't there. Hypr-prop says that Blender isn't using Xwayland. Godot _is_ Xwayland and doesn't work like you said.

**Comment by vaxerski** [comment] 2023-09-22 23:01
haunted. I've never seen that happen.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/b6a8bdd9-e4ee-440b-a442-b8ebd7f3b700)

**Comment by sweetbbak** [comment] 2023-09-23 00:42
It only happens with specific applications. 
https://github.com/sweetbbak/dots/tree/main/.config/hypr

**Comment by vaxerski** [comment] 2023-09-23 12:35
it's your windowrules that cause the issue.

Specifically, these:
```
windowrulev2 = center,xwayland:1
windowrulev2 = float,xwayland:1
```

Hyprland does what you told it to.

**Closed by vaxerski** 2023-09-23 12:35 UTC
Labels: bug

**Comment by sweetbbak** [comment] 2023-09-23 18:58
That was me attempting to troubleshoot the issue. It does it without it as well.

**Comment by vaxerski** [comment] 2023-09-23 19:04
well, no. You just have those rules duplicated and all over the place.

**Comment by sweetbbak** [comment] 2023-09-23 19:25
Yea, it did. My bad. I still have the issue with Blender but at this point I'm guessing that it's probably Blenders fault.

**Comment by tuconnaisyouknow** [comment] 2025-05-09 00:05
Hi, sorry for asking this late, did you fix this issue ?
