### ISSUE TITLE
groupbar border?

### ISSUE THREAD

**Issue by gksudolol** [hyprwm/Hyprland#8406] opened 2024-11-10 01:37 UTC
### Description

With rounding enabled, the groupbar kinda looks out of place. Maybe something like `bar_precedence_over_border` similar to how hyprbars has it?

![Screenshot-2024-11-10-01-27-46](https://github.com/user-attachments/assets/4c710e9d-7ec4-443b-af98-df9cfef09827)

**Comment by MightyPlaza** [comment] 2024-11-10 01:48
decoration priority iirc, it isn't polished doe

**Comment by izmyname** [comment] 2024-11-23 19:50
I think the best way would be to put groupbars inside a window's border - make them look like it's a 'part' of the window or smth.

**Comment by MightyPlaza** [comment] 2024-11-23 20:22
> decoration priority iirc, it isn't polished doe

like I said you can already set it in there with `group:groupbar:priority`, but it isn't polished
mostly because of the issue you can already experience in hyprbars where there are wrong pixels where the boxes touch

additionally this is just a dupe of the groupbar feature request issue

**Comment by izmyname** [comment] 2024-11-23 20:30
`group:groupbar:priority` is also poorly documented. Default=3, what 3? What is this even supposed to mean?

**Comment by izmyname** [comment] 2024-11-23 20:33
> see `hyprctl decorations <window>`

It didn't make it more clear, tbh.

Anyway, if you say - this is bugged, I'll better wait till it gets good.

**Comment by MightyPlaza** [comment] 2024-11-23 20:36
> > see `hyprctl decorations <window>`
> 
> It didn't make it more clear, tbh.
> 
> Anyway, if you say - this is bugged, I'll better wait till it gets good.

it sets the decoration priority for the groupbar, (using 10001 should make it appear inside the border)
it's not bugged it just doesn't get rounded which likely looks bad if you're not using 0 rounding

**Comment by izmyname** [comment] 2024-11-23 20:39
I use rounding, so I guess this not for me.

In case rounding gets fixed - I think it'd be better to replace priority with smth like `groupbar_inside_border = 0/1`

**Comment by MightyPlaza** [comment] 2024-11-23 20:43
> I use rounding, so I guess this not for me.
> 
> In case rounding gets fixed - I think it'd be better to replace priority with smth like `groupbar_inside_border = 0/1`

no because then you wouldn't be able to control it in relation to other decorations
for example if you want groupbar bellow hyprbar bellow the border

**Comment by vaxerski** [comment] 2024-11-23 22:09
#2415

**Closed by vaxerski** 2024-11-23 22:09 UTC
Labels: enhancement
