### ISSUE TITLE
GPU usage is about 16% when computer is idle

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#1247] opened 2022-12-18 06:41 UTC
I don't know if it's a bug.
I'm a intel/nvidia hybrid user. I use `intel_gpu_top` util in `intel-gpu-tools` package from arch linux to see the usage of graphics card. The `Render/3D` part always has about 16% usage when my computer is idle. But in `wayfire` and `sway`. There is 0% usage when idle.

**Comment by mshzsh** [comment] 2022-12-18 11:46
@dragove It was like this for me, of course I tested on `bspwm` and `hyprland`, and I noticed that `bspwm` uses nvidia, but when I switch to `hyprland`, nvidia is completely disabled and Intel only works, and that's the reason for 16% usage.

**Comment by NotAShelf** [comment] 2022-12-18 11:50
That is because Nvidia cannot be used in Wayland without additional configuration. See [here](https://wiki.archlinux.org/title/wayland#Nvidia_driver), [here](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting) and most importantly [here](https://wiki.hyprland.org/Nvidia/). It is pretty much expected behavior that your Nvidia GPU will be disabled if you have not completed those steps.

And for future reference, you should avoid testing on X11 if you are looking for a bug on Hyprland. The Nvidia experience is not on par on X11 and Wayland.

**Comment by mshzsh** [comment] 2022-12-18 12:00
> That is because Nvidia cannot be used in Wayland without additional configuration. See [here](https://wiki.archlinux.org/title/wayland#Nvidia_driver), [here](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting) and most importantly [here](https://wiki.hyprland.org/Nvidia/). It is pretty much expected behavior that your Nvidia GPU will be disabled if you have not completed those steps.

I did all these steps before but it didn't work on my laptop because there is no definitive way to make Wayland work on all nvidia graphics.


> And for future reference, you should avoid testing on X11 if you are looking for a bug on Hyprland. The Nvidia experience is not on par on X11 and Wayland.


I have not used sway and wayfire with nvidia yet, and I guessed that maybe this happened to you because of the switch to Intel.

**Comment by NotAShelf** [comment] 2022-12-18 12:06
> there is no definitive way to make Wayland work on all nvidia graphics.

Exactly, Nvidia on Linux is already sloppy and wayland is even worse thanks to their lack of interest. There is a reason why Hyprland does not officially support Nvidia. If you can make it work, great! If not, sucks.

> I have not used sway and wayfire with Nvidia yet, and I guessed that maybe this happened to you because of the switch to Intel.

Whether or not you have used Sway and Wayfire is irrelevant to the discussion. You will not get comparable results on X11. If you see something break on Hyprland, and test it on bspwm, it's not going to give us any data to work on. The experience is **not on par**. If you want to identify a Hyprland bug, you need to test on another Wayland - preferably a wlroots based - compositor. Otherwise the results are meaningless.

**Comment by mshzsh** [comment] 2022-12-18 12:14
> Whether or not you have used Sway and Wayfire is irrelevant to the discussion. You will not get comparable results on X11. If you see something break on Hyprland, and test it on bspwm, it's not going to give us any data to work on. The experience is not on par. If you want to identify a Hyprland bug, you need to test on another Wayland - preferably a wlroots based - compositor. Otherwise the results are meaningless.

You're absolutely right, but I'm not making any comparison between hyprland and bspwm, I just gave an example to say that this problem is probably due to nvidia being inactive, otherwise it's stupid to find a bug in wayland through X11! :open_mouth:

**Comment by vaxerski** [comment] 2022-12-18 12:41
fixed in a163ca92377a56c196222a48c0a5676a7bb4ac3b

**Closed by vaxerski** 2022-12-18 12:41 UTC
Labels: bug
