### ISSUE TITLE
Some Xwayland windows spawn out of view + mouse input mapped incorrectly after monitor reconnect

### ISSUE THREAD

**Issue by phonetic112** [hyprwm/Hyprland#3862] opened 2023-11-16 04:21 UTC
### Hyprland Version

Hyprland, built from branch main at commit 91d6be1f09a0c0eaf585e88d315a7e56cac315a3 dirty (groupbar: Fix position of groupbar titles on monitor scales != 1.0 (3856)). Tag: v0.32.3-21-g91d6be1f  flags: (if any)

### Bug or Regression?

Bug

### Description

Some Xwayland windows like `xeyes`, `glxgears`, and wine/proton apps spawn out of view after disconnecting and reconnecting my monitor. Wine applications also get their mouse input mapped incorrectly, so I can't click on or hover over anything in the menus. I have to restart Hyprland to fix this. 

I think Xwayland apps using GTK/Qt are unaffected.

### How to reproduce

1. Start Hyprland
2. Open a wine application, observe expected behavior
3. Close wine application
4. Disconnect and reconnect monitor
5. Open a wine application
6. Observe that you cannot click anything in the window

**Comment by andresilva** [comment] 2023-11-16 10:54
Isn't this a duplicate of https://github.com/hyprwm/Hyprland/issues/3727?

**Comment by vaxerski** [comment] 2023-11-16 11:02
I would say so

**Closed by vaxerski** 2023-11-16 11:02 UTC
Labels: bug

**Comment by rszyma** [comment] 2023-11-17 11:48
It would be good to report this as a comment in https://github.com/hyprwm/Hyprland/issues/3727, because it adds more context for this bug to happen
