### ISSUE TITLE
Rendering fails with external monitor

### ISSUE THREAD

**Issue by gegnew** [hyprwm/Hyprland#1623] opened 2023-02-23 20:54 UTC
### Steps to reproduce
- set up hyprland
- plug it in to external monitor
- configure like so:
```
monitor = DP-1, preferred, 0x0, auto  # <-- external
workspace=DP-1,1
monitor=eDP-1, preferred, 835x1440, auto
workspace=eDP-1, 9
workspace=eDP-1, 10
```

### Expected outcome
hyprland, but with a second screen

### Noted outcome
If I try to do anything on a workspace assigned to the external monitor (e.g. open the special workspace, change to another workspace on the external monitor), the monitor...freezes, I guess?

If I change focus to my laptop screen (either with the mouse or by changing to a workspace assigned to the laptop screen), then change focus back to the monitor, the expected changes are rendered.

**Comment by etherrorcode404** [comment] 2023-02-23 21:46
have you tried ```monitor=,preferred,auto,1```?

**Comment by digiwhite1** [comment] 2023-02-24 12:23
Actually I've faced with the same behavior on my setup (laptop + external monitor) but at the and I've got a crash.

The config part:
```
monitor=eDP-1,preffered,auto,auto
workspace=eDP-1,1

monitor=HDMI-A-2,2560x1440,auto,auto
workspace=HDMI-A-2,2
```
Here is a crash log example:
```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
This was an accident, I swear!

Hyprland received signal 11 (SIGSEGV): Segmentation Fault

System info:
	System name: Linux
	Node name: andromeda
	Release: 6.1.12-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEv+0x661) [0x55704c4568d1]
		??
		??:0
	#1 | Hyprland(_Z10handleSegvi+0x9) [0x55704c3f7519]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x38f50) [0x7fe168769f50]
		??
		??:0
	#3 | Hyprland(_ZN15CHyprOpenGLImpl12renderBorderEP7wlr_boxRK18CGradientValueDataif+0x5a8) [0x55704c4e5a98]
		??
		??:0
	#4 | Hyprland(_ZN13CHyprRenderer12renderWindowEP7CWindowP8CMonitorP8timespecb15eRenderPassModebb+0x97a) [0x55704c4ecf1a]
		??
		??:0
	#5 | Hyprland(_ZN13CHyprRenderer26renderAllClientsForMonitorERKiP8timespec+0x66a) [0x55704c4f06ba]
		??
		??:0
	#6 | Hyprland(_ZN6Events21listener_monitorFrameEPvS0_+0xb46) [0x55704c470cb6]
		??
		??:0
	#7 | Hyprland(_Z13handleWrappedP11wl_listenerPv+0x3c) [0x55704c48eafc]
		??
		??:0
	#8 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x7fe168e89f6e]
		??
		??:0
	#9 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch_idle+0x23) [0x7fe168e8b923]
		??
		??:0
	#10 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xfd) [0x7fe168e8ba3d]
		??
		??:0
	#11 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7fe168e8c197]
		??
		??:0
	#12 | Hyprland(main+0x60d) [0x55704c3ed4ed]
		??
		??:0
	#13 | /usr/lib/libc.so.6(+0x23790) [0x7fe168754790]
		??
		??:0
	#14 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fe16875484a]
		??
		??:0
	#15 | Hyprland(_start+0x25) [0x55704c3f7415]
		??
		??:0
```
hyprland has been build based on Aur recipe, latest git version: 
```
hypctl version
Hyprland, built from branch main at commit 60e37d727def25c87a3fd6c47751c05f6082260fdirty (fix cyclenext on empty focus).
flags: (if any)

```

**Comment by vaxerski** [comment] 2023-02-24 12:50
looks like a dupe of #1579 

can you try setting an explicit scale for your monitor?

**Comment by digiwhite1** [comment] 2023-02-24 13:13
@vaxerski this one works:
```
monitor=eDP-1,1920x1080,0x0,1
workspace=eDP-1,1

monitor=HDMI-A-2,2560x1440,1920x0,1
workspace=HDMI-A-2,2
```

**Comment by vaxerski** [comment] 2023-02-24 13:15
dupe then, see #1579

**Closed by vaxerski** 2023-02-24 13:15 UTC
Labels: bug

**Comment by gegnew** [comment] 2023-02-24 16:09
Thanks for the quick response!
