### ISSUE TITLE
Workspace swipe on last workspace shaky jitters

### ISSUE THREAD

**Issue by sarveshrulz** [hyprwm/Hyprland#444] opened 2022-07-29 00:50 UTC
When swiping on last workspace, everything looks like it's shaking and stuck there till further input, it's like it's trying to go to non-existent next workspace in infinite loop and going back as there isn't any next workspace...

**Comment by vaxerski** [comment] 2022-08-19 07:17
does it still happen? I'm unable to reproduce.

**Comment by vaxerski** [comment] 2022-10-20 16:55
should be fixed

**Closed by vaxerski** 2022-10-20 16:55 UTC
