### ISSUE TITLE
Steam causes mouse follow cursor

### ISSUE THREAD

**Issue by crypticC0der** [hyprwm/Hyprland#2236] opened 2023-05-04 10:11 UTC
when steam is open and smaller than it wants to be (some ui elements out of frame within the app ie the top right close button)  it causes focus to follow mouse

to reproduce: 
disconnect focus from mouse ie options 0 2 or 3, open steam, open a bunch of terminals or whatever low workload program you want, notice how focus begins following mouse

this isn't an issue when steam is big enough
there doesn't seem to be any issue I can find but I've mentioned this a couple of times and haven't found a fix, someone mentioned it being due to Xwayland, maybe have a option to surpress Xevents from certain programs

**Comment by crypticC0der** [comment] 2023-05-04 18:03
the new steam beta update fixes this

**Comment by FakeMichau** [comment] 2023-10-16 13:12
> the new steam beta update fixes this

I cannot reproduce this on the stable version so it's probably fixed and the issue can be closed.

**Comment by izmyname** [comment] 2024-07-29 16:31
Bump. Close the issue, please.

**Closed** 2024-07-29 18:42 UTC
Labels: bug
