### ISSUE TITLE
focus not follow mouse moving from other app to terminal/rofi

### ISSUE THREAD

**Issue by linc01** [hyprwm/Hyprland#5782] opened 2024-04-28 03:59 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: arlucy
Release: 6.8.7-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The focus not follow mouse moving from other app to terminal. 
Case 1: Window A is a browser and Window B is a terminal
If you move the mouse from browser to the terminal you just can see the color changed of the window frame, but the focus not move completely. Mouse is work on the terminal but you can't input. And if you move the cursor back to the browser and move back to the terminal again, everything works fine.
Case 2: Window A is a terminal and Window B is a terminal
No bug everything works fine
Case 3: Window A is a any app and Window B is a terminal
Same as Case 1
Case 4: Window A is a browser or any app and Window B is any app
No bug everything works fine

Rofi is as same as the terminal, you have to move the mouse to let it focus on the pop up rofi window.

### How to reproduce

Just open some windows to reproduce.

### Crash reports, logs, images, videos

No crash report and I don't know when it happened. May be it started just after the latest update, not sure.  I ave fcitx5 5.1.9 installed. BTW, the rofi focus error can be fixed by replacing rofi to  rofi-wayland.

**Comment by linc01** [comment] 2024-04-28 04:14
I've tried alacrity, foot, all the same. Kitty is even worse, you can not typing any more if you once move the mouse away the kitty window.

**Comment by Sharpless298** [comment] 2024-04-28 04:43
#fcitx/fcitx5/issues/1031

**Comment by sungyoonc** [comment] 2024-04-28 05:40
Maybe dupe of #5763?

**Comment by linc01** [comment] 2024-04-28 06:08
> [fcitx/fcitx5#1031](https://github.com/fcitx/fcitx5/issues/1031)

In my case the input is completely disappear and everything goes to be fine if I move the focus twice.

**Comment by linc01** [comment] 2024-04-28 06:22
> Maybe dupe of #5763?

@sungyoonc maybe, but when creating a new terminal emulator in an empty workspace, I can type into it. In the case2, nothing unusual.

**Comment by sungyoonc** [comment] 2024-04-28 06:26
Then can you try the latest git of hyprland? Your issue seems like the same issue I reproduced here. https://github.com/hyprwm/Hyprland/issues/5763#issuecomment-2081340217

**Comment by linc01** [comment] 2024-04-28 07:32
> Then can you try the latest git of hyprland? Your issue seems like the same thing I reproduced here. [#5763 (comment)](https://github.com/hyprwm/Hyprland/issues/5763#issuecomment-2081340217)

@sundhaug92 thanks, I'll find another laptop to try the latest git, will let you know if it works.

**Comment by hnsylzg** [comment] 2024-04-30 05:47
The latest version of hyprland solves this problem but introduces a new problem. The submap cannot be displayed on the waybar.

**Comment by sungyoonc** [comment] 2024-04-30 06:03
> The latest version of hyprland solves this problem but introduces a new problem. The submap cannot be displayed on the waybar.

@hnsylzg That is probably fixed in https://github.com/Alexays/Waybar/pull/3183 . Please try the git version of waybar and if that doesn't fix it, make a new issue.

**Comment by linc01** [comment] 2024-04-30 10:43
> > The latest version of hyprland solves this problem but introduces a new problem. The submap cannot be displayed on the waybar.
> 
> @hnsylzg That should probably be fixed in [Alexays/Waybar#3183](https://github.com/Alexays/Waybar/pull/3183) . Please try the git version of waybar, and if that doesn't fix it, make a new issue.

I had installed a git version on my macbook but not have a chance to test these issues, the SUPER +Q not work, SUPER + M works occasionally.

**Comment by vaxerski** [comment] 2024-04-30 13:18
dupe of #5763

**Closed by vaxerski** 2024-04-30 13:18 UTC
Labels: bug

**Comment by linc01** [comment] 2024-04-30 21:36
> dupe of #5763

Thanks, I've installed the git version and will try it after I fix the SUPER(COMMAND) key issue.

**Comment by linc01** [comment] 2024-05-13 20:52
the latest update 0.40 fixed this bug
