### ISSUE TITLE
gaps out still exist w/ config option no_gaps_when_only on master layout

### ISSUE THREAD

**Issue by entailz** [hyprwm/Hyprland#5629] opened 2024-04-18 00:19 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e8e02e81e84bb04efa0c926361ec80c60744f665  (README: minor cleanup).
Date: Tue Apr 16 12:36:21 2024
Tag: v0.39.1-1-ge8e02e81, commits: 4461
```

</details>

### Bug or Regression?

Bug

### Description

Outter gaps are still showing when adding a new buffer to window group while no_gaps_when_only = 2 is set in master layout. This phenomena does not occur when config option is set in dwindle layout. 

### How to reproduce

```
master {
  no_gaps_when_only = 2
}
```
group two windows on a new/empty workspace.

**Comment by thejch** [comment] 2024-04-18 23:25
dupe of https://github.com/hyprwm/Hyprland/issues/5552 ?

**Closed** 2024-04-19 01:47 UTC
Labels: bug
