### ISSUE TITLE
Image remains when switch window in monocle mode, no matter turn on/off the animation

### ISSUE THREAD

**Issue by TTtrace** [hyprwm/Hyprland#2114] opened 2023-04-21 01:29 UTC
https://user-images.githubusercontent.com/39454079/233519241-3a17dbf1-7014-422e-975b-b94e1ed0c961.mp4

As the video shown here, how to avoid this?

**Comment by vaxerski** [comment] 2023-04-21 01:30
dupe of #683

**Closed by vaxerski** 2023-04-21 01:30 UTC
Labels: bug
