### ISSUE TITLE
Hard Crash when attaching external monitors using KVM

### ISSUE THREAD

**Issue by erahhal** [hyprwm/Hyprland#4638] opened 2024-02-08 01:50 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 754eaf5b8b65c9764abe67ec2d599036cd51e381  ().
Date: 2024-01-24
Tag: 

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

I've got two external 4k monitors using DP and flip back and forth between two laptops using a KVM. The laptop with Hyprland crashes on occasion when flipping back to it.

Crash log attached.
[hyprlandCrashReport6786.txt](https://github.com/hyprwm/Hyprland/files/14203331/hyprlandCrashReport6786.txt)

### How to reproduce

Not sure. Here's my setup:

2 LG IPS 4K@60Hz IPS monitors
Level1Techs Dual Monitor KVM using Display Port
Machine 1: Dell XPS 9560 running Sway
Machine 2: Lenovo Thinkpad X1 Carbon 11th Gen running Hyprland

Thinkpad is connected to KVM through a Thinkpad Thunderbolt 4 dock. Both monitor cables are connected to the dock.

Kanshi is used to update layout and resolution on detection of output changes.

I'll be using the Dell for a while, come back to the Thinkpad, and the screen is black and the keyboard is locked, including caps lock. After 20-30 seconds it exits and goes back to the login screen.

This only happens occasionally.

Unclear if this is due to the KVM, the Thunderbolt dock, the change in external outputs, Kanshi, or all of them.

### Crash reports, logs, images, videos

[hyprlandCrashReport6786.txt](https://github.com/hyprwm/Hyprland/files/14203332/hyprlandCrashReport6786.txt)

**Comment by 1over137** [comment] 2024-02-08 21:47
Relevant kanshi config
```
profile {
	output eDP-1 disable
	output DP-3 enable mode 2560x1440 scale 1

}

profile {
	output eDP-1 enable scale 1
}
```

**Comment by erahhal** [comment] 2024-02-08 22:21
Perhaps a coincidence but I also disable eDP-1.

**Comment by alexandru0-dev** [comment] 2024-02-10 13:27
> Ok, I was able to reproduce this reliably by using unplugging the desktop monitor with `kanshi` running and I did a git bisect.
> 
> [7b3d039](https://github.com/hyprwm/Hyprland/commit/7b3d03938888f399c3c14adfce73ea22bbe461ea) is the first bad commit
> 
> Unfortunately I don't have enough time or familiarity with the code to fix this myself for now. Hopefully @vaxerski takes a look at it.

had the same exact behavior happening to me. thxx for finding the bad commit, hopefully it's going to get solved

**Comment by alexandru0-dev** [comment] 2024-02-10 13:28
> Perhaps a coincidence but I also disable eDP-1.

the idea is that Hyprland crashes due to no monitor available. So disabling the eDP-1 is causing the "issue".

**Comment by erahhal** [comment] 2024-02-11 00:59
I've upgraded to 0.34.0, and I haven't seen a crash yet, but I've seen the screen go fully red and had to go to a TTY to kill everything and relaunch. Mouse still moved.

**Comment by vaxerski** [comment] 2024-02-13 18:11
red screen of death = lockscreen died

you _can_ get around this by enabling restoring lockscreens in config and having a locked bind to launch swaylock or whatever lock

**Comment by vaxerski** [comment] 2024-02-13 18:20
I'll say this is a dupe of #4628

**Closed by vaxerski** 2024-02-13 18:20 UTC
Labels: bug
