### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1038] opened 2022-11-17 21:07 UTC
[stack-trace.txt](https://github.com/hyprwm/Hyprland/files/10035597/stack-trace.txt)
[config.txt](https://github.com/hyprwm/Hyprland/files/10035598/config.txt)
[log.txt](https://github.com/hyprwm/Hyprland/files/10035599/log.txt)

The crash happened after "reviving" my Laptop from being suspended in with `systemctl suspend`.

**Comment by vaxerski** [comment] 2022-11-17 21:53
unsure of the cause, have some suspects that should be fixed with d2a7e22efdc16b9ebe4b2f62b32bab8d6b6d03c5

closing for now, feel free to reopen if happens again.

**Closed by vaxerski** 2022-11-17 21:53 UTC
Labels: bug
