### ISSUE TITLE
Persistent Input Method Candidate Words and UI Ghosting Bug

### ISSUE THREAD

**Issue by WantenMN** [hyprwm/Hyprland#5290] opened 2024-03-27 10:34 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ae52b7f4680716976d05b638aaa90e169d199117  ().
Date: 2024-03-26
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: Wanten-Nixos-Uakari
Release: 6.6.22
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:25:07 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] [10de:1f11] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05pre-git"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

After inputting text, remnants of the input method candidate words persist on the screen, creating a ghosting effect. Additionally, when navigating to a new page in various browser extensions, the display remains stuck on the previous page until manually scrolled, revealing the new content at the bottom. It appears that the page fails to refresh immediately, resulting in residual artifacts.

### How to reproduce

Please watch the video below.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/41904684/4dafc977-c17a-40dd-aee7-33942caf7410

**Comment by M4he** [comment] 2024-03-27 15:11
Is this related to https://github.com/hyprwm/Hyprland/issues/5256 ?

On another note, not related to IME at all but I get a lot of redraw artifacts in Qt applications specifically:

[kwrite_popup_ghosting.webm](https://github.com/hyprwm/Hyprland/assets/1408105/e8d1e478-d82b-4d65-87ee-c6a7aa7dfa4b)

Example above is KWrite's word suggestion popup. I don't know if it is worth yet another issue so I'm posting it here since it seems to be redraw-related as well. Same in Cantata (a Qt mpd GUI) where popup tooltips will leave behind flickering remnants like crazy sometimes.

**Comment by vaxerski** [comment] 2024-03-27 16:16
that was fixed in git @M4he

**Comment by vaxerski** [comment] 2024-03-27 16:17
to me this is #5256 so I will redirect you there

**Closed by vaxerski** 2024-03-27 16:17 UTC
Labels: bug

**Comment by M4he** [comment] 2024-03-27 17:00
> that was fixed in git @M4he

Does not seem to be the case unfortunately, I can still repro what is shown in my above recording of KWrite on ae52b7f4680716976d05b638aaa90e169d199117 but maybe it is really a different root cause than the IME stuff and only seems similar visually ...

**Comment by vaxerski** [comment] 2024-03-28 01:29
that's not IME lmao

**Comment by WantenMN** [comment] 2024-03-31 05:02
@vaxerski @M4he 

The system I use is NixOS, which allows for convenient rollback to previous commit versions, but I forgot to do so at the time.

Today, after repeated rollbacks and upgrades, I identified the issue. The candidate words in the input method (fcitx5) persist after input and create a residual shadow due to this commit: "IME: Improve handling of text-input and ime-relay" (5c1097cbc19131a7770b2a3f01f6f24e626991d2).

My current flake.lock version:
<details>

```json
    "hyprcursor": {
      "inputs": {
        "hyprlang": "hyprlang",
        "nixpkgs": [
          "hyprland",
          "nixpkgs"
        ],
        "systems": [
          "hyprland",
          "systems"
        ]
      },
      "locked": {
        "lastModified": 1711466786,
        "narHash": "sha256-sArxGyUBiCA1in+q6t0QqT+ZJiZ1PyBp7cNPKLmREM0=",
        "owner": "hyprwm",
        "repo": "hyprcursor",
        "rev": "d3876f34779cc03ee51e4aafc0d00a4f187c7544",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "hyprcursor",
        "type": "github"
      }
    },
    "hyprland": {
      "inputs": {
        "hyprcursor": "hyprcursor",
        "hyprland-protocols": "hyprland-protocols",
        "hyprlang": "hyprlang_2",
        "nixpkgs": "nixpkgs",
        "systems": "systems_2",
        "wlroots": "wlroots",
        "xdph": "xdph"
      },
      "locked": {
        "lastModified": 1710816831,
        "narHash": "sha256-8PyLk/gfMo4asjbqsoXw1I3zfnkCPSSX0r6UCJP3ctw=",
        "owner": "hyprwm",
        "repo": "Hyprland",
        "rev": "05c84304ccb1169b550504830139e07e28500a3b",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "Hyprland",
        "type": "github"
      }
    },
    "hyprland-protocols": {
      "inputs": {
        "nixpkgs": [
          "hyprland",
          "nixpkgs"
        ],
        "systems": [
          "hyprland",
          "systems"
        ]
      },
      "locked": {
        "lastModified": 1691753796,
        "narHash": "sha256-zOEwiWoXk3j3+EoF3ySUJmberFewWlagvewDRuWYAso=",
        "owner": "hyprwm",
        "repo": "hyprland-protocols",
        "rev": "0c2ce70625cb30aef199cb388f99e19a61a6ce03",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "hyprland-protocols",
        "type": "github"
      }
    },
    "hyprlang": {
      "inputs": {
        "nixpkgs": [
          "hyprland",
          "hyprcursor",
          "nixpkgs"
        ],
        "systems": "systems"
      },
      "locked": {
        "lastModified": 1709914708,
        "narHash": "sha256-bR4o3mynoTa1Wi4ZTjbnsZ6iqVcPGriXp56bZh5UFTk=",
        "owner": "hyprwm",
        "repo": "hyprlang",
        "rev": "a685493fdbeec01ca8ccdf1f3655c044a8ce2fe2",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "hyprlang",
        "type": "github"
      }
    },
    "hyprlang_2": {
      "inputs": {
        "nixpkgs": [
          "hyprland",
          "nixpkgs"
        ],
        "systems": [
          "hyprland",
          "systems"
        ]
      },
      "locked": {
        "lastModified": 1711250455,
        "narHash": "sha256-LSq1ZsTpeD7xsqvlsepDEelWRDtAhqwetp6PusHXJRo=",
        "owner": "hyprwm",
        "repo": "hyprlang",
        "rev": "b3e430f81f3364c5dd1a3cc9995706a4799eb3fa",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "hyprlang",
        "type": "github"
      }
    },
```

</details>

If I modify (upgrade) 05c84304ccb1169b550504830139e07e28500a3b to 5c1097cbc19131a7770b2a3f01f6f24e626991d2, the aforementioned issue occurs.

This commit's code diff altered the logic related to input methods, thereby causing this problem.

**Comment by vaxerski** [comment] 2024-03-31 20:26
feel free to MR, IMEs work properly on my end on -git.
