### ISSUE TITLE
[QUESTION] about the focus_on_activate function

### ISSUE THREAD

**Issue by TAforever** [hyprwm/Hyprland#3870] opened 2023-11-17 12:12 UTC
### Description

This is a very useful feature that I unfortunately cannot use.
The function is very useful when I click on a link in a third-party application and instantly go to the browser automatically, but if, for example, I play some online game and I receive a message from Telegram, then I automatically go to the workspace where Telegram is located. If a letter arrives, this does not happen with Thunderbird. Can anything be done about this?

**Comment by vaxerski** [comment] 2023-11-17 12:19
I believe you can disable that in telegram. This is a dupe of some other issue here

**Closed by vaxerski** 2023-11-17 12:19 UTC
Labels: enhancement

**Comment by TAforever** [comment] 2023-11-17 12:51
> I believe you can disable that in telegram. This is a dupe of some other issue here

Unfortunately, there is no such setting in Telegram and the problem relates to the focus_on_activate function

**Comment by vaxerski** [comment] 2023-11-17 15:25
https://github.com/hyprwm/Hyprland/issues/2732

**Comment by TAforever** [comment] 2023-11-17 15:48
> #2732
Thank you sir!

**Comment by TAforever** [comment] 2023-11-17 15:49
> #2732

Thank you sir!
