### ISSUE TITLE
Disappearing Cursor with new Impl

### ISSUE THREAD

**Issue by BenCarmichael01** [hyprwm/Hyprland#5975] opened 2024-05-10 00:13 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: bendesktop
Release: 6.8.6-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
09:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] [10de:2504] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240506.ad7efee"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>
Not shown above for some reason but Hyprland commit is 1753059b07be52cf78fa2676c4c71d2edb560199 

### Bug or Regression?

Regression

### Description

When playing Valheim, the game captures my cursor when controlling the camera, as expected. But when i open any menus my cursor is invisible. I can still see that the cursor is hovering over stuff but it isn't visible. It can be restored by switching ws away and then back, or by opening and closing fuzzel as i've done in the attached logs. After this, it works until i close the menu, then the issue repeats the next time i open the menu.

 I have confirmed this is a regression by testing on commit e4e84064f2d07810e0c150bce1369a0a00503e9a where this does not happen. Leads me to believe its an issue with the new cursor implimentation. 

### How to reproduce

As above, may also display in other games but i don't have any i can test rn.

If anthing else is needed please let me know.

### Crash reports, logs, images, videos

Log of the issue at commit 1753059b07be52cf78fa2676c4c71d2edb560199
[hyprland-cursor-bad.log](https://github.com/hyprwm/Hyprland/files/15268813/hyprland-cursor-bad.log)

Roughly the same actions performed in e4e84064f2d07810e0c150bce1369a0a00503e9a. No idea if this would help.
[hyprland-cursor-good.log](https://github.com/hyprwm/Hyprland/files/15268814/hyprland-cursor-good.log)

 Both running with debug:disable_logs=false

Config: [hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/15268942/hyprland.conf.txt) generated from home-manager hence the weird formatting.

**Comment by vaxerski** [comment] 2024-05-10 01:41
cursor events aren't logged unless you launch hl with `HYPRLAND_TRACE=1` so the logs wont show much unless you do that.

Also, does `cursor:no_hardware_cursors` fix this? If so, we can narrow it down to hw cursors.

**Comment by Agent00Ming** [comment] 2024-05-10 09:48
Pretty sure NVIDIA reverts to sw cursors because the cursor shows up in screenshots. I can repro this in Valheim on iGPU hw cursors here:  [hyprland_cursor_trace.log](https://github.com/hyprwm/Hyprland/files/15273326/hyprland_cursor_trace.log)

**Comment by BenCarmichael01** [comment] 2024-05-10 10:35
Tried again with hardware cursors disabled, same issue happening. The logs also seem to be saying 
`[TRACE] Output HDMI-A-1 rejected hardware cursors, falling back to sw`
 even though hw cursors should already be disabled
[hyprland-cursor-trace.log](https://github.com/hyprwm/Hyprland/files/15273898/hyprland-cursor-bad.log)

**Comment by vaxerski** [comment] 2024-05-10 11:14
it will print that when they are disabled too

**Comment by vaxerski** [comment] 2024-05-10 11:17
hm, anything else exhibiting this? I don't feel like buying and installing a huge game for testing, and I can't see anything wrong on first glance.

**Comment by Agent00Ming** [comment] 2024-05-10 11:19
It's 1.66GB :stuck_out_tongue_closed_eyes: (native linux, xwayland)

**Comment by Agent00Ming** [comment] 2024-05-10 11:21
Yeah, it also happens on Hollow Knight (native linux, xwayland)

**Comment by vaxerski** [comment] 2024-05-10 11:54
reprod

**Comment by vaxerski** [comment] 2024-05-10 12:05
and now I cant anymore tf

**Comment by vaxerski** [comment] 2024-05-10 12:06
[patch.txt](https://github.com/hyprwm/Hyprland/files/15274686/patch.txt)
maybe this?

**Comment by BenCarmichael01** [comment] 2024-05-10 12:12
uhh am i being dumb
```
Hyprland on  main [!?⇣] via △ 
❯ git apply patch.txt                                      
error: src/managers/PointerManager.cpp: No such file or directory
```

**Comment by BenCarmichael01** [comment] 2024-05-10 12:12
nvm ignore me

**Comment by BenCarmichael01** [comment] 2024-05-10 12:25
Still happening with patch
[hyprland-patch1.log](https://github.com/hyprwm/Hyprland/files/15274979/hyprland-patch1.log)

**Comment by Agent00Ming** [comment] 2024-05-10 14:04
What happens when the cursor is going hidden/locked to camera rotation initially:
```
[LOG] cursorImage request: surface 0
[LOG] Callback 57ae0512af90 -> 57ae0512af88, CPointerManager removed.
[LOG] Callback 57ae05c3a788 -> 57ae05c3a780, CWLSurface removed.
[LOG] Callback 57ae05c3a7f0 -> 57ae05c3a7e8, CWLSurface removed.
[LOG] CWLSurface 57ae05c3a6e0 called destroy()
```

And this is what happens when attempting to show the cursor again/unlocking cursor from camera rotation:
```
[LOG] cursorImage request: surface 57ae367f0690
[LOG] Registered signal for owner 57ae05c3a6e0: 57ae367f09a8 -> 57ae05c3a760 (owner: CWLSurface)
[LOG] Registered signal for owner 57ae05c3a6e0: 57ae367f0968 -> 57ae05c3a7c8 (owner: CWLSurface)
[LOG] CWLSurface 57ae05c3a6e0 called init()
```

hiding again/locking (without a visible cursor):
```
[LOG] cursorImage request: surface 0
[LOG] Callback 57ae05c3a788 -> 57ae05c3a780, CWLSurface removed.
[LOG] Callback 57ae05c3a7f0 -> 57ae05c3a7e8, CWLSurface removed.
[LOG] CWLSurface 57ae05c3a6e0 called destroy()
```

No trace events are logged in this time period. (`HYPRLAND_TRACE=1`)

**Comment by vaxerski** [comment] 2024-05-10 17:33
[patch.txt](https://github.com/hyprwm/Hyprland/files/15278129/patch.txt)
try

**Comment by Agent00Ming** [comment] 2024-05-10 18:02
nope, still the same

**Comment by BenCarmichael01** [comment] 2024-05-10 22:50
Yeh still the same for me, also reprod on my intel laptop so not just an Nvidia issue.

**Comment by vaxerski** [comment] 2024-05-11 01:45
@Agent00Ming can you put a bunch of logs and see if code reaches PointerManager.cpp@227 after the second log? ([LOG] cursorImage request: surface 57ae367f0690)

**Comment by Agent00Ming** [comment] 2024-05-11 13:58
[loggingpatch.txt](https://github.com/hyprwm/Hyprland/files/15282991/loggingpatch.txt)
(line counts with the patch applied)
Excluding 254 (movement = logged), 312 is the last thing logged and it's logging 250 on movement nothing else is logged afterwards

**Comment by Agent00Ming** [comment] 2024-05-11 14:30
No matter what I do it seems like `if (surf->wlr()->current.buffer) {` is never true?

**Comment by vaxerski** [comment] 2024-05-11 14:53
what if you replace it with `wlr_surface_has_buffer(surf->wlr())`?

**Comment by Agent00Ming** [comment] 2024-05-11 15:02
now 235 is logged but only once when the game window first acquires the cursor and never again until focusing a different window

**Comment by vaxerski** [comment] 2024-05-11 15:39
that should be how it works (the surface itself isnt changed, only its contents). Updating should happen insude the `commit` listener above

**Comment by Agent00Ming** [comment] 2024-05-11 15:47
none of these are logged when I unhide the cursor by opening a menu though but moving the cursor after supposedly hiding it again logs a 312

**Comment by Agent00Ming** [comment] 2024-05-11 15:50
```
void CPointerManager::resetCursorImage(bool apply) {
    if (currentCursorImage.surface) {
        for (auto& m : g_pCompositor->m_vMonitors) {
            wlr_surface_send_leave(currentCursorImage.surface->wlr(), m->output);
        }

        currentCursorImage.destroySurface.reset();
        currentCursorImage.hyprListener_commitSurface.removeCallback();
        currentCursorImage.surface = nullptr;
        Debug::log(WARN,"CPM:LINE 296 REACHED");
    } else if (currentCursorImage.pBuffer) {
        wlr_buffer_unlock(currentCursorImage.pBuffer);
        currentCursorImage.hyprListener_destroyBuffer.removeCallback();
        currentCursorImage.pBuffer = nullptr;
        Debug::log(WARN,"CPM:LINE 301 REACHED");
    }

    if (currentCursorImage.pBufferTexture) {
        wlr_texture_destroy(currentCursorImage.pBufferTexture);
        currentCursorImage.pBufferTexture = nullptr;
        Debug::log(WARN,"CPM:LINE 307 REACHED");
    }

    currentCursorImage.scale   = 1.F;
    currentCursorImage.hotspot = {0, 0};
    Debug::log(WARN,"CPM:LINE 312 REACHED"); // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< HERE

    for (auto& s : monitorStates) {
        if (s->monitor.expired() || s->monitor->isMirror() || !s->monitor->m_bEnabled)
            continue;

        s->entered = false;
    }

    if (!apply) {
        Debug::log(WARN,"CPM:LINE 322 REACHED");
        return;
    }
    for (auto& ms : monitorStates) {
        if (ms->cursorFrontBuffer) {
            if (ms->monitor->output->impl->set_cursor)
                ms->monitor->output->impl->set_cursor(ms->monitor->output, nullptr, 0, 0);
            wlr_buffer_unlock(ms->cursorFrontBuffer);
            ms->cursorFrontBuffer = nullptr;
        }
    }
}
```

**Comment by Agent00Ming** [comment] 2024-05-11 16:44
> what if you replace it with `wlr_surface_has_buffer(surf->wlr())`?

log with that change only and logging patch
[cursor_invisible.log](https://github.com/hyprwm/Hyprland/files/15283543/cursor_invisible.log)

**Comment by RandomLegend** [comment] 2024-05-12 11:39
For me it also happens with blender for example, so not only wine or games.
https://imgur.com/a/sCC7hbj

**Comment by Agent00Ming** [comment] 2024-05-12 11:41
Yep just replicated that in blender as well

**Comment by SoulHarsh007** [comment] 2024-05-12 12:45
It happens for me on VMWare too, when VMWare grabs the cursor, the cursor in VM disappears, moving it to another workspace and back quickly brings the cursor in VM back.

**Comment by happenslol** [comment] 2024-05-14 13:08
I can reproduce with Hades 2, whenever the mouse is hidden by the game it's hidden from that point on and won't reappear unless I switch windows

**Comment by vaxerski** [comment] 2024-05-14 15:45
enjoy

**Closed by vaxerski** 2024-05-14 15:45 UTC
Labels: bug
