### ISSUE TITLE
System freezes after resuming suspend

### ISSUE THREAD

**Issue by LamprosPitsillos** [hyprwm/Hyprland#5005] opened 2024-03-07 10:34 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.36.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: infernoPC
Release: 6.6.19
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar  1 12:35:11 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240303.b8697e5"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Not consistently , after resuming suspend ( opening laptop lid ) , i see the screen as it was before suspending ( closing the lid ) . The system is now frozen and does not respond to any input having to force restart my laptop. 

### How to reproduce

Suspend and Resume the system a few times

### Crash reports, logs, images, videos

[ My config ](https://github.com/LamprosPitsillos/nixos-config/blob/main/home-manager/programs/wm/hyprland.nix)
[Log gist](https://gist.github.com/LamprosPitsillos/34055fd7bcb00415a64350e9c9f46410)|
No crash report with PID inside logs containing this pattern.
Around line `4025` i see this , and it repeats until the end of the file
```
[LOG] [22:19:06.004899605] Callback 2fe9a00 -> 2fe99f8, Keyboard removed.
[LOG] [22:19:06.004917890] Destroyed keyboard 2fe9900
[LOG] [22:19:06.034516398] Session got activated!
[LOG] [10:11:58.467246434] Session got activated!
[LOG] [10:11:58.467442388] Applying monitor rule for eDP-1
[LOG] [10:11:58.467477884] Not applying a new rule to eDP-1 because it's already applied!
[wlr] [backend/drm/drm.c:816] connector eDP-1: Failed to page-flip output: a page-flip is already pending
[wlr] [backend/drm/drm.c:816] connector eDP-1: Failed to page-flip output: a page-flip is already pending
[wlr] [backend/drm/drm.c:816] connector eDP-1: Failed to page-flip output: a page-flip is already pending
[wlr] [backend/drm/drm.c:816] connector eDP-1: Failed to page-flip output: a page-flip is already pending

```

**Comment by vaxerski** [comment] 2024-03-07 13:27
dupe of something, fixed in git

**Closed by vaxerski** 2024-03-07 13:27 UTC
Labels: bug

**Comment by vaxerski** [comment] 2024-03-07 17:19
#4839
