### ISSUE TITLE
can this be build with system installed wlroots?

### ISSUE THREAD

**Issue by adcdam** [hyprwm/Hyprland#317] opened 2022-07-07 04:16 UTC
i have wlroots 0.15.1 installed it would be nice if hyprland can be build using system wlroots instead of using a subproject.
A meson_options.txt build with system wlroots would be nice.

**Comment by vaxerski** [comment] 2022-07-07 08:32
no. dupe of #302

**Closed by vaxerski** 2022-07-07 08:32 UTC
Labels: bug
