### ISSUE TITLE
Added watchdog commit causes build failure

### ISSUE THREAD

**Issue by MichaelDeets** [hyprwm/Hyprland#3462] opened 2023-09-30 23:10 UTC
### Hyprland Version

9cc614d096db4b7c1de6baaa055ca6f741aa4370

### Bug or Regression?

Bug

### Description

The commit to [WLListener.cpp](https://github.com/hyprwm/Hyprland/commit/9cc614d096db4b7c1de6baaa055ca6f741aa4370#diff-dbedcdc29869cf35292c45df11b79ca704265bc4490365c79744f58681c263da) results in the error:

`../hyprland-9999/src/helpers/WLListener.cpp:9:5: error: ‘g_pWatchdog’ was not declared in this scope`

Reversing the diff from WLListener.cpp allows the build to finish.

### How to reproduce

Compile latest git version of Hyprland using GCC.

### Crash reports, logs, images, videos

`../hyprland-9999/src/helpers/WLListener.cpp: In function ‘void handleWrapped(wl_listener*, void*)’:`

`../hyprland-9999/src/helpers/WLListener.cpp:9:5: error: ‘g_pWatchdog’ was not declared in this scope`

`    9 |     g_pWatchdog->startWatching();`

**Comment by tchofy** [comment] 2023-09-30 23:54
Isn't this a dupe of https://github.com/hyprwm/Hyprland/issues/3452?

**Comment by gnusenpai** [comment] 2023-09-30 23:58
Not exactly. This issue is a build error; the one mentioned is a runtime crash.
Just happens to be the same commit.

**Comment by memchr** [comment] 2023-10-01 03:08
just `#include "Watchdog.hpp"` in WLListener.cpp

**Closed** 2023-10-01 11:26 UTC
Labels: bug
