### ISSUE TITLE
Black screen when screen capturing

### ISSUE THREAD

**Issue by liamrahum** [hyprwm/Hyprland#2062] opened 2023-04-15 08:24 UTC
I don't know if it's a Hyprland specific issue, but when I try to capture my screen using programs like OBS and Webcord, I get the prompt for choosing the window I want to capture, but it'd just show a black screen

I tried the unofficial NVIDIA package (hyprland-nvidia-git), all I could capture was specific screens & entire screen would be black again
I tried switching from xdg-desktop-portal-hyprland to wlr, but I got the same result

If you think you know where the problem is I'd be happy to send log files of it if necessary

(Note that I didn't upload screenshots or a video of it because.. I can't)

**Comment by vaxerski** [comment] 2023-04-15 09:48
well, it's an nvidia issue. Dupe of #2000. You may want to try the patch I posted there

**Closed by vaxerski** 2023-04-15 09:48 UTC
Labels: bug
