### ISSUE TITLE
special workspace behavior with multi monitor

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1151] opened 2022-12-02 19:17 UTC
- add something in the special workspace
- use togglespecialworkspace to show it (works)
- use togglespecialworkspace to hide it (works)
-  move focus to a workspace on a different monitor
- togglespecialworkspace -> does nothing (probably just doesn't show the window)
- togglespecialworkspace -> does nothing (probably hidding the special workspace that is invisible)
- togglespecialworkspace  -> finally works as expected

**Comment by gegnew** [comment] 2023-02-23 09:34
also experiencing this

**Comment by vaxerski** [comment] 2023-02-23 19:00
well, I can't repro.

**Comment by fedoranvar** [comment] 2023-03-16 11:48
same for me

1) open special workspace on first monitor 
2) focus on second monitor
3) first `togglespecial` hides special on first monitor and i loose focus on my active window on second monitor
4) second `togglespecial` returns focus to windows on second monitor
5) third `togglespecial` shows special on second monitor

@vaxerski 
it feels like, that system treats this `special` like it's on all monitors

feels like time race:
so system tries to show this `special` on second monitor before moving this `special` from first to second monitor

**Comment by KrolixW** [comment] 2023-03-16 18:26
It also happens to me. Here's [video ](https://youtu.be/kvVMNOXk1ZY)

**Comment by fedoranvar** [comment] 2023-03-27 10:44
right now i'm using this hack:
```
bind=SUPER,f1,togglespecialworkspace,pde
bind=SUPER,f1,focusmonitor,+1
bind=SUPER,f1,focusmonitor,-1
```

**Comment by ch3n9w** [comment] 2023-04-09 14:33
> right now i'm using this hack:
> 
> ```
> bind=SUPER,f1,togglespecialworkspace,pde
> bind=SUPER,f1,focusmonitor,+1
> bind=SUPER,f1,focusmonitor,-1
> ```

This works, but it will make spacial workspace lose focus.

**Comment by KrolixW** [comment] 2023-04-09 15:17
> This works, but it will make spacial workspace lose focus.
To fix loosing focus i had to add additional toggles, so final workaround looks like this
`bind = $mainMod, T, togglespecialworkspace, telegram
bind = $mainMod, T, focusmonitor, +1
bind = $mainMod, T, focusmonitor, -1
bind = $mainMod, T, togglespecialworkspace, telegram
bind = $mainMod, T, togglespecialworkspace, telegram
`
Super weird, but works

**Comment by fedoranvar** [comment] 2023-04-19 03:45
i've commented `general` section in my config and toggling special workspace works  without crutches

**Comment by fedoranvar** [comment] 2023-04-19 03:53
@vaxerski 
i've reproduced wrong behaviour with `general.layout = master`

if i'll remove this, then specialworkspace works fine

**Comment by primalmotion** [comment] 2023-05-17 23:02
It seems it has been fixed in a recent version. I can't reproduce anymore

**Comment by KrolixW** [comment] 2023-05-17 23:47
Still an issue for me on latest commit (79b8576)

**Comment by fedoranvar** [comment] 2023-05-18 15:56
@KrolixW 
have you checked this behaviour with default config?

**Comment by KrolixW** [comment] 2023-05-18 17:07
> @KrolixW have you checked this behaviour with default config?

default config has dwindle layout selected. The issue only occurs if you set layout to master

**Closed** 2023-09-01 20:57 UTC
Labels: bug
