### ISSUE TITLE
Firefox slow and stuttery on 2nd screen

### ISSUE THREAD

**Issue by juliuskoskela** [hyprwm/Hyprland#5973] opened 2024-05-09 21:30 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

This is not the commit I built the faulty Hyprland from! I have already rolled back my system from the faulty commit. The rest of the info is accurate though. The faulty system was built from b0861b6.

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  ().
Date: 2024-04-16
Tag: , commits: @COMMITS@

flags: (if any)


System Information:
System name: Linux
Node name: vega
Release: 6.6.30
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])
12:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240507.b211b39"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Using Firefox on my 2nd (secondary) monitor was unusably slow. Typing in the search bar, playing videos etc. had huge lag. When I switched to first monitor the problem disappeared. When I rolled back from b0861b6 to latest commit in tag 0.39.1 the problem on the 2nd screen vanished.

### How to reproduce

When using Hyprland b0861b6 with 2 monitors attached, open Firefox on the 2nd (secondary) window and use it in a general way, watch Youtube, browse etc.

**Comment by vaxerski** [comment] 2024-05-09 21:32
it's 0.40 xD

Anyways, since this is a _regression_ (even though you marked it wrongly as a bug) please do a bisect: https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue

**Comment by juliuskoskela** [comment] 2024-05-09 21:46
> it's 0.40 xD
> 
> Anyways, since this is a _regression_ (even though you marked it wrongly as a bug) please do a bisect: https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue

I can do the bisect. Yeah the perf dropped so drastically I figured it's a bug, thanks for correcting.

**Comment by juliuskoskela** [comment] 2024-05-09 22:15
I realized I had built from main from commit b0861b6, I have updated the issue accordingly.

**Comment by burein-ita** [comment] 2024-05-10 02:32
Is not slow, for some reason firefox only only refreshes when the cursor moves.

**Comment by Arjun31415** [comment] 2024-05-10 06:30
Can confirm, happens to me too. Last working commit is e4e84064f2d07810e0c150bce1369a0a00503e9a

**Comment by sungyoonc** [comment] 2024-05-10 11:39
For me, this only happens when I fullscreen firefox (maximize and fakefullscreen works fine)

**Comment by Icey-Glitch** [comment] 2024-05-10 18:31
> Is not slow, for some reason firefox only refreshes when the cursor moves or when another application in the same monitor redraws itself.

I experience the same behavior.

**Comment by sungyoonc** [comment] 2024-05-11 04:01
Can anyone check if #6010 fixes the issue?

**Comment by Arjun31415** [comment] 2024-05-11 04:33
> Can anyone check if #6010 fixes the issue?

Yes It does for me

**Comment by vaxerski** [comment] 2024-05-12 00:00
closing then

**Closed by vaxerski** 2024-05-12 00:00 UTC
Labels: bug

**Comment by vale981** [comment] 2024-12-10 16:26
strangely, this is still an issue for me
