### ISSUE TITLE
XWayland crashes occasionally since v0.41.0

### ISSUE THREAD

**Issue by Arantier** [hyprwm/Hyprland#6522] opened 2024-06-15 19:02 UTC
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: arantier-laptop
Release: 6.9.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/arantier/.config/hypr/hyprland.conf: Read Succeeded
source=~/.config/hypr/configs/displays.conf

general {
    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
}

source=~/.config/hypr/configs/appearance.conf
source=~/.config/hypr/configs/input.conf

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

debug:disable_logs = false

source=~/.config/hypr/configs/widgets.conf
# exec=~/.config/hypr/assets/hyprland-display-gen.py


Config File: /home/arantier/.config/hypr/configs/displays.conf: Read Succeeded
# Office
# monitor=eDP-1,  2160x1440,      0x1920,         1.5
# monitor=DP-1,   1920x1080,      0x0,            1.0,    transform,1

# Common
monitor=eDP-1,  2160x1440,      343x1080,       1.5
monitor=,       highres,        0x0,            1.0


Config File: /home/arantier/.config/hypr/configs/appearance.conf: Read Succeeded
source = ~/.config/hypr/assets/colors.conf

general {
    gaps_in=5
    gaps_out=5
    border_size=3
    col.active_border=$teal
    col.inactive_border=$dark-teal
}

decoration {
    rounding=6
    blur {
        enabled = true
        size = 3 # minimum 1
        passes = 1 # minimum 1 
        new_optimizations = true
    }
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,3,default
    animation=specialWorkspace,1,5,default,fade
}

misc {
    disable_hyprland_logo=true
}

exec=swaybg -i ~/.config/hypr/assets/background.png -m fill

env = _JAVA_AWT_WM_NONREPARENTING,1
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb

windowrulev2=float,class:blueman-manager

# windowrulev2=tile,title:Android Emulator.*
# windowrulev2=size 365 100%,title:Android Emulator.*
# windowrulev2=tile,title:Emulator - .*
# windowrulev2=size 365 100%,title:Emulator - .*
# windowrulev2=float,title:Layout Inspector - .*
# windowrulev2=size 90% 90%,title:Layout Inspector - .*
# windowrulev2=center,title:Layout Inspector - .*

windowrulev2=float,class:foot

windowrulev2=float,class:vkteams,title:"In call:.*"
windowrulev2=size 590 330,class:vkteams,title:"In call:.*"

windowrulev2=float,class:Slack,title:.*Huddle.*
windowrulev2=size 90% 90%,class:Slack,title:.*Huddle.*
windowrulev2=center,class:Slack,title:.*Huddle.*

# windowrulev2=float,class:thunar
# windowrulev2=size 80% 80%,class:thunar
# windowrulev2=center,class:thunar

# Trying to fix refocusing problem. 
# After release of version older than v0.25.0 remove
# Update: it's back again. Yay...
# windowrulev2=nofocus,class:^jetbrains-(?!toolbox),floating:1,title:^win\d+$



Config File: /home/arantier/.config/hypr/assets/colors.conf: Read Succeeded
# Decided to put it here because, well, it's not a config
$teal = 0xFF32B595
$pink = 0xFFB74E73
$dark-teal = 0xFF0F2C25
$dark-teal-70 = 0x0F2C2570
$white = 0xFFFFFFFF


Config File: /home/arantier/.config/hypr/configs/input.conf: Read Succeeded
input {
    kb_file=
    kb_layout=us,ru
    kb_variant=
    kb_model=
    kb_options=grp:caps_toggle
    kb_rules=

    follow_mouse=2
    float_switch_override_focus = false

    touchpad {
        natural_scroll=yes
        middle_button_emulation=true
        drag_lock=true
    }

    sensitivity=0 # -1.0 - 1.0, 0 means no modification.
}

source=~/.config/hypr/configs/keybindings.conf


Config File: /home/arantier/.config/hypr/configs/keybindings.conf: Read Succeeded
# Mouse binds
bindm=SUPER,mouse:272,movewindow

# Start terminal
bind=SUPER,RETURN,exec,foot

# Kill active window
# Alt+F4
bind=ALT,F4,killactive

# Show menu
bind=SUPER,D,exec,rofi -show drun

# Lock screen
bind=SUPER,L,exec,swaylock

# Shutdown
# Ctrl+Alt+Delete
bind=CTRLALT,Delete,exec,poweroff

# Reload everything
bind=SUPERSHIFT,C,forcerendererreload

# Moving stuff around
bind=SUPERSHIFT,left,movewindow,l
bind=SUPERSHIFT,right,movewindow,r
bind=SUPERSHIFT,up,movewindow,u
bind=SUPERSHIFT,down,movewindow,d

bind=SUPERCTRL,left,moveworkspacetomonitor,+0 l
bind=SUPERCTRL,right,moveworkspacetomonitor,+0 r
bind=SUPERCTRL,up,moveworkspacetomonitor,+0 u
bind=SUPERCTRL,down,moveworkspacetomonitor,+0 d

bind=SUPER,mouse_down,workspace,e+1
bind=SUPER,mouse_up,workspace,e-1

# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⣶⣿⣿⣿⣿⣿⣿⣶⣆⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣸⣿⣿⠉⠉⠉⠄⠉⢹⣿⣦⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢿⣿⣿⣁⠄⠄⠤⠤⡀⠻⣿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⣿⣿⣿⡗⠖⡶⢾⣶⠊⡏⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢻⣿⣿⣅⣈⠂⠐⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⢿⣾⣇⣂⣠⠄⠄⠄⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢘⣿⣗⠒⠄⢨⠶⢁⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠨⣿⣿⡿⠋⠁⣴⣿⣿⣷⣦⣄⡀⠄⠄⠄⠄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⣠⣄⣶⣎⢱⢄⢀⣾⣿⣿⣿⣿⣿⣿⣿⣶⣦⣤⣄⠄⠄⠄⠄ 
# ⠄⠄⠄⠄⠄⠄⠄⢠⣾⣿⣿⡞⢝⡟⠃⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⣿⣇⠄⠄⠄ 
# ⠄⠄⠄⠄⠆⢄⠄⢛⡫⠝⢿⡥⠟⡃⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣼⣭⣻⣿⣿⡀⠄⠄ 
# ⠄⠄⠄⣴⣆⠄⢋⠄⠐⣡⣿⣆⣴⣼⣿⣿⣿⣿⣿⣿⣿⣿⠏⢈⣿⣿⣿⣿⣿⣿⣷⡄⠄ 
# ⠄⠄⣼⣿⣷⠄⠉⠒⣪⣹⣟⣹⣿⣿⣿⣿⣿⣟⣿⣿⣿⡇⢀⣸⣿⣿⣿⢟⣽⣿⣿⣇⠄
# I'm stuff
bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

# Center window on main monitor
bind=SUPER,p,movewindow,mon:eDP-1
bind=SUPER,p,centerwindow
# And resize to fit, if needed
bind=SUPERSHIFT,p,resizeactive,exact 1200 800

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=SUPERSHIFT,1,movetoworkspacesilent,1
bind=SUPERSHIFT,2,movetoworkspacesilent,2
bind=SUPERSHIFT,3,movetoworkspacesilent,3
bind=SUPERSHIFT,4,movetoworkspacesilent,4
bind=SUPERSHIFT,5,movetoworkspacesilent,5
bind=SUPERSHIFT,6,movetoworkspacesilent,6

bind=SUPERSHIFT,8,movetoworkspacesilent,8
bind=SUPERSHIFT,9,movetoworkspacesilent,9
bind=SUPERSHIFT,0,movetoworkspacesilent,10

bind=SUPERSHIFT,Space,togglefloating,
bind=SUPER,W,fullscreen,1

# Resize mode: now with mouse
bind=SUPER,R,submap,resize
submap=resize
    bindm=,mouse:272,resizewindow
    bind=,escape,submap,reset
    binde=,right,resizeactive,10 0
    binde=,left,resizeactive,-10 0
    binde=,up,resizeactive,0 -10
    binde=,down,resizeactive,0 10
submap=reset

# Scratchpad settings
bind=SUPER,Tab,togglespecialworkspace,
bind=SUPERSHIFT,Tab,movetoworkspacesilent,special

bind=SUPER, Q, pin,

# Brightness control
bind=,XF86MonBrightnessUp,exec,light -S "$(light -G | awk '{ print int(($1 + .72) * 1.4) }')"
bind=,XF86MonBrightnessDown,exec,light -S "$(light -G | awk '{ print int($1 / 1.4) }')"

# Sound control
bind=,XF86AudioMute,exec,pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=,XF86AudioRaiseVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ +5%
bind=,XF86AudioLowerVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=,XF86AudioMicMute,exec,~/.config/hypr/assets/mute-input.sh

# Playback control
bind=,XF86AudioPause,exec,playerctl pause
bind=,XF86AudioPlay,exec,playerctl play-pause
bind=,XF86AudioNext,exec,playerctl next

# Printscreen
bind=SUPERSHIFT,S,exec,grim -g "$(slurp -d)" - | wl-copy

bind=SUPER,47,exec,emote

bindnt=,SUPER_L,exec,eww update observe_mode=true
bindnrt=SUPER,SUPER_L,exec,eww update observe_mode=false


Config File: /home/arantier/.config/hypr/configs/widgets.conf: Read Succeeded
exec-once=/usr/bin/swaync
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=/usr/bin/blueman-applet
# Not working cuz id keeps jumpong
exec-once=pulsemixer --id source-47 --set-volume 15

exec=~/.config/hypr/assets/eww-starter.sh

======Config-End========

```

</details>

### Description

From time to time, usually while working in Android Studio, XWayland crashes down with all apps running on it. Logs show that "XWayland has yeeten the xwm off?!", which is amusing, but not helpful. 

The only way to fix it that I could figure out is to reboot the PC. I've tried to use this script from Hyprland Desktop Portal page of Hyprland wiki, but it didn't help:
```sh
#!/usr/bin/env bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
```

On the side note, because this might be related, recent update killed all remaining screehsharing that I had as well. And something broke adb connection to my phone, and now I can't launch apps from Android Studio on it, but I assume it's just another "update" from Android Studio.

### How to reproduce

Run QT apps (especially with popups) on XWayland for some time?

### Crash reports, logs, images, videos

Here are the parts of the log, which contain the error messages, related to issue:
```
[LOG] CWLSurface 588825c2a570 called init()
[LOG] xwayland window 588825aaf6a0 -> association to 588825343920
[LOG] [LinuxDMABUF] Creating a dmabuf, with id 496: size [Vector2D: x: 138, y: 35], fmt 875713112, planes 2
[LOG] [LinuxDMABUF]  | plane 0: mod 144115206333774337 fd 1020 stride 1024 offset 0
[LOG] [LinuxDMABUF]  | plane 1: mod 144115206333774337 fd 1021 stride 512 offset 131072
[LOG] XWayland surface 588825aaf6a0 mapping
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 57275fad-115b-4bc6-8afa-f0172cf96adf
[LOG] Searching for matching rules for jetbrains-studio (title: win416)
[LOG] Map request dispatched, monitor eDP-1, window pos: [1248.00000, 1216.00000], window size: [138.00000, 35.00000]
[LOG] [ForeignToplevelWlr] Newly mapped window 0000588825c2bf20
[LOG] Searching for matching rules for jetbrains-studio (title:  )
[LOG] Searching for matching rules for jetbrains-studio (title: win416)
[LOG] XWayland surface 588825aaf6a0 unmapping
[LOG] [Window 588825c2bf20: title: "win416", class: jetbrains-studio] unmapped
[LOG] Framebuffer created, status 36053
[LOG] Unmapped was not focused, ignoring a refocus.
[LOG] Searching for matching rules for jetbrains-studio (title:  )
[LOG] CWLSurface 588825c2a570 called destroy()
[LOG] xwayland window 588825aaf6a0 -> association to 0
[LOG] Dissociate for 588825aaf6a0
[LOG] [Window 588825c2bf20: title: "win416", class: jetbrains-studio] destroyed, queueing.
[LOG] [xwm] New XSurface at 588825aaf6a0 with xid of 4213049
[LOG] [xwm] New XWayland window at 588825c1eda0 for surf 588825aaf6a0
[LOG] [WLCompositor] New wl_surface with id 499 at 588825343920
[LOG] [xwm] New XWayland surface at 1
[WARN] [xwm] CXWM::onNewSurface: no matching xwaylandSurface
[ERR] [LinuxDMABUF] FIXME: surface feedback stub
[LOG] [xwm] surface 588825aaf6a0 requests serial 1b1
[LOG] [xwm] Handled message prop 244 -> WL_SURFACE_SERIAL
[LOG] [xwm] New XWayland resource at 588825c36e10
[LOG] Window 588825c1eda0 set class to jetbrains-studio
[LOG] Searching for matching rules for jetbrains-studio (title: )
[LOG] [xwm] Handled prop 67 -> ?
[LOG] Window 588825c1eda0 set title to win417
[LOG] Searching for matching rules for jetbrains-studio (title: win417)
[LOG] [xwm] Handled prop 39 -> ?
[LOG] [xwm] Handled prop 68 -> ?
[LOG] [xwm] Handled prop 35 -> WM_HINTS
[LOG] [xwm] Handled prop 304 -> _NET_WM_STATE
[LOG] [xwm] Handled prop 309 -> _NET_WM_NAME
[LOG] [xwm] Handled prop 305 -> _NET_WM_WINDOW_TYPE
[LOG] [xwm] Handled prop 40 -> WM_NORMAL_HINTS
[LOG] CWLSurface 5888253c8ee0 called init()
[LOG] xwayland window 588825aaf6a0 -> association to 588825343920
[ERR] [WLCompositor] Cannot leave surface 588825646290 from eDP-1, client hasn't bound the output
[LOG] CWLSurface 5888250856c0 called destroy()
[LOG] XWayland surface 5888259421c0 unmapping
[LOG] [Window 588825980390: title: "VK Teams", class: vkteams] unmapped
[LOG] Searching for matching rules for vkteams (title: VK Teams)
[LOG] Unmapped was not focused, ignoring a refocus.
[LOG] Searching for matching rules for org.telegram.desktop (title: Telegram (2))
[LOG] CWLSurface 588825966550 called destroy()
[LOG] xwayland window 5888259421c0 -> association to 0
[LOG] XWayland surface 588824439960 unmapping
[LOG] [Window 588825913830: title: " ", class: jetbrains-studio] unmapped
[LOG] Framebuffer created, status 36053
[LOG] Removing last node (dwindle)
[LOG] On closed window, new focused candidate is [Window nullptr]
[LOG] Registered signal for owner 588824438a60: 588825c01588 -> 588824438b18 (owner: CPointerManager)
[LOG] Registered signal for owner 588825955b40: 5888258151d8 -> 588825955b50 (owner: CRenderbuffer)
[LOG] Callback 588825955b78 -> 588825955b70, CRenderbuffer removed.
[LOG] Registered signal for owner 588825955b40: 5888259aed08 -> 588825955b50 (owner: CRenderbuffer)
[LOG] Callback 588825955b78 -> 588825955b70, CRenderbuffer removed.
[LOG] CWLSurface 588825873660 called destroy()
[LOG] xwayland window 588824439960 -> association to 0
[LOG] [xwm] surface 588825aaf6a0 requests serial 1b2
[LOG] [xwm] Handled message prop 244 -> WL_SURFACE_SERIAL
[ERR] XWayland has yeeten the xwm off?!
[CRITICAL] XWayland has yeeten the xwm off?!
[LOG] Cleanup: destroyed a window
[LOG] Keybind triggered, calling dispatcher (0, , 65515)
[LOG] Executing eww update observe_mode=true
[LOG] Process Created with pid 100405
[LOG] Keybind triggered, calling dispatcher (64, , 65293)
```

**Comment by Arantier** [comment] 2024-06-15 19:08
On the side note: dear god, last few months are testing my faith in Linux. First menus, lists and other pop-ups in Android Studio stopped working correctly. Then eww started treating 100% of the screen width as just the half of it and I had to hardcode the width. Each time I was launching "sudo pacman -Syu" I was hoping that these issues would be fixed, but instead my system got only worse. But these were just major inconveniences. Random XWayland crashes on the other hand make me lose all unsaved code from Studio *every day* and I can't screen share now, which breaks several of my work responsibilities. Honestly, one or two updates like that and I won't take it anymore man :(

**Comment by vaxerski** [comment] 2024-06-15 19:15
Brother, you're coming to hyprland amidst the biggest backend rewrite of all its time and expecting everything to work just fine.

Complaining will not get anything fixed, if you want a rock-solid experience either revert to 0.39.1 until the turmoil is over or go to KDE/Gnome altogether.

Also, search the bug tracker, dupe of #6398

**Closed by vaxerski** 2024-06-15 19:15 UTC
Labels: bug

**Comment by Arantier** [comment] 2024-06-15 19:27
Thanks for the pointer and suggestion. I see what you mean about searching similar issues, but it's kinda hard to use because all of them are hidden as closed. I understand the point about it being an issue with XWayland, rather than with Hyprland, but not having one of them open hurts the navigation and made me think, that this is a different issue because of issue still being present.

Also I wasn't neither expecting it to work in a 0.41.0, nor I was complaining, this isn't Reddit or Discord. I simply have no idea how to roll in into open source projects with suggestions and how to correctly present the issue, because often some maintainers take bug reports and criticism as a personal attack. So sorry if my report looked like one, had no intention of bringing unconstructive feedback.

**Comment by Arantier** [comment] 2024-06-15 20:53
Rollback worked great, faith restored a bit. Thank you very much!
