### ISSUE TITLE
Brave browser gets mis-rendered if opened on a display aside other windows

### ISSUE THREAD

**Issue by pshirshov** [hyprwm/Hyprland#3358] opened 2023-09-17 18:47 UTC
### Hyprland Version

d126d2c09204a09b0b10ce4f999520fc901fbf0a

### Bug or Regression?

Bug

### Description

Parts of the brave browser UI aren't visible if it's opened on a display with other windows. This doesn't happen if Brave is the only window on a display.

### How to reproduce

1) Set fractional scaling to 1.5 and force_zero_scaling to true (I'm not sure if that's necessary)
2) Open a terminal 
3) Open brave browser, parts of the UI would be rendered outside of the visible area

### Crash reports, logs, images, videos

![20230917_19h44m13s_grim](https://github.com/hyprwm/Hyprland/assets/295225/c41b80a7-d1c8-48b0-82f9-078820de1b6d)

**Comment by MightyPlaza** [comment] 2023-09-17 18:51
this doesn't seem like a hyprland issue
you may try another wayland compositor like sway if you want to be sure
(also make sure brave is running under native wayland)
(you'll probably want to pick a better browser, with proper linux/wayland support)

**Comment by pshirshov** [comment] 2023-09-17 20:10
I can't reproduce this problem under Sway and Plasma Wayland.

**Comment by MightyPlaza** [comment] 2023-09-17 20:12
latest sway build as well? (https://aur.archlinux.org/packages/sway-git-wlroots-git)
even stranger if running under wayland

**Comment by pshirshov** [comment] 2023-09-17 20:13
Nope, it's sway 1.8.1 which comes from nixpkgs. Hyprland comes from its flake so it's fresh.

**Comment by MightyPlaza** [comment] 2023-09-17 20:17
that's isn't latest build from git, that release is from May
hyprland likely didn't have this issue back then

**Comment by pshirshov** [comment] 2023-09-17 20:38
I'll try to check with latest sway, but there should be a possible workaround. If I change window size (or do this: `bind = $extMod, M, fullscreen, 1`), the browser window gets fixed. So it should definitely be solvable at Hyprland level.

**Comment by vaxerski** [comment] 2023-09-22 22:54
IIRC this is an issue after some chromium update, fixable by nudging the browser's size. Dupe of... I forgot which number. Search the tracker.

**Closed by vaxerski** 2023-09-22 22:54 UTC
Labels: bug

**Comment by TommyLuco** [comment] 2023-10-08 17:01
As a temporary workaround i've just set up a window rule to resize Brave to 100% (and due to it then being window managed, it renders always correctly)

What I used:
```windowrule=size 100%,^(brave-browser)$```
