### ISSUE TITLE
Cannot (mousewheel) scroll with Alacritty in hyprland

### ISSUE THREAD

**Issue by wreedb** [hyprwm/Hyprland#468] opened 2022-08-04 03:46 UTC
Alacritty does not respond to scroll wheel in Hyprland. I've duplicated this 3 times on 3 different distributions (arch, fedora, gentoo) all compiled from source while following the instructions given.  I have attempted manually binding scroll wheel actions in alacritty to no evail.

steps to reproduce:
build hyprland from master branch
open alacritty
try to scroll with mouse wheel

due to alacritty being the most popular terminal amongst tiling wm users, i assumed this would have been in the issues already. I searched closed and open issues and didn't find an issue about it- so here we are

**Comment by frigaut** [comment] 2022-08-04 06:14
I can confirm that.
Interestingly, trackpad scroll works.

**Comment by frigaut** [comment] 2022-08-04 07:29
Related to #465 ?

**Comment by vaxerski** [comment] 2022-08-04 08:02
probable dupe of #465

**Closed** 2022-08-04 08:02 UTC
Labels: bug
