### ISSUE TITLE
Opening a layer surface via another layer surface steals mouse events from that layered surface.

### ISSUE THREAD

**Issue by the-fuckin-nobody** [hyprwm/Hyprland#4281] opened 2023-12-28 15:13 UTC
### Hyprland Version

Hyprland, built from branch main at commit 07132741bc02631966ca06ed54b55598a8487a5d  (renderer: use 120 as the denominator in scale checks). Date: Thu Dec 28 04:17:01 2023 Tag: v0.33.1-102-g07132741  flags: (if any) no xwayland

### Bug or Regression?

Bug

### Description

This issue is a bit difficult to mention(for me :-) ), so forgive me if the title feels a bit misguiding.
Okay this bug has been persistent since like 6 months. So I found that whenever I click on any waybar module that launches any other layer surfaces (say rofi/wofi etc.), and exit that layer surface then mouse events kind of don't work on waybar i.e. whenever I click on any other module inside of waybar or say anywhere within waybar, the same module that I activated earlier gets activated again and again until i right click on waybar even it can't receive mouse hover events.

And I can confirm that it is not the issue with waybar but with the compositor itself as I can get everything working flawlessly in another wayland compositor  I use (swayfx).

my hyprland config:
```
source = ~/.config/hypr/rose-pine.conf
env = XCURSOR_SIZE,18
env = GTK_THEME,Kanagawa-B-LB
env = SHELL,/usr/bin/fish
general {
	border_size = 2
	gaps_in = 3
	gaps_out = 10
	gaps_workspaces = 20
	layout = master
	no_cursor_warps = false
	no_border_on_floating = false
	no_focus_fallback = false
	col.active_border = $pine $foam $iris 45deg
	col.inactive_border = 0x00000000
	col.nogroup_border = $gold $iris 45deg
	col.nogroup_border_active = $pine $foam $iris 45deg
	apply_sens_to_raw = false
	resize_on_border = true
	extend_border_grab_area = 0
	hover_icon_on_border = true
    cursor_inactive_timeout = 5
}

decoration {
	# rounding = 1
# 	active_opacity = 1.0
# 	inactive_opacity = 0.8
# 	fullscreen_opacity = 1.0
	drop_shadow = false
# 	shadow_range = 0
#   shadow_render_power = 0
# 	shadow_ignore_window = true
# 	shadow_offset = [0, 5]
# 	shadow_scale = 1.0
# 	dim_special = 0.0
 	dim_inactive = on
	dim_strength = 0.1
	dim_around = 0.4
 	blur {
 		enabled = true
 		size = 1
 		passes = 2
		ignore_opacity = true
 		new_optimizations = true
		xray = false
		noise = 0.000
		contrast = 1
		brightness = 1
	}
}
animations {
	bezier = easein, 0.55, -0.68, 0.48, 1.682
	bezier = easeout,0.390, 0.575, 0.565, 1.000
	enabled = true
 	animation = windows, 1, 3, easein, slide
	animation = windowsIn, 1, 3, easeout, slide
	animation = windowsOut, 1, 3, easein, slide
	animation = windowsMove, 1, 3, easein, slide
	animation = border, 1, 1, easein
	animation = borderangle, 1, 50, easein, loop
	animation = workspaces, 1, 3, easein, slidefade 20%
}

dwindle {
	pseudotile = false
	force_split = 2
    preserve_split = false
    smart_split = false
    smart_resizing = false
    permanent_direction_override = true
    no_gaps_when_only = 0
    use_active_for_splits = false
    use_active_for_splits = false
}
master {
    allow_small_split = false
    mfact = 0.55
    new_is_master = false
    new_on_top = false
    no_gaps_when_only = false
    orientation = left
    inherit_fullscreen = false
    always_center_master = true
	drop_at_cursor = false
}
input {
	kb_model = 
	kb_layout = us
	kb_variant = 
	kb_options = 
	kb_rules = 
	kb_file =  
	numlock_by_default = false
	repeat_rate = 20
	repeat_delay = 600
	sensitivity = 0.6
	accel_profile = adaptive
	scroll_method = 2fg
	scroll_button = 0
	natural_scroll = true
	follow_mouse = 1
    mouse_refocus = false
	float_switch_override_focus = 1

	touchpad {
		disable_while_typing = true
		natural_scroll = true 
		scroll_factor = 1.5
		middle_button_emulation = true
		tap_button_map = lrm
		clickfinger_behavior = true
		tap-to-click = true
		drag_lock = false
		tap-and-drag = true 
	}
}

device:elan0001:00-04f3:327e-mouse {
    natural_scroll = true
}

gestures {
	workspace_swipe = true
	workspace_swipe_fingers = 3
	workspace_swipe_distance = 300
	workspace_swipe_invert = true
	workspace_swipe_forever = true
	workspace_swipe_create_new = false
}

misc {
	disable_hyprland_logo = false
	disable_splash_rendering = true
	vfr = true
	vrr = 1
	mouse_move_enables_dpms = true 
	key_press_enables_dpms = true
	disable_autoreload = true
	animate_manual_resizes = true
	focus_on_activate = true
	no_direct_scanout = true
	new_window_takes_over_fullscreen = 1
	layers_hog_keyboard_focus = false
    allow_session_lock_restore = true
    hide_cursor_on_touch = true
}

binds {
	workspace_back_and_forth = true
	allow_workspace_cycles = true 
}

monitor=, highres, auto, 1

exec = /home/dex/.config/hypr/bin/autostart.sh
exec-once = swayidle timeout 300 'lock-screen' timeout 400 'hyprctl dispatch dpms off' resume 'hyprctl dispath dpms on' before-sleep 'lock-screen'
exec-once = hyprctl setcursor Bibata-Gruvbox 18
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Kanagawa-B-LB"
exec-once = gsettings set org.gnome.desktop.interface font-name 'Fantasque Sans Mono 10'
exec-once = gsettings set org.gnome.desktop.interface cursor-blink true
exec-once = gsettings set org.gnome.desktop.interface cursor-size 18
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Kanagawa-BL'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Gruvbox'

# trigger when the switch is toggled
#bindl=,switch:off:Lid Switch,exec,lock-screen
# trigger when the switch is turned on
bindl=,switch:on:Lid Switch,exec,lock-screen && hyprctl dispatch dpms off
# trigger when the switch is turned off
bindl=,switch:off:Lid Switch,exec,hyprctl dispatch dpms on
$term = foot
$browser = firefox
$file-manager = dolphin
$media-player = mpv
$launcher = rofi_launcher
$emoji = rofi_emoji
$screenshot = rofi_screenshot
$powermenu = rofi_powermenu
$run = rofi_runner

bind = SUPER, minus, movetoworkspace, special
bind = SUPER, Return, exec, [workspace 1]$term
bind = SUPER_SHIFT, Return, exec, $term
bind = SUPER_Control, Return, exec, [float;noanim] $term
bind = SUPER_SHIFT, W, exec, $browser
bind = SUPER_SHIFT, d, exec, $file-manager
bind = SUPER, q, killactive
bind = SUPER_SHIFT, space, togglefloating
bind = SUPER_SHIFT, E, exit
bind = SUPER_SHIFT, R, exec, hyprctl reload
bind = SUPER, d, exec, $launcher
bind = SUPER, w, exec, rofi_windows
bind = SUPER, r, exec, $run
bind = SUPER, period, exec, $emoji
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
#bindr = SUPER, SUPER_L, exec, killall rofi || $launcher
bindle = , XF86AudioRaiseVolume, exec, volume-control --inc
bindle = , XF86AudioLowerVolume, exec, volume-control --dec
bindle = , XF86AudioMute, exec, volume-control --toggle
bindle = , XF86MonBrightnessUp, exec,brightness-control --inc 1
bindle = , XF86MonBrightnessDown, exec, brightness-control --dec 1
bindr = SUPER, p, exec, color-picker
bind = SUPER, s, exec, $screenshot
bind = , Print, exec, screenshot --full
bind = SUPER, n, exec, networkmanager_dmenu
bind = SUPER, Print, exec, screenshot --area
bind = SUPER, Tab, cyclenext
binde = SUPER_Control, Left, resizeactive, -10 0 
binde = SUPER_Control, Right, resizeactive, 10 0 
binde = SUPER_Control, Up, resizeactive, 0 -10 
binde = SUPER_Control, Down, resizeactive, 0 10 
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d
bind = SUPER, l, movefocus, r
bind = SUPER, h, movefocus, l
bind = SUPER_SHIFT, k, movewindow, u
bind = SUPER_SHIFT, j, movewindow, d
bind = SUPER_SHIFT, l, movewindow, r
bind = SUPER_SHIFT, h, movewindow, l
bind = SUPER, x, exec, $powermenu 
bind = SUPER, f, fullscreen, 0
bind = SUPER_SHIFT, F, fullscreen, 1
bind = Alt_Control, Left, workspace, e-1
bind = Alt_Control, Right,workspace, e+1
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER_Control, 1, movetoworkspace, 1
bind = SUPER_Control, 2, movetoworkspace, 2
bind = SUPER_Control, 3, movetoworkspace, 3
bind = SUPER_Control, 4, movetoworkspace, 4
bind = SUPER_Control, 5, movetoworkspace, 5
bind = SUPER_Control, 6, movetoworkspace, 6
bind = SUPER_Control, 7, movetoworkspace, 7
bind = SUPER_Control, 8, movetoworkspace, 8
bind = SUPER_SHIFT, 1, movetoworkspacesilent, 1
bind = SUPER_SHIFT, 2, movetoworkspacesilent, 2
bind = SUPER_SHIFT, 3, movetoworkspacesilent, 3
bind = SUPER_SHIFT, 4, movetoworkspacesilent, 4
bind = SUPER_SHIFT, 5, movetoworkspacesilent, 5
bind = SUPER_SHIFT, 6, movetoworkspacesilent, 6
bind = SUPER_SHIFT, 7, movetoworkspacesilent, 7
bind = SUPER_SHIFT, 8, movetoworkspacesilent, 8
bind = SUPER_SHIFT, M, exec,layoutmsg addmaster
bind = SUPER, m, exec, layoutmsg focusmaster

#Floats
windowrulev2 = float, class:(swayimg.*)
windowrulev2 = float, title:(Task Manager.*)
windowrulev2 = animation popin 80%, class:(swayimg.*)
windowrule = float,title:^(Sign In.*)
windowrule = float, title:Picture-in-Picture|Library
windowrule = noborder, title:Picture-in-Picture|Library
windowrulev2 = noborder,floating:1, class:(foot|foot)
windowrulev2 = opacity 1.00,fullscreen:1

#Opacities
windowrulev2 = opacity 0.80 override,class:^(firefox)$
windowrulev2 = opacity 1.0, class:^(org.kde.dolphin)$
windowrulev2 = opacity 0.80 0.80,class:^(file-roller)$
windowrulev2 = opacity 0.80 0.80,class:^(qt5ct)$
windowrulev2 = opacity 0.80 0.80,class:^(discord)$ #Discord-Electron
windowrulev2 = opacity 0.80 0.70,class:^(pavucontrol)$
windowrulev2 = opacity 0.80,class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = opacity 0.80 0.80,class:^(org.telegram.desktop)$


windowrule = workspace 2, $browser|chromium
windowrule = workspace 3, $file-manager
windowrulev2 = workspace 4, title:(nvim).*
windowrule = workspace 4, code-oss
windowrulev2 = workspace 5, class:(libreoffice-).*
windowrulev2 = workspace 5, class:.*(zathura)
windowrule = workspace 6, title:Telegram.*|Discord.*
windowrule = workspace 7, mpv|vlc
windowrule = workspace 8, qt5ct|qt6ct|kvantum.*|pulse*|pipewire*|font-manager|font-viewer
layerrule = blur, rofi
layerrule = blur, waybar
layerrule = ignorealpha 0.2, waybar
layerrule = ignorezero, rofi
windowrule = opaque, $browser
windowrulev2 = idleinhibit always,class:(mpv) 
#windowrule = animation popin, ^($term)$
```

### How to reproduce

- add any module that launches a layer surface (say rofi), to a statusbar (say waybar)
- click on that module
- then click on any other module or anywhere inside waybar
- same module gets activated
- now, right click on waybar
- starts working fine as it was before

**Comment by MatthiasBenaets** [comment] 2023-12-30 21:09
Isn't this a dupe of https://github.com/hyprwm/Hyprland/issues/1348#issuecomment-1565604984 ? try the workaround in this comment.

**Comment by the-fuckin-nobody** [comment] 2023-12-31 11:46
Okay I'll mark this as closed then.

**Closed** 2023-12-31 11:46 UTC
Labels: bug
