### ISSUE TITLE
A copy of the cursor stays at the laptop screen when moved to another display

### ISSUE THREAD

**Issue by hexlic** [hyprwm/Hyprland#7348] opened 2024-08-15 13:03 UTC
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: $HOSTNAME
Release: 6.10.4
Version: #1 SMP PREEMPT_DYNAMIC Mon Aug 12 15:25:56 CEST 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:


```

Monitor config setup
```
$ hyprctl systeminfo -c | grep "^monitor"
monitor = eDP-1, 1920x1080@60, 728x1152, 1.5,  bitdepth,10
monitor = DP-4,  3440x1440@60, 0x0,      1.25, bitdepth,10
monitor = DP-5,  3440x1440@60, 0x0,      1.25, bitdepth,10
monitor = DP-6,  3440x1440@60, 0x0,      1.25, bitdepth,10
monitor = ,      preferred,    auto,     1
monitor = HDMI-A-1, preferred, auto,     2
```

</details>

### Description

When I move my cursor from one monitor to the other, a copy of the cursor stays at the first one, usually being the laptop screen.
The copy also reflects some of the changes of the main cursor - it changes icons and sometimes positions with the real one.

I labeled this as a regression as this worked in 0.41.2.

### How to reproduce

Move the mouse cursor from the laptop screen to the external screen.

**Comment by gulafaran** [comment] 2024-08-21 22:39
does this occur in -git? i cant seem to reproduce it

**Comment by hexlic** [comment] 2024-08-24 08:11
on Gentoo it says that I need to have [GCC 14 or newer](https://github.com/gentoo/gentoo/commit/c38d0cc5700abde6618d391bc4ca9c8f114e1d70) for compiling it. Is that true?

**Comment by vaxerski** [comment] 2024-08-24 20:45
yes

**Comment by mkavanagh-23** [comment] 2024-08-25 00:24
I’ve also had this issue but I am not sure I would label it a regression as I’ve been noticing this on and off for the past several months.

It just never was much of a bother to me so I never filed an issue here

**Comment by vaxerski** [comment] 2024-08-25 14:36
I've had this for a while but haven't seen it recently on git

**Comment by vaxerski** [comment] 2024-08-28 18:27
has it happened?

**Comment by mkavanagh-23** [comment] 2024-08-28 18:49
Haven’t been able to reproduce it yet, tried playing around with monitor settings to see if I could, honestly don’t think I’ve seen it at least since the switch to aquamarine. 

Not sure if OP did any more testing or is still experiencing it

**Comment by vaxerski** [comment] 2024-08-29 07:52
closing then, feel free to reopen if it comes up again

**Closed by vaxerski** 2024-08-29 07:52 UTC
Labels: bug

**Comment by hexlic** [comment] 2024-08-29 20:30
I have switched to 0.41.1 which works well.

I don't really know how to get gcc 14 on Gentoo so I do not know how to get the git version :{

**Comment by vaxerski** [comment] 2024-08-29 20:36
me neither, I dont use gen2

**Comment by tealblu** [comment] 2024-09-02 13:41
just installed hyprland (non-git) on my arch system and experiencing this issue! would love some troubleshooting help

**Comment by vaxerski** [comment] 2024-09-02 15:28
try git
