### ISSUE TITLE
[BUG] blur doesn't work for Kitty terminal

### ISSUE THREAD

**Issue by awarewen** [hyprwm/Hyprland#2886] opened 2023-08-04 13:09 UTC
### Hyprland Version

v0.28.0-3-g2e6693fb

### Bug or Regression?

Bug

### Description

after hyprland upgrade,i change my 'hyprland.conf' blurs conf, but it doesn't work for Kitty terminal.
kitty: 0.28.1

blur work fine with 'foot' terminal

![图片](https://github.com/hyprwm/Hyprland/assets/53365857/071e255f-564a-4a9f-afde-edd9f683e8cf)

### How to reproduce

nop

### Crash reports, logs, images, videos

hyprland.conf blurs:
```
  blur {
    enabled           = true
      size              = 3
    passes            = 3
    new_optimizations = true
    xray              = true
    ignore_opacity    = true
  }

```

**Comment by vaxerski** [comment] 2023-08-04 16:55
Since you replied "how to reproduce" with "no", I cannot reproduce at all and thus your issue is invalid. Closing. If anything, your kitty is outdated.

**Closed by vaxerski** 2023-08-04 16:55 UTC
Labels: bug

**Comment by awarewen** [comment] 2023-08-05 13:44
Found it: `windowrule = forcergbx, ^(kitty)$` .  `forcergbx ` doesn's work with blur.

**Comment by notquitethereyet** [comment] 2024-11-21 00:46
@awarewen latest commit #[940f7aa](https://github.com/hyprwm/Hyprland/commit/940f7aa990dbc99815bab8d355999d8277534b17) fixes it.
