### ISSUE TITLE
Text copied under xwayland can't be saved with cliphist

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6247] opened 2024-05-26 10:10 UTC
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 553232a3e4c112c8511309e6b685cb614895e714  (hyprctl: Add Config Flag to `hyprctl systeminfo` (6160)).
Date: Sun May 26 04:46:07 2024
Tag: v0.40.0-137-g553232a3, commits: 4743

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.9.1-3-cachyos-echo-lto
Version: #1 SMP PREEMPT_DYNAMIC Thu, 23 May 2024 07:58:33 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

cliphist works under wayland, it doesn't work in xwayland.

### How to reproduce

1. Install `wl-clipboard`, `cliphist`
2. Execute the `wl-paste --watch cliphist store` command in the terminal
3. Find an xwayland app to copy text
4. Use `cliphist list` to view copied text

**Comment by Agent00Ming** [comment] 2024-05-26 10:15
<details><summary>please elaborate. I can do so just fine...</summary>

![image](https://github.com/hyprwm/Hyprland/assets/107314235/cb3888f0-608f-44eb-b0e8-fe58e9237663)

</details>

**Comment by hdm9527** [comment] 2024-05-26 10:48
> please elaborate. I can do so just fine...

Both chrome xwayland mode and idea can be reproduced.

https://github.com/hyprwm/Hyprland/assets/39702328/3a91d51e-03ec-437d-930f-80313fb1bbaf

**Comment by Agent00Ming** [comment] 2024-05-26 11:37
Then please change the title accordingly, chrome has the option of native wayland but intelliJ is the one real issue. i.e. "(xwayland) intelliJ idea cannot interact with wayland clipboard" or something

**Comment by hdm9527** [comment] 2024-05-26 12:19
> Then please change the title accordingly, chrome has the option of native wayland but intelliJ is the one real issue. i.e. "(xwayland) intelliJ idea cannot interact with wayland clipboard" or something

This is a bug, you can compile hyprland with this commit 4cdddcfe.

>Here's hyprland compiled with 4cdddcfe, cliphist working under xwayalnd

https://github.com/hyprwm/Hyprland/assets/39702328/457692ed-551b-4d3d-8818-14011cf08060

**Comment by Agent00Ming** [comment] 2024-05-26 12:23
I am well aware of that, but that's in the past now. If you want the bug to get fixed in the future then maybe consider helping out by labeling it correctly and with updated information as development goes on.

**Comment by hdm9527** [comment] 2024-05-26 12:42
> I am well aware of that, but that's in the past now. If you want the bug to get fixed in the future then maybe consider helping out by labeling it correctly and with updated information as development goes on.
> 
> Were you not aware of #6132 ?

I know, #6086 was merged yesterday. I haven't learned C++, but can I provide log and debug information.

**Comment by drnikos** [comment] 2024-05-26 13:38
I also have the same problem, I can only use copy paste for between wayland windows or xwayland windows, but I cant do that between wayland-xwayland. Also cliphist only stores the things I copy from wayland apps

**Comment by niksingh710** [comment] 2024-05-26 14:22
@hdm9527 ig it is somehow related to latest MR vax is working on.

btw which ui you used for cliphist share that.

**Comment by hdm9527** [comment] 2024-05-26 14:26
> @hdm9527 ig it is somehow related to latest MR vax is working on.
> 
> btw which ui you used for cliphist share that.

[This script](https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.local/share/bin/cliphist.sh)

**Comment by CarloCattano** [comment] 2024-06-01 09:45
I cant copy into any electron apps , discord , slack , telegram ....

**Comment by snvfrgh** [comment] 2024-06-04 15:07
I also encounter the same problem.

**Comment by Tristan971** [comment] 2024-06-12 15:39
Does this issue require more information from us affected users? (same symptoms, all xwayland applications affected)

**Comment by CarloCattano** [comment] 2024-06-12 15:43
It's working with latest. No issue present at all

**Comment by Tristan971** [comment] 2024-06-12 15:44
Care to precise if by « latest » you mean master or 0.41.0? Because the latter definitely is not fixed.

**Comment by hdm9527** [comment] 2024-06-12 15:55
> Care to precise if by « latest » you mean master or 0.41.0? Because the latter definitely is not fixed.

main branch (master)

**Comment by degobbis** [comment] 2024-06-15 20:36
I have the same problems, see #6519, when I'm using the latest official package 0.41.1
No Problems with version 0.40.0.

**Comment by vaxerski** [comment] 2024-06-15 20:37
what's the easiest app to repro this with? chromium seems to be copying text just fine for me.

**Comment by Tristan971** [comment] 2024-06-15 20:52
Copying from chrome to discord, kitty to intellij/jetbrains ides, …

**Comment by degobbis** [comment] 2024-06-15 21:04
In my case, from KeePass to Firefox Developer-Edition or KeePass to Geany or KeePass to Alacritty

**Comment by vaxerski** [comment] 2024-06-16 14:29
![image](https://github.com/hyprwm/Hyprland/assets/43317083/615d164f-be8a-42a0-93f9-1b47f4a16cc7)
kitty (wl) to intellij (xwl) works fine on my end:

![image](https://github.com/hyprwm/Hyprland/assets/43317083/a6432d92-b908-4181-b825-abd92b1f0e81)
![image](https://github.com/hyprwm/Hyprland/assets/43317083/9d2827af-ceca-4f83-8a76-fec83478b39e)

**Comment by degobbis** [comment] 2024-06-16 14:42
THX for your reply, it's just not helpful to tell me that it works for you.
It doesn't work for me as described in my issue.

What can I say, some change in version 0.41.0 is causing this problem, and unfortunately I am not able to analyse it.
Tell me what you need to better isolate it, and please tell me how to get to it, so I'll do my best to help.

**Comment by hdm9527** [comment] 2024-06-16 14:48
> kitty (wl) to intellij (xwl) works fine on my end:
> 
> ![image](https://private-user-images.githubusercontent.com/43317083/340110397-a6432d92-b908-4181-b825-abd92b1f0e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDkzMTEsIm5iZiI6MTcxODU0OTAxMSwicGF0aCI6Ii80MzMxNzA4My8zNDAxMTAzOTctYTY0MzJkOTItYjkwOC00MTgxLWI4MjUtYWJkOTJiMWYwZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE0NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODMyM2RjMjZmYmJjM2FlYjg1YzU3ZTIyNWM5M2ZkZDZlMTNlZDVjYmQ2OWY4YmYyMWUzYWQ3Mjc1NGU3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZfniVrLVRwfcAS4PECKyljsOt_U2_TBKaDHXq5oOUM) ![image](https://private-user-images.githubusercontent.com/43317083/340110404-9d2827af-ceca-4f83-8a76-fec83478b39e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDkzMTEsIm5iZiI6MTcxODU0OTAxMSwicGF0aCI6Ii80MzMxNzA4My8zNDAxMTA0MDQtOWQyODI3YWYtY2VjYS00ZjgzLThhNzYtZmVjODM0NzhiMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE0NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NTViNzUxOTM5OWM4MjA4NDFhODA4ODEzMjhmYmIzODhlZWI5ZmI2ZmUyZGY4MWI1NGU2MTBhMjljYmI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cWXTOkWVrTD4NflDpLGCl7bDsitCl2Ob2UNr6a1CEo)

freerdp(xwl) does not work. From freerdp to kitty cannot be pasted.

**Comment by Tristan971** [comment] 2024-06-16 14:49
> kitty (wl) to intellij (xwl) works fine on my end:

(lol) is there a good way for us to provide you with debug log/info of it not working on our end? Presumably there’s an external factor at fault but I couldn’t figure it out

**Comment by fiskhest** [comment] 2024-06-16 14:50
Still seeing issues copying from discord and slack on my end. Like @Tristan971 asks, is there any other debug info we can provide?

**Comment by vaxerski** [comment] 2024-06-16 14:53
post a hyprland log from hl launched with `HYPRLAND_TRACE=1 HYPRLAND_LOG_WLR=1 Hyprland`

**Comment by degobbis** [comment] 2024-06-16 16:09
Here my Logs:
[systeminfo.log](https://github.com/user-attachments/files/15858949/systeminfo.log)
[hyprland.log](https://github.com/user-attachments/files/15858948/hyprland.log)

**Comment by hdm9527** [comment] 2024-06-16 16:19
From freerdp to kitty, paste unrecognizable characters.
![image](https://github.com/hyprwm/Hyprland/assets/39702328/d6cc7ad8-bc44-4c2b-b293-1bfc7cb48ade)
There's a lot of `ignoring clipboard access: xwayland Unfocused`
[Hyprland-45401.log](https://github.com/user-attachments/files/15858991/Hyprland-45401.log)

**Comment by Tristan971** [comment] 2024-06-16 16:21
> post a hyprland log from hl launched with `HYPRLAND_TRACE=1 HYPRLAND_LOG_WLR=1 Hyprland`

Great thanks. Can't do it just yet (not near my machine for another 2 days) but I will.

**Comment by vaxerski** [comment] 2024-06-16 16:22
are you trying to paste something large like an image? Incremental clipboard (anything over 64kB I believe) is not supported.

**Comment by hdm9527** [comment] 2024-06-16 16:23
Only text, about 100-200 words

**Comment by Tristan971** [comment] 2024-06-16 16:24
I had noticed the limitation for images, but:
1. It (used to) work for (large/full-screen) images in some cases (flameshot -> discord)
2. It never worked for the same images in some other cases (flameshot -> slack)
3. In this case copying a (short-ish) URL is what failed and prompted me to find the issue

**Comment by hdm9527** [comment] 2024-06-16 16:26
Starting Hypnland, the first one is working, and then it cannot be pasted

**Comment by vaxerski** [comment] 2024-06-16 16:38
"then"? I've started 2 xwayland apps and fiddled with them and I couldn't get c+p to break. Copying text, mind you.

**Comment by vaxerski** [comment] 2024-06-16 16:38
> It (used to) work for (large/full-screen) images in some cases (flameshot -> discord)

yes, before the xwayland rewrite where INCR was never implemented

**Comment by Tristan971** [comment] 2024-06-16 16:39
Got it.

Either way I'll come back with detailed trace logs as soon as I can for the supported case of small buffers 👍

**Comment by hdm9527** [comment] 2024-06-16 16:45
The freerdp (xwl) paste is broken, probably a problem with remote desktop.

**Comment by degobbis** [comment] 2024-06-16 16:50
By the way, for RDP I use Remmina with freerdb, I also have problems with copying between host and RDP. What I also notice here is that the keyboard layout is not adopted.

**Comment by degobbis** [comment] 2024-06-16 17:10
Finally, I would like to confirm that after downgrading to version 0.40.0, with the same configuration, the clipboard and keyboard recognition also work again in Remmina RDP

**Comment by vaxerski** [comment] 2024-06-16 17:17
that we already know. read my comment https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2171765718

**Comment by degobbis** [comment] 2024-06-16 17:22
> that we already know. read my comment [#6247 (comment)](https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2171765718)

All right, then I'll wait for further instructions for testing. In the meantime, I'm working with version 0.40.0.

**Comment by Tristan971** [comment] 2024-06-16 17:23
> post a hyprland log from hl launched with `HYPRLAND_TRACE=1 HYPRLAND_LOG_WLR=1 Hyprland`

@degobbis you can follow these instructions to help debugging the issue

**Comment by degobbis** [comment] 2024-06-16 17:25
> > post a hyprland log from hl launched with `HYPRLAND_TRACE=1 HYPRLAND_LOG_WLR=1 Hyprland`
> 
> @degobbis you can follow these instructions to help debugging the issue

Done here https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2171754871

**Comment by vaxerski** [comment] 2024-06-16 17:52
please try now

**Comment by degobbis** [comment] 2024-06-16 18:57
OK, now I have downloaded the master branch and compiled with cmake. 
Here the Log: 
[hyprland.log](https://github.com/user-attachments/files/15859543/hyprland.log)

`hyprctl systeminfo -c` now returns this error: `Couldn't read (5)% `

**Comment by vaxerski** [comment] 2024-06-16 19:19
```
[TRACE] [xwm] Selection notify for 247 prop 246 target 243
[ERR] [xwm] can't set clipboard: no MIMEs
[TRACE] [xwm] Selection notify for 247 prop 246 target 243
[ERR] [xwm] can't set clipboard: no MIMEs
```
This is likely the root cause, but I can't repro this happening at all. What X app is trying to copy?

**Comment by degobbis** [comment] 2024-06-16 19:23
Is KeePass over this Buttons
![grafik](https://github.com/hyprwm/Hyprland/assets/10517822/fa07d284-9c36-4a55-b184-b46d7ef03fb8)

**Comment by vaxerski** [comment] 2024-06-16 19:34
thanks! repro'd and fixed. Try now.

**Comment by degobbis** [comment] 2024-06-16 20:10
I can confirm that the error with copying from KeePass has been fixed.

Maybe it's just the self-compiled version, but hyprctl systeminfo -c still returns the error Couldn't read (5)%  

Also hyprpm update must be executed again for the split-monitor-workspaces plugin to work with every new login.

And maybe you can also have a look at why the keyboard layout is not passed cleanly to the RDP connection via Remmina with the rdesktop plugin.

In Hyprland the keyboard layout is used correctly.
Here is the log file: [hyprland.log](https://github.com/user-attachments/files/15859718/hyprland.log)

**Comment by vaxerski** [comment] 2024-06-16 20:24
really odd with the hyprctl thing. Never seen that happen.

For RDP keymaps, I'd open a new issue. This is to track clipboard issues, which if none remain, should be closed. @hdm9527

**Comment by degobbis** [comment] 2024-06-16 20:34
> really odd with the hyprctl thing. Never seen that happen.
> 
> For RDP keymaps, I'd open a new issue. This is to track clipboard issues, which if none remain, should be closed. @hdm9527

OK, tell me the issue ID when you have opened it.

**Comment by vaxerski** [comment] 2024-06-16 20:55
uhh, you're the one to experience it so you should open it, lol

**Comment by hdm9527** [comment] 2024-06-17 01:25
> thanks! repro'd and fixed. Try now.

Some xwayland apps cannot be copied to cliphist, e.g. intellij.

**Comment by hdm9527** [comment] 2024-06-17 09:38
> > thanks! repro'd and fixed. Try now.
> 
> Some xwayland apps cannot be copied to cliphist, e.g. intellij.

```
❯ wl-paste -l
text/html;charset=UTF-16
text/html;charset=UTF-16BE
text/html;charset=UTF-16LE
text/html;charset=ISO-8859-1
text/html;charset=US-ASCII
text/html
text/rtf
text/plain;charset=utf-8
text/plain
STRING
text/plain;charset=UTF-16
text/plain;charset=UTF-8
text/plain;charset=UTF-16BE
text/plain;charset=UTF-16LE
text/plain;charset=ISO-8859-1
text/plain;charset=US-ASCII
text/plain
text/plain;charset=unicode
JAVA_DATAFLAVOR:application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
JAVA_DATAFLAVOR:application/x-java-serialized-object; class=com.intellij.openapi.editor.impl.EditorCopyPasteHelperImpl$CopyPasteOptionsTransferableData
```

**Comment by fiskhest** [comment] 2024-06-17 16:27
> post a hyprland log from hl launched with `HYPRLAND_TRACE=1 HYPRLAND_LOG_WLR=1 Hyprland`

Strangely enough, I cannot reproduce if I launch hyprland as quoted from a tty.

However, when I launch hyprland through gdm, I see sporadic issues copying from slack - it works roughly 1/10 tries, but when it works, it is saved to cliphist but my primary selection buffer is empty so I have to invoke and copy it from cliphist to get it to stick to my primary buffer.

**Comment by Nama** [comment] 2024-06-18 00:25
Wayland and XWayland windows keep separate primary clipboards (middle mouse click to paste).

If I select the text in Firefox/kitty "uwu" I can paste "uwu" only in Wayland windows.
If I select the text in discord "owo" I can paste "owo" only in XWayland windows.
The clipboards don't even override each other. I still paste "uwu" in Wayland windows after selecting "owo" in Xwayland window.
On newest commit.
[hypr2.log](https://github.com/user-attachments/files/15878627/hypr2.log)


This sounds relevant (but I have no idea):
```
[TRACE] [pointer] hw transformed hotspot for DP-3: [Vector2D: x: 3, y: 1]
[LOG] Searching for matching rules for kitty (title: ~)
[LOG] [WLDataDevice] CWLDataDeviceProtocol::onKeyboardFocus: cannot send selection to a client without a data_device
[LOG] Set keyboard focus to surface 1, with [Window 5826e12ad5e0: title: " - Discord"]
[LOG] Searching for matching rules for discord (title:  - Discord)
[LOG] Window rule workspace 1 -> class:^(discord)$ matched [Window 5826e12ad5e0: title: " - Discord"]
[LOG] [PrimarySelection] CPrimarySelectionProtocol::updateSelection: cannot send selection to a client without a data_device
[LOG] [XDGShell] xdg_surface 5826e12ba3a0 requests geometry 0x0 1232x1410
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 5826df7a33e0 called init()
[LOG] Callback 5826deb395d0 -> 5826deb395c8, CPointerManager removed.
```

**Comment by vaxerski** [comment] 2024-06-18 18:06
Primary selection is not shared between wl and xwl, correct, I did not implement that. This issue is about the clipboard as far as I am aware.

**Comment by Nama** [comment] 2024-06-18 18:11
oh? came here from #6132 
That also worked until 0.41.0 ._.

**Comment by Tristan971** [comment] 2024-06-18 20:09
I can confirm that the issue is solved for me with the last few commits on master

**Comment by vaxerski** [comment] 2024-06-18 20:39
I'll close this then, for primary selection one can open a new issue (though I doubt I'll implement that myself, consider not using xwayland)

**Closed by vaxerski** 2024-06-18 20:39 UTC
Labels: bug

**Comment by Tristan971** [comment] 2024-06-18 20:40
> consider not using xwayland

you know how it is... but can't blame you for not wanting to deal with this shit either
