### ISSUE TITLE
Terminal (kitty, alacritty)  are laggy  on external display.

### ISSUE THREAD

**Issue by shubax101** [hyprwm/Hyprland#6851] opened 2024-07-12 09:09 UTC
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e728e56cbc6af0a9be1276b2cf8e019a894016e7  (meson: install wayland.hpp header).
Date: Fri Jul 12 02:28:23 2024
Tag: v0.41.2-31-ge728e56c, commits: 4917

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.9.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  555.58.02  Tue Jun 25 01:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/shubax/.config/hypr/hyprland.conf: Read Succeeded

$scrPath = $HOME/.local/share/bin
$rofiScript = $HOME/.config/rofi/scripts


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=,highrr,auto,1


exec-once = waybar
exec-once = blueman-applet
exec-once = pipewire-pulse
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once = greenclip daemon

# exec = killall -q hyprpaper || hyprpaper

$terminal = kitty
$fileManager = dolphin
$browser = firefox
$menu = wofi --show drun
$scrPath = $Home/.local/share/bin


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = PATH,$PATH:$scrPath
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#####################################
#       F*** nvidia specific        #
#####################################


env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __NV_PRIME_RENDER_OFFLOAD,1
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1
env = WLR_DRM_NO_ATOMIC=1
env = __VK_LAYER_NV_optimus,NVIDIA_only
env = NVD_BACKEND,direct


env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = WLR_NO_HARDWARE_CURSORS,1


decoration:blur:enabled = false
decoration:drop_shadow = false
misc:vfr = true


general { 
    gaps_in = 2
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = false 
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 1.0
    drop_shadow = false
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = false
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


# Window/Session actions
bind = $mainMod, Q, killactive # close focused window
bind = $mainMod, Delete, exit, # kill hyprland session
bind = $mainMod, W, togglefloating, # toggle the window between focus and float
bind = $mainMod, G, togglegroup, # toggle the window between focus and group
bind = $mainMod, F, fullscreen, # toggle the window between focus and fullscreen
bind = $mainMod, L, exec, swaylock # launch lock screen
bind = $mainMod+Shift, F, exec, $scrPath/windowpin.sh # toggle pin on focused window
bind = Ctrl+Alt, W, exec, killall waybar || waybar # toggle waybar

# Application shortcuts
bind = $mainMod, Return, exec, $terminal # launch terminal emulator
bind = $mainMod, E, exec, $fileManager # launch file manager
bind = $mainMod, C, exec, $editor # launch text editor
bind = $mainMod, B, exec, $browser # launch web browser
bind = $mainMod, H, exec, $terminal htop # launch system monitor (htop/btop or fallback to top)
bind = $mainMod+Shift, H, exec, $terminal btop # launch system monitor (htop/btop or fallback to top)

# Rofi menus
bind = $mainMod, R, exec, pkill -x rofi || $rofiScript/launcher_t6 # launch application launcher
bind = $mainMod, Backspace, exec, pkill -x rofi || $rofiScript/powermenu_t6 # launch application launcher


# Move between grouped windows
bind = $mainMod CTRL , H, changegroupactive, b
bind = $mainMod CTRL , L, changegroupactive, f

$scriptPath = $HOME/.config/hypr/scripts
# Screenshot/Screencapture
bind = Ctrl+Shift, X, exec, $scriptPath/screenshot.sh # partial screenshot capture (frozen screen)
bind = $mainMod+Alt, P, exec, $scrPath/screenshot.sh m # monitor screenshot capture
bind = , Print, exec, $scrPath/screenshot.sh p # all monitors screenshot capture


# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$

# This fixed lags
opengl {
  nvidia_anti_flicker = false
}

# FPS Meter on the screen
# debug {
#   overlay = on
# }

======Config-End========
```

</details>

### Description

I am new to hyprland Long story short . I installed NVIDIA graphic drivers. After restarting hyprland It was lagging (not much but one could easily feel it), the experience was not smooth as it was before installing the NVIDIA graphic drivers. After digging deeper into the things. The solution i found was to add 

opengl {
  nvidia_anti_flicker = false
}

into the hyprland config file. Everything was smooth again. Until i found terminals like kitty or alacritty are lagging a lot i can't even type the command They are freezing. This terminal lagging problem is only on the external screen. On my main laptop screen terminal is running smooth. Other apps are running smooth on both laptop screen and external screen. When i drag terminal from external screen to main screen it works smooth. Same is happing when i type into google chrome search engine. Lags are observed when i type in terminal, Google chrome search bar . where as when i type something in Firefox no lags are observed . All these problems are observed in external display.

### How to reproduce

IDK

**Comment by vaxerski** [comment] 2024-07-13 14:07
nvidia moment I am guessing, possibly could be fixed with #6608, anyways dupe of some other issue

**Closed by vaxerski** 2024-07-13 14:07 UTC
Labels: bug
