### ISSUE TITLE
fullscreen bug, on monitor scale or resolution modified

### ISSUE THREAD

**Issue by lisuke** [hyprwm/Hyprland#1821] opened 2023-03-18 14:41 UTC
step:
1. Start the application and set it to full screen mode.
2. Modify monitor scale or resolution.
3. Full screen window can't resize.

**Comment by vaxerski** [comment] 2023-03-18 14:49
dupe of #1091

**Closed by vaxerski** 2023-03-18 14:49 UTC
Labels: bug

**Comment by lisuke** [comment] 2023-03-18 15:19
Okay, I'm also debugging.
