### ISSUE TITLE
0.41 cause problem when using stylus and touch

### ISSUE THREAD

**Issue by lVentus** [hyprwm/Hyprland#6577] opened 2024-06-18 01:50 UTC
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh



Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: ventus
Release: 6.8.12
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240613.e9ee548"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"
```

</details>

### Description

When I am using stylus to write, on xournalpp, rnote, writelabs, gimp..... if I use stylus, and touch the screen. The app will crush and log segmentation fault, and core dumped. At first I didn't think it is hyprland problem, But then I tried gnome and kde they all work fine, only when I am using hyprland, it will crash. Then I roll back to 0.40. It works! So I think some work in 0.41 may cause these problems.
But there is another problem, how can I install plugins.
I noticed, when I lock the hyprland url to a specific commit,  these happend:
```
• Removed input 'hyprland/hyprutils'
• Removed input 'hyprland/hyprutils/nixpkgs'
• Removed input 'hyprland/hyprutils/systems'
• Removed input 'hyprland/xdph/hyprland-protocols/nixpkgs'
• Removed input 'hyprland/xdph/hyprland-protocols/systems'
```
some plugins(hyprspace) need hyprutils, so I can't compile them.
if I use `hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1";` and use hypr version in nixos-unstable.
then the version of plugins and hyprland will be not matched, and can't be load.

### How to reproduce

use handwriting app in v0.41

### Crash reports, logs, images, videos

```
segmentation fault, 
core dumped.
```

**Comment by Agent00Ming** [comment] 2024-06-18 01:55
#6312 ?

**Comment by lVentus** [comment] 2024-06-18 02:24
> #6312 ?

Similar? But i am not sure. I am fine using mouse+touchpad+touchscreen. Only when i use pen, then I can't use other inputs. Or I can't use pen after any touch screen operation. It happened before, when i use master version, before 0.41 release.

**Comment by Agent00Ming** [comment] 2024-06-18 09:54
what about #6251?

**Comment by lVentus** [comment] 2024-06-18 10:03
> what about #6251?

No, it is not. First one is more similar. I think it should be some problems in stylus/tablet rewrite.

**Comment by Agent00Ming** [comment] 2024-06-18 10:08
Get `WAYLAND_DEBUG=1` logs of crashing apps in hyprland and the equivalent (not crashing) in kde plasma/gnome so there's something to compare with.

**Comment by fufexan** [comment] 2024-06-18 14:33
Dupe of https://github.com/hyprwm/Hyprland/issues/6312, please continue discussion there.

**Closed by fufexan** 2024-06-18 14:33 UTC
Labels: bug
