### ISSUE TITLE
Allow floating windows under tiled windows

### ISSUE THREAD

**Issue by Andy3153** [hyprwm/Hyprland#2683] opened 2023-07-11 15:47 UTC
So, I'm trying to replicate aspects of my config from KDE on Hyprland, and everything is coming along nicely. Except that I used to have Cava inside a terminal, positioned to cover the bottom half of my screen, and have it be under all windows.

I managed to get everything I wanted using window rules (and some aspects of it even better than with KDE's window rules):
```conf
windowrulev2 = float,          class:(kitty),title:(cava)
windowrulev2 = pin,            class:(kitty),title:(cava)
windowrulev2 = noanim,         class:(kitty),title:(cava)
windowrulev2 = noblur,         class:(kitty),title:(cava)
windowrulev2 = noborder,       class:(kitty),title:(cava)
windowrulev2 = nodim,          class:(kitty),title:(cava)
windowrulev2 = nofocus,        class:(kitty),title:(cava)
windowrulev2 = noinitialfocus, class:(kitty),title:(cava)
windowrulev2 = noshadow,       class:(kitty),title:(cava)
windowrulev2 = rounding 0,     class:(kitty),title:(cava)
windowrulev2 = size 100% 50%,  class:(kitty),title:(cava)
windowrulev2 = move 0% 50.2%,  class:(kitty),title:(cava)
``` 

...but I can't get the window under all of the other windows. Basically, the entire point of my visualizer.

Did I miss something, or are floating windows never allowed under tiled windows?

If so, I was thinking I could maybe specify a layer for the window to be in (I mean the things you could see by running `hyprctl layers`)?

EDIT: searching around more through the issue tracker, I noticed #2081 talks about basically the same feature

**Comment by vaxerski** [comment] 2023-07-11 22:31
I'll close this as a dupe of #2081

**Closed by vaxerski** 2023-07-11 22:31 UTC
Labels: enhancement
