### ISSUE TITLE
Binding workspaces to monitors stopped working

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#5870] opened 2024-05-04 08:33 UTC
### Hyprland Version

```
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: adonis-PC
Release: 6.8.8-300.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:53:31 UTC 2024


GPU information: 
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:


```

### Bug or Regression?

Bug

### Description

Workspaces are not bound to monitors anymore.

I have workspaces called 11,12 ... 21,22.. etc. respectively for each of my  monitors.
However, hyprctl only shows the names "1", "2" on each monitor. 

This used to work a time ago.

### config
```
monitor=,preferred,auto,1
monitor=DP-2,3440x1440,3440x0,1
monitor=DP-3,1920x1080,2360x1440,1
monitor=DP-1,3440x1440@144,3440x1440,1,bitdepth,10
monitor=HDMI-A-1,1920x1080,6880x1440,1
monitor=DP-3,transform,1
monitor=HDMI-A-1,transform,1

workspace=11, monitor:DP-1
workspace=12, monitor:DP-1
workspace=13, monitor:DP-1

workspace=21, monitor:DP-2
workspace=22, monitor:DP-2
workspace=23, monitor:DP-2

workspace=31, monitor:HDMI-A-1
workspace=32, monitor:HDMI-A-1
workspace=33, monitor:HDMI-A-1

workspace=41, monitor:DP-3
workspace=42, monitor:DP-3
workspace=43, monitor:DP-3
```

### $ hyprctl -j workspaces
```json
[
  {
    "id": 1,
    "name": "1",
    "monitor": "DP-1",
    "monitorID": 0,
    "windows": 2,
    "hasfullscreen": false,
    "lastwindow": "0x55fe2f13a210",
    "lastwindowtitle": "zsh"
  },
  {
    "id": 2,
    "name": "2",
    "monitor": "DP-2",
    "monitorID": 1,
    "windows": 1,
    "hasfullscreen": false,
    "lastwindow": "0x55fe2f19aa90",
    "lastwindowtitle": "Workspace Rules – Hyprland Wiki - Brave"
  },
  {
    "id": 3,
    "name": "3",
    "monitor": "DP-3",
    "monitorID": 2,
    "windows": 0,
    "hasfullscreen": false,
    "lastwindow": "0x0",
    "lastwindowtitle": ""
  },
  {
    "id": 4,
    "name": "4",
    "monitor": "HDMI-A-1",
    "monitorID": 3,
    "windows": 1,
    "hasfullscreen": false,
    "lastwindow": "0x0",
    "lastwindowtitle": ""
  }
]
```

## $ hyprctl -j monitors | jq -r '.[] | select(."focused"==true).activeWorkspace'

```json
"activeWorkspace": {
    "id": 1,
    "name": "1"
  },
```

**Comment by thejch** [comment] 2024-05-04 09:55
dupe of https://github.com/hyprwm/Hyprland/issues/5849?

**Comment by vaxerski** [comment] 2024-05-04 15:09
mhm

**Closed by vaxerski** 2024-05-04 15:09 UTC
Labels: bug

**Comment by ad-on-is** [comment] 2024-06-28 11:36
@thejch I see https://github.com/hyprwm/Hyprland/issues/5849 is closed, but I'm still experiencing this issue
