### ISSUE TITLE
Firefox and Thunderbird inner borders overflow 

### ISSUE THREAD

**Issue by U-L-M-S** [hyprwm/Hyprland#4413] opened 2024-01-10 22:55 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
❯ hyprctl version
Hyprland, built from branch main at commit 1e6e9b66a5837d62d374edd405bdf561813ebbce dirty (hyprctl: Fix build warnings (3821)).
Tag: v0.32.0-8-g1e6e9b66

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Firefox and Thunderbird inner borders are overwriting.
![image](https://github.com/hyprwm/Hyprland/assets/96896184/e77b6ba4-224f-4ebe-b6a6-cc97de934b5f)
![image](https://github.com/hyprwm/Hyprland/assets/96896184/f7182928-b1e3-487d-b552-0bd93593a747)

### How to reproduce

I just updated my system 2 days ago and as soon I power on today I found these bugs.
It may be problem on my hyprland configs, but I don't know where.

WindowRules.conf:
```conf
# Float Necessary Windows
windowrule=float,Rofi
windowrule=float,pavucontrol

windowrulev2=float, title:(gato)
windowrulev2=size 950 430, title:(gato)
windowrulev2=animation popin, title:(gato)
windowrulev2=center, title:(gato)

windowrule=size 800 500,title:^(float_kitty)$
windowrule=float,title:^(full_kitty)$
windowrule=tile,title:^(kitty)$
windowrule=float,title:^(fly_is_kitty)$
windowrule=animation popin,Rofi

windowrulev2 = float,class:^(brave)$,title:^(Save File)$
windowrulev2 = float,class:^(brave)$,title:^(Open File)$
# windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(org.twosheds.iwgtk)$
windowrulev2 = float,class:^(blueberry.py)$
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float,class:^(geeqie)$
windowrulev2 = tile,class:^(neovide)$

# Increase the opacity 
windowrule=opacity 0.92,Thunar
windowrule=opacity 0.96,discord
windowrule=opacity 0.9,VSCodium
windowrule=opacity 1,obsidian
windowrule=opacity 0.7,neovide

^.*nvim.*$
windowrule=opacity 1,neovim
bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

```
hyprland.conf:
```conf
source=~/.config/hypr/configs/ENVariables.conf
source=~/.config/hypr/configs/Execs.conf
source=~/.config/hypr/configs/Keybinds.conf
source=~/.config/hypr/configs/Monitors.conf
source=~/.config/hypr/configs/WindowRules.conf


input {
  kb_layout=de
  repeat_rate=50
  repeat_delay=240
  numlock_by_default=1

  touchpad {
    disable_while_typing=1
    natural_scroll=1
    clickfinger_behavior=1
    middle_button_emulation=0
    tap-to-click=1
  }
}


gestures { 
  workspace_swipe=true 
  workspace_swipe_min_speed_to_force=5
}

general {
    layout=dwindle
    sensitivity=1.0 # for mouse cursor

    gaps_in=11.8
    gaps_out=15.5
    border_size=2
    col.active_border=0xff5e81ac
    col.inactive_border=0x66333333

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
}

decoration {
	rounding=19
 #   blur=1
 #   blur_size=13  # minimum 1
 #   blur_passes=3  # minimum 1, more passes = more resource intensive.
 #   blur_new_optimizations=1

    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
}

# Blur for waybar 
blurls=waybar

animations {
    enabled=1
    bezier=overshot,0.13,0.99,0.29,1.1
    animation=windows,1,4,overshot,slide
    animation=fade,1,10,default
    animation=workspaces,1,8.8,overshot,slide
    animation=border,1,14,default
}

dwindle {
    pseudotile=1 # enable pseudotiling on dwindle
    force_split=0
    no_gaps_when_only = true
}

master {
  new_on_top=true
  no_gaps_when_only = true
}

misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
  mouse_move_enables_dpms=true
  vfr = true
  hide_cursor_on_touch = true
}


```

**Comment by MightyPlaza** [comment] 2024-01-10 23:02
update please

looks like dupe of multiple closed issues, like: https://github.com/hyprwm/Hyprland/issues/4350

**Closed** 2024-01-11 11:59 UTC
Labels: bug
