### ISSUE TITLE
Divide the monitor

### ISSUE THREAD

**Issue by cjuniorfox** [hyprwm/Hyprland#7117] opened 2024-07-30 21:18 UTC
### Description

I wanted to do something easily doable on X11, but I didn't realize how to do the same on Hyprland.
I have a LG ultra-wide and I want to be able to split the monitor in half, behaving like two monitors side to side—one to the left and the other to the right. The idea is to replicate the setup if I have two monitors where on the left monitor I have a full-screen application like a game and at the right some additional content for a secondary monitor. There's some sort to do that?

**Comment by Rattlyy** [comment] 2024-07-31 00:24
duplicate of #3575

**Closed** 2024-07-31 08:05 UTC
Labels: enhancement
