### ISSUE TITLE
Crashing on 0.40-93fea8 with qjackctl graph, bitwig or reaper

### ISSUE THREAD

**Issue by kiike** [hyprwm/Hyprland#6198] opened 2024-05-22 20:22 UTC
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 93fea890433ec11d7a915f5e0466b2e8b513e895  ().
Date: 2024-05-22
Tag: , commits:

flags: (if any)


System Information:
System name: Linux
Node name: dhalsim
Release: 6.8.10
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:15:12 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 980] [10de:13c0] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240521.dirty"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I am trying to also use Hyprland for my music production needs. However, the programs that I normally use for that purpose, namely Qjackctl when using the graph window, Bitwig or REAPER, strangely whenever menus are concerned, trigger Hyprland crashes. I can't pinpoint the exact reason that will trigger the crash, but it will happen reliably soon.

### How to reproduce

Screw around with qjackctl graph window, bitwig audio settings or reaper routing window.

### Crash reports, logs, images, videos

[crashreport.txt](https://github.com/hyprwm/Hyprland/files/15408382/crashreport.txt)
[coredump2.txt](https://github.com/hyprwm/Hyprland/files/15408384/coredump2.txt)
[coredump.txt](https://github.com/hyprwm/Hyprland/files/15408385/coredump.txt)

**Comment by kiike** [comment] 2024-05-22 20:22
Since I have an Nvidia card, I'll try and change from the proprietary drivers to the nouveau ones temporarily.

**Comment by vaxerski** [comment] 2024-05-22 20:23
I am gonna go insane from the 10th dupe of #6133

**Closed by vaxerski** 2024-05-22 20:23 UTC
Labels: bug

**Comment by kiike** [comment] 2024-05-22 20:25
I hope you won't get crazy. Sorry for the noise then. Cheers!
