### ISSUE TITLE
Close window without removing imepopup created by current window

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#7593] opened 2024-08-31 09:41 UTC
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c5fd5771814958ad274ea9abb961fff621a35b9c dirty (config: Add a window rule to render while unfocused (7582)).
Date: Fri Aug 30 23:37:52 2024
Tag: v0.42.0-96-gc5fd5771, commits: 5165

flags: (if any)
```

</details>

### Description

The imepopup created by the current window is not removed when the window is closed. when switching the input method to enter Chinese in another window, there are two imepopups, one is at position 0x0 and the other one works as expected.

### How to reproduce

1. Start chromium(xwayland) and kitty.
2. In kitty use ctrl+space to switch to Chinese input method, then close kitty.
3. In chromium press ctrl+space to switch input mode, ime popup appears in the upper left corner of the screen.

### Crash reports, logs, images, videos

```log
[LOG] Cleanup: destroyed a window
[LOG] [CWLCompositorResource] New wl_surface with id 31 at 625b4eeb4720
[LOG] [CInputMethodV2] New IME Popup with resource id 34
[LOG] [17:30:31.428618305] CWLSurface 625b4e21b5d0 called init()
[LOG] New input popup
[LOG] Mapped an IME Popup
[ERR] BUG THIS: No owner in imepopup::damageentire
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
```

https://github.com/user-attachments/assets/1ea0a490-76fc-4eb8-ae2e-c1a233163027

**Comment by sungyoonc** [comment] 2024-09-01 14:01
Can you try this? 
[patch.txt](https://github.com/user-attachments/files/16829129/patch.txt)

Also, this might be a duplicate of #5288

**Comment by hdm9527** [comment] 2024-09-01 14:26
> Can you try this? [patch.txt](https://github.com/user-attachments/files/16829129/patch.txt)
> 
> Also, this might be a duplicate of #5288

Thanks, this patch should fix it, imepopup works as expected.

**Closed** 2024-09-01 16:44 UTC
Labels: bug
