### ISSUE TITLE
Hyperctl dispatch dpms off/on - waking up (all) the screens does not work

### ISSUE THREAD

**Issue by arcolinuxz** [hyprwm/Hyprland#1869] opened 2023-03-24 05:43 UTC
Referencing to this https://github.com/hyprwm/Hyprland/issues/1811 from the past that is now closed I would like to open this one as Hyprland is now behaving differently. It is not crashing as much as it is not waking up the monitors after using the mouse or keyboard.

Current setup on ArcoLinux (based on Arch Linux) is now:

hyprland-git r2643.463690a2-1 from AUR
config from https://github.com/arcolinux/arcolinux-hyprland
Wayland parameters from https://github.com/arcolinux/arcolinux-wayland-profile
Hyprland parameters from https://github.com/arcolinux/arcolinux-hyprland-profile

**Comment by arcolinuxz** [comment] 2023-03-24 05:44
The lines in question have now been commented out.

`# with lock
# CURRENLTY LINE BELOW DOES NOT WORK - hyperctl dispatch dpms off
# !!!! exec-once = swayidle -w timeout 1200 '$lock' timeout 1200 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep '$lock'

# this however works with lock
#exec-once = swayidle -w timeout 1200 'swaylock -f -c 111111' timeout 1200 '' resume '' before-sleep 'swaylock -f -c 111111'

# without lock
# CURRENLTY LINE BELOW DOES NOT WORK - hyperctl dispatch dpms off
# !!!! exec-once = swayidle -w  timeout 1200 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'`

**Comment by arcolinuxz** [comment] 2023-03-24 05:55
When I clicked the mouse/keyboard after activating this line

I got the right monitor that woke up - the left monitor is still black and will not wake up whatever I do.

here is the code from this line

cat /tmp/hypr/$(ls -t /tmp/hypr/ | head -n 2 | tail -n 1)/hyprland.log > log

https://pastebin.com/Jp52Tk0N

**Comment by arcolinuxz** [comment] 2023-03-24 06:12
I was wondering if there is a Wayland app that dims my screen but does not lock it after several minutes?
In order to have something in the meantime.

**Comment by arcolinuxz** [comment] 2023-03-24 06:15
line 673 in the pastebin caught my eye

[LOG]  [hookSystem] New hook event registered: mouseButton
[ERR] Couldn't commit output HDMI-A-1
[ERR] Couldn't commit output HDMI-A-1
[LOG] Hyprctl: dispatcher dpms : on

**Comment by vaxerski** [comment] 2023-03-24 12:32
dupe of #1760

**Closed by vaxerski** 2023-03-24 12:32 UTC

**Comment by arcolinuxz** [comment] 2023-03-24 17:04
great it is solved
