### ISSUE TITLE
Searching for hyprland-toplevel-export-v1.xml at the wrong location

### ISSUE THREAD

**Issue by Bkeinn** [hyprwm/Hyprland#1207] opened 2022-12-11 12:23 UTC
I am trying build Hyprland on Fedora so this might be the problem.
I followed the steps to build it on Fedora.
My previous problem was, that hyprland-protocols were not installed so I build it myself without tutorial so I might have messed something up.
```
cd subprojects/hyprland-protocols
meson _build
sudo ninja -C _build install
```
The next time I run 
`sudo meson _build`
I got an new error
`protocols/meson.build:36:1: ERROR: File //usr/local/share/hyprland-protocols/protocols/hyprland-toplevel-export-v1.xml does not exist.`
So I just searched my disk for this file an found it there:
`/usr/local/share/protocols/hyprland-toplevel-export-v1.xml`

I created a new folder named `hyprland-protocols` and moved `protocols` inside and the `Error` was gone.

**Comment by vaxerski** [comment] 2022-12-11 12:32
I don't think you are supposed to install the protocols, but I'll leave that to @fufexan

**Comment by fufexan** [comment] 2022-12-11 15:42
The nix package actually does install the protocols (copy, rather) in `protocols/hyprland-protocols`. 

Meson should find the files automatically if the subproject is where it's supposed to be (protocols/hyprland-protocols).

**Comment by Sergij-SApcPro** [comment] 2023-01-29 15:08
I can confirm that the same happens on Fedora 37. BTW thanks for the fix @Bkeinn.

**Comment by MrRoy** [comment] 2023-01-30 23:02
The problem seems to be because pkg-config reports the wrong path for hyprland-protocols:
```
# pkg-config hyprland-protocols --variable=pkgdatadir
//usr/share/hyprland-protocols

# ls /usr/share/hyprland-protocols
ls: cannot access '/usr/share/hyprland-protocols': No such file or directory

# ls /usr/share/protocols/
hyprland-toplevel-export-v1.xml
```

**Comment by fufexan** [comment] 2023-02-18 23:36
@MrRoy what commit did you test that on? Is it broken with hyprland-protocols master?

**Comment by MrRoy** [comment] 2023-02-19 01:43
@fufexan on release 0.21.0 and 0.20.1
For the gentoo package, I worked around it by using `meson install --skip-subprojects`

**Comment by ignamartinoli** [comment] 2023-08-03 15:35
@romanstingler Yep. It was resolved in an update.

**Closed** 2023-08-03 15:43 UTC
Labels: bug
