### ISSUE TITLE
hyprland crashes when single monitor is shutdown

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#3249] opened 2023-09-10 22:37 UTC
### Hyprland Version

0d53401217b79a9dd552f84ce5d3f8b2985641ee

### Bug or Regression?

Bug

### Description

Hyprland crashes when the monitor (single) is shutdown.

### How to reproduce

The crash seems to happen at random but I've managed to find a mostly minimal way to reproduce it. 

1. Start Hyprland with empty config
2. Start Waybar with default config (this is important I haven't been able to reproduce if waybar isn't running)
3. Start Firefox
4. Power off/on monitor
5. Crash

### Crash reports, logs, images, videos

[hyprlandCrashReport259720.txt](https://github.com/hyprwm/Hyprland/files/12570909/hyprlandCrashReport259720.txt)

**Comment by vaxerski** [comment] 2023-09-10 22:45
fixed in https://github.com/hyprwm/Hyprland/commit/3859607b6cf26ead21f4a23ee11458b7b67fe542

if still happens, dupe of like #2770 or sumn

**Closed by vaxerski** 2023-09-10 22:45 UTC
Labels: bug

**Comment by andresilva** [comment] 2023-09-10 22:50
Confirmed fixed, at least can't reproduce anymore with steps above. 10 minutes from issue report to fix, that's crazy ❤️

**Comment by vaxerski** [comment] 2023-09-10 22:56
we do DEVELOPMENT here no bitching around bae
